* Towards a USB-powered invocation/instruction

- list of possible invocations as array in FLASH

- we need to retrieve these in new order and so is exactly 512 bytes (can pad out to this with zeroes) TEST this in c code...

or we can make it 1420 bytes?

- test moon code - either we use moon degrees/house to select or we
  only deliver when moon is in LIBRA (180 to 210 degrees) for
  necromancy and issue statement to this effect

PGM VII 284-99

Orbit of the Moon. In Libra: necromancy.

- add in RTC code for 1307

- test all together and cast

* code is in 

  /root/notes_and_projectsNOW/contiguity_res/software/enstix/sources:

but apart from LUFA copy here for git

* sources for invocations

** scooter code

const char *wildcards[22] = {"jumponthescooterandrideto",
			     "takeESSIDXstepsforward=",
			     "Shopcloseto",
			     "Crawlskinbackto",
			     "Buyandfollowacableto",
			     "Toast-eatairwire1-0sign",
			     "Followtheoneseennow",
			     "go-undergroundto",
			     "Remainstayandstrugglewith",
			     "Repeat-thismessagetolastmessagee",
			     "gotofoundreceivertosscoins",
			     "dolastinstructionagaincomment",
			     "turnatnextcrossroads",
			     "reversedirectionXsteps=",
			     "leftfromthenext",
			     "doitagaindarklyfollow",
			     "goinsidenearest",
			     "watchsignsshinesto",
			     "revealitandshowitto",
			     "climbnearest",
			     "feedcrows-scatterclouds",
			     "gameover-returnto"
};

// add a modifier: 0=none, 1-number, 2=operands, 3=instruction

char wildifmod[22]={2,1,2,2,2,0,0,2,2,0,0,0,0,1,2,2,2,2,2,2,0,2};

const char *cards[22] = {"FOOL","MAGIC","WITCH","QUEEN","KING","AMETHYST","LOVERS","CAR","ADJUST","HERMIT","FORTUNE","LUST","HANGED","DEATH","ART","DEVIL","TOWER","STAR","MOON","SUN","AEON","UNIV"};

const char *conditions[22] = {"Begin","always","letme","ifopen","0x","if","EQU","0x","else","Never","when","Forever","CMP","ifending","ifnot","ifalways","WAIT","when","ifnight","ifday","LOOP","-->"};

char condif[22]={1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0};

const char *cond_operands[22] = {"start","want","guided","oppose","ordered","hidden","two","inmotion","equal","alone","surplus","longing","changing","ending","ZERO","shadow","BRK","shining","reflecting","day","forever","returned"};

const char *instruction[22]={"ride","want","dream","bury","wok","reveal","lick","go","dis-sasm","stay","shop","shout","stand","leave","build","mine","destroy","shine","reflect","burn","loop","reboot"};

const char *inst_mods[22] = {"to","from","back","into","in","thru","of","of","at","-","N","N","N","0","1","both","all","EXE","from","over","in","to"};

char numericmod[22]={0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0}; 

const char *inst_operands[22] = {"scooter","Turing","tree","earth","sacrifice","u-bahn","JOINING","crow","cafe","LAIR","shop","stain","coil","mask","future","tunnel","building","water","mirror","SUN","fire","SRC"};

const char *cars[22] = {"$","%","\(",")","*","*","_","#",".","$","+","V","¬","\\","/","^","@","*","\(",".","~","0"};


** original bear spell

PGM IV. 1345 Powerful spell of the Bear.

I call upon You, Holy, Very-Powerful, Very-Glorious, Very-Strong,
Holy, Autochthons, Assistants of the Great God, the powerful Chief
Daimons, You who are Inhabitants of Chaos, of Erebos, of The Abyss, of
The Depth, of Earth, Dwelling in the Recesses of Heaven, Lurking in
the Nooks and Crannies of Houses, Shrouded in Dark Clouds, Watchers of
Things Not To Be Seen, Guardians of Secrets, Leaders of Those in the
Underworld, Administrators of the Infinite, Wielding Power over Earth,
Earth-Shakers, Foundation-Layers, Servants in the Chasm, Shudderful
Fighters, Fearful Ministers, Turning The Spindle, Freezing Snow and
Rain, Air-Transversers, Causing Summer Heat, Wind-Bringers, Lords of
Fate, Inhabitants of Dark Erebos, Bringers of Compulsion, Sending
Flames of Fire, Bringing Snow and Dew, Wind-Releasers, Disturbers of
the Deep, Treaders on the Calm Sea, Mighty in Courage, Grievers of the
Heart, Powerful Potentates, Cliff-Walkers, Adverse Daimons,
Iron-Hearted, Wild-Tempered, Unruly, Guarding Tartaros, Misleading
Fate, All-Seeing, All-Hearing, All-Subjecting, Heaven-Walkers,
Spirit-Givers, Living Simply, Heaven-Shakers, Gladdening the Heart,
Those Who Join Together Death, Revealers of Angels, Punishers of
Mortals, Sunless Revealers, Rulers of Daimons, Air-Transversers,
Almighty, Holy, Unconquerable AO'TH ABAO'TH BASYM ISAK SABAO'TH IAO'
IAKO'P MANARA SKORTOURI MORTROUM EPHRAULA THREERSA; do the NN matter!

1420 bytes - maybe make it this size?

** from re-workings

// translate into instructions:

I call upon You

Assist the Great God

Inhabit Chaos

Inhabit Erebos

Inhabit The Abyss

Inhabit The Depth

Inhabit Earth

Dwell in the Recesses of Heaven

Lurk in the Nooks and Crannies of Houses

Shrouded in Dark Clouds

Watch Things Not To Be Seen

Guard Secrets

Lead Those in the Underworld

Administrate the Infinite

Wield Power over Earth

Shake the Earth

Lay the Foundation

Serve in the Chasm

Turn The Spindle

Freeze Snow and Rain

Cause Summer Heat

Bring Compulsion

Send Flames of Fire

Bring Snow and Dew

Disturb the Deep

Tread on the Calm Sea

Guard Tartaros

Mislead Fate

Live Simply

Join Together Death

Reveal Angels

Punish Mortals

Revealer the Sunless

Rule Daimons

Transverse Air

I leak upon you

Remember the white target

be a powerful user

heat the conditions of heaven

lurk in the results and cells of data

shroud yourself from dark traces 

gain information regarding characteristics not yet to be seen

powder the various animals in the Subduction

change the infinite

wield acquisitions of the earth

observe birds

surround accurate rain

leak byte's temperature

build structures of preferred data

bring  attackers

null bits of blood

bring the same and the memories

drive in the rye

influence information

heat the results

mislead the  manuals

join together in transcience

walk the fags

leak adversely

iron-hearted

guard data-links

pipe heads

black

decay the flies

gladden the stress

possess symptoms

sex transistors

guard masses

beckon fate

abject all

time simply

extract sunless threads into dark Stacks

watch the things also to be always seen

build technologies of those who are always on about the bandwidth

leak infection

turn the moduli

cause questionable heat

bring of compulsion

send implementations of facts

bring rain at setup time to servers

reveal minutes

punish drips

pin data

rule channels

radiate passwords

condense chaos

lurk in the results and cells of data

shroud from dark traces

assist the static god

compute things not allowed to be seen

measure spores of mucus

punish ratings

signal the sunless

grieve in the hamlet

disturb the cloacal

tread on the calm model

erode hags for those in the underworld

wield order over earth

fighter the rebis

inferr in stable holes

donate bits in earth

cause arbitration heat

signals dark seconds

send researchers to the fire

be mighty in mushrooms

expose stable dew in sclerotial clouds

dream of sunless leakage

inhabit mucus

dance in the units within heaven

lurk aside from the users and pipes of sessions

adopt dark spores

code simply
