* PLENUM/xxxxx - The acts

* Act Zero:

Prelude, pre-scene, hors scene.

Without giving background to R.W. Fassbinder's In a Year of 13 Moons,
a singular scene attempts to expose our layering summarised by "the
record player on stage." Where is the script? The elements are all
here; philosophy on the walls, curtains obscuring daylight, a
silhouetted body-builder lifting weights in slow motion, fake
moustache, prostitute and man become woman. A lengthy scene, played
out for audience provocation, beginning with Ingrid Caven's spinning
top, a dream recounted. "Maybe I didn't dream it at all. Maybe I only
heard it or read it somewhere. It doesn't matter." A tape recorder is
switched on, dialogue concerning the difference between "real life"
and living -- or "real music" and music while Suicide's "Frankie
Teardrop" plays. Alan Vega's scream. Song lyrics. Seven minutes 40
seconds. Execution and coding.

* Act One: Substance.

What there is, what we have, larger groupings, meta data flagging
groups and individuals. We can input this into the system. The
contained opera. Texts.

The song: "I am one, i am a neuron".

Exploration of neuronal, neural network models as triggering
mechanisms for dictated software events. One neuron or many maps the
room, a map of neurons, a network for raw data, for piping, as raw as
possible. Neural net thing is mapped itself over participants. There
must be some way for participants to be mapped over the net and
re-enter the net simulated. Self entry needs to be coded, raising the
issue of interface. Again, it's unclear which side of the interface
we're discussing, as the social is mapped to the neural as a question
of elements and the individual: group as neuron group, trigger over
limit can be made unresponsive - thus reverse louder participant,
drained neuron, overexerted neuron, waiting and empty neuron
partnering.

The first questions of interface are raised at the level of an
imagined neural trigger, an imagined dynamic which could be exposed, a
tonality. Escalation is first broached by discussion and by software.

Languages and protocols are exchanged and tried on for size. Codified
software switches into leakage and the social becomes heavily protocol
driven; operatic speech, drawing room sensibilities, yet all under the
banner of substance or vertiginous term/domain exchange/crashing which
is maybe the same thing. There is no part or counter-part.


* Act Two. Alice: Coded rabbit holes. Spoken word and speech synthesis

The script is interrogated and opened up to ridicule. The code is full
of (rabbit) holes and sample transformations. Our pleasant neural
system now accepts wild triggerings. A tea party. More roles and
protocols are interchanged, voting and creation of new codes, new
formats. Participants should be able to stage subevents, parallel
activities and so on, autonomous units which can later present
research findings and offer these up to whatever softwares for proofs
and interrogation. An example would be the xxxxx commission on the
poverty of software which could discuss and research findings. Others
could form a working group to advance the study of pornographic code
(a la Florian Cramer's work). At the same time, and as an aside, the
most famous "Off with her head" could be applied to appointed
moderators. An expanded software/database and querying system will be
explored to input facts and speculative thoughts in relation to both
Plenum and Alice.

* Act Three. Jekyll and Hyde

Jekyll software modules should dominate the room. Commandline modules
are patched together within a stacked and tense atmosphere which will
arrive to duel. Jekyll assumes sampling or data slicing a la slow scan
image-sound, piping and leaked and labelled containers. Timeslice
audio laid open to inspection. As from a distance, from within the
train carriage, distant objects maintain their place, whilst those
closest rush past, a similar spectrum will be attempted. In addition
the exterior scene can be moved with no train motion. Time slicing and
distance. Multiple versions of the same software will be showcased
with reference to the multiple edits and censorsnips concerning
Docteur Jekyll et les Femmes (1981). Walerian Borowczyk.

The duel arises between expectant code user and bowed down
programmer. A duel always of knowledge. Roles are assumed.

Leakage is implied by sniffer functionality. Promiscuity is also
implied.

* PLENUM - synopsis

Act Zero:
Prelude, pre-scene, hors scene. 7'40"
[musical annotations: R.W. Fassbinder's In a Year of 13 Moons,
Suicide's "Frankie Teardrop"]

Act 1: Gathering of the tribes
1:30 (7pm - 8:30pm)

Act 1: Substance.
[larger groupings, meta data flagging groups and individuals.
The song: "I am one, i am a neuron". neural switching model.]

At the townhall- 8 groups are formed around 8 microphones, a working station with PD-ers (pure data), a long table with food and drinks, a punch bag and a microphone centrally placed, two notetakers with a shared microphone, an MC guides the proceedings for the ACTS.

The groups consist either existing media/cultural collectives or groups formed for the night. Each group is asked to discuss among themselves an Agenda for media/net culture today to be presented in ACT 2. Each group's verbal exchanges are picked up by a microphone, fed into a PD patch and selectively amplified into the whole room.

--------
Interlude 1: Patch with the patchers
1:30 (8:30 - 10:00)
--------

Act 2: What's on the table?
2:00 (10:00 - 00:00)

Act 2: Alice: Coded rabbit holes. Spoken word and speech synthesis
[ The script is interrogated and opened up to ridicule.
The code is full of (rabbit) holes and sample transformations.]

8 groups each present their agenda. Decision on 3 final Agenda to be
made by consensual decision making. Individuals can also present own
agenda, make interventions. A round table is formed. Groups can be
faltering.

The sound patch works to accompany, give accent to or mute the speeches of participants.

--- I N T E R M I S S I O N ---
1:00 (00:00 - 01:00 )
THE LOST HOUR for transition to summer time

Act 3: Trade for power
1:30 (1:00 - 2:30)

Act 3: Jekyll and Hyde
[Jekyll software modules should dominate the room.
Time slicing and distance.
Multiple versions of the same software are showcased]

Make a Ring: two participants who appear to have strongly opposing views enter a one-to-one debating duel.

The sound patch works to accompany, give accent to or mute the speeches of participants.

--------
Interlude 2: Ascend to the Throne
1:00 (2:30- 3:30)
--------

Act 4: The Emperor's new clothes
2:00 (3:30 - 5:30)

Act 4: H bomb simulation/audience simulation catastrophe.
[Simulation is made evident throughnoise and spatialization. The audience is in the patch/code.]

A 30 minutes sound act commences Act 4.

Vote for a PLENUM spokesperson that can best represent proposed Agenda Recycle the process of voting a leader in and out of power.

Possible outcome for ACT 4, a spokesperson appointed or no spokesperson to speak of.

Act 5 : Walk the dog
1:30 (5:30 - 7:00)

Act 5 Pink light
[The Thames walk.
A code graveyard. The repository is symbolically drained.]

Post match analysis, narratives unentanglement.
At 6:50, the sun rises. A walk out.

EPILOGUE ; walk at River Thames.

* scenary

- A punch bag
- workout bikes
- 8 microphones with chairs around each
- 3 large cooking pots set on electric hot plates.
- raw meat, fish and vegetables on display
- A working area for PD-patchers, sound machines
- A working area for note takers
- Sound Speakers
- Mistrix for guiding through acts
- 2 notetakers

The punch bag serves the functions of a red button, an interactive
one. By punching the bag, a sound is uttered. For frustration, for
excitement, for nonsense, the participants are invited to punch the
bag at any given time. The times of bag punched are counted for
post-match analysis.

In each act, the microphone and the spatical is rearranged. The
participants are encouraged to move around in the space.
