* tech list

[- 1 hot plate + 2 large pots]=pedro

- 18 power points (for all participants, mixer, beamer etc.)
- OHP/overhead projector
- video beamer/projector with VGA input and cable
- VGA switcher for 4x connections
- 16 channel audio mixer connected to PA: MACKIE 1604VLZ4 or identical (must have 8 direct outs/after faders)
- 4 microphones in the room with cables to mixer
- 1 microphone for patchers use
- network access
- mushroom mycelium (can we ask Taro?)

* packing

- basic final session setup//eurorack+cables//incenses
- dark interpreter
- all cables - audio/power/network
- soundcard
- pickups/contacts - TODO: cabling
- fermented products
- radio receivers/scanner thing/arduino and mycelial transmitters - for data radio, cables???
- ohp transparencies and pens

* acts/schedule

19:35 - 21:00 (85min - TALK) - UNFINISHED BUSINESS - STWST
21:00 - 21:30 (30min - RE:TALK) PD patching playback

[session 2]
21:30-23:00 (90min - TALK)  - UNFINISHED CODE - Winnie Soon
23:00-23:30
 (30min - RE:TALK) patching playback

[session 3] 
23:30-01:00 (90min - TALK) - UNFINISHED LAB  - Pedro Soler
01:00-01:30 (30min - RE:TALK) PD patching playback

[session 4]
01:30-3:00 (90min - TALK) - UNFINISHED NETWORK - Davide Bevilacqua
3:00-3:30
 (30min - RE:TALK) PD patching playback

[session 5] 
3:30-5:00 (90min - TALK) - UNFINISHED BODY - Quimera Rosa
5:00-5:30
 (30min - RE:TALK) PD patching playback

EXTRA - 5:30 -6:28 (58 minute) -  PLAYBACK THE FUTURE

** 1 prologue/STWST

- open patch in development, PING PATCH, tuning, self discussion

** 2 unfinished code/winnie

- more projection, OHP diagrams, teletext? comic code, silence of speech at the borders, code commentary, quotation

LPC speech re-process, get speech files, buffering, code commit work, how to capture and re-work artificial voices...

eg.

: git diff HEAD~132   | python ../../test.py
 

https://dobbeltdagger.net/publication/vocable-code-13082018

https://github.com/siusoon/VocableCode/blob/master/vocablecode_program/voices.json

https://dobbeltdagger.net/sites/default/files/vocablecode13082018_stack_winniesoon.pdf

https://github.com/siusoon/VocableCode/blob/master/vocablecode_program/vocableCode_xx.js

https://github.com/siusoon/VocableCode/commits/master/vocablecode_program/vocableCode.js

conversation with winnie: 20/8/2019

*commits = execution* - play across levels of code, commentary, commit, execution and voice

time gaps, visibility of github platform as infrastructure

machine voice, vocable code, performing code

10 min - intro, queer code, queer is... auto-completion

source code as poem, binary logic

20 min - groups, sentences, whiteboard 

8 min - perform and voice sentences, chaos, repetition, executing sentences

javascript, code base - loads voices on demand not pre-loaded so there is micro-temporality if buffering

what is the temporality of wav file, against mp3, other encodings

** 3 lab pedro

- cooking pots mic/ed, dripping speech, fermentation, an object for each of the labs?

** 4 network

- leaking network, data radios, plastic tubes?, radio speech/hiss

** 5 body

- smoke, smells, sense, low frequency, incense

** playback the future

PLAYBACK:

Last orders and with only fifty eight minutes to go before sunrise,
before all the future versions and patches are stowed, stashed,
unsniffed, and enclosed for all possible futures, we play back the
stoney tapes of future palate depositions, intrusions, compressions,
degradations, and gradings of lightly spoken lithic entropy.

With some urgency, we rifle through all of the late summer evening's
signs and codes towards a future dream divination, a sleepy incubation
in near darkness to uncover those hidden things for tomorrow. Of a
dream of thirteen moons, thirteen years ahead, the previous Thames
walk. A thankful code graveyard. The repository is symbolically
drained.

"Maybe I didn't dream it at all. Maybe I only heard it or read it
somewhere. It doesn't matter."

* TODO TODO

- pd patch working, soundcard//NO PCMCIA, refamiliarise

missings: OSC stuff??, rossler, ann/neuron, mixer~X, mux~X, pink~ question?, piperead~//ext13Xinstalled

- test possible speech solutions: festival, own klatt>crappy, what else? espeak

klatt working say > /dev/dsp : /root/projects/ERD_MODULES/RAVEN/older_notes_and_software/docs/rsynth-2005-12-16/

: echo "hello" | espeak // different voices, options etc.

- LPC and praat
- darkint speech work/worm
- something with git, version control, speech of diffs, of commits
- transmitters/audio?
- data radio


** pd/flite // other notes

*** 

libflite: relocation R_X86_64_PC32 against symbol and other errors

fix in libflite

: ./configure --with-audio=none --with-pic --with-lang --with-vox --enable-shared

and in flite external:

: make VOICE=slt

for female voice

*** 

image in pd: 




mixer in ggee crashes in all permutations...
