UNAME := $(shell uname -r)
KERNEL26 := 2.6
KERNELVERSION := $(findstring $(KERNEL26),$(UNAME))

all:: 

ifeq ($(KERNELVERSION),2.6)

obj-m	:= island.o

INCLUDE	:= -I/usr/include/asm/mach-default/
#KDIR	:= /lib/modules/$(shell uname -r)/build
KDIR	:= /usr/src/linux
PWD		:= $(shell pwd)

all::
	$(MAKE) -C $(KDIR) $(INCLUDE) SUBDIRS=$(PWD) modules

else

TARGET	:= island
INCLUDE	:= -I/usr/src/linux/include -I/usr/include/asm/mach-default/
CFLAGS	:= -O2 -Wall -DMODULE -D__KERNEL__ -DLINUX
CC	:= gcc

all:: ${TARGET}.o

${TARGET}.o: ${TARGET}.c
	$(CC) $(CFLAGS) ${INCLUDE} -c ${TARGET}.c

endif

user: user.c
	gcc -o $@ $<

clean::
	$(RM) .island* *.cmd *.o *.ko *.mod.c
	$(RM) -R .tmp*
