* expert meeting

** names 

Kontakt: alazul@gmail.com alfonsoborragan.com -DONE

artists: kat, ioana, quimera rosa, from ars: ANAIS TONDEUR (FR), 

universities, medical geology, environmental medecine:

wageningen university, netherlands -> soil sciences and geology - Thom W. Kuyper

A. John F. Boere, Flemming R. Cassee - National Institute for Public Health and the Environment (RIVM), Bilthoven, The
Netherlands

Petra Krystek - Institute for Environmental Studies (IVM), VU University, Amsterdam, The Netherlands

Institute for Risk Assessment Sciences, Utrecht University, Utrecht, The Netherlands

look at: https://www.medicalgeology.org/pages/public/courses/univcourses.html

https://www.kingston.ac.uk/staff/profile/professor-gavin-gillmore-273/

https://jenniferleblond.com/about/

Eduardo de Mulder (Delft Technical University)

John Farmer j.g.farmer@ed.ac.uk

lothar.viereck-goette@uni-jena.de 	

Tim Jones jonestp@cf.ac.uk



someone with geo psych health: 

** simple description/invitation

I'm currently working on an artistic research project which intersects
geology and human biology at the v2__lab interdisciplinary center for
art and technology in Rotterdam as part of the Alex Adriaansens
Residency 2019/2020. I came across the work of your lab recently in
research for this project. 

The project, Tiny Mining, explores the material basis of computational and
communications technology and infrastructures in relation to the human
body and asks what such a potential relationship could be in terms of
a closer connection between the material and environmental effects of
the extraction and return (planned obsolescence, e-waste) of
technology and the body. At the same time it explores and
asks questions about the practical and ethical nature of this proposed
new relationship.

I was wondering if you would be interested in contributing with your
knowledge base within the field of environmental geology. I do think
and hope that the collaboration would lead to a wider awareness and
interest in this field - this is indeed one part of the project which
is very important for me as I think it is neglected in a lot of
"anthropocene" discourse current in the humanities.


I will be hosting an expert meeting in Brussels on the 12th and 13th
November. It would be great if you can join in any capacity (short
coffee, skype call). If this is not possible if you would be
interested in offering any advice by email, or if you can suggest
anyone who might be able to contribute. I can of course send more
detailed information regarding the project!

best wishes
Martin Howse

www.1010.co.uk

** remote description

Invitation to collaborate on an artistic research project

I'm currently working on an artistic research project which intersects
geology and human biology at the v2__lab interdisciplinary center for
art and technology in Rotterdam as part of the Alex Adriaansens
Residency 2019/2020. I came across your company/work recently in
research for this project. 

The project, Tiny Mining, explores the material basis of computational and
communications technology and infrastructures in relation to the human
body and asks what such a potential relationship could be in terms of
a closer connection between the material and environmental effects of
the extraction and return (planned obsolescence, e-waste) of
technology and the body. At the same time it explores and
asks questions about the practical and ethical nature of this proposed
new relationship.

I was wondering if you would be interested in contributing with your
knowledge base within the field of environmental/medical geology. I do
think and hope that the collaboration would lead to a wider awareness
and interest in this field - this is indeed one part of the project
which is very important for me as I think it is neglected in a lot of
"anthropocene" discourse current in the humanities.

I will be hosting an expert meeting in Brussels on the 12th and 12th
November. I would like to invite you to join by way of a short,
introductory skype call. In 2020 I will be working at v2__lab in
Rotterdam on the project and it could be interesting to meet more
locally if this is possible.

I am delighted, of course, to send more detailed information regarding
the project and am happy to answer any questions.

best wishes
Martin Howse



** 


I would like to invite you to an expert meeting hosted by myself and
v2__lab interdisciplinary center for art and technology in Rotterdam
within the context of the Tiny Mining [TM] awarded the Alex
Adriaansens Residency 2019/2020.

A brief background and description of the project follows:

Tiny Mining [TM]

The project, Tiny Mining, explores the material basis of computational
and communications technology and infrastructures in relation to the
human body and asks what such a potential relationship could be in
terms of a closer connection between the material and environmental
effects of the extraction and return (planned obsolescence, e-waste)
of technology and the body. At the same time it explores and asks
questions about the practical and ethical nature of this proposed new
relationship.

The focus of the project is on the transitional interior and inferior
geologies of media and communications. The notion of interior geology
refers also to the circulatory system of an earth addiction encompassing
extraction (of precious metals, of radioactive minerals),
transport/circulation and consumption (the ingestion of earth-derived
energies, materialities and earth-bound pharmaceutical products) and
return or excretion (traces of isotopes and pollution elements in the
body).

Tiny Mining is an open source project which explicitly attempts to
mine, harvest or recover precious or useful minerals from within
living bodies. It is made manifest as a collection of online practices
and recipes for DIY recovery of elements, an ongoing research, an
online community of DIY practitioners sharing artefacts and
techniques, and as a drive for venture capital investment furthering
the commercial exploitation of this extraction.

It would be wonderful if you could join an expert meeting to
brainstorm, speculate and discuss this project and to perhaps cement
future collaboration. I can offer to cover travel costs, accommodation
and to provide dinner and lunch. Ideally the date would be xx November
and we would meet in the afternoon, have dinner together and then work
the next day, leaving late afternoon.

Let me know if you have any questions, or can suggest any further
experts who might be interested in this project.

https://v2.nl/alex-adriaansens-residency

* schedule

see google docs...

* books/materials/docs

9781862393561 - A History of Geology and Medicine Gsl Special Publications PDF we have
