#+TITLE: Tiny Mining
#+AUTHOR: Martin Howse
#+LANGUAGE:  en
#+OPTIONS:   H:1 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:https://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [smaller]
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)


* Tiny Mining Testimony

\includegraphics[height=0.6\textheight]{first_presentation_resources/circ_images/003circ000.jpeg}

I'm not sure how it works from the inside, some kind of nano-parasite,
chelation is one of their buzz-words. Bio-remediation, all those
things which sound healthy for the body, healing for the planet. And
it is supposed to be good for the planet, for the earth. 

* 

Why dig deep holes in the earth to pull out minerals when you can let
the body extract minerals and then simply harvest these with
nano-pills. In some extreme cases they say that it can even heal
people if they have too much of one mineral, or too much of the wrong
kind of minerals - heavy metals they say, or radioactivity. But those
are special cases. I started tinymining because I needed the money,
and somehow it felt good, like I was more in contact with something
out there, not in here.

* 

I know it doesn't sound natural, but I think it is. It shows us,
beneath all the technological crust, that we're one with nature. We're
geological. Sometimes I even feel a bit more earthy, more stony after
taking the pills. Like something is slowly flowing and changing
through me, it feels a bit like watching an ice cube slowly melt, but
you feel it yourself, that melting, see yourself. 

* 

There's also always a mineral taste in my mouth and some foods taste a
bit different. It could be the taste of blood though. Slightly
metallic, always a bit sandy when I think about it, when I feel
it. But redder, like red itchy eyes, but you feel it in the mouth,
maybe a bit sore and rubbed.

* 

I'm starting to feel that the company wants to hide the natural way of
doing our things, of farming and eating, so that they can be
financed and nourished by the mining that takes place within us.


[Testimony from a Tiny Mining user]

* Statements - internal geology

\includegraphics[height=0.\textheight]{first_presentation_resources/circ_images/019FFF02067.JPG}

If we take idea of the earth/planet as a body and consider its
circulations, ecologies, self-regulation (cybernetics) and general
well-being or health - consider extraction or mining from these
perspectives.

* 

To be made more tangible and able to be experienced through the
application of extraction, its philosophies and technologies to the
human body, to consider ourselves as an interior geology, as an open
resource for exploitation.

* What is Tiny Mining

Tiny Mining is a speculative, interventionist artistic research and
media project examining the links between extractivism, pharmacology
and medical or environmental geology.

* 

Tiny Mining explores the material basis of computational and
communications technology and infrastructures in relation to the human
body and asks what such a potential relationship could be in terms of
a closer connection between the material and environmental effects of
the extraction and return (planned obsolescence, e-waste) of
technology and the body could be. At the same time it explores and
asks questions about the practical and ethical nature of this proposed
new relationship.

* How does it work?

Tiny Mining projects and furthers a speculative near future in which
potentially precious or useful minerals can be mined from within
living (primarily human) bodies for the profit of both a larger
corporation and its "users". 

Tiny Mining explores twin models of exploitation.

* 

Under the startup, distributed, late/post-capitalist
model of corporations such as Amazon, pre-programmed nano-parasites
for tiny mining are ordered by app under a subscription model with
monthly payments (for mining revenues) delivered via paypal. 

* 

A burgeoning DIY scene, calling themselves with some irony the "users"
subvert and hack this proprietary model, offering online, underground
resources for hacking tiny mining, sharing artefacts, recipes and
techniques to mine and recover one's "own" minerals, and to extract
and market these precious resources on dark, cryptographic networks
and finance models.

* 

We will explore both of these potential outcomes of this near-future
scenario within a series of fictions, video works, practical
investigations, installations and interventions. 

* 

On the one hand, a startup company will be created, seeking venture
capital for investment and exploring various models for the
functionality of a tiny nano-mining pill. 

* 

At the same time, Tiny Mining is an open source project which
explicitly attempts to mine, harvest or recover precious or useful
minerals from within living bodies. It is made manifest as a
collection of online practices and recipes for DIY recovery of
elements, an ongoing research, and as an online community of DIY
practitioners sharing artefacts and techniques.

* Where does it come from?

** The Crystal World

\includegraphics[height=0.8\textheight]{first_presentation_resources/12ctm_photo_by_tamami_iinuma_dsf8230m.jpg}

** Dissolutions

\includegraphics[height=0.8\textheight]{first_presentation_resources/circ_images/001versionDsmall.png}

** Shift Register

\includegraphics[height=0.8\textheight]{first_presentation_resources/shiftregister-1.jpg}

Internal geology: radioactoive isotopes, Sillamae, Erzgebirge.

* Concept

Media, computation and communications have always been geological,
entering into material cycles through both extraction (mining, for
example, copper), and processing (for example, the reburial of copper
and fiber optic cables in the earth). What is perhaps new, in the
recent naming of the becoming-geological of humankind (as the
anthropocene or capitalocene), is the conjoined transformation and
awareness of humans and their home planet as at once media and matter,
information and geology. Industrial plastics, dust and radioactive
isotopes lodge within all kinds of bodies, equally marking all things
as geologic. 

* 

At the same time, humankind can be defined as always incorporating the
earth: as food, as pharmakon and as media and this incorporation can
be defined as geological. We can catalogue a history and a "bestiary"
of an inner geology with its bezoars, otoliths, gallstones and
gastroliths. Geology is not outside us; various timescales must be
compared and contrasted (of lives and deaths, eating and shitting, of
deep time and geological formation).

* 

This idea of a sensitivity to planetary and bodily health underwrites
the Tiny Mining project with the Anthropocene viewed as both
symptomatic and as psychosomatic. 

* 

The focus of the project is on the transitional interior and inferior
geologies of media and communications. The notion of interior geology
refers also to the circulatory system of an earth addiction encompassing
extraction (of precious metals, of radioactive minerals),
transport/circulation and consumption (the ingestion of earth-derived
energies, materialities and earth-bound pharmaceutical products) and
return or excretion (traces of isotopes and pollution elements in the
body).

* 

Matter, like media are both purposefully ingested and accidentally
absorbed, forming new internal, circulatory and transitional
geologies. 

* 

Tiny Mining explores these multiple links and circulations between
technology, the environment and the human body and psyche. It's
important in times of climate disruption and environmental destruction
that we begin to think and work deeply within these relationships and
within the histories of media such as scientific discourse,
pharmacological matters and medical geology; to think an alien,
potentially geological post-nature.

* Research directions/where we are now

Preliminary research suggests the formulation of a nanite, molecular
machine or nanomachine, a parasitic composite of polarized molecules
that once stimulated, produce mechanical movements on cellular
surfaces in order to remove, harvest and restructure minerals from the
human body on a macroscopic scale.

The parasite, named Argotine (with reference to the rich history and
folklore of the ergot fungus) is designed as an assemblage of
nanoscopic units, each of them measuring around 10nm, that have
specific compositions and electrical charges corresponding to the
desired mining process.

* 

The different nanomachines create bonds, communicate and form larger
structures (up to 100 micrometers) similar to fungi's mineral mining
hyphae. Once injected into the bloodstream, they travel and stick to
the affected/healthy cells where the extraction begins.

This micro/tiny mining process, as in the case of soil mineral
extractions performed by plants, fungi and microorganisms is
facilitated thanks to bioleaching (the process of extracting metals
from their ores through the use of living organisms) through
chelation. The process is highly efficient for lead, arsenic,
antimony, molybdenum, gold, silver and cobalt extractions.

* Possible outcomes

\includegraphics[height=0.5\textheight]{first_presentation_resources/v2_images/FFF03718.JPG}

Tiny Mining projects a series of research manifestations,
interventions and outcomes which can be collected as an installation
for exhibition. These can be summarised as follows:

* 

- Video documentation of users, interview with users and documentation
  of the DIY processes of mining and extraction. We are particularly
  interested in documenting and assessing the (psychological) side
  effects of Argotine, one of the key pharmaceutical components within
  Tiny Mining practice. Side effects include glossolalia (speaking in
  tongues). 

* 

- The online and legal manifestation and presence of the Tiny Mining
  company and technical research around the feasibility and
  possibilities of Tiny Mining technical solutions in consultation
  with nanotechnology, bioprocess engineers and medical geology
  scientists in Berlin. We will produce and publish a series of white
  papers outlining the chemistry, biology and financial
  instrumentation of Tiny Mining. Sales pitches will be created and
  disseminated.

* 

- A set of online, DIY resources for a community of
  "users". Discussion groups, HOWTOs, and DIY kit documentation will
  be maintained and produced throughout the project which aims also to
  promote a small community of near fictional "users".

* 

- 3D renderings and real artefacts (home-spun, pseudo-scientific and 3D
  printed) relating to both the Tiny Mining corporation and DIY
  use. For example, the DIY "kit" for self mining and extraction with
  instructions and implements, waste objects form the DIY operations
  which have become venerated as talismans.

* 

- A workshop at the v2_labs examining real-world, hands-on and DIY
  solutions approaching Tiny Mining and the geo-logical inversions
  which it enacts alongside discussion with invited theorists and
  practitioners who work with both the geological and the internal.

In the workshop, we will explore the genealogies and histories of
geophagy, pharmacology, iatrochemistry and non-linear geology.

We will link these to Medical Geology, and the transport and
circulation of psychoactive pharmacology, composing rich new and
alternate mythologies of contemporary interior geologies.

We will invent and enact rituals for a newly spectral, transitional
geological era.

* Schedule

12th: AM:

- Introduction to the project (presentation/documentaries/reader)

- Introduction by Ines Tomasek (medical geology)

- Discussion of various aspects of the project: economic models, internal geology, anthropocene discourses, medical geology, pharma-geo-ecologies

- Previous artistic and otherwise examples (Alfonso, Theun)

- How we already see it developing: the company, open source mining, what technologies, what artistic or technical outcomes?

- What we hope to achieve in this meeting: forging future collaborations, current knowledge base, firm directions and foundation for the project, what are new directions and unexpected inspirations.

- Questions, ideas, notes

* 

12th PM:

- Brainstorming: where is a good place to start:
- Process overview/threads/questions below...

* 

13th AM:

- Possible skype sessions with other experts?

- What knowledge resources do we have - try and collect these and discuss how to  make these accessible/shared?

- Work on say technologies, connections and/or specific minerals from previous day’s research - perhaps in the form of annotated maps of the body and of micro/macro circulations and extractions?

* 

13th PM: (Alfonso leaves at 18.56 . 17.00 finish)

- Plans for the future, project scheduling, what could be future events or workshops?

- Summing up

* 

The expert meeting I imagine as laying the foundation for the project,
gaining inspirations and also attracting attention as a kick-off event
which can be further described, discussed and elaborated in some kind
of research update which I would make. It's a first step which
outlines future directions for the project: defining both what is
possible practically from a scientific perspective and what makes
sense to a certain degree from a more speculative point of view. At
the same time seeing where the project aligns and fits with current
knowledge within the fields of medical geology and environmental
medicine. It would also be a way of forging future potential
collaborations.

* Some questions and directions to be considered here

* Technical:

- How it works in terms of interior mining, maps of the body, what minerals we are targeting? 

- What are existing models/other species models for this extraction (bacteria, fungi, lichens - chelation, remediation, bioleaching, biosorption, phytolithics)?  

- How does diet affect these, links to exterior mining, pollution, how are certain minerals absorbed into the body? Ingestion, particles, skin.

- How the tiny mining pill or injection or … will cope with the body’s regulatory mechanisms for metals such as copper and zinc? Pharmakon of poison and cure in terms of deficits and abundance of certain metals.

* 

- What are the physical and psychological side effects of both interior mining and increased intake of certain minerals?

- What are other cultural/mythological/historical practices of ingestion which might relate here?

- How are the extracted products eliminated from the body (saliva, urine, vomited stones, sweat, faeces)?

- What further processing and refinement would they be subject to?

- What knowledges do we immerse ourselves in and how might we also promote these sciences? How do we work with scientists?

* Social:

- What is the business model for the corporation, how does it extract profit and control and monitor extractions?

- What other contemporary businesses are close to this? For example, homeopathic chelation and what can we borrow in terms of messages and models?

- What is the message of the company - how does it promote itself as ecological? What other values does it promote?

- How is that message communicated corporately?

- What DIY models are there and what communities can we model ours on, what resources need to be made available? (eg. Transcranial magnetic stimulation - TMS, drug refining, smart drugs, homeopathic chelation)

* 

- What are the interests of the DIY community? How might certain other desires emerge in this movement? What language and terms might these desires be expressed within and how much can they be interwoven with or skewed by any potential side effects? 

- What artefacts (fetishes as well as tools) might be produced by the DIY community?

- How does the company work with or against the DIY extraction movement?

- How do the processes of extraction and refinement differ in both cases?

- What social and medical consequences could there be for sustained and global interior mining practices?


* Artistic/conceptual:

- How far is this a “real” project - what does it set out to achieve?

- What other projects or cultural artefacts operate in similar terrain and what can we learn from these?

- Other (cultural) projects which can relate: eg. (mediamatic)-resomation-saponification-and-taxidermy , quimera rosa, Anais Tondeur, Jacob Remin, speculative science fictions, post-continental philosophy - eg. Spinal Catastrophism, death studies

- What are potential outcomes?

- (research publications (medical trials), leaked video clip of an interview with a user, DIY tools and resources, the company formation as a real entity) 

* 

- Who are our collaborations?

- How best to kick-start the project?

- What are the conceptual consequences for say climate change, and anthropocene discourse? What is important within the notion of “internal geology”, what other disciplines or discourses contribute to this notion, how can we best formulate it?

- What does the project have to do with ideas of death and immortality? 


