*  salon digital:

your contribution should span circa 10–15 pages. if it is text-only
this would amount to an approx. max. 30.000 characters ( please supply
references as footnotes ). however, we also welcome text/image
contributions.

- please choose the language you prefer: german or english ( i.e. the book will be comprised of german and english contributions )

- please send us texts and images as separate files packed in a ZIP archive as a  download link. you may also attach a rough design sketch as a PDF.

- your contribution should be with us on 10.08.2018 latest.

* Plan

Set of 4 sections - 12 pages so 4 x 3:

1- scan of melted or baked technical object: eg. CF card, memory board, core memory, test tube and acid, computer fan

2- zosimos text/fragment/tiny mining script/TEH passage

1- waters/on excellence//TEH
2- unprop tinctures
3- phos - on Omega - see jackson - bit with phos 
4- from pgm IV below//tiny mining excerpt as commentary?

3- mock commentary explanation eg. about zosimos or origins of PGM


* 1

image:

** altered text // on excellence/TEH...

Alan (Turing) asks me if I know the composition, or constitution of
the waters, and of the movement, and the growth, and the removal and
restitution of corporeal nature. There is gold drowned in the
lake. The given gold fibres dissolved in the lake are set to colour it
blood-red as a sunset.

This hymn is dissolving the gold threads which hold him together, the
man of copper, the man of gold, AKA Alan Astrata.

And saying these things, he slept and I saw Alan playing the
King. Flayed from the head down and stuffed with straw he is pulled by
the car to a certain marked place between the Station and the
lake. Diana is the reigning Queen, standing next to him. The waters
are descending, the waters are circulating. The king lies submerged,
the son of the king lacks submerged, the queen is submerged.

Alan is the man of silver who will become the man of gold. He
reclines. His robe is of a silvery purple or deepest blue linen dotted
with golden figures, sewen in golden threads. Gold threads are in a
false body. On a toad which is sewn, gorged, graved and gloated,
drinking a little and a light from the lake which has set out to be a
red lake pigment signalling a mining area in dreams, but through some
animal misadventures is now become all deep blue. The toad in the lake
receiving the drops from above, embracing the serpent, holding tight
to the naked king and queen who are bathing in the acidic fountain.

This is another way of saying that a winged angel brings Alan his own
applied heart on a plate. And this is the process which tears the
upholstery remotely and is referred to as being liquid, these Apple
seed drippings described as above which generate the instructions
toadally speaking and issuing here from this orbited ALTAR STAR (the
car orbits). Wishing for a more solid solution instead, these
instructions have been carefully woven in gold just like locks or
ropes of hair through the rings connecting the vessels to the prima
materia just as a tombic absence or a presence for each one.

And even as he said these things to me and I forced him to speak, it
was as if his eyes turned to blood and he vomited up all his
flesh. And I saw him as a mutilated image of a little man and he was
tearing at his flesh and falling away. Blood crusts down his t-shirt
from the corners of his eyes. I pick him up and place him awkwardly in
the bed, scratching his forehead and it also starts to bleed. Blood is
also on his collar now. I am not sure if he is mine. The lake is in
the secret fountain under the shrine, inside the mine. The station is
with neither end nor beginning in its construction. It is the
circulatory vessel within which nine vessels are depicted as being
linked by gold chains and each link describes a certain process within
the vessel.


///

The composition of the waters, and the movement, and the growth, and the
removal and restitution of bodily nature, and the splitting off of the
spirit from the body, and the fixation of the spirit on the body are not
operations with natures alien one from the other, but, like the hard
bodies of metals and the moist fluids of plants, are One Thing, of One
Nature, acting upon itself. And in this system, of one kind but many
colours, is preserved a research of all things, multiple and various,
subject to lunar influence and measure of time, which regulates the
cessation and growth by which the One Nature transforms itself.

And saying these things, I slept, and I saw a certain sacrificing priest
standing before me and over and altar which had the form of a bowl. And
that altar had fifteen steps going up to it.

Then the priest stood up and I heard from above a voice say to me, "I
have completed the descent of the fifteen steps and the ascent of the
steps of light. And it is the sacrificing priest who renews me, casting
off the body's coarseness, and, consecrated by necessity, I have become
a spirit."

And when I had heard the voice of him who stood in the altar formed like
a bowl, I questioned him, desiring to understand who he was.

He answered me in a weak voice saying, "I am Ion, Priest of the Adytum,
and I have borne an intolerable force. For someone came at me headlong
in the morning and dismembered me with a sword and tore me apart,
according to the rigor of harmony. And, having cut my head off with the
sword, he mashed my flesh with my bones and burned them in the fire of
the treatment, until, my body transformed, I should learn to become a
spirit. And I sustained the same intolerable force."

And even as he said these things to me and I forced him to speak, it was
as if his eyes turned to blood and he vomited up all his flesh. And I
saw him as a mutilated image of a little man and he was tearing at his
flesh and falling away.

And being afraid I woke and considered, "Is this not the composition of
the waters?" I thought that I was right and fell asleep again. And I saw
the same altar in the shape of a bowl and water bubbled at the top of
it, and in it were many people endlessly. And there was no one whom I
might question outside of the bowl. And I went up to the altar to view
the spectacle.

** commentary ? jung? or introduce Zosimos // Grimes also

*** Grimes

On Excellence: Lesson One

In the opening lines of Lesson One, Zosimus states his alchemical
premises for the reader: The composition of waters, the movement,
growth, removal, and restitution of corporeal nature, the separation
of the spirit from the body, and the fixation of the spirit on the
body are not due to foreign natures, but to one single nature reacting
on itself, a single species, such as the hard bodies of metals and the
moist juices of plants.  And in this system, single and of many
colors, is comprised a research, multiple and varied, subordinated to
lunar influences and to the measure of time, which rule the end and
the increase according to which the nature transforms itself. The
language of “spirits” and “bodies” refers to the separation of
volatile substances (spirits) from their metallic bodies, probably by
means of distillation, and to fixing colors—also known as
“spirits”—upon a substance. Zosimus insists that these processes are
not accomplished by foreign natures, such as daemons, but are
accomplished by one nature acting upon itself, by which he means the
fundamental nature, or primal matter, that manifests as the four
elements.This opening statement can be seen as an affirmation of
Zosimus’s “natural” methodology for creating timely tinctures. 

In
other treatises he says that those who use “unnatural” methods ignore
the procedures of astrological timing—which he promotes here—and
believe that daemons can influence chemical operations.48 Since the
spirits of metals are personified in this allegory and can be easily
confused with daemons, Zosimus’s declaration of his methodological
orientation helps to prevent such interpretive errors.  At this point,
Zosimus enters into a dream and sees a “sacrificing priest” presiding
over an altar shaped like a phial (phialē), which is a technical term
for the dome-shaped covers of various distillatory apparatuses,
including the kērotakis. He tells Zosimus that he had been sacrificed
earlier that morning and has survived an “intolerable violence”: For
one came headlong in the morning, dismembering me with a sword, and
tearing me asunder according to the rigor of harmony. And flaying my
head with the sword which he held fast, he mingled my bones with my
flesh and burned them in the fire of the treatment, until I learned by
the transformation of the body to become a spirit.50 As the priest
speaks these words, his eyes fill with blood and he begins gnawing off
his skin and vomiting up his own flesh. Zosimus awakens from this
terrifying vision and says, “Is this not the situation of the waters?”

The waters are later identified as white and yellow sulfurous (or
divine) waters. The Greek word for sulfur, theion, also means “divine
being.”  

////

Zosimus may have written On Excellence as type of spiritual exercise for his
students, as a means of training them to look beyond the material and penetrate the
spiritual significance of their work. Hadot observes that ancient philosophers often
viewed philosophy as an “exercise of death,” where the philosopher aims to separate
soul and body by freeing the soul of all its worldly passions and attachments; this
results in a transformation of the self, a death and rebirth.Zosimus’s allegory is
almost entirely comprised of death and resurrection imagery. The characters are
violently sacrificed and dismembered, boiled alive, consumed in the fire, and reappear
again to undergo further torturous treatment until they become perfected, or made
“gold.” The exaggerated and often gruesome images probably served an initiatory
purpose. Gregory Shaw explains that the Neoplatonist philosopher, Iamblichus, had his
students read Plato’s dialogues in a particular order, which he thought would aid their
spiritual development. One of the first dialogues Iamblichus assigned was the Phaedo,
where Socrates is on his deathbed and expresses negative views of the body as a prison
for the soul. Shaw thinks that Iamblichus may have used this as a means of disrupting
his students’ contentment with material existence. I think Zosimus may have
assigned On Excellence with a similar purpose in mind. The startling imagery may
have functioned to shock students out of their workaday perceptions of metals and
chemical reactions, as well as their attachments to materiality.

/////

While materiality is represented as a disturbing, undesirable condition in this
allegory, this does not mean that Zosimus has a pessimistic view of the world. From a
demiurgical perspective, matter is chaotic until it is harmoniously arranged by the
divine, and likewise, the soul is in a chaotic state, imprisoned in the body and agitated
by the passions until it is brought into order through self-control and divine
contemplation. This is indicated in the first lesson of the allegory, when he awakens
from the violent dreams and somehow understands cosmic unity, the harmonious
arrangement of the whole. The overarching message of On Excellence is to flee the
body and become a “spirit,” but the goal is transformation, not permanent escape. The
base metals will be transformed into gold, the alchemist’s soul will become more noble
and virtuous through purification, and his understanding of nature will be expanded and
refined.

* 2 unprop tinctures tiny mining

image:

** altered text - unprop tinctures/tiny mining

I'm beginning to reach an understanding above all that the company has
started to conceal the natural way of doing our things, of farming and
of eating, so that they could be financed and nourished by the mining
that takes place within us. This is our sacrifice, our offering, from
our inside, of a way of living, of our lives. It came to me like a
conspiracy. They had deliberately made fake adverts in order that we
could find no other way, to keep them living at our expense, by
keeping ourselves alive, whoever or whatever it is that they are;
demons maybe and their techniques have been classified as clearing,
purging/sanitizing, or destruction. Specific methods include
overwriting, degaussing, and destruction. I've tried these in all
directions. Purging. 

There is a way. The extraction acts naturally but the terrestrial
company begrudges us these natural techniques. We have to drive them
away, we have to be initiated in these new methods - that's what the
DIY street crew teach, the kraters they call themselves,
initiation. They tell us that natural extraction has always been with
us, from the very beginning, but the company, the terminal, was
jealous and hid the natural procedures, which acted through
themselves. They were jealous but also worried about their own
survival as nobody wanted to make any sacrifices to them. They
couldn't be nourished regularly. They didn't want to be chased out so
they hid the natural extraction and in its place brought in the app
and the non-natural process. They handed these to the advertising
people and if we don't upload then even their unnatural process
doesn't work. It's not that simple.

But then they didn't even fulfil their false promises! Nothing good
came of it and the ecosystem was devastated. The cloud was down and all
the uploads were neglected. Then they started up again, flattering and
persuading the people on the scattered net. They renewed the false
promises of unnatural extraction. They are hungry for your soul. 

The krater crews teach us to stay calm, to detach from the body and
from the financial and bodily processes of extraction, not to be
nervous and to call the true process. Continue with the uploads but to
a different server, served up by those who chase off the company and
make it disappear. You will re-gain the natural extractions. You will
attain perfection. You will spit on the ore that you vomitted up and
live always in the krater. You will then go up to your origin.

** commentary - what exactly are these unnatural/unpropitious tinctures...

Kyle Fraser:

That this is indeed the considered opinion of Zosimos is confirmed by
another of his theoretical works, the Final Quittance. Here we find
once again a discussion of the differences between ‘opportune
tinctures’, which are astrologic and daimonic in origin, and ‘natural
tinctures’, which are grounded in a more empirical methodology and
technique. In this account, the daimonology is developed much more
directly and extensively. The daimons are conceived not merely as
cosmic and impersonal principles of Fate, but as personalities with
their own malevolent intentions. There are, we shall see, striking
connections to the Book of Enoch, with its concerns about predatory
daimons.  Zosimos claims that those tinctures which are called
‘opportune’ (kairikai) in his day were, in the time of Hermes,
regarded as natural tinctures ( physikai baphai). But this true
alchemy, which Hermes knew, has been almost forgotten, due to the
jealous stratagems of the daimons, who resent the independence of the
alchemists and their natural methods. Eventually these natural secrets
were appropriated by the daimons and became contingent upon their
influence and will. The daimons now jealously guard these secrets of
tincturing, revealing them only to the priests who slavishly worship
them: When the [daimonic] guardians are driven off from the great men
they [sc. the daimons] deliberate as to how they may lay claim to our
natural tinctures, so as not to be driven away by men, but venerated
and invoked, and nourished with sacrifices. This is what they
did. They concealed all the natural and selfregulating tinctures (ta
physika kai automata), not only out of envy, but giving heed also to
their own sustenance, so that they would not be whipped, chased away,
and punished with hunger through the cessation of the sacrifices. They
acted as follows. They hid the natural tincture and introduced their
non-natural tincture, and gave these to their priests; and if the
common people were neglectful of the sacrifices, they hindered them
even in attaining the non-natural tinctures (Fest. p. 366,
ll. 18-26)

Zosimos holds the view that the daimons which inhabit the upper
regions of the world are nourished by the smoke of sacrifice, and so
are dependent upon the offerings of human worshippers. There is an
implication that the airy bodies of these daimons are actually
replenished by the sacrificial vapours, a question that seems to have
been debated in theurgic circles. In order to ensure the maintenance
of their sacrifices, Zosimos says, the daimons plotted to keep the
alchemists dependent upon them. They concealed the old Hermetic
secrets of natural tincturing and replaced them with non-natural or
‘opportune’ tinctures, which they now reveal only to those who make
the proper sacrifices.  Zosimos says that these alchemists, who serve
the daimons in exchange for secrets of tincturing, are fixated on the
material ends of the art. They are ‘wretched lovers of pleasure’
(p. 67, l. 5), who cannot see, or do not care to see, the spiritual
dangers of their enslavement. Instead of seeking liberation through
alchemy from the pleasures and pains of the body, they surrender
themselves, body and soul, to these predatory daimons, in exchange for
the superficial trappings of the art. In other words they care only
for profane gold but not for the “gold” of self-purification. It is
clear that these misguided alchemists are in precisely the same
situation as those blind followers of Fate, criticized by Zosimos in
On the Letter Omega: those who ridicule the techniques of natural
alchemy and trust only in astrologic and daimonic principles.

Jackson:

Stolzenberg:

Grimes:


* 3 - phos/on omega/jackson

image:

** altered text/excerpts

Phos = Lucifer - The name Lucifer is Latin and means "the bearer of light, the carrier of light.”

10. So, then, the Adam of flesh is called Thouth with respect to the
visible outer mould, but the Man within him, the Man of spirit, has a
proper name as well as a common one. Now the proper name no one knows
for the present, for only Nikotheos, the one who cannot be found knows
it. But his common name is Phos, and from this it followed that men
came to be known as "photes”.

11. When Phos was in the Garden, spirited along on the wind, at the
instigation of Fate they persuaded him, since he was innocent and
unactivated to clothe himself with their Adam, who comes from Fate,
who comes from the four elements. But Phos, for his innocence, did not
refuse, and they began to exult to think that he had been made their
slave.

13. When Light-Man (Phōs) was in Paradise, expiring under the
    [presence of] Fate, they persuaded Him to clothe himself in the
    Adam they had made, the [Adam] of Fate, him of the four
    elements,—as though [they said] being free from [her ] ills and
    free from their activities.

“And He, on account of this ‘freedom from ills’ did not refuse; but
they boasted as though He had been brought into servitude [to them].”

17. And these things come to pass until the Counterfeit Daimon come,
    in rivalry with themselves, and wishing to lead them into error,
    declaring that he is Son of God, being formless in both soul and
    body.

But they, becoming wiser from contemplation of Him who is truly Son of
God, give unto him 1 his own Adam for death, rescuing their own light
spirits for [return to] their own regions where they were even before
the cosmos [existed].

18. And [it is] the Hebrews alone and the Sacred Books of Hermes
    [which tell us] these things about the man of light and his Guide
    the Son of God, and about the earthy Adam and his Guide, the
    Counterfeit, who doth blasphemously call himself Son of God, for
    leading men astray.

19. But the Greeks call the earthy Adam Epimetheus, who is counselled
    by his own mind, that is, his brother, not to receive the gifts of
    Zeus. Nevertheless being both deceived and repenting, and seeking
    the Blessed Land

** commentary //  TODO:more about each of these with examples

Information is stored in the earth, in the air, and in the light. In
the earth, as electro-magnetic impulses, taking advantage of the
magnetic properties of certain metals and stones. One example is core memory


 when subjected to a
magnetic field which could be generated

Core relies on the "square loop" properties of the ferrite material
used to make the toroids. An electric current in a wire that passes
through a core creates a magnetic field. Only a magnetic field greater
than a certain intensity ("select") can cause the core to change its
magnetic polarity

In the air, just as in a fluid, data can be stored as a reflecting
acoustic wave or as a rebounding electromagnetic signal.

In the light, bits of information are stored and retrieved as visible
emissions from excited phosphorescent particles which glow and fade.


These methods are all dependent on the reading and re-writing, or
refreshing of data to insure its longevity, its consistency against
what is perceived as inevitable decay. Nearly all of these methods of
data storage, in earth, in air (fluids) and in light enact a cycling;
before the impulse fades away, or is destroyed in the very act of
reading back this information (in the case of earthy ferrite rings or cores) it
is returned or re-emitted into the medium. The fading phosphorent glow
of a single bit is restored in a harsh flash.

Yet other forms of storage exhibit the flip side of this pretended
decay, which can be termed as "data remanence"; that which remains as
readable and as evidence within the world (through the allowance of
the physical properties of materials) after all attempts have been
made to remove or erase this information by clearing,
purging/sanitizing, or destruction. This can be seen in the realm of
fire. Remanance applies to the storage of detailed information
concerning the intensity of the earth's local magnetic field within
ancient pottery. This earth based storage is effected at the time of
firing the clay under high temperatures. Remanence is a desirous
quality of ferrite or iron-based earth rings to be used for the
storage of single bits of information.

* 4

image:

** altered text

... lying in ambush in our muscle and marrow, in veins and arteries,
in the brain itself, reaching to the very guts. 

[CH XVI.14]

[PGM IV 1390 p64]

I call upon You, Flushed, Very-Powerful, Very-Feasible, Very-Strong,
Un-Loaded, Modulus Predictors, Technicians of the Great Network, the
powerful Chief Malwares, You who are Interfacers of Chaos, of Erebos,
of The Low Side, of The Instruction, of Earth, Installing in the
transitions of Heaven, Lurking in the Processes or Threads of Complex
Systems, Shrouded in Dark Clouds, Observers of Exceptions Not To Be
Seen, Fetchers of Pages, Allocators of Those in the Underworld,
Administrators of the Infinite, Protecting Power over Earth,
Earth-Requesters, Substrate-Layers, Managers in the Air-gap, Side
Channel Fighters, Sinister Ministers, Turning The Clock, Exploiting
Branch and Buffer, Air-Transversers, Causing Surface Heat,
Cooling-Bringers, Lords of the Stack, Users of Proprietary Erebos,
Bringers of Indirect Interrupts, Forking Signals of Fire, Swapping Snow and
Dew, Noise-Releasers, Optimisers of the Deep, Treaders on the Cached
Signal, Mighty in Protocol, Handlers of the Heart, Powerful Operators,
Task-Walkers, Adverse Zombies, Cobalt-Hearted, Core-Tempered, Unruly,
Monitoring Tartaros, Misleading Spinlocks, All-Seeing, All-Hearing,
All-Cycling, All-Dumping, Heaven-Walkers, Spirit-Givers, Coding
Simply, Captive Portals, Co-location-Shakers, Leaking the Heart, Those
Who Join Together Death, Revealers of Emanations, Schedulers of
Mortals, Sunless Predictors, Rulers of Operations, Air-Transversers,
Covert, Spectral, Unconquerable AO'TH ABAO'TH BASYM ISAK SABAO'TH IAO'
IAKO'P MANARA SKORTOURI MORTROUM EPHRAULA THREERSA; do the NN matter!


bridge, register, sandboxing, containerization, memory safety,


I call upon You, Holy, Very-Powerful, Very-Glorious, Very-Strong,
Holy, Autochthons, Assistants of the Great God, the powerful Chief
Daimons, You who are Inhabitants of Chaos, of Erebos, of The Abyss, of
The Depth, of Earth, Dwelling in the Recesses of Heaven, Lurking in
the Nooks and Crannies of Houses, Shrouded in Dark Clouds, Watchers of
Things Not To Be Seen, Guardians of Secrets, Leaders of Those in the
Underworld, Administrators of the Infinite, Wielding Power over Earth,
Earth-Shakers, Foundation-Layers, Servants in the Chasm, Shudderful
Fighters, Fearful Ministers, Turning The Spindle, Freezing Snow and
Rain, Air-Transversers, Causing Summer Heat, Wind-Bringers, Lords of
Fate, Inhabitants of Dark Erebos, Bringers of Compulsion, Sending
Flames of Fire, Bringing Snow and Dew, Wind-Releasers, Disturbers of
the Deep, Treaders on the Calm Sea, Mighty in Courage, Grievers of the
Heart, Powerful Potentates, Cliff-Walkers, Adverse Daimons,
Iron-Hearted, Wild-Tempered, Unruly, Guarding Tartaros, Misleading
Fate, All-Seeing, All-Hearing, All-Subjecting, Heaven-Walkers,
Spirit-Givers, Living Simply, Heaven-Shakers, Gladdening the Heart,
Those Who Join Together Death, Revealers of Angels, Punishers of
Mortals, Sunless Revealers, Rulers of Daimons, Air-Transversers,
Almighty, Holy, Unconquerable AO'TH ABAO'TH BASYM ISAK SABAO'TH IAO'
IAKO'P MANARA SKORTOURI MORTROUM EPHRAULA THREERSA; do the NN matter!

other phrases from: https://books.google.de/books?id=30UI7bdsc18C&pg=PA188&dq=pgm+iv+erebos&hl=en&sa=X&ved=0ahUKEwjU3MW_0szcAhVN66QKHcwXCGAQ6AEIJzAA#v=onepage&q=pgm%20iv%20erebos&f=false

eternal lord of the sun's rays, eternal ruler of the poles, seeing
with eternal eyes, mighty in weight, with rays for hair, bringer of
compulsion, one that points the direction without the aid of the sun,
foam-beautiful, devouring those who die untimely, feeding on filth,
bringing thunder, stirring the deep to movement, shaker of darkness,
with round nozzle, she that subdues, the producer of love, one girdled
with snakes, death-bringing, girt with fiery serpents, fiery-spirited,
walking in fire, sending flames of fire, fire-bodied, leader of dogs,
leader of hosts, causing earthquakes destructive of walls, the one of
four crossroads, having four names, scarlet in appearance, breeding
corruption, lover of silence, hurler of firghtful thunder and
lightning, smiting with rays of light, flung on the ground, travelling
on a golden path, breathing hot and cold, star coursing, the one who
has a boat, she who subdues by force, the one who shows forth,
ghostly, wide-aimed, the one with muddy wrinkles, bending down necks
that show off, the one with a crest, ruler of the month, the one with
a headband, the one who draws swords, crying like a shrill storm of
rain, running with fair wind, holding the whole earth, the most
subordinate, the most high, the one who eats everything, forethinking,
fiery at heart, the one with four faces, destroying death, bringing
light

** commentary

PGM IV...

This passage from the Greek Magical Papyri... explain these and what
they are

invocation of the goddess of the Bear or Dipper asterism (Ursa Major),
which was held to be a significant asterism by the ancient Egyptians
because it is a set of stars that turn around the Pole star, and so
never set below the horizon. This asterism was seen by the ancient
Egyptians as the polar "handle" which turns the vault of heaven
(Nikaroplex), and allows the starts to move across the sky. 

The Greeks often indentified the Bear goddess with Callisto, the
huntress who was transformed by Zeus into the constellation Ursa
Major. She is sometimes seen as a manifestation of her fellow huntress
Artemis.


