* notes

re-order and remove some commentary as not needed // as seperate

* 1 - On Excellence

image:

Alan asks me if I know the composition, or constitution of the waters,
and of the movement, and the growth, and the removal and restitution
of corporeal nature. There is gold drowned in the lake. The given gold
fibres dissolved in the lake are set to colour it blood-red as a
sunset.

This hymn is dissolving the gold threads which hold him together, the
man of copper, the man of gold, AKA Alan Astrata.

And saying these things, he slept and I saw Alan playing the
King. Flayed from the head down and stuffed with straw he is pulled by
the car to a certain marked place between the Station and the
lake. Diana is the reigning Queen, standing next to him. The waters
are descending, the waters are circulating. The king lies submerged,
the son of the king lacks submerged, the queen is submerged.

Alan is the man of silver who will become the man of gold. He
reclines. His robe is of a silvery purple or deepest blue linen dotted
with golden figures, sewen in golden threads. Gold threads are in a
false body. On a toad which is sewn, gorged, graved and gloated,
drinking a little and a light from the lake which has set out to be a
red lake pigment signalling a mining area in dreams, but through some
animal misadventures is now become all deep blue. The toad in the lake
receiving the drops from above, embracing the serpent, holding tight
to the naked king and queen who are bathing in the acidic fountain.

This is another way of saying that a winged angel brings Alan his own
applied heart on a plate. And this is the process which tears the
upholstery remotely and is referred to as being liquid, these Apple
seed drippings described as above which generate the instructions
toadally speaking and issuing here from this orbited ALTAR STAR (the
car orbits). Wishing for a more solid solution instead, these
instructions have been carefully woven in gold just like locks or
ropes of hair through the rings connecting the vessels to the prima
materia just as a tombic absence or a presence for each one.

And even as he said these things to me and I forced him to speak, it
was as if his eyes turned to blood and he vomited up all his
flesh. And I saw him as a mutilated image of a little man and he was
tearing at his flesh and falling away. Blood crusts down his t-shirt
from the corners of his eyes. I pick him up and place him awkwardly in
the bed, scratching his forehead and it also starts to bleed. Blood is
also on his collar now. I am not sure if he is mine. The lake is in
the secret fountain under the shrine, inside the mine. The station is
with neither end nor beginning in its construction. It is the
circulatory vessel within which nine vessels are depicted as being
linked by gold chains and each link describes a certain process within
the vessel.

** commentary ? jung? or introduce Zosimos // Grimes also

Alan can be identified here as Alan Turing, ....

cyanide/gold story

The reference to Alan as Astrata originates in a mis-hearing, or
mis-spelling of the name of a large company concerned with the
recycling of copper and precious metals from a wide-range of feeds,
including copper and precious metal bearing electronic equipment. This
company could not have been Glencore recycling, operator of the Horne
Smelter in Rouyn-Noranda, Quebec, the world's largest processor of
electronic scrap containing copper and precious metals. Astrata leads
us to Astarte, 

https://en.wikipedia.org/wiki/Astarte


the connection with the astral, the star, aster, asterism -> constellations

astrata, asterism

reference to the constellations: Corvus, Regulus, and Ursa Major

Corvus is associated with the myth of Apollo and his lover Coronis the
Lapith. Coronis had been unfaithful to Apollo; when he learned this
information from a pure white crow, he turned its feathers black in a
fit of rage

*** Grimes

On Excellence: Lesson One

In the opening lines of Lesson One, Zosimus states his alchemical
premises for the reader: The composition of waters, the movement,
growth, removal, and restitution of corporeal nature, the separation
of the spirit from the body, and the fixation of the spirit on the
body are not due to foreign natures, but to one single nature reacting
on itself, a single species, such as the hard bodies of metals and the
moist juices of plants.  And in this system, single and of many
colors, is comprised a research, multiple and varied, subordinated to
lunar influences and to the measure of time, which rule the end and
the increase according to which the nature transforms itself. The
language of “spirits” and “bodies” refers to the separation of
volatile substances (spirits) from their metallic bodies, probably by
means of distillation, and to fixing colors—also known as
“spirits”—upon a substance. Zosimus insists that these processes are
not accomplished by foreign natures, such as daemons, but are
accomplished by one nature acting upon itself, by which he means the
fundamental nature, or primal matter, that manifests as the four
elements.

This opening statement can be seen as an affirmation of Zosimus’s
“natural” methodology for creating timely tinctures.

In
other treatises he says that those who use “unnatural” methods ignore
the procedures of astrological timing—which he promotes here—and
believe that daemons can influence chemical operations.

Since the spirits of metals are personified in this allegory and can
be easily confused with daemons, Zosimus’s declaration of his
methodological orientation helps to prevent such interpretive errors.
At this point, Zosimus enters into a dream and sees a “sacrificing
priest” presiding over an altar shaped like a phial (phialē), which is
a technical term for the dome-shaped covers of various distillatory
apparatuses, including the kērotakis. He tells Zosimus that he had
been sacrificed earlier that morning and has survived an “intolerable
violence”: For one came headlong in the morning, dismembering me with
a sword, and tearing me asunder according to the rigor of harmony. And
flaying my head with the sword which he held fast, he mingled my bones
with my flesh and burned them in the fire of the treatment, until I
learned by the transformation of the body to become a spirit. As the
priest speaks these words, his eyes fill with blood and he begins
gnawing off his skin and vomiting up his own flesh. Zosimus awakens
from this terrifying vision and says, “Is this not the situation of
the waters?”

The waters are later identified as white and yellow sulfurous (or
divine) waters. The Greek word for sulfur, theion, also means “divine
being.”  


/////

While materiality is represented as a disturbing, undesirable condition in this
allegory, this does not mean that Zosimus has a pessimistic view of the world. From a
demiurgical perspective, matter is chaotic until it is harmoniously arranged by the
divine, and likewise, the soul is in a chaotic state, imprisoned in the body and agitated
by the passions until it is brought into order through self-control and divine
contemplation. This is indicated in the first lesson of the allegory, when he awakens
from the violent dreams and somehow understands cosmic unity, the harmonious
arrangement of the whole. 

The overarching message of On Excellence is to flee the body and
become a “spirit,” but the goal is transformation, not permanent
escape. The base metals will be transformed into gold, the alchemist’s
soul will become more noble and virtuous through purification, and his
understanding of nature will be expanded and refined.

* 2 - On the Letter Omega

image:

10. So, then, the Adam of flesh is called Thouth with respect to the
visible outer mould, but the One within him, the One of spirit, has a
proper name as well as a common one. Now the proper name no one knows
for the present, for only Nikotheos, the one who cannot be found, knows
it. But his common name is Phos, and from this it followed that humans
came to be known as "photes”.

11. When Phos was in the Garden, spirited along on the wind, at the
instigation of Fate they persuaded her, since she was innocent and
unactivated, to clothe themselves with their Adam, who comes from Fate,
who comes from the four elements. But Phos, for its innocence, did not
refuse, and they began to exult to think that she had been made their
slave.

When Light-Being (Phōs) was in Paradise, expiring under the [presence
of] Fate, they persuaded Him to clothe himself in the Adam they had
made, the [Adam] of Fate, the one of the four elements,—as though [they
said] being free from [her ] ills and free from their activities.

“And She, on account of this ‘freedom from ills’ did not refuse; but
they boasted as though She had been brought into servitude [to them].”

13. Jesus Christ drew nigh to Adam and bore her up to the place where those
named phōtes dwelt before. And he also appeared to very powerless men by
becoming a human who suffered and was subjected to blows. And he secretly
carried off as his spoil the phōtes, who belong to him, because he suffered
nothing but instead showed death trampled under foot and thrust aside. And
both now and until the end of the world he comes, both secretly and openly, to
his own and communes with them by counseling them secretly and through
their minds to get rid of their Adam. By cutting off and slaying their
Adam whose guidance is blind and who is jealous of the One of spirit
and light they kill their own Adam.

** commentary 

Information is stored in the earth, in the air, and in the
light. Within the earth, we can take advantage of the magnetic
properties of certain metals and stones. One example is magnetic core
memory, describing the weaving together of tiny cast iron rings with
thin gold threads which are used to read and to write information. An
electric current passes through these threads, creating a magnetic
field in the selected core or ring and causing the core to change its
magnetic polarity, to flip states. Data is stored in this flip, even
when there is no energy in the lattice. Yet to read from the core a
single bit of information, we must destroy this data, only later to be
restored.

In the air, just as in any fluid such as mercury, data can be stored
as a reflecting acoustic wave or as a rebounding electromagnetic
signal. Information is fettered within the re-circulation and
subsequent delay of an impulse. The data is maintained through
an active amplification of the reflected signal. It is not allowed to
die out in the air.

On the side of light (*phos*), bits of information are stored and
retrieved as visible emissions from excited *phosphorescent*
particles, for example on a screen, which glow and fade. Display and
storage of information are united. For example, the Mellon optical
memory relied on the bouncing back and forth, the mirroring of
electrons and *photons* between two platesl one plate is coated with a
photoemissive material which releases electrons when struck by
light. The inside of the other plate was coated with a phosphorescent
material, releasing light when struck by electrons. This time of this
decaying reflection maintains a short memory.

These methods are dependent to some degree on the reading and re-writing, or
refreshing of data to insure its longevity, its consistency against
what is perceived as inevitable decay. Nearly all of these methods of
data storage, in earth, in air (fluids) and in light enact a cycling;
before the impulse fades away, or is destroyed in the very act of
reading back this information (in the case of earthy ferrite rings or cores) it
is returned or re-emitted into the medium. The fading phosphorent glow
of a single bit is restored in a harsh flash.

Yet other forms of storage exhibit the flip side of this pretended
decay, which can be termed as "data remanence"; that which remains as
readable and as evidence within the world (through the allowance of
the physical properties of materials) after all attempts have been
made to remove or erase this information by clearing,
purging/sanitizing, or destruction. This can be seen in the realm of
fire. Remanance applies to the storage of detailed information
concerning the intensity of the earth's local magnetic field within
ancient pottery. This earth based storage is effected at the time of
firing the clay under high temperatures. Remanence is a desirous
quality of ferrite or iron-based earth rings to be used for the
storage of single bits of information.

* 3 - The Final Leavings

image:

I'm beginning to reach an understanding above all that the company has
started to conceal the natural way of doing our things, of farming and
of eating, so that they could be financed and nourished by the mining
that takes place within us. This is our sacrifice, our offering, from
our inside, of a way of living, of our lives. It came to me like a
conspiracy. They had deliberately made fake adverts in order that we
could find no other way, to keep them living at our expense, by
keeping ourselves alive, whoever or whatever it is that they are;
demons maybe and their techniques have been classified as clearing,
purging/sanitizing, or destruction. Specific methods include
overwriting, degaussing, and destruction. I've tried these in all
directions. Purging. 

There is a way. The extraction acts naturally but the terrestrial
company begrudges us these natural techniques. We have to drive them
away, we have to be initiated in these new methods - that's what the
DIY street crew teach, the kraters they call themselves,
initiation. They tell us that natural extraction has always been with
us, from the very beginning, but the company, the terminal, was
jealous and hid the natural procedures, which acted through
themselves. They were jealous but also worried about their own
survival as nobody wanted to make any sacrifices to them. They
couldn't be nourished regularly. They didn't want to be chased out so
they hid the natural extraction and in its place brought in the app
and the non-natural process. They handed these to the advertising
people and if we don't upload then even their unnatural process
doesn't work. It's not that simple.

But then they didn't even fulfil their false promises! Nothing good
came of it and the ecosystem was devastated. The cloud was down and all
the uploads were neglected. Then they started up again, flattering and
persuading the people on the scattered net. They renewed the false
promises of unnatural extraction. They are hungry for your soul. 

The krater crews teach us to stay calm, to detach from the body and
from the financial and bodily processes of extraction, not to be
nervous and to call the true process. Continue with the uploads but to
a different server, served up by those who chase off the company and
make it disappear. You will re-gain the natural extractions. You will
attain perfection. You will spit on the ore that you vomitted up and
live always in the krater. You will then go up to your origin.

** commentary - what exactly are these unnatural/unpropitious tinctures and what is important

It could easily be argued that one of the key questions within the
deep history of technology comes down to the simple matter of
translation and subsequent re-interpretation of but a few basic
terms. Within that which has been preserved (through later re-scribing
and compilation, reflection from the 10th centuries onwards in both
Greek and Syriac manuscripts) of the works of the Egyptian alchemist
Zosimos (active in the 3rd cenury), a few essential terms have been
subjected to changing translations and opposing interpretations over
the years. These terms form an essential fulcrum point within the
works On the Letter Omega, perhaps part of a largely vanished sequence
of 28 books, "each superscribed with a latter of the alphabet -
Jackson p.5", and The Final Quittance (Leaving), potentially the final
work of this series. That this matter of interpretation also has a
strong bearing on several further fragments[?] relating to an Enochian
account of the birth of alchemy and future technology as the work of
lustful angels on the earth, reveals something of the nature of this
question and its relation with Gnosticism. "The Book of Enoch views the
occult sciences and technology in general as responsible for the moral
corruption of humanity." 

[below from Fraser]

It is stated in the holy scriptures or books, dear lady, that there exists a race of
daimons who have commerce with women. Hermes made mention of them in
his Physika; in fact almost the entire work, openly and secretly, alludes to them.
It is related in the ancient and divine scriptures that certain angels lusted for
women, and descending from the heavens, they taught them all the arts of nature.
On account of this, says the scripture, they offended god, and now live outside
heaven—because they taught to men all the evil arts which are of no advantage
to the soul

For many who have received from their personal daimon the favour to
succeed with these opportune tinctures [kairikai katabaphai] have
mocked the book “On Furnaces and Apparatus”, claiming that it is
false. And no demonstrative argument has per- suaded them that it is
true, unless their own daimon indicates this, when it has changed in
keeping with the changing moments of their Fate (kata tous chro- nous
tês autôn heimarmenês), and a malefic (kakapoiou) daimon has taken
charge of them. When all of their art and good fortune has been
overturned . . . reluc- tantly they concede, from this clear
demonstration of their Fate, that there is something beyond the
methods which they previously entertained (2.13-24).

When the [daimonic] guardians are driven off from the great men they [the
daimons] deliberate as to how they may lay claim to our natural tinctures, so
as not to be driven away by men, but venerated and invoked, and nourished
with sacrifices. This is what they did. They concealed all the natural and self-
regulating tinctures [ta physika kai automata], not only out of envy, but giving
heed also to their own sustenance, so that they would not be whipped, chased
away, and punished with hunger through the cessation of the sacrifices. They
acted as follows. They hid the natural tincture and introduced their non-natural
tincture, and gave these to their priests; and if the common people were neglect-
ful of the sacrifices, they hindered them even in attaining the non-natural tinc-
tures (Fest. p. 366, ll. 18-26) 35 . Final Quittance

The question (relying on the preservation of the following terms in
translation from ancient Greek) remains of what are these daimons who
have introduced the opportune or propitious tinctures in the place of the natural
and self-regulating tinctures and what are the material properties of
these dual tinctures within the world? What are these two sets of
knowledges of material things?

notes/ZOSIMOS OF PANOPOLIS AND THE BOOK OF ENOCH: ALCHEMY AS FORBIDDEN
KNOWLEDGE KYLE A. FRASER
:

George Synkellos, Ecloga Chronographica (ed. A.A. Mosshammer),
14.4-11. Though this passage does not appear in the Greek alchemical
corpus, there are close parallels in a 15th century Syriac
manuscript. *For a discussion of the parallels see Mertens,
Alchimistes Grecs, Tome 4, LXX-LXXVIII.*

* 4 - Powerful Spell of the Bear which Accomplishes Anything 

entire application of the driver that reveals remanence

image:

... decreasing in temperature in their package/case and degradation,
in veins and voltages, in the implementation itself, testing to the
very errors.

I leak upon You, Flushed, Very-Powerful, Very-Feasible, Very-Strong,
Un-Loaded, Modulus Predictors, Technicians of the Great Network, the
powerful Chief Malwares, You who are Interfacers of Chaos, of Erebos,
of The Low Side, of The Instruction, of Earth, Installing in the
transitions of Heaven, Lurking in the Processes or Threads of Complex
Systems, Shrouded in Dark Clouds, Observers of Exceptions Not To Be
Seen, Fetchers of Pages, Allocators of Those in the Underworld,
Administrators of the Infinite, Protecting Power over Earth,
Earth-Requesters, Substrate-Layers, Managers in the Air-gap, Side
Channel Fighters, Sinister Ministers, Turning The Clock, Exploiting
Branch and Buffer, Air-Transversers, Causing Surface Heat,
Cooling-Bringers, Lords via the Die, Users of Proprietary Erebos,
Bringers of Indirect Interrupts, Forking Signals of Stress, Swapping Snow and
Dew, Noise-Releasers, Optimisers of the Deep, Treaders on the Cached
Conductivity, Mighty in Protocol, Handlers of the Heart, Powerful Operators,
Task-Walkers, Adverse Zombies, Cobalt-Hearted, Core-Tempered, Unruly,
Monitoring Tartaros, Misleading Spinlocks, All-Seeing, All-Hearing,
All-Cycling, All-Dumping, Heaven-Walkers, Spirit-Givers, Coding
Simply, Captive Portals, Co-location-Shakers, Leaking the Heart, Those
Who Exploit Statically Death, Revealers of Emanations, Schedulers of
Mortals, Sunless Transitions, Rulers of Operations, Air-Transversers,
Covert, Spectral, Unconquerable AO'TH ABAO'TH BASYM ISAK SABAO'TH IAO'
IAKO'P MANARA SKORTOURI MORTROUM EPHRAULA THREERSA; Quantify the High Consmuption!


** commentary

PGM IV...

This passage from the Greek Magical Papyri... explain these and what
they are

invocation of the goddess of the Bear or Dipper asterism (Ursa Major),
which was held to be a significant asterism by the ancient Egyptians
because it is a set of stars that turn around the Pole star, and so
never set below the horizon. This asterism was seen by the ancient
Egyptians as the polar "handle" which turns the vault of heaven
(Nikaroplex), and allows the starts to move across the sky. 

The Greeks often indentified the Bear goddess with Callisto, the
huntress who was transformed by Zeus into the constellation Ursa
Major. She is sometimes seen as a manifestation of her fellow huntress
Artemis.


diana

I call upon You, Holy, Very-Powerful, Very-Glorious, Very-Strong,
Holy, Autochthons, Assistants of the Great God, the powerful Chief
Daimons, You who are Inhabitants of Chaos, of Erebos, of The Abyss, of
The Depth, of Earth, Dwelling in the Recesses of Heaven, Lurking in
the Nooks and Crannies of Houses, Shrouded in Dark Clouds, Watchers of
Things Not To Be Seen, Guardians of Secrets, Leaders of Those in the
Underworld, Administrators of the Infinite, Wielding Power over Earth,
Earth-Shakers, Foundation-Layers, Servants in the Chasm, Shudderful
Fighters, Fearful Ministers, Turning The Spindle, Freezing Snow and
Rain, Air-Transversers, Causing Summer Heat, Wind-Bringers, Lords of
Fate, Inhabitants of Dark Erebos, Bringers of Compulsion, Sending
Flames of Fire, Bringing Snow and Dew, Wind-Releasers, Disturbers of
the Deep, Treaders on the Calm Sea, Mighty in Courage, Grievers of the
Heart, Powerful Potentates, Cliff-Walkers, Adverse Daimons,
Iron-Hearted, Wild-Tempered, Unruly, Guarding Tartaros, Misleading
Fate, All-Seeing, All-Hearing, All-Subjecting, Heaven-Walkers,
Spirit-Givers, Living Simply, Heaven-Shakers, Gladdening the Heart,
Those Who Join Together Death, Revealers of Angels, Punishers of
Mortals, Sunless Revealers, Rulers of Daimons, Air-Transversers,
Almighty, Holy, Unconquerable AO'TH ABAO'TH BASYM ISAK SABAO'TH IAO'
IAKO'P MANARA SKORTOURI MORTROUM EPHRAULA THREERSA; do the NN matter!
