*  new sonic acts - more emphasis on algorithmic


Sonic Acts: OVEREXPOSED/Particulate - 3000 characters

/quote from software book/

OVEREXPOSED/Particulate focusses on the materiality of particles and
pollution, exploring directly and physically how these become encoded
in bodies within the framework of the becoming-geological of
humankind. What I'm interested in is exploring direct connections
between particulate phenomena (from collective breath, exhalation, to
global anthropogenic discharges of smoke and cumulative particle
emissions) and the algorithmic/software, in the sense that pollution
encodes certain bodies, inscribing tracers and markers of capital's
flows within bodies, and finally rendering up these bodies for further
scientific study and manipulation (both as subjects and global
markers). Pollution and its corrolary, anthropogenic air-borne
particulate matter, are equally subject to multiple algorithmic
exchanges, flows and manipulations, for example in the direct cases of
cryptocurrency mining or of more literal and dusty extractive
operations. The flows of pollution and particles are generated by, and
thus trace and mirror, the energetic exchanges engendered by
algorithmic financial operations and instruments. At the same time,
particulate matter shares the event-driven temporality of the
algorithmic, of software, yet is subject to the continuous time
constraints of an equally algorithmic "nature" inscribed within
modelled, feedback loops of global warming.

It is this precise intersection of flows of bodies, particles and
algorithms which I will explore in writing and in practice during the
residency, building on the practical work enacted by the Tiny Mining
project, which commenced an investigation into the implications of the
becoming-geological of humankind. Within this project the questionable
term of the anthropocene was re-written as the ingestion and
inhalation of our "own" entry point into geological time.

The residency would focus on the creation of various practical case
studies which explore these points of intersection; for example
investigating how particulate indicators (radioactive or otherwise)
can be measured and traced through my own body, how literal
algorithmic actions could result in the generation of particles, and
what connections exist between software and energetic exchanges which
take part in particulate flows.

These case studies would be documented and described in the research
journal, and act as entry points or stimuli for a speculative,
theoretical text which could also be described as a series of
meditations on becoming-geological, playing out across the timescales
of the geological, and the algorithmic. A final performative
presentation/demonstration would expose and activate aspects of these
studies, acting itself as a reflexive case study for a particle-bound
audience.


* biog to rewrite???

Biog:

Martin Howse is occupied with an investigation of the links between
the earth (its living creatures and geophysical phenomena), software
and the human psyche (psychogeophysics) through the construction of
experimental situations (performance, laboratories, walks, and
workshops), material art works and texts.

From 1998 to 2005 Howse was director of ap, a software performance
group working with electronic waste, pioneering an early approach to
digital glitch. From 2007 to 2009 he hosted a regular workshop,
micro-residency and salon series in Berlin. Howse has worked and
collaborated on acclaimed projects and material practices such as The
Crystal World, Psychogeophysics, Earthboot, Sketches towards an Earth
Computer, Dissolutions and, most recently, Tiny Mining. For the last
fifteen years he has initiated numerous open-laboratory style projects
and performed, published, lectured and exhibited worldwide. He is
equally the creator of the skin-driven audio divination noise module,
The Dark Interpreter, and the ERD modular synthesizer series.



* rotting symposium

* for rotting sounds 2019 exhibition and workshop

** exhibition: Enrichment and depletion

TODO:
- build environment, run test code baremetal
- fast interrupt out
- pulse in within 400 per second interrupt (as long as is zero we wait
  for a one in delayed loop)...
- test output and low pass
- tweaks

- sigma delta with rock/radioactive decay, uv light - ingestion of rock in dying animal?

pulses with clock are stored and looped very fast -> low pass

- read in with clock at 400 khz (for 200cps average - we may need to
  extend pulse time to catch pulses as bits), output/loop round output
  up to last recorded and max buffersize
- on pi? raw? as we need lots of memory for storage

http://www.valvers.com/open-software/raspberry-pi/step01-bare-metal-programming-in-cpt1/

- low pass?

[what were we doing which also used looped storage and playback of bits? was from myx/sdcard so not so applicable....]

- where is PSU? - in the peli box!


** workshop: Circulation corruption.

All technology that is derived of earth, must be decomposed and again
reduced to earth.
[Basil Valentine]

Old earth, no more lies, I've seen you, it was me, with my other
ravening eyes, too late.
[Samuel Beckett]

Circulation and corruption (workshop) examines the various
circulations of media through the matters and bodies of the earth and
atmosphere, and through a certain corruption or dissolution of
(digital) identity, meaning and description.

Within a one and a half day hands-on, speculative workshop we will
collectively explore the interfaces and exchanges between living
systems (earth, compost, worms, mycelium) and active audio
electronics. We will participate primarily with our hands and our ears
within circulations amongst earths, composts, mushroom mycelium,
moulds, active chemistry, worms, crows, dusts, smokes and fogs and
impulses and waves.

During the workshop we will construct a series of open circuits which
do not conceal their materiality but participate equally within
material and electrochemical exchanges and circulations. These
circuits are inspired through a media archaeology of electronic music
production, and through the history of alchemical engagement with
minerals, with decay and with the earth. These technical and
conceptual influences are equally opened to circulation and corruption during
the workshop.

We will work with a range of materials (for example, machine cut
copper sheets and oyster mushroom mycelium) and approaches (for
example, with radio transmission and signal reception) to design and
build these open circuits which will enter into processes of
appreciable decay, corruption and dissolution. These open circuits
will be placed during the workshop in selected interior and exterior
locations to participate in various time scales of deterioration and
degradation.

ouroboros, latch and comparator circuits opened to moulds and decay, fungi, degradation


