#+TITLE: circulation/corruption reader
#+AUTHOR: anonymous
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) 
#+CATEGORY:   geophysics
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE)
#+latex_header: \usepackage[a4paper,includeheadfoot,margin=2.54cm]{geometry}
#+latex_header: \usepackage[final]{pdfpages}.

\includegraphics[width=40em]{/root/org/images/halley.jpg}

\includegraphics[width=40em]{resources/Donum_Dei_MPH_123_3.jpg}

* Circulations and corruption

\includegraphics[width=40em]{resources/K068882sm.jpeg}

\includegraphics[width=40em]{resources/K066056sm.jpeg}

It is a living thing, which no more dies, but when used gives an eternal increase.
[Splendor Solis]

Let the waters above the heavens fall and the earth will yield its fruit

A serpent and a toad coming up above the earth (literally 'stepping
up above,') is our Magistery.

The way up and the way down [are] one and the same [...] Fire, water,
earth are the way down, and earth, water, fire is the way up. And
these two ways are forever being traversed in opposite directions at once.

[Heraclitus]

\includegraphics[width=40em]{resources/K150158sm.jpeg}

\includegraphics[width=40em]{resources/K150156sm.jpeg}

\includegraphics[width=40em]{/root/org/images/tcb.jpg}

\includegraphics[width=50em]{resources/harleysm.jpeg}

\includegraphics[width=50em]{resources/ashmolesm.jpeg}


* Anna Lowenhaupt Tsing. The Mushroom at the End of the World

We are contaminated by our encounter; they change who we are as we
make way for others. As contamination changes world-making projects,
mutual worlds and new directions may emerge. Everyone carries a
history of contamination; purity is not an option. One value of
keeping precarity in mind is that it makes us remember that changing
with circumstances is the stuff of survival. 

Collaboration means working across difference, which leads to
contamination. Without collaborations, we all die. 

[Anna Lowenhaupt Tsing. The Mushroom at the End of the World]

* Samuel Beckett - Molloy, later reprinted separately under the title of "Sucking-Stones". 

I took advantage of being at the seaside to lay in a store of
sucking-stones. They were pebbles but I call them stones. Yes, on this
occasion I laid in a considerable store. I distributed them equally
between my four pockets, and sucked them turn and turn about. This
raised a problem which I first solved in the following way. I had say
sixteen stones, four in each of my four pockets these being the two
pockets of my trousers and the two pockets of my greatcoat.

Taking a stone from the right pocket of my greatcoat, and putting it
in my mouth, I replaced it in the right pocket of my greatcoat by a
stone from the right pocket of my trousers, which I replaced by a
stone from the left pocket of my trousers, which I replaced by a stone
from the left pocket of my greatcoat, which I replaced by the stone
which was in my mouth, as soon as I had finished sucking it. Thus
there were still four stones in each of my four pockets, but not quite
the same stones. And when the desire to suck took hold of me again, I
drew again on the right pocket of my greatcoat, certain of not taking
the same stone as the last time. And while I sucked it I rearranged
the other stones in the way I have just described. And so on.

But this solution did not satisfy me fully. For it did not escape me
that, by an extraordinary hazard, the four stones circulating thus
might always be the same four. In which case, far from sucking the
sixteen stones turn and turn about, I was really only sucking four,
always the same, turn and turn about. But I shuffled them well in my
pockets, before I began to suck, and again, while I sucked, before
transferring them, in the hope of obtaining a more general circulation
of the stones from pocket to pocket. But this was only a makeshift
that could not long content a man like me. So I began to look for
something else.

And the first thing I hit upon was that I might do better to transfer
the stones four by four, instead of one by one, that is to say, during
the sucking, to take the three stones remaining in the right pocket of
my greatcoat and replace them by the four in the right pocket of my
trousers , and these by the four in the left pocket of my trousers,
and these by the four in the left pocket of my greatcoat, and finally
these by the three from the right pocket of my greatcoat, plus the
one, as soon as I had finished sucking it, which was in my mouth.
Yes, it seemed to me at first that by so doing I would arrive at a
better result.

But on further reflection I had to change my mind and confess that the
circulation of the stones four by four came to exactly the same thing
as their circulation one by one. For if I was certain of finding each
time, in the right pocket of my greatcoat, four stones totally
different from their immediate predecessors, the possibility
nevertheless remained of my always chancing on the same stone, within
each group of four, and consequently of my sucking, not the sixteen
turn and turn about as I wished, but in fact four only, always the
same, turn and turn about. So I had to seek elswhere than in the mode
of circulation. For no matter how I caused the stones to circulate, I
always ran the same risk.

It was obvious that by increasing the number of my pockets I was bound
to increase my chances of enjoying my stones in the way I planned,
that is to say one after the other until their number was
exhausted. Had I had eight pockets, for example, instead of the four I
did have, then even the most diabolical hazard could not have
prevented me from sucking at least eight of my sixteen stones, turn
and turn about. The truth is I should have needed sixteen pockets in
order to be quite easy in my mind. And for a long time I could see no
other conclusion than this, that short of having sixteen pockets, each
with its stone, I could never reach the goal I had set myself, short
of an extraordinary hazard. And if at a pinch I could double the
number of my pockets, were it only by dividing each pocket in two,
with the help of a few safety-pins let us say, to quadruple them
seemed to be more than I could manage. And I did not feel inclined to
take all that trouble for a half-measure.

For I was beginning to lose all sense of measure, after all this
wrestling and wrangling, and to say, All or nothing. And if I was
tempted for an instant to establish a more equitable proportion
between my stones and my pockets , by reducing the former to the
number of the latter, it was only for an instant. For it would have
been an admission of defeat. And sitting on the shore, before the sea,
the sixteen stones spread out before my eyes, I gazed at them in anger
and perplexity. For just as I had difficulty in sitting in a chair,
or in an arm-chair, because of my stiff leg, you understand, so I had
none in sitting on the ground, because of my stiff leg and my
stiffening leg, for it was about this time that my good leg, good in
the sense that it was not stiff, began to stiffen. I needed a prop
under the ham you understand, and even under the whole length of the
leg, the prop of the earth. And while I gazed thus at my stones,
revolving interminable martingales all equally defective, and crushing
handfuls of sand, so that the sand ran through my fingers and fell
back on the strand, yes, while thus I lulled my mind and part of my
body, one day suddenly it dawned on me, dimly, that I might perhaps
achieve my purpose without increasing the number of my pockets, or
reducing the number of my stones, but simply by sacrificing the
principle of trim.

The meaning of this illumination, which suddenly began to sing within
me, like a verse of Isaiah, or of Jeremiah, I did not penetrate at
once, and notably the word trim, which I had never met with, in this
sense, long remained obscure. Finally I seemed to grasp that this word
trim could not here mean anything else, anything better, than the
distribution of the sixteen stones in four groups of four, one group
in each pocket, and that it was my refusal to consider any
distribution other than this that had vitiated my calculations until
then and rendered the problem literally insoluble. And it was on the
basis of this interpretation, whether right or wrong, that I finally
reached a solution, inelegant assuredly, but sound, sound.

Now I am willing to believe, indeed I firmly believe, that other
solutions to this problem might have been found and indeed may still
be found, no less sound, but much more elegant than the one I shall
now describe, if I can. And I believe too that had I been a little
more insistent, a little more resistant, I could have found them
myself. But I was tired, but I was tired, and I contented myself
ingloriously with the first solution that was a solution, to this
problem. But not to go over the heartbreaking stages through which I
passed before I came to it here it is, in all its hideousness.

All (all!) that was necessary was to put, for example, six stones in
the right pocket of my greatcoat, or supply pocket, five in the right
pocket of my trousers, and five in the left pocket of my trousers,
that makes the lot, twice five ten plus six sixteen, and none, for
none remained, in the left pocket of my greatcoat, which for the time
being remained empty, empty of stones that is, for its usual contents
remained, as well as occasional objects. For where do you think I hid
my vegetable knife, my silver, my horn and the other things that I
have not yet named, perhaps shall never name. Good. Now I can begin
to suck. Watch me closely. I take a stone from the right pocket of my
greatcoat , suck it, stop sucking it, put it in the left pocket of my
greatcoat, the one empty (of stones). I take a second stone from the
right pocket of my greatcoat, suck it put it in the left pocket of my
greatcoat. And so on until the right pocket of my greatcoat is empty
(apart from its usual and casual contents) and the six stones I have
just sucked, one after the other, are all in the left pocket of my
greatcoat.

Pausing then, and concentrating, so as not to make a balls of it, I
transfer to the right pocket of my greatcoat, in which there are no
stones left, the five stones in the right pocket of my trousers, which
I replace by the five stones in the left pocket of my trousers, which
I replace by the six stones in the left pocket of my greatcoat. At
this stage then the left pocket of my greatcoat is again empty of
stones, while the right pocket of my greatcoat is again supplied, and
in the vright way, that is to say with other stones than those I have
just sucked. These other stones I then begin to suck, one after the
other, and to transfer as I go along to the left pocket of my
greatcoat, being absolutely certain, as far as one can be in an affair
of this kind, that I am not sucking the same stones as a moment
before, but others.

And when the right pocket of my greatcoat is again empty (of stones),
and the five I have just sucked are all without exception in the left
pocket of my greatcoat, then I proceed to the same redistribution as a
moment before, or a similar redistribution, that is to say I transfer
to the right pocket of my greatcoat, now again available, the five
stones in the right pocket of my trousers, which I replace by the six
stones in the left pocket of my trousers, which I replace by the five
stones in the left pocket of my greatcoat. And there I am ready to
begin again. Do I have to go on? No, for it is clear that after the
next series, of sucks and transfers, I shall be back where I started,
that is with the first six stones back in the supply pocket, the next
five in the right pocket of my stinking old trousers and finally the
last five in left pocket of same, and my sixteen stones will have been
sucked once at least in impeccable succession, not one sucked twice,
not one left unsucked.

It is true that next time I could scarcely hope to suck my stones in
the same order as the first time and that the first, seventh and
twelfth for example of the first cycle might very well be the sixth,
eleventh, and sixteenth respectively of the second, if the worst came
to the worst. But this was a drawback I could not avoid. And if in
the cycles taken together utter confusion was bound to reign, at least
within each cycle taken separately I could be easy in my mind, at
least as easy as one can be, in a proceeding of this kind. For in
order for each cycle to be identical, as to the succession of stones
in my mouth, and God knows I had set my heart on it, the only means
were numbered stones or sixteen pockets. And rather than make twelve
more pockets or number my stones, I preferred to make the best of the
comparative peace of mind I enjoyed within each cycle taken
separately.

For it was not enough to number the stones, but I would have had to
remember, every time I put a stone in my mouth, the number I needed
and look for it in my pocket. Which would have put me off stone for
ever, in a very short time. For I would never have been sure of not
making a mistake, unless of course I had kept a kind of register, in
which to tick off the stones one by one, as I sucked them. And of
this I believed myself incapable. No, the only perfect solution would
have been the sixteen pockets, symmetrically disposed, each one with
its stone. Then I would have needed neither to number nor to think,
but merely, as I sucked a given stone, to move on the fifteen others,
a delicate business admittedly, but within my power, and to call
always on the same pocket when I felt like a suck. This would have
freed me from all anxiety, not only within each cycle taken
separately, but also for the sum of all cycles, though they went on
forever.

But however imperfect my own solution was, I was pleased at having
found it all alone, yes, quite pleased. And if it was perhaps less
sound than I had thought in the first flush of discovery, its
inelegance never diminished. And it was above all inelegant in this,
to my mind, that the uneven distribution was painful to me, bodily.
It is true that a kind of equilibrium was reached, at a given moment,
in the early stages of each cycle, namely after the third suck and
before the fourth, but it did not last long, and the rest of the time
I felt the weight of the stones dragging me now to one side, now to
the other. There was something more than a principle I abandoned,
when I abandoned the equal distribution, it was a bodily need. But to
suck the stones in the way I have described, not haphazard, but with
method, was also I think a bodily need. Here then were two
incompatible bodily needs, at loggerheads. Such things happen.

But deep down I didn't give a tinker's curse about being off my
balance, dragged to the right hand and the left, backwards and
forewards. And deep down it was all the same to me whether I sucked a
different stone each time or always the same stone, until the end of
time. For they all tasted exactly the same. And if I had collected
sixteen, it was not in order to ballast myself in such and such a way,
or to suck them turn about, but simply to have a little store, so as
never to be without. But deep down I didn't give a fiddler's curse
about being without, when they were all gone they would be all gone, I
wouldn't be any the worse off, or hardly any. And the solution to
which I rallied in the end was to throw away all the stones but one,
which I kept now in one pocket, now in another, and which of course I
soon lost, or threw away, or gave away, or swallowed.

* Samuel Beckett Fizzles/Old Earth

Old Earth, no more lies, I've seen you, it was me, with my other's
ravening eyes, too late. You'll be on me, it will be you, it will be
me, it will be us, it was never us. It won't be long now, perhaps not
tomorrow, nor the day after, but too late. Not long now, how I gaze
on you, and what refusal, how you refuse me, you so refused. It's a
cockchafer year, next year there won't be any, nor the year after,
gaze your fill. I come home at nightfall, they take to wing, rise
from little oaktree and whirr away, glutted, into the shadows. I
reach up, grasp the bough, pull myself up and go in. Three years in
the earth, those the moles don't get, then guzzle guzzle, ten days
long, a fortnight, and always the flight at nightfall. To the river
perhaps, they head for the river. I turn on the light, then off,
ashamed, stand at gaze before the window, the windows, going from one
to another, leaning on the furniture. For an instant I see the sky,
the different skies, then they turn to faces, agonies, loves, the
different loves, happiness too, yes, there was that too, unhappily.
Moments of life, of mine too, among other, no denying, all said and
done. Happiness what happiness, but what deaths, what loves, I knew
at the time it was too late then. Ah to love at your last and see
them at theirs, the last minute loved ones, and be happy, why ah,
uncalled for. No but now, now, simply stay still, standing before a
window, one hand on the wall, the other clutching your shirt, and see
the sky, a long gaze, but no, gasps and spasms, a childhood sea, other
skies, another body.



* PUTREFACTION

** Splendor Solis:

\includegraphics[width=40em]{resources/19ss.jpg}

PUTREFACTION takes place when the natural heat of a moist body is
expelled by an external heat, or else when the natural heat of the
subject is destroyed by cold. For then the natural warmth leaves
everything and gives room to putrefaction. The Philosophers do not
mean th is kind of Putrefaction. Their Putrefaction is a moistening of
dry bodies, that they may be restored to their former state of
Greening and Growing. In this process of Putrefaction, moist and dry
are joined together and not destroyed, but the moisture is quite
separated from the dryness, then it is necessary to separate the dry
parts that turned to ashes. This Incineration the Philosophers will
also not have, but they will have their Putrefaction, which is a
drying, trituration and calcination, to be done in such wise, that the
natural moisture and dryness be united together, but separated and
dried up from the superfluous moisture that is destructive. Even as
the food is being absorbed on entering an animal's stomach, that it
may be digested and changed and afterwards supply the feeding force
and moisture necessary to the existence and augmentation of nature,
and be separated of its superfluous parts. How then everything has to
be fed in its way according to its nature will be shown in the
aforesaid Philosopher's Stone.


This Dissolution is nothing but a killing of the moist with the dry,
in fact a PUTREFACTION, and consequently turns the MATTER black.

The Soul is extracted by Putrefaction, and when nothing more of the
soul remains, then have you well washed the Body, that they both again
are one.


** Donum Dei: (excerpts and images)

\includegraphics[width=40em]{resources/dd000.jpeg}

\includegraphics[width=40em]{resources/Donum_Dei_Sloane_2560_8.jpg}

\includegraphics[width=40em]{resources/Donum_Dei_Sloane_2560_7.jpg}

\includegraphics[width=40em]{resources/Donum_Dei_Sloane_2560_6.jpg}

\includegraphics[width=40em]{resources/Donum_Dei_Sloane_2560_5.jpg}

\includegraphics[width=40em]{resources/Donum_Dei_Sloane_2560_4.jpg}

Here is made the putrefaction of Philosophers which was never seen and
is called sulphur.


Convert the natures of the Elements and thou shalt find what thou
seekest. To convert the natures is to make a body a spirit in our
Magistery, first we make of gross thin, and of a body water, and by
consequent we make that which is beneath as that which is above, and
the contrary, for the bodies dissolved are reduced to the nature of
spirits, and they be never separated asunder, like as water is mixed
with water, and truly all the regiment and work is none other, but
water permanent having in himself all things which we need. Therefore
hold fast that water which is good operations, for he maketh white to
white, and red to red, it is on and the same thing which hath in him
flesh or soul; the agent, or calx, and the 4 Elements, to whom it hath
dominion, it is not made of other Elements which agreeth not in his
nature. The putrefaction of the Philosophers is the head of the Crow
a blackness transparent and shining. Here be the bodies put in
putrefaction and be made black earth, and when you seest thy matter to
be made black rejoice for that is the beginning of the operation. And
it is necessary to be putrefied. I am black of white, and red of
white, and citrine of red, and certainly I am a true sayer and not
liar. And know ye that this red of the art is the Crow which in the
blackness of the night and in the clearness of the day flyeth without
wings. Of the bitterness in his throat the colour is taken, from his
body the redness, and from his back pure water. Understand the gift of
God, receive it and hide it from all unwise philosophers, for it is
not hidden from the caverns of the metals, which stone is mineral, and
animal, shining colours, or high hill, and an open sea. Behold I have
expound it to you, truly when it is first black, we call it the cave
of the science which is not without blackness, for it is the tincture
which we seek, for in every body we give or put colour, which thing
was hidden in his brass, as the Soul in man's body. Therefore dear
Son, when thou art in thy work, see first thou have the black colour,
and then art thou sure thou dost putrefy and proceedest the right way,
patience and tarrying be necessary in our work. O Blessed Nature and
blessed is thine operation, for of imperfect thou makest perfect with
true putrefaction, which is black and obscure. Then after thou shalt
make to spring new, and divers things, which thy viridity or green
lion makest divers colours appear. The Head of the Crow is
transparent blackness. This is upon the matter the black clouds,
spirits or forms, This earth which is upon the matter descendeth in
another vessel to the bottom and thence worms be brought forth.

The Head of the Crow is black earth and feculent in the which be
engendered worms, whereof the one devoureth the other, for the
corruption of the one is the generation of the other.

The black clouds descendeth unto the body from whence they came out
and there is made connection between the earth and water and is made
ashes. The crow is black, the Dove is white, the Phoenix burneth

* Ripley's Putrefaction

[Eirenaeus Philalethes/George Starkey: Ripley reviv'd: or, an exposition upon Sir George Ripley's Hermetico poetical works]

\includepdf[pages=151-173]{resources/ripley.pdf} 

** Ripley's Eighth Gate - Sublimation

\includegraphics[width=40em]{resources/corbeau.jpeg}

\begin{verse}
And Sublimations we make for three causes,\\
The first cause is, to make the body spiritual,\\
The second is, that the spirit may be corporeal ,\\
And become fixed with it and consubstantial,\\
The third cause is, that from its filthy original\\
It may be cleansed, and its saltiness sulphurious,\\
May be diminished in it, which is infectious.\\
\end{verse}


* Feedback and open circuits

\includepdf[pages=-]{resources/feedback000.pdf}

\includepdf[pages=-]{resources/feedbacktech.pdf}

\includepdf[pages=-]{resources/bare555.pdf}

\includepdf[pages=-]{resources/diyopamp.pdf}

* Earth currents

\includegraphics[width=40em]{resources/Nathan-Stubblefield-demonstration.jpg}

\includegraphics[width=40em]{resources/induc1.jpg}

\includegraphics[width=40em]{resources/snowbatt1.jpg}

\includegraphics[width=40em]{resources/stubbcoils.jpg}

\includepdf[pages=2-18]{resources/telluric.pdf}

\includepdf[pages=-]{resources/stubblefield.pdf}

\includepdf[pages=1-28]{resources/stubblefield2.pdf}

\includepdf[pages=-]{resources/earth000.pdf}

\includepdf[pages=141-159]{resources/persingerelf.pdf}

* Bodily circulations

.. that is by a hyemal winter fire, with which she rotteth; & then
with a vernal or spring firre by which it groweth & indueth his green
mantle; & then with his aestival or summer heat, by which he
flourisheth & putteth on a crest or helmet of a more golden colour,
hastening by this intense agent unto his maturity; and lastly he
changeth that fire to an autumnal or harvest operation by which the
mark of maturity so aimed at all the year is touched on the very head
that then corruption may begin again.

[connected to experiment with wheat - begins to "violate by corruption
the bands of those four elements which did preserve that vegetable
form until in a manner I had deprived it of quite all shape, & reduced
the whole body unto a muddy or slimy substance ..."]

\includegraphics[width=40em]{resources/invasion.jpg}

\includegraphics[width=40em]{resources/fludd_exc_basilisk.jpg}

\includepdf[pages=-]{resources/debusfluddblood.pdf}

\includepdf[pages=55-72]{resources/debusparacelsians.pdf}

\includepdf[pages=-]{resources/circulationblood.pdf}

\includepdf[pages=2-28]{resources/fluddwheat.pdf}


* Ergot and parasites

\includegraphics[width=40em]{resources/ergot-life-cycle-n.jpg}

\includepdf[pages=-]{resources/ergot_lifecycle.pdf}

* Mycelium

\includegraphics[width=40em]{resources/mushroomcycle.png}

* Media

\includepdf[pages=-]{resources/thermocultures.pdf}

\includepdf[pages=-]{resources/mediaarch.pdf}

\includepdf[pages=73-95]{resources/Geologyofmedia.pdf}

* Video and other materials

Friedrich Kittler. Non-Linear Oscillators & Computer Motherboards. 2010: https://www.youtube.com/watch?v=CxIHwCnVYIE

Ergot: the story of a parasitic fungus: https://www.youtube.com/watch?v=ielb0C1JYsw
