* Deprecation: Rotting of Shiftless Registers /// (25 minutes) presentation


** intro/abstract Deprecation: rotting or shiftless registers

Deprecation explores the shift register, a digital device, circuit or
conceit, which links technical and media histories with the esoteric
and the geological. The shift register was implicated in early forms
of computer memory, and provides for ways of thinking about both
digital and human preservation and dissolution in the context of the
questionable term of the anthropocene.

** 1- what is a SR?

*** what exactly is a shift register - how does it operate

A shift register is a type of digital circuit using a cascade of flip
flops where the output of one flip-flop is connected to the input of
the next. They share a single clock signal, which causes the data
stored in the system to shift from one location to the next. By
connecting the last flip-flop back to the first, the data can cycle
within the shifters for extended periods, and in this form they were
used as a form of computer memory. In this role they are very similar
to the earlier delay line memory systems and were widely used in the
late 1960s and early 1970s to replace that form of memory.
[wikipedia] 

Key characteristics are the movement of well-defined data
from one cell to another as a form of memory, which is against
disintegration, and dissolution 

That these material forms such as the delay line were built on
necessary decay - acoustic delay line, light delay line, Alan Turing delay line
re-circulation against loss and decay of a signal, fading out

*** Ouroboros

In the rarified realm of digital designers, an equivalent to the
Ouroboros is the linear-feedback-shift register (LFSR), in which the
output from a standard-shift register is manipulated and fed back to
its input so as to cause the function to endlessly cycle through a
sequence of patterns.

Much like the Ouroboros, LFSRs keep on rearing their heads again and
again and again, because however much you know, there are always more
tricks to learn. The great psychoanalyst Carl Jung speculated that the
Ouroboros could be part of the collective consciousness, so had he
dabbled in electronics, he may well have considered LFSRs to form part
of the digital consciousness. Hold onto that couch, Carl; I’m on my
way! 
[EDN website/beebop boolean boogie]

*** the first shift register? collosus

One of the first known examples of a shift register was in the Mark 2
Colossus, a code-breaking machine built in 1944. It was a six-stage
device built of vacuum tubes and thyratrons. A shift register was
also used in the IAS machine, built by John von Neumann and others at
the Institute for Advanced Study in the late 1940s.

Five separate processors presented little difficulty. A
photoelectric reader to supply them with data would have to read six
lines of tape simultaneously, however, and would be very difficult to
construct. Six lines were needed so that two consecutive but different
lines could be presented to each of the five processors. This
difficulty was solved by shift registers invented for the
purpose. Data read from the tape were read into six-bit shift
registers, which meant that six consecutive characters from the
message tape were available for processing using a tape reader that
had to read only one line at a time and was thus simplified compared
with the readers first used with the Robinson machine.

*** musical/artistic use of shift registers

As a bridge between random noise and recurring patterns. 

Historic use in instruments like the Triadex Muse, Benjolin, and
misuses of digital filter structures.

*** To describe an obsession - SR as ouroboros

Providing a link between the technological and the mystical (how to put this)

*** SR as Swiss project title

- that part of this lecture is about explaining how that title was
  chosen and what it means so to explain here would make us ahead of
  ourselves.

What that project was about? 

- how we can render experiential the questionable markers of the anthropocene?

Shifting registers, shifting marks of registration of this
questionable new era.

Shift Register investigates and renders legible the material evidence
of human activities on the earth, registering these not as indicators
of human achievement, but as ambiguous negotiations and signposts of
planetary exhaustion. The project undertakes fieldwork and research
re-routed from the natural and physical sciences as the means to bear
witness to these sites of human impact.

Another shift sideways:

Martin Howse has attempted to interrogate the nature of such
computational enclosures, with their “separation of users and of their
desires and affects,” and how “The possibility of transferring
execution outside these sets of containers or black boxes into the
world is resolutely denied.” In different ways, each of these pieces
pose what Howse (cited in Sayej 2013) sees as a key question to be
addressed:

    where exactly do these seemingly abstract coded processes which
    seriously effects our lives, where do these take place? At first
    it seems simple, somewhere inside this machine or black box, a
    laptop, a smartphone, but looking at it closer there’s no easy
    answer. And I feel that this answer has to do with our skin and
    the Earth.

For Howse (with a nod to JG Ballard's Crash), one method or exploit
for triggering a reacquainting of the faultlines of such a question is
the act of shifting the site of an executable process from its typical
or stabilised domain to a less typical or stable one. To this end,
Howse carries out a range of experiments that, in one way or another,
attempt to shift computational sites of execution into “new material
(data), outside the particular confines of a trusted and identifiable
process or skin,"

*** SR as geological, as depth and as circulation

That there is something geological and stratified about the shift
register, data is shuffled down the line. We think of an ice or
geological core sample. What is most recent is at the top of the
sample, forever shifting down. Peat samples that we took!

But the shift register is enacted in bits in algorithmic time, SR as
particulate/discrete/digital in a sense.

*SR is a discrete form of circulation*

SR forms one link between the digital and the geological...

At the same time the SR is somehow organic in the sense that decay is
organic an alive - there is the transition from something dying or
decaying (losing its identity, its unitary body) to become something
living. Catholic shift registers of resurrection... alive until it
dies again and is reborn in a new identity. This is hat it inherits
from the oroborus in terms of hermetic philosophy.

I was reminded of Samuel Beckett's stones or pebbles:

https://www.youtube.com/watch?v=TXoq_H9BrTE

I took advantage of being at the seaside to lay in a store of
sucking-stones. They were pebbles but I call them stones. Yes, on this
occasion I laid in a considerable store. I distributed them equally
between my four pockets, and sucked them turn and turn about. This
raised a problem which I first solved in the following way. I had say
sixteen stones, four in each of my four pockets these being the two
pockets of my trousers and the two pockets of my greatcoat. Taking a
stone from the right pocket of my greatcoat, and putting it in my
mouth, I replaced it in the right pocket of my greatcoat by a stone
from the right pocket of my trousers, which I replaced by a stone from
the left pocket of my trousers, which I replaced by a stone from the
left pocket of my greatcoat, which I replaced by the stone which was
in my mouth, as soon as I had finished sucking it. Thus there were
still four stones in each of my four pockets, but not quite the same
stones

And looking into what this could have to do with Shift Registers when
I found this:

Another type of Gray code, the Beckett–Gray code, is named for Irish
playwright Samuel Beckett, who was interested in symmetry. His play
"Quad" features four actors and is divided into sixteen time
periods. Each period ends with one of the four actors entering or
leaving the stage. The play begins with an empty stage, and Beckett
wanted each subset of actors to appear on stage exactly once.

Clearly the set of actors currently on stage can be represented by a
4-bit binary Gray code. Beckett, however, placed an additional
restriction on the script: he wished the actors to enter and exit so
that the actor who had been on stage the longest would always be the
one to exit. The actors could then be represented by a first in, first
out queue (a shift register), so that (of the actors onstage) the
actor being dequeued is always the one who was enqueued first.

gray code: an ordering of the binary numeral system such that two
successive values differ in only one bit (binary digit).

Beckett was unable to find a Beckett–Gray code for his play, and
indeed, an exhaustive listing of all possible sequences reveals that
no such code exists for n = 4.

Beckett code is a FIFO which is an SR.

** 2- Shift registers as a methodology for becoming geological!

Becoming geological, preserved, immortal, supposedly protected against
decay. To be immortal is to be dead.

The contradiction is that logic is antithetical and opposed to the
(dead hence ever living) earth.

[IF TIME:
[We can ask what are the naive necessities for logic or SR in the earth:

- that it must be transmissable and measurable (it cannot be indeterminate or die out)
- that it must be within the limit of certain thresholds (to signify a 1 or a 0 and be able to pass this on)
- non-linearity of logical operations (eg. XOR)
- bounded cells, no leakage, no less, no decay
- it can be clocked or strobed to define certain operations - the timing is event-driven, of thresholds, discontinuous and discrete
- that the measurable nature of the energetic transforms employed (eg. electrochemical, thermodynamic) are common to input and outputs
- that the measurable nature of the energetic transforms is not subject to interference from other flows or transformations

what types of logic are there? such as fluid gates, heat gates
]]

That it is already geological - the shift registers of extraction and
return, of refinement, depracation, obsolesence and return to the
earth.

// A repeating and circling text

Copper is extracted from the earth (according to speculative
algorithms running on hardware which is partially dependent on the
future extraction of these metals or at least geological and
metallurgical research into alternative resources which will inform
and affect the extraction of these and other elements), refined
(rendered as an identity, as copper) and reworked, re-combined with
other equally refined mineralities to fulfill the demands of logic or
the SR in the earth to become deprecated like any protocol, abandoned,
rendered obsolete, once again refined and seperated from any other
unwanted elements (which are returned to the earth with traces of that
use and of those other constituents), to be re-used ideally within new
logics, or quite possibly the same logical structures embedded in
"new" interfaces, promoted algorithmicallly by hardware which is
partially dependent on the future extraction of these metals or at
least geological and metallurgical research into alternative resources
which will inform and affect the extraction of these and other
elements), refined and reworked, re-combined with other equally
refined mineralities to fulfill the demands of logic or the SR in the
earth.

** 3- more feedback loops, geological feedback loops 

... and as a necessary byproduct of these loops:

We inhale and ingest our own geological indicators (metals, isotopes, markers)

That it is not outside us, we eat and inhale our own - belonging to
us, anthropogenic - signifiers of the becoming geological (not just
marking an outside, but an inside, a double psychological loop)

- feedback loops of warming and particulate exhalations of burning forests...


** conclusion - towards decaying, mortal particulate logics

The link between SR and Tiny Mining

I started thinking about the ingestion of particles, starting to think
if this becoming geology through ingestion is not so foreign to
humanity so far - the project of a becoming immortal as a dead or
undecaying geological mummy. The anthropocene could be seen as some
kind of circular ingestion of the markers of our own entry into
geological timeframes, which seems to have a familiar logic!

If the project of humanity is not this becoming geological - becoming
immortal as a dead or undying body of jade or mercury (Chinese Alchemy)

The questionable term of the anthropocene is re-written as the
ingestion and inhalation of our "own" entry point into geological
time. (explain this with ref to radioactive tracers, markers)

