* Circulations (and corruptions)

- format? - about the workshop/various circulations/circulations in own work/circulations in electronic/music//workshop schedule and practical

- what is it about circulation that encourages corruption, putrefaction and decay?

- how can we think of corruption in terms of material and/of media?
  parasitism, degradation of information, making present of a material
  substrate and material constraints, signals disturbed/noise,
  muddied, what it means to corrupt something, to mix in additional
  meanings, to degrade a signal

- parasites

- what are alchemical cycles which involve putrefaction

- electronics and feedback, parasitic feedback/effects and putrefaction

corruption as only images - donum dei sloane 2560

- key emblem decoded
- circulations of media
- within the body - fludd/blood, breath. worms
- within the earth - telluric
- within the air - fludd also - wind, temp changes. crows
- within electronics and electronic music - feedback


** intro etc/notes from workshop.org

All technology that is derived of earth, must be decomposed and again
reduced to earth.
[Basil Valentine]

Old earth, no more lies, I've seen you, it was me, with my other
ravening eyes, too late.
[Samuel Beckett]

Circulation and corruption (workshop) examines the various
circulations of media through the matters and bodies of the earth and
atmosphere, and through a certain corruption or dissolution of
(digital) identity, meaning and description.

Within a one and a half day hands-on, speculative workshop we will
collectively explore the interfaces and exchanges between living
systems (earth, compost, worms, mycelium) and active audio
electronics. We will participate primarily with our hands and our ears
within circulations amongst earths, composts, mushroom mycelium,
moulds, active chemistry, worms, crows, dusts, smokes and fogs and
impulses and waves.

During the workshop we will construct a series of open circuits which
do not conceal their materiality but participate equally within
material and electrochemical exchanges and circulations. 

*These circuits are inspired through a media archaeology of electronic
music production, and through the history of alchemical engagement
with minerals, with decay and with the earth. These technical and
conceptual influences are equally opened to circulation and corruption
during the workshop.*

We will work with a range of materials (for example, machine cut
copper sheets and oyster mushroom mycelium) and approaches (for
example, with radio transmission and signal reception) to design and
build these open circuits which will enter into processes of
appreciable decay, corruption and dissolution. These open circuits
will be placed during the workshop in selected interior and exterior
locations to participate in various time scales of deterioration and
degradation.

*** notes:

ouroboros, latch and comparator circuits opened to moulds and decay, fungi, degradation


the circulatory system of an earth addiction encompassing extraction
(of precious metals, of radioactive minerals), transport (along old
and new Silk Roads) and consumption (the ingestion of earth-derived
energies, materialities and earth-bound pharmaceutical products) and
return or excretion (traces of isotopes and pollution elements in the
body).

** notes etc


*** jussi

There’s no information to circulate without a physics and a chemistry.

*** Fludd/Huffman p116 - The Second Book Containing the Mysteries of Wheat or Bread.

.. that is by a hyemal winter fire, with which she rotteth; & then
with a vernal or spring firre by which it groweth & indueth his green
mantle; & then with his aestival or summer heat, by which he
flourisheth & putteth on a crest or helmet of a more golden colour,
hastening by this intense agent unto his maturity; and lastly he
changeth that fire to an autumnal or harvest operation by which the
mark of maturity so aimed at all the year is touched on the very head
that then corruption may begin again.

[connected to experiment with wheat - begins to "violate by corruption
the bands of those four elements which did preserve that vegetable
form until in a manner I had deprived it of quite all shape, & reduced
the whole body unto a muddy or slimy substance ... "]

*** splendor solis plate 19

This Dissolution is nothing but a killing of the moist with the dry,
in fact a PUTREFACTION, and consequently turns the MATTER black

*** Aurora Consurgens (date?)

THE  FIRST  PARABLE:  OF  THE   BLACK  EARTH  WHEREIN  THE  SEVEN  PLANETS  TOOK  ROOT

Beholding from afar off I saw a great cloud looming black over the
whole earth, which had absorbed the earth and covered my soul, because
the waters had come in even unto her, wherefore they were putrefied
and corrupted before the face of the lower hell and the shadow of
death, for a tempest hath overwhelmed me

*** Ripley Putrefaction

This text has been modernised by Adam McLean from the 1591 edition of The Compound of Alchymy. 

THE FIFTH GATE - PUTREFACTION

Now we begin the chapter of Putrefaction,
Without which pole no seed may multiply,
Which must be done only by continual action,
Of heat in the body, moist not manually.
For bodies else may not be altered naturally,
Since Christ doth witness, unless the grain of wheat die in the ground,
Increase may thou not get.

And likewise unless the matter putrefy,
It may in no way truly be altered,
Neither may thy elements be divided kindly,
Nor the conjunction of them perfectly celebrated,
That thy labour therefore be not frustrated,
The privitie of our putrefying well understand,
Before ever you take this work in hand.

And Putrefaction may thus be defined, after philosophers sayings,
To be the slaying of bodies,
And in our compound a division of things three,
Leading forth into the corruption of killed bodies,
And after enabling them unto regeneration,
For things being in the earth, without doubt,
Be engendered of rotation in the heavens about.

And therefore as I have said before,
Thine elements commixed and wisely coequate,
Thou keep in temperate heat,
Eschewing evermore that they be not incinerate by violent heat,
To dry powder, unprofitably rubificated,
But into powder black as a crow's bill,
With heat of the Bath or else of our dunghill.

Until the time that ninety nights be passed,
In moist heat keep them for any thing,
Soon after by blackness you shall espy,
That they draw close to putrefying,
Which after many colours you shall bring,
With patience easily to perfect whiteness,
And so thy seed in his nature will multiply.

Make each the other then to hug and kiss,
And like as children to play them up and down,
And when their shirts are filled with piss,
Then let the woman to wash be bound,
Which often for faintness will fall in a swoon,
And die at last with her children all,
And go to purgatory to purge their filth original.

When they be there, by little and little increase,
Their pains with heat, aye, more and more,
Never let the fire from them cease,
And see that thy furnace be apt therefore,
Which wise men call an Athanor,
Conserving heat required most temperately,
By which thy matter doth kindly putrefy.

Of this principle speaks wise Guido,
And sayeth "by rotting dieth the compound corporeal",
And then after Morien and others more,
Upriseth again regenerated, simple and spiritual,
And were not heat and moisture continual,
Sperm in the womb might have no abiding,
And so there should be no fruit thereof upspring.

Therefore at the beginning our stone thou take,
And bury each one in other within their grave,
Then equally between them a marriage make,
To lie together six weeks let them have their seed conceived,
Kindly to nourish and save,
From the ground of their grave not rising that while,
Which secret point doth many a one beguile.

This time of conception with easy heat abide,
The blackness showing shall tell you when they die,
For they together like liquid pitch that tide,
Shall swell and bubble, settle and putrefy,
Shining colours therein you shall espy,
Like to the rainbow marvellous to sight,
The Water then beginneth to dry upright.

For in moist bodies, heat working temperate,
Engenders blackness first of all,
Which is the assigned token of kindly Conjunction,
And of true Putrefaction: remember this,
For then perfectly to alter thou can not miss,
And thus by the gate of blackness thou must come in,
To light of Paradise in whiteness if you wilt win.

For first the Sun in his uprising shall be obscured,
And pass the waters of Noah's flood on earth,
Which was continued a hundred and fifty days,
Ere this water went away,
Right so our waters shall pass (as wise men understood),
That you with David shall say,
"Abierunt in sicco flumina" : bear this away.

Soon after that Noah planted his vineyard,
Which royally flourished and brought forth grapes,
After which space you shall not be afraid,
For it likewise shall follow the nourishing of our stone,
And soon after that 30 days be gone,
You shall have grapes right as ruby red,
Which is our Adrop, our Ucifer, and our red lead.

For like as souls after pains transitory,
Be brought to Paradise, which ever is joyful life,
So shall our stone after his darkness in Purgatory be purged,
And joined in Elements without strife,
Rejoice the whiteness and beauty of his wife,
And pass from darkness of purgatory to light of Paradise,
In whiteness Elixir of great might.

And that you may the rather to putrefaction win,
This example take you for a true conclusion,
For all the secret of Putrefaction rests therein,
The heart of oak that hath of water continual infusion,
Will not soon putrefy, I tell you without delusion,
For though it lay in water a hundred years and more,
Yet should you find it sound as ere it was before.

But if you keep it sometimes wet and sometimes dry,
As thou may see in timber by usual experiment,
By process of time that oak shall utterly putrefy,
And so likewise according to our intent,
Sometimes our tree must with the Sun be burnt,
And then with water we must make it cool,
That by this means to rotting we may bring it well.

For now in wet, and now again in dry,
And now in heat, and now again to be in cold,
Shall cause it soon to putrefy,
And so shall thou bring to rotting your gold,
Treat thy bodies as I have thee told,
And in thy putrefying with heat be not too swift,
Lest in the ashes thou seek after your thrift.

Therefore your water you draw out of the earth,
And make the soul therewith to ascend,
Then down again into the earth it throw,
That they oftentimes so ascend and descend,
From violent heat and sudden cold descend your glass,
And make your fire so temperate,
That by the sides the matter be not vitrified.

And be you wise in choosing of the matter,
Meddle with no salts, sulphurs nor mean minerals,
For whatsoever any worker to thee does clatter,
Our Sulphur and Mercury be only in metals,
Which some men call oils and waters,
Fowls and bird, with many other names,
So that fools should never know our stone.

For of this world our stone is called the ferment,
Which moved by craft as nature does require,
In his increase shall be full opulent,
And multiply his kind after thine own desire,
Therefore is God vouchsafe you to inspire,
To know the truth, and fancies to eschew,
Like unto you in riches shall be but few.

But many men be moved to work after their fantasy,
In many subjects in which be tinctures gay,
Both white and red divided manually to sight,
But in the fire they fly away,
Such break pots and glasses day by day,
Poisoning themselves and losing their sight,
With odours, smokes, and watching up by nights.

Their clothes be bawdy and worn threadbare,
Men may them smell for multipliers where they go,
To file their fingers with corrosives they do not spare,
Their eyes be bleary, their cheeks lean and blue,
And thus I know they suffer loss and woe,
And such when they have lost that was in their purse,
Then do they chide, and Philosophers sore do curse.

To see their houses is a noble sport,
What furnaces, what glasses there be of diverse shapes,
What salts, what powders, what oils, or acids,
How eloquently of Materia Prima their tongues do clap,
And yet to find the truth they have no hope,
Of our Mercury they meddle and of our sulphur vive,
Whereon they dote, and more and more unthrive.

For all the while they have Philosophers been,
Yet could they never know what was our Stone,
Some sought it in dung, in urine, some in wine,
Some in star slime (some thing it is but one),
In blood and eggs : some till their thrift was gone,
Dividing elements, and breaking many a pot,
Shards multiplying, but yet they hit it not.

They talk of the red man and of his white wife,
That is a special thing, and of the Elixirs two,
Of the Quintessence, and of the Elixir of life,
Of honey, Celidonie, and of Secondines also,
These they divide into Elements, with others more,
No multipliers, but will they be called Philosophers,
Which natural Philosophy did never read or see.

This fellowship knows our Stone right well,
They think them richer than is the King,
They will him help, he shall not fail,
To win for France a wondrous thing,
The holy Cross home will they bring,
And if the King were taken prisoner,
Right soon his ransom would they make.

A marvel it is that Westminster Kirk,
Which these Philosophers do much haunt,
Since they can so much riches work,
As they make boast of and avaunt,
Drinking daily at the wine due taunt,
Is not made up perfectly at once,
For truly it lacketh yet many stones.

Fools do follow them at their tail,
Promoted to riches wishing to be,
But will you hear what worship and avail,
They win in London that noble city ?
With silver maces (as you may see),
Sargents awaiteth on them each hour,
So be they men of great honour.

Sargents seek them from street to street,
Merchants and Goldsmiths lay after them to watch,
That well is him that with them may meet,
For the great advantage that they do catch,
They hunt about as does a dog,
Expecting to win so great treasure,
That ever in riches they shall endure.

Some would catch their goods again,
And some more good would adventure,
Some for to have would be full fain,
Of ten pounds one, I you ensure,
Some which have lent their goods without measure,
And are with poverty clad,
To catch a noble, would be full glad.

But when the Sargents do them arrest,
Their pockets be stuffed with Paris balls,
Or with signets of St Martin's at the least,
But as for money it is pissed against the walls,
Then they be led (as well for them befalls),
To Newgate or Ludgate as I you tell,
Because they shall in safeguard dwell.

Where is my money become, saith one ?
And where is mine, saith he and he ?
But will you hear how subtle they be anon,
In answering that they excused be,
Saying of our Elixirs we were robbed,
Else might we have paid you all your gold,
Though it had been more by ten-fold.

And then their creditors they flatter so,
Promising to work for them again,
In right short space the two Elixirs,
Doting the Merchants that they be fain,
To let them go, but ever in vain,
They work so long, till at the last,
They be again in prison cast.

If any them ask why they be not rich ?
They say that they can make fine gold of tin,
But he (say they) may surely swim the ditch,
Which is upholded by the chin,
We have no stock, therefore may we not win,
Which if we had, we would soon work enough,
To finish up Westminster Kirk.

And some of them be so devout,
They will not dwell out of that place,
For they may without doubt,
Do what them list to their solace,
The Archdeacon is so full of grace,
That if they bless him with their cross,
He forceth little of other mens loss.

And when they there sit at the wine,
These monks they say have many a pound,
Would God (saith one) have some were mine,
Yet care away, let the cup go round,
Drink on saith another, the mean is found,
I am a master of that Art,
I warrant us we shall have part

Such causes Monks evil to do,
To waste their wages through their dotage,
Some bringeth a mazer, and some a spoon,
Their Philosophers gives them such comage,
Behighting them winning with domage,
A pound for a penny at the least again,
And so fair promises make fools fain.

A Royal medicine one upon twelve,
They promise them thereof to have,
Which they could never for themselves,
Yet bring about, so God me save,
Beware such Philosophers no man deprave,
Which help these Monks to riches so,
In threadbare coats that they must go.

The Abbot ought well to cherish this company,
For they can teach his Monks to live in poverty,
And to go clothed and monied religiously,
As did Saint Bennet, eschewing superfluity,
Easing them also of the ponderosity of their purses,
With pounds so aggravated,
Which by Philosophy be now alleviated.

Lo who meddles with this rich company,
Great boast of their winning they may make,
For they shall reap as much by their Philosophy,
As they of the tail of an ape can take,
Beware therefore for Jesus' sake,
And meddle with nothing of great cost,
For if thou do, it is but lost.

These Philosophers (of which I spoke before),
Meddle and blunder with many a thing,
Running in errors ever more and more,
For lack of true understanding,
But like must always bring forth like,
So hath God ordained in every kind,
Would Jesus they would bear this is mind.

They expect of a Nettle to have a Rose,
Or of an Elder to have an apple sweet,
Alas, that wisemen their goods should lose,
Trusting such doctrines when they them meet,
Which say our Stone is trodden under foot,
And makes them vile things to distil,
Till all their houses with stench they fill.

Some of them never learned a word in Schools,
Should such by reason understand Philosophy ?
Be they Philosophers ? Nay, they be fools.
For their works prove them without wit,
Meddle not with them, if you would be happy,
Lest with their flattery they so thee till,
That you agree unto their will.

Spend not thy money away in waste,
Give not to every spirit credence,
But first examine, grope and taste,
And as thou provest, so put your confidence,
But ever beware of great expense,
And if the Philosopher do live virtuously,
The better you may trust his Philosophy.

Prove him first, and him appose,
Of all the secrets of our Stone,
Which if he know not, you need not to lose,
Meddle you no further, but let him be gone,
Though he make ever so piteous a moan,
For then the Fox can fagg and faine,
When he would to his prey attain.

If he can answer as a Clerk,
How he has not proved it indeed,
And you then help him to his work,
If he be virtuous I hold it merited,
For he will thee quite if ever he speeds,
And thou shalt know by a little anon,
If he have knowledge of our Stone.

One thing, one glass, one furnace, and no more,
Behold if he does hold this principle,
And if he do not, then let him go,
For he shall never make thee a rich man,
Timely it is better you forsake him,
Than after with loss and variance,
And other manner of unpleasance.

But if God fortune you to have,
This Science by doctrine which I have told,
Reveal it not to whosoever it craves,
For favour, fear, silver or gold.
Be no oppressor, lecher not boaster bold,
Serve thy God and help among the poor,
If you wish this life to continue long.

Unto thyself your secrets ever keep,
From sinners, who have not God in dread,
But will cast you in prison deep,
Till you teach them to do it indeed,
Then slander on you shall spring and spread,
That you do coin then will they say,
And so undo you for ever and aye.

And if you teach them this cunning,
Their sinful living for to maintain,
In hell therefore shall be your winning,
For God will take disdain of you and them,
As thou nought could therefore you faine,
That body and soul you may both save,
And here in peace to have your living.

Now in this Chapter I have taught you,
How you must putrefy your body,
And so to guide you that you be not caught,
And put to durance loss and villany
My doctrine therefore remember wisely,
And pass forth towards the sixth gate,
For thus the fifth is triumphate.

The end of the Fifth Gate


*** 

All technology that is derived of earth, must be decomposed and again
reduced to earth.
[Basil Valentine]

Old earth, no more lies, I've seen you, it was me, with my other
ravening eyes, too late.
[Samuel Beckett]

Circulation and corruption (workshop) examines the various
circulations of media through the matters and bodies of the earth and
atmosphere, and through a certain corruption or dissolution of
(digital) identity, meaning and description.

Within a one and a half day hands-on, speculative workshop we will
collectively explore the interfaces and exchanges between living
systems (earth, compost, worms, mycelium) and active audio
electronics. We will participate primarily with our hands and our ears
within circulations amongst earths, composts, mushroom mycelium,
moulds, active chemistry, worms, crows, dusts, smokes and fogs and
impulses and waves.

During the workshop we will construct a series of open circuits which
do not conceal their materiality but participate equally within
material and electrochemical exchanges and circulations. These
circuits are inspired through a media archaeology of electronic music
production, and through the history of alchemical engagement with
minerals, with decay and with the earth. These technical and
conceptual influences are equally opened to circulation and corruption during
the workshop.

We will work with a range of materials (for example, machine cut
copper sheets and oyster mushroom mycelium) and approaches (for
example, with radio transmission and signal reception) to design and
build these open circuits which will enter into processes of
appreciable decay, corruption and dissolution. These open circuits
will be placed during the workshop in selected interior and exterior
locations to participate in various time scales of deterioration and
degradation.

*** notes:

ouroboros, latch and comparator circuits opened to moulds and decay, fungi, degradation


the circulatory system of an earth addiction encompassing extraction
(of precious metals, of radioactive minerals), transport (along old
and new Silk Roads) and consumption (the ingestion of earth-derived
energies, materialities and earth-bound pharmaceutical products) and
return or excretion (traces of isotopes and pollution elements in the
body).

*** from pharmacy event

Title: Digestion.

Martin Howse

No more fruit, no more trees, no more vegetables, no more plants
pharmaceutical or otherwise and consequently no more food, but
synthetic products to satiety, amid the fumes, amid the special humors
of the atmosphere, on the particular axes of atmospheres wrenched
violently and synthetically from the resistances of a nature which has
known nothing of war except fear.

[Antonin Artaud. To have done with the Judgement of God.]

The health of any body is the concern of an interior against any
outside, of a border and a boundary. The earth or body fortress is
assailed by demonic winds and breath from outside its protecting
walls. Spiritus mali, under the sign of four demons, designated as
four elements, enter the body through gaps in the enclosing skin,
through the mouth and the open pores.

Guarded by four angels, the body becoming earth is concerned with its
proper health as its property, rather than that of its improper
parasites; a modern morality play of pneumatic, breath-borne or skin
un-cleansed bacteria (beyond good and evil, a further taxonomy of
ancient breaths and atoms). A partic-ular pharmakon prompts action
against other decidedly out-of-control entities pursuing or making
happen an unconscious, deep sea set and tabled processes against death
(of their own) or otherwise; breathing and thus speaking out against
all planetary and algorithmic parasites.

What could it then mean to talk about the health of an earth or
planet, its body and property and with reference to which atmospheric
border, which morals and politics of a landing stage? The earth as a
fortress, for either catalogued inhabitants named as bacteria, or for
deathless macro-parasites, morphs into a robot-tended forest
green-house adrift in that exterior space. Another planet is to be
prepared for fit habitation, for a future garden of delights, leaving
behind a toxic landscape which has become simply too elemental,
crossing an entropic boundary but in which direction. A truly modern
Fludd was correct in shaming the elements as evil agents in disease;
monocultures of gold, iron and oxygen binding to cyanide, unable to
sustain any form of life. Monocultures of wheat are set out on that
outside drifting landscape. How does a toxic site appear, what could a
poisonous or poisoned geology be?

As is the case with all fortress, castle and boundary conditions (the
earth as a container and always interior), expressed within Edgar
Allen Poe's The Masque of the Red Death, the real and only threat to
any health has always been inside the castle, body or planet. The
plague and pestilence has always already entered, from the very
beginning unobserved and masqueraded, retreating from an infested
atmosphere, enjoying any feast, and yet always disguised as
death. Here we learn that it is the superposition of language on both
earth and body, as timely virus and as a clocking border control,
which renders both of these sites toxic to all life.

*** SR Unthology circulation:

Fludd: it endeavor[s] to arise anew, and it hastens through the
branches of the aorta to the South, that is the liver, and North or
the spleen.

the incorruptible spirit ... sendeth his beames of life ouer all the
whole frame of man, to illuminate, give life, and circular motion vnto
his spirit.

circulation: the sun impresses on the wind a circular motion, breathed
in, and reaching the heart, is carried around the body in circulation



** own works which deal with circulations

*** earthcomputer

*** earthboot

*** worms.txt

*** mycelium works

*** TEH

*** SR in Messene/heatsick

*** what else?

** schedule
