* workshop: Circulation corruption.

All technology that is derived of earth, must be decomposed and again
reduced to earth.
[Basil Valentine]

Old earth, no more lies, I've seen you, it was me, with my other
ravening eyes, too late.
[Samuel Beckett]

Circulation and corruption (workshop) examines the various
circulations of media through the matters and bodies of the earth and
atmosphere, and through a certain corruption or dissolution of
(digital) identity, meaning and description.

Within a one and a half day hands-on, speculative workshop we will
collectively explore the interfaces and exchanges between living
systems (earth, compost, worms, mycelium) and active audio
electronics. We will participate primarily with our hands and our ears
within circulations amongst earths, composts, mushroom mycelium,
moulds, active chemistry, worms, crows, dusts, smokes and fogs and
impulses and waves.

During the workshop we will construct a series of open circuits which
do not conceal their materiality but participate equally within
material and electrochemical exchanges and circulations. These
circuits are inspired through a media archaeology of electronic music
production, and through the history of alchemical engagement with
minerals, with decay and with the earth. These technical and
conceptual influences are equally opened to circulation and corruption during
the workshop.

We will work with a range of materials (for example, machine cut
copper sheets and oyster mushroom mycelium) and approaches (for
example, with radio transmission and signal reception) to design and
build these open circuits which will enter into processes of
appreciable decay, corruption and dissolution. These open circuits
will be placed during the workshop in selected interior and exterior
locations to participate in various time scales of deterioration and
degradation.

** notes:

ouroboros, latch and comparator circuits opened to moulds and decay, fungi, degradation


the circulatory system of an earth addiction encompassing extraction
(of precious metals, of radioactive minerals), transport (along old
and new Silk Roads) and consumption (the ingestion of earth-derived
energies, materialities and earth-bound pharmaceutical products) and
return or excretion (traces of isotopes and pollution elements in the
body).

* from pharmacy event

Title: Digestion.

Martin Howse

No more fruit, no more trees, no more vegetables, no more plants
pharmaceutical or otherwise and consequently no more food, but
synthetic products to satiety, amid the fumes, amid the special humors
of the atmosphere, on the particular axes of atmospheres wrenched
violently and synthetically from the resistances of a nature which has
known nothing of war except fear.

[Antonin Artaud. To have done with the Judgement of God.]

The health of any body is the concern of an interior against any
outside, of a border and a boundary. The earth or body fortress is
assailed by demonic winds and breath from outside its protecting
walls. Spiritus mali, under the sign of four demons, designated as
four elements, enter the body through gaps in the enclosing skin,
through the mouth and the open pores.

Guarded by four angels, the body becoming earth is concerned with its
proper health as its property, rather than that of its improper
parasites; a modern morality play of pneumatic, breath-borne or skin
un-cleansed bacteria (beyond good and evil, a further taxonomy of
ancient breaths and atoms). A partic-ular pharmakon prompts action
against other decidedly out-of-control entities pursuing or making
happen an unconscious, deep sea set and tabled processes against death
(of their own) or otherwise; breathing and thus speaking out against
all planetary and algorithmic parasites.

What could it then mean to talk about the health of an earth or
planet, its body and property and with reference to which atmospheric
border, which morals and politics of a landing stage? The earth as a
fortress, for either catalogued inhabitants named as bacteria, or for
deathless macro-parasites, morphs into a robot-tended forest
green-house adrift in that exterior space. Another planet is to be
prepared for fit habitation, for a future garden of delights, leaving
behind a toxic landscape which has become simply too elemental,
crossing an entropic boundary but in which direction. A truly modern
Fludd was correct in shaming the elements as evil agents in disease;
monocultures of gold, iron and oxygen binding to cyanide, unable to
sustain any form of life. Monocultures of wheat are set out on that
outside drifting landscape. How does a toxic site appear, what could a
poisonous or poisoned geology be?

As is the case with all fortress, castle and boundary conditions (the
earth as a container and always interior), expressed within Edgar
Allen Poe's The Masque of the Red Death, the real and only threat to
any health has always been inside the castle, body or planet. The
plague and pestilence has always already entered, from the very
beginning unobserved and masqueraded, retreating from an infested
atmosphere, enjoying any feast, and yet always disguised as
death. Here we learn that it is the superposition of language on both
earth and body, as timely virus and as a clocking border control,
which renders both of these sites toxic to all life.

** 

SR Unthology circulation:

Fludd: it endeavor[s] to arise anew, and it hastens through the branches of the aorta to the South, that is the liver, and North or the spleen.

the incorruptible spirit ... sendeth his beames of life ouer all the whole frame of man, to illuminate, give life, and circular motion vnto his spirit.

circulation: the sun impresses on the wind a circular motion, breathed in, and reaching the heart, is carried around the body in circulation


* plan/schedule/activities

divide up days? divide up domains? series of walks/investigations seperated by more building/discussion

eg. earth walk, em-signals/mould walk...

** day one: presentation and introductions
** earth - telluric currents and signals in the earth

measure earth current, capacitors, earth signals listened to, earth battery and comms, worms and wormvoice

** myc, moulds, fermentations?

mycelium radio demo, prepare cultures, prepare smoke mix, bread mix

** bodies - crows and bread

start baking in the earth, cultures for rye/ergot

** atmospheres - smoke and particles, electromagnetic walk

smoke and laser, em signal capture and recordings/notes

** open circuits within each of these environments? during/before each activity

techniques - etch? glass stacked for earth and bread, circuits for moulds in and on dishes, for the crows, worms...

detektor, ouroboric, simple myc radio, 555 or open 555, multivibrator

** day two - working in 3 groups on construction and placement of circulation/corruptions

* tech materials/equipment

- beamer, active monitor speaker, chairs, tables, multiple power points
- hotplate for cooking, 2 very basic medium size (1-2L) cooking pots, chopsticks, 
- portable/battery powered speaker, minijack to minijack (3.5mm) stereo cables (x6)
- for building stuff: soldering irons/stations, craft knives, scissors, sellotape
- mycelium, approx A4 size plastic trays, plastic gloves, ziplock bags, silver foil and some kind cylinder/wax paper for caps
- 1kg organic rye flour, 1kg organic rye grain, 500g-1kg sugar
- small bag of charcoal
- for moulds: agar agar (15g), 200g potatoes, 20g glucose


Medium 129: POTATO DEXTROSE AGAR 

 Infusion from potatoes (see below)         1000.0     ml
 Glucose                                      20.0      g
 Agar                                         15.0      g

Potato infusion:
Boil 200 g scrubbed and sliced potatoes in 1000 ml water for 1 hour. Pass through fine sieve. Avoid
new potatoes.

*Malt agar* for fungi Mix 2 g of malt extract with 2 g of agar with 10
cm3 of water into a paste. Slowly add more water with stirring until
the volume is 100 cm3. Heat in a boiling water bath to 95 °C in the
required container

* prep

- reader and ask headphones, recording apparatus, soldering iron/station

* packing list/to get

- complete setup for exhibition with psu, rocks etc - *long light cable to fix up*

- example circuits, solder iron, solder
- scales
- wire cutters, tweezers, magnifiers
- plastic/ohp sheets
- *glass sheets*, copper sticky and sheets, wire, crocodile clips, *needles*, foil
- *9v batteries, AA  batteries*
- electronics, parts for each circuit: check, parts from reichelt, wire
- petri dishes
- magnifiers
- 2radios
- audio cables
- 2 different metals - copper we have and ...? pie dish?

- detektors x2or3, myc radio, new loop antennas and amp(XLR cable), wormvoice, vlf, TODO_earthdiffamp-INA114, earth boot for measurement
- *laser with battery*, photodiodes
- potassium nitrate, fuses or *sparklers*
- multimeter
- zoom recorder (*test with loop antennas*)
- etch kit
- general kits of parts just in case, smd bulk/other parts


* parts orders

// check parts, check etch

24x 9v clips X
any copper boardsX

** simple elektor sniffer:

2x 10k X
2x 100k X
1k X
3x10uF X
[220uF]
BC547B X
headphone socket? X
1xAA clip X

** multivibrator large and small x12

2x 3904 big X
2x 4k7 X
2x 150 X 

2x 3904 smd X
2x 4k7 X
2x 150 X

** radio transmitter x12 - on glass/plastic or petri dishes

0.8mm wire X
547c X
1nf X
2x 10k X
470R X

** ouroboros x12 - hand-drawn

large and small - check all

6x 3904 X SMD?X
6x 1n4148 X SMD?X
6x 1n XSMD X 
6x 33k XSMD X

** NON

[** NON- 555 x12

390R - check all
2.2u
150K
555]

[** open 555 x1 only

13x 3906 SMT ??mouser
13x 3904 SMT 

7x 4k7 X
820
1k X
10k X
100k X
15k X
6k8
3k9 Xsome
220 
100 Xsome ]
