BOARD_TAG = pro5v328
BOARD_CLOCK=8mhz
ARDUINO_LIBS = Wire SPI OneWire DallasTemperature SdFat DS3232RTC Time PowerSaver
MONITOR_PORT = /dev/ttyACM1
F_CPU = 8000000L
include /root/Arduino-Makefile/Arduino.mk
