* Lattice iCE40-HX8K breakout board
* verilog
* resources


https://github.com/nesl/ice40_examples/ - examples and installing tools

** misc

https://github.com/mcmayer/iCE40

https://stuartl.longlandclan.id.au/blog/2015/12/06/fpga-fun/

https://github.com/sjlongland/icestick/tree/ice40-hx8k

https://github.com/SubProto/icestick-vga-test

http://hedmen.org/icestorm-doc/icestorm.html

** pwm

https://github.com/ZipCPU/wbpwmaudio

https://hackaday.io/project/162557-fpga-dabbling

** flip/flop//SR

https://reference.digilentinc.com/learn/programmable-logic/tutorials/use-flip-flops-to-build-a-clock-divider/start 

https://www.rs-online.com/designspark/a-gentle-introduction-to-fpga-programming

http://www.bitweenie.com/listings/verilog-shift-register/

https://github.com/Obijuan/open-fpga-verilog-tutorial/wiki/Chapter-10:-shift-register

https://esrd2014.blogspot.com/p/d-flip-flop.html

** random/noise also SR

https://casper.ssl.berkeley.edu/wiki/Variable_Correlation_Digital_Noise_Source_for_FPGA

https://github.com/frisnit/fpga-noise/blob/master/verilog/noise_generator.v

http://liu.diva-portal.org/smash/get/diva2:305133/FULLTEXT01.pdf



** verilog

http://www.asic-world.com/verilog/veritut.html

** tools?

http://www.clifford.at/icestorm/ 

https://wiki.debian.org/FPGA/Lattice - full outline and links

https://github.com/abnoname/iceZ0mb1e

* TODO:

- toolchain and basic example, upload

The pipeline employs the following tools:

    yosys - for logic synthesis of Verilog code. The output is a
    netlist describing how all cells are connected together in BLIF
    format.

    arachne-pnr - for placement and routing of the netlist. The output
    is a textual bitstream.

The final step, i.e. preparing the bitstream for the FPGA, and
transferring it to the FPGA, uses:

    fpga-icestorm - for the Lattice boards, using libusb/libftdi


DONE following https://github.com/nesl/ice40_examples/ on x200

- how to connect to I/O, clocking internal and clocking from outside!

pinmap.pcf -- the pin map file relating variable names referenced in
top.v to physical I/O pins on the ICE40 HX8K. The syntax here is
set_io <wire_name> <physical pin name>.

we look at ice40breakout.pdf to see pins!

- simple shift register with all ins and outs



- how to do simulation
- how to maybe implement ouroboric/SR mutated functionality


