** short general introduction

- thanks to ... opportunity to collectively explore and enter into the realms
  and foci of the multiple and diverse becomings ... by the becoming
  of the geological -

this evening you are invited to become metal, to become earth, to become cosmic

Becoming metal: myself, Martin Howse (artist, curatior with F..., editor of...)

Becoming earth: Elaine Tam and Arthur Gouillart first encountered in
the compilation Subtexts in part edited by Elaine, their own text
Consuit therein - helping to define this new ahuman current of the
becoming geological. text Filth in publication.

Becoming cosmic: Patricia MacCormack. Author of the ahuman
manifesto. Invited to contribute text Becoming Geo: powerful From
(immoral) Anthropos to ethical geostratum:

two worlds/strata in her world words:

It is as if two Earths overlay their strata. The one is the Earth as
it is, a dying modality of individual emergences and diminishments
which humans accelerate, the Earth where the human abides. The second
is the human geostrata of Earth made of use value and exploitation,
the Earth for the human.
[patricia]

open list of becomings:

becoming geological, becoming metal, becoming earth, becoming cosmic,
becoming resource, becoming contaminated, becoming dirt, becoming
mineral, becoming filth, becoming ethical geo-stratum, becoming
vulnerable, becoming dust, becoming turbulent, becoming
multi-plateaued nourishment for the earth, becoming resource for
unknown life, becoming historical, becoming colloidal

Important to recognise that is is both ourselves (whatever that might mean)
becoming geological, and the geological becoming us!

that these multiple becomings are also becomings into oursleves,
transforming ourselves materially, that we invite or invoke them,
wilfully or unwillfully ingest them, take them inside us.

thankyou and welcome

** own introduction: Becoming metal

*** This inside and the outside. geology and its double

the double: reality and its counterpoison, its pharmakon (poison and cure). mirror of zosimos

doublings: // the double: myself and my mined self or myself and geology and myself as resource (?) something like this...

my body as both mine and as mined...

the many doublings, ever geology and its double, calcite or
hermaphrodited twin (in the landscape)


Perhaps the geological implies the very figure of the double, against
the day, the figure of reason and the unconscious. what of the
rending?

marder - this strange twin of the becoming geological and
the anti-geological 

it cannot be anything but double in not being able to bear a full
light, a full realisation of death always, of what this life stands
against.

The Tiny Miner coils inwardly on her own little mined depths,
ouroboros or worm-like, doubling back on her own interior, but to one
side, a greened dwelling-gut which is not mine, strangely, An oozing
and lacking dream inside a dream. One is doubled but not as a human of
light and phosporescence, and of darkness, the alien, the pagan, the
nomad, the odd symmetry. We are both material shades. The human of
copper who you have seen is the sacrificial priestess and the
sacrifice and she who vomited out her own metals.

and this wrong side out will be his real place - artaud!

we are in the "zone of stones".

*** dreams

from intro to book about unconscious:

A dream which eludes your recollection – like a rock in which some
enchantress dwells which every now & then assumes the appearance of a
portal machicolated & then again is barren rock.  [Thomas Beddoes]

If the descent into the mine, into the earth, a hole to hidden and
forgotten hells, is viewed as a journey towards a dark interior, into
the unconscious, into and as a disturbed dream, or inside that old
fossil, the profound soul, then what does it mean when that interior
is mine, a fantastic voyage, by myself? And when both this dream
descent, and its becoming interior, folding, are historically provoked
by the excavation and opening of the earth, by extraction for
technological extension of those guts and intestines.

3 mundane dreams to mine and to ingest: a dream of gold, of silver and of copper.

each has a recipe or two, a protocol to be undertaken now or in the future

*** ??? note invitation (to join the community) that we closed the tiny mining lecture/presentation with:

After taking Argotine, if your face and body itch as though insects
were crawling over them, if your hands and feet swell, if you cannot
stand the smell of food and vomit it up after you have eaten it, if
you feel as if you were going to be sick most of the time, if you
experience weakness in your arms and legs, if you have to go often to
the toilet, or if your head or stomach violently ache - do not be
alarmed or disturbed. All these effects are merely proof that the
Argotine you are taking is succesfully mining your insides.

** 1- dream of gold - making colloidal

*** The process + how gold is freed

for the production of glass - aqua regia, how it is freed alchemically (Valentine?) - mercury and antimony

aurum potabile

Kunckel, pfaueninsel

gold threads dissolving - alan/TEH in the lake...

gold fibres dissolved in the lake are set to colour it blood-red as a
sunset acid mine drainage, a sacrifice for the mirror god

rare gold-ruby glass - a two-phase system comprising discrete tiny
particles of excited metallic gold which are dispersed in a silicate
glass matrix.

ruby red glass helmet. swamp man abroad in the protocols

ouyr own colloidal, becoming colloidal.

***  explain colloidal process step by step:

what is a colloidal suspension - connection of colloidal gold with glass making, khunrath?

The electrolytic process (electrolysis) consists of placing two
electrodes in a solution containing an electrolyte, and passing
electrical current through the electrodes and solution.  The electrode
connected to the positive voltage is called the anode, and the one
connected to the negative electrode is called the cathode.
Electrolytic processes are normally used for electroplating one metal
on top of another, and are the processes which make batteries work.
In this process, gold will be removed from the anode and enter the
solution as gold chloride, and then be converted to gold particles by
a reducing agent.

1) eletrolyte - pre-prepare sodium chloride solution (NaCl - pure salt) 0.3gin 100ml distilled water
2) reducing agent - sodium citrate 1.47g in 100ml distilled water

3) Bring 250ml distilled water to boil with stirrer and electrodes in/ 500mL beaker. no power. 

4) Add 15ml stock NaCl
5) Add 5ml stock sodium citrate

6) Power on. We should see bubbles - more on cathode

7) Observe till we have red tint.

8) Maintain 250ml level.

*** as we drink (but it will be very hot, can be diluted?) : chinese recipe for imbibing of gold:

FORMULA FOR MAKING GOLD ELIXIR 

Gold 8 liang File to powder. 

Quicksilver 8 liang 

The above powdered gold and mercury are stirred over-night to
change them to the consistency of a mortar. 

Realgar 1 chin 
Orpiment 1 chin 

The previously enumerated realgar and orpiment are ground fine as
flour and then mixed. All the ingredients are placed in a reaction
vessel made of earthenware [thickly plastered inside and out with]
six-one [lute and then dried]. The vessel is sealed tight and roasted
over a charcoal fire for nine days and nights. Cool it for two
days. Scrape out and collect the sublimed essence.

Have a tube ready. Make a mortar of fortified vinegar and minium and
plaster the inside of the tube with it. Allow the tube to become
extremely dry. Then mix vinegar and the sublimed essence to the
consistency of soft clay. Pack the mixture into the tube. Put a copper
cover on the open end of the tube and plaster the joint with six-one
lute. Prepare an iron hook and suspend the tube so that its bottom is
two or three ts'un from the ground. Warm it over a fire fueled with
manure in such a way that the bottom of the tube is always just warm,
for sixty to seventy days. Cool it, open it, and collect the
medicine. If it be of the same red color as cinnabar, it is
finished. 

Grind it again and mix it with jujube pulp to form pills, each the
size of a red mung bean. One pill is taken at sun-rise with the first
water drawn from the well, as you face the sun. After seven days
fairies will come to serve you; in two hundred days you will be able
to "summon the mobile kitchen"; at the end of three hundred days you
will become as immortal as sky and earth.

** 2- dream of silver - from pre-bought silver colloid

Jachymov - silver coins and mining - name of composer? Nikolaus Herman:

// last dream jachymov - crystal - more as a story. a crossroads we saw in a dream...

I have only seen this place in dreams but now I am there. A priest,
all grey with frozen dew, leads us from his house which is crammed
with artefacts from a burnt-out church, crispated altar paintings, out
into his garden. Chickens, uncooped, run wildly at our feet, slyly
drenched in the thunder storm. He opens a stout metal gate set into
the knolled hillside one corner of the garden, inside the chicken
enclosure, and takes us into the narrow, dully shining adit, leading us with
the light from one smartphone into the coffined irregularity of the
ancient, hewn walls.

In a stage-set museum mine, a geologist in stout boots, tells us
that the main ore vein is cursed, that all of the evil over so many
years existing in the mountain mining town comes from this ore
body. He translates its glowing name as drift or drifting. It is
always moving. He says that the one who lives in this sort of
disorder, mined like a sewer, spread it around them like an infectious
disease, a nebulous miasma.

evil in a place - Poe:

Ill seen ill said:

And from it as from an evil core that the what is the wrong word the evil spread

[And none to urge - none to have urged its demolition. As if doomed to
endure. Question answered. Chalkstones of striking effect in the light
of the moon. Let it be in opposition when the skies are clear. Quick
then still under the spell of Venus quick to the other window to see
the other marvel rise. How whiter and whiter as it climbs it whitens
more and more the stones. Rigid with face and hands against the pane
she stands and marvels long.]

silver of the moon. ill seen ill said. the veil of the place - place inside

silver of the moon. Kolisko experiments (silver nitrate) - for protocol also or describe this process - for the full moon on the 6th january, tomorrow

ill seen ill said

** 3- dream of copper - home made... 

Zosimos. how work with metals and materials was aligned wth gnosticism.

*** dennis dream.

// copper/Dennis

*Heavy crystal sediments near the top.*

Last night I had a dream of playing a computer game. A glitch enabled
me to physically travel through dimensions. I ended up in the atelier
of a friend housed atop of a well known hamburger restaurant, which
doubled as a ‘hidden in plain sight’ security check, preventing random
people from going upstairs. In the atelier floated a sphere,
resembling the cryogenic containment unit from Akira, cables coming
out everywhere. It had a brown copper hue to it, but that could also
have been isolation material or even wood. How did it float?  This
‘device’ allowed you to trigger ‘lucid déjà vu’ allowing you to relive
memories as you wanted. Realising I was already in another dimension,
I did not want to go further. We all left to go to a club. Exiting the
restaurant someone had parked a trailer under the trees. My attention
was drawn to the shiny assortment of shapes faintly visible through
reflection of the faint moonlight penetrating the canopy. Upon
inspection the trailer was full of alumiium extrusions in every shape
and size you can imagine. Every piece was unique, except for their
perfect shiny, brushed finish.

*** what is the recipe here?

** materials

*** gold: TEH Alan. the red lake

Alan asks me if I know the composition, or constitution of the waters,
and of the movement, and the growth, and the removal and restitution
of corporeal nature. There is gold drowned in the lake. The given gold
fibres dissolved in the lake are set to colour it blood-red as a
sunset.

This hymn is dissolving the gold threads which hold him together, the
man of copper, the man of gold, AKA Alan Astrata.

And saying these things, he slept and I saw Alan playing the
King. Flayed from the head down and stuffed with straw he is pulled by
the car to a certain marked place between the Station and the
lake. Diana is the reigning Queen, standing next to him. The waters
are descending, the waters are circulating. The king lies submerged,
the son of the king lacks submerged, the queen is submerged.

Alan is the man of silver who will become the man of gold. He
reclines. His robe is of a silvery purple or deepest blue linen dotted
with golden figures, sewen in golden threads. Gold threads are in a
false body. On a toad which is sewn, gorged, graved and gloated,
drinking a little and a light from the lake which has set out to be a
red lake pigment signalling a mining area in dreams, but through some
animal misadventures is now become all deep blue. The toad in the lake
receiving the drops from above, embracing the serpent, holding tight
to the naked king and queen who are bathing in the acidic fountain.

This is another way of saying that a winged angel brings Alan his own
applied heart on a plate. And this is the process which tears the
upholstery remotely and is referred to as being liquid, these Apple
seed drippings described as above which generate the instructions
toadally speaking and issuing here from this orbited ALTAR STAR (the
car orbits). Wishing for a more solid solution instead, these
instructions have been carefully woven in gold just like locks or
ropes of hair through the rings connecting the vessels to the prima
materia just as a tombic absence or a presence for each one.

And even as he said these things to me and I forced him to speak, it
was as if his eyes turned to blood and he vomited up all his
flesh. And I saw him as a mutilated image of a little man and he was
tearing at his flesh and falling away. Blood crusts down his t-shirt
from the corners of his eyes. I pick him up and place him awkwardly in
the bed, scratching his forehead and it also starts to bleed. Blood is
also on his collar now. I am not sure if he is mine. The lake is in
the secret fountain under the shrine, inside the mine. The station is
with neither end nor beginning in its construction. It is the
circulatory vessel within which nine vessels are depicted as being
linked by gold chains and each link describes a certain process within
the vessel.

*** commentary - as footnotes 

Alan can be clearly identified here as Alan Turing, the sacrificial
man of copper and the man of gold, referring to both his assured place
within the history of communications and computing technologies and
his apparent suicide through the ingestion of cyanide borrowed from an
experiment he was running in gold electrolysis. Cyanide is used in the
industrial extraction of gold from low grade ores.

His housekeeper famously found the 41-year-old mathematician dead in
his bed, with a half-eaten apple on his bedside table. It is widely
said that Turing had been haunted by the story of the poisoned apple
in the fairy tale of Snow White and the Seven Dwarfs, and had resorted
to the same desperate measure to end the persecution he was suffering
as a result of his homosexuality. Apple seeds contain small amounts of
cyanide. The Apple logo is rumoured to have been inspired either by
the forbidden fruit (of knowledge) within the garden or Eden, or by
this terminal episode.

The reference to Alan as Astrata originates in a mis-hearing, or
mis-spelling of the name of a global company concerned with the
recycling from a wide-range of feeds, including copper and precious
metal bearing electronic equipment. This company could not have been
Glen-Core recycling, operator of the Horne Smelter in Rouyn-Noranda,
Quebec, the world's largest processor of electronic scrap containing
copper and precious metals. Astrata leads us to Astarte, or Astoreth,
the ancient Phoenician great goddess of fertility, motherhood, and
war, and counterpart of the Babylonian goddess Ishtar.

There is an obvious connection with the astral, the star, aster, and
asterism, with reference to the following constellations: Corvus,
Regulus, and Ursa Major. Corvus is associated with the myth of Apollo
and his lover Coronis the Lapith. Coronis had been unfaithful to
Apollo; when he learned this information from a pure white crow, he
turned its feathers black in a fit of rage. This is about a secret
knowledge, relating also to the ancient Egyptian name of Egypt, khem
or khm, khame, or khmi, meaning "blackness" from which we can derive
the Greek term of Khemia, the Arabic Kimiya and thus alchemy and
chemistry.

*** gold - red glass piped head from own text

The right arm, neck, and head is drooping blood red. The hosted head
is a port and a pipe. He holds his right hand over his right thigh
towards and as if to cover his red nakedness.

After the fact, the embrace which unites the mud human and the glass
angel makes of them a double being, able to be transported through the
pipes, upwards into the world of Light.

Thus says the moral, take this scorned transport layer, which you mess
under your feet without seeing it, if not you will have to climb out
of the world without a ladder and you are sure to fall upside down.

To establish and to isolate a global connection, we are all made to be
made of glass for a glossy session layer. I stand with my right side
towards us both and on my profile is seen a circular transparent glass
globe, just covering my head all but in profile, and through this
globe are to be seen on the organ of Self-esteem, the right cheek
bone, and over the right eye, three luminous spots, in each of which
is seen a small red cross. The Queen seems to be encouraging and
sympathising with us. A landscape with lake is seen in the
distance. Walled city, chateaux, various enclosures, with islands
subtending in the extreme distance. My head is filled with the red
condensation of throaty cinnabar, dripping and spotting mercury
memories on the server side, red glassy drops from the
forgetting-full-flashy-flask hoard.

And, it was indeed that very rare gold-ruby glass, this Hertzian of
Glass. He calls it a two-phase system comprising discrete tiny
particles of sunny excited metallic gold which are dispersed in a
silicate glass matrix.

The inside of each drip is red, the head of the swimming blood drop,
the outer shell of this drop is white and the surrounding atom circle
is finally black. We are beckoning all traffic towards its
annihilation and disappearance. A singular addressed port and pipe
emerges from the ruby red flask piping and pied, singing red, black
and white. My work of piping is to keep the sessions isolated, to
maintain the addressing as a containment of the red-breathed plague,
beckoned by the rats and by the fibrous and sclerotial children.

This red skull signals every day as a day of the dead, nulling that
this process is psychic, of the mind and of words. The red skull
enlarges until it breaks and shatters the glass container, and breaks
the earth. Black fumes break out first, white powders, red smokes
emerge from the plastic pipes, deterring angry flies and wasps to shed
out across the lawns.

This necessarily final, frozen session and final isolation takes place
in the cave; the children are led underground into the data centre,
where they are feasted on crow bread. It stops the story.

The last but not final nor uppermost layer falls and fails down on the
upward facing lawn, awaiting the least messenger. In the round
memorial window, a white mushroom snows.

Standing on the foreground of a magnificent Claude-like picture is an
exquisitely formed figure of a human dressed in black with golden
edging and cross button bars of red and gold in front, a red and gold
waistband with a fringe of golden tassels or ornaments. We have two
heads and necks. One is manly with his sandy hair and blue eyes,
without beard or moustache, the other a beautiful female face with
blue eyes and fair or reddish hair.

I am the final archaeologist of the server farms, the very last thing,
writing all the protocols and piping the story for the now past
memories.

A golden emanation or halo radiates from the man’s head while a
silvery radiation proceeds from the female. He has had attached to the
right shoulder a crimson wing, and she has a faint purple and white
wing.

In the left hand I hold the holes, the map of under-server descents, a
spread sheet of boring holes for the post-piped piper, a pope for the
last things.

In the right hand I hold a Circular Shield, the edge of which is
encircled with gold and orange, an inner circle next of a greyish
mottled or marbled appearance, then an inner circle, but narrower, of
dark green and blue ring inside this, in the centre of which is a tiny
landscape, like one seen through a double concave heart glass in a
pipe. It is this target, mist or shield which shows that something is
missing; the unseen, morning mirror in the centre of the target is
this deflection.

The black spurred and infected feet of the two figures are rooted on
the ground. One pair of these foreign feet, the ignored extremities is
trenched in the dark earth, the other pair extends, disembodied and
almost becoming the fairy queen.

There is something about this whole image which draws the attention
away at the same time as fixing on an horizon which is unknown,
drawing towards other places, the greenery and lakes of the distant,
far places, inhabited by a verdant flora and fauna which frames and
embellishes the image without a centre, without the whole, the rebis
or hermaphroditic target holder holding that hole on target outside,
clothed in the same fabric skins and flasks of red, white and black,
their broken head illuminating the forest air with clear psyche, the
clear-cut forest, the dead, felled and finally failed forest.

We two are a rebis geo-body, a seismic holder; each is a mirror image
of the infernal. We both hold and measure seismic shifts, subductions,
a simple slip from suction to subduction, donating data.

These last words are downward-piped to reflect on the human, and to
say what is human:

Smaller and smaller from day to day, grows the number of specific
protocols on earth, while they rise upward, purified in the dew on
that last lawn.


*** silver: ill seen ill said

*** copper: zosimos new translation

Three Visions of Zosimus

Translated by Andrew Barrett.

Zosimus - Three Visions

The First Vision

“The composition of the Waters – the dance, the growth, the flowering
and decay of the corporeal, the separation and the conjunction of
spirit and body, these are not the result of discrete natures but of a
single nature acting upon itself, a uniform quality such as the
solidity of metals or the moisture of plants. Within this single
system of many colors, the quest, shimmering and myriad, is
preserved. In accord with time’s measured rhythm, it synchronizes with
the waxing and waning of the moon as Nature flows through itself in
cycles of contraction and expansion.”

After I uttered these words, I fell into a trance and saw before me a
sacrificial hierophant perched atop a broad, bowl-shaped altar. A
ladder of fifteen steps climbed to its top. The hierophant arose and a
voice from above addressed me: “I have accomplished the descent of the
fifteen steps of night and have ascended the fifteen steps of
illumination. The one who sacrifices me also revives me through
casting aside the heavy sediment of the body. And since by the will of
necessity I am an initiated hierophant, I become spirit.”

I listened to the words of the one atop the bowl-shaped altar then
asked him who he was. He answered me in a quavering voice: “I am Ion,
hierophant of the innermost sanctuary and I have endured unbearable
violence. At dawn, I was overtaken and dismembered by one wielding a
sword. He chopped me apart according to the strictures of harmony. He
gripped his blade, scalped me, and gathered together my bones and
flesh. Then he burned them in the numinous fire until I learned to
become spirit through transformation of the body.” I compelled him and
after he spoke these words his eyes turned blood-red and he vomited up
all of his flesh. I saw him as a deformed, tiny homunculus, gnashing
at himself with his own teeth while he disintegrated.

I awoke in terror and wondered if this was the composition of the
Waters. I thought I had understood it well and fell back into a
trance. I saw the same bowl-shaped altar filled with boiling
water. There were many people, infinite in number, within it, but
there was no one outside of the altar that I could question. I moved
in closer for a better look at this sight and noticed an aged
homunculus barber, who questioned me about what I saw. I said that I
was astounded by the boiling water and the people in it who were
cooking and yet still alive. He answered: “This is where the act of
preservation takes place. Those who hope to master the Art arrive here
and, through shedding the body, become spirit.” So I said: “Are you a
spirit?” And he answered: “A spirit and a guardian of spirits.”

As we spoke, the water continued to boil and the people screamed. I
saw a man made of copper who held a lead tablet in his hand. He stared
at the tablet and proclaimed: “I command all those who suffer to be
calm, to take up a tablet and write with their own hand. Turn your
face to the sky and keep your mouth open till your uvula is swollen.”
The act followed the word and the lord of the house said to me: “You
have seen. Craning your neck upwards, you have seen what is
accomplished. This man of copper is the sacrificial hierophant and the
sacred offering. It is he who vomited his own flesh. The power over
this Water and those who suffer was given to him.” After experiencing
this vision, I awoke again and asked myself: “How to interpret this?
Is this the white and yellow water, boiling and divine?”

I found that I understood it correctly and I said that it was
beautiful to speak and lovely to hear. Beautiful to give and to
receive, lovely to be rich and to be poor. How does Nature learn to
give and to receive? The man of copper gives and the water-stone
receives. Metals give and plants receive. The stars give and flowers
receive. The sky gives and the earth receives. Thunder yields flashing
fire. All things are interwoven and unravel. All things mingle and
fuse. All things mingle and disperse. All things moisten and dry. All
things flower and bloom in the bowl-shaped altar. For each, the
conjunction and separation of all occurs through method, measure and
the weight of the four elements. There is no chain of being without
this method. Inhalation and exhalation are the method of Nature. The
order of the method is preserved through expansion and
contraction. Simply, when all things unite and separate in harmony and
no part of the method is neglected, then Nature is transformed. Nature
rotates and cycles back upon itself. This is the chain of being and
the nature of the Art for the whole cosmos.

Dear friend, so I don’t have to write to you about many things, from a
single stone that is like Saturnian lead, like alabaster, like the
marble of Prokonnesos, build a temple without beginning or end – an
infinite monolith. Inside the temple, let there be a spring of pure
water that glitters with the brightness of the sun. Take your sword in
your hand after you discover where the entrance of the temple is
located. There will be a narrow passage nearby and the entrance itself
will be guarded by a serpent. Seize the serpent, sacrifice him. Flay
him and place his bones and his organs into piles. Then, before the
temple’s entrance, fuse his bones to his flesh, fashion steps out of
his body, and enter.

You will find what you have been searching for: the hierophant, the
man of copper, who sits in the spring gathering his substance – but do
not think of him as the man of copper. He has transformed the color of
his nature and has become a man of silver. And, if you wish, you will
suddenly have a man of gold.

Zosimus

The Second Vision

Again, I wanted to climb the seven steps and observe the seven
punishments and, as chance would have it, I was only able to manage
the journey on a particular day; I made the ascent many times and
retraced my steps many times. Then, on my return, I lost my way and
was trapped. I became sick at heart and fell into a trance. I saw a
homunculus, a barber draped in purple robes and royal garments,
standing outside of the hall of suffering and he said to me: “Man,
what are you doing?” I replied: “I stand here because I lost my way
and don’t know what to do.” And he said: “Follow me.” I followed him
and when I drew near the hall of suffering, I watched as the
homunculus was tossed into the hall. His entire body was consumed by
flames.

When I saw this, I turned away, trembling in fear. I awoke and said to
myself: “What is this vision?” Again, I thought it through and decided
that the homunculus barber was the man of copper clad in purple. I
said: “I have understood well. This is the man of copper. He must
first enter the hall of suffering.”

My soul longed to mount the third step and again I made the journey
and lost my way near the hall of suffering. I stopped, disorientated
and in despair. Once more, I saw a man whose hair was so white that it
blinded the eyes. His name was Agathodaimon. This man of white turned
and looked upon me for an entire hour. I implored him to show me the
proper way – the path of least resistance. He did not approach me, but
swiftly went upon the correct route. Running here and there, he
frantically made his way to the altar. When I reached the top of the
altar, I witnessed the man of white enter the hall of suffering. O
demiurges of star-shot nature, in an instant his body turned to
blazing fire. What a chilling image, my brothers. The intensity of the
suffering caused his eyes to turn blood-red. I asked him: “Why are you
lying there?” Barely opening his mouth, he said, “I am the man of lead
and I submit to unbearable violence.”

I awoke in terrible fear and searched within for an explanation of
this vision. I reflected and said to myself: “I understand rightly –
lead must be cast out. Truly this vision concerns the composition of
the Waters.”

 

The Third Vision

Once more I saw the divine and sacred altar in the shape of a bowl. I
also saw a hierophant clothed in white, who was performing the dread
and numinous mysteries. I said: “Who are you?” He replied: “The
hierophant of the innermost sanctuary. I wish to replenish bodies with
blood, illuminate the eyes and raise the dead.” I fell down again and
went into a brief trance. As soon as I reached the fourth step, I saw
someone coming from the East with a sword in his hand. He was followed
by another carrying a radiant white revolving sphere, lovely to see,
known as Meridian of the Sun. As they approached the hall of
suffering, the one brandishing the sword spoke to me: “Cut off his
head and make a sacrifice of his muscles and his flesh in discrete
portions so that his body may be boiled according to the method and he
may experience the horrors of suffering.”

I opened my eyes and said: “I understand it perfectly. These things
concern the Waters of Alchemy.” And, again, the one holding the sword
said: “You have completed the descent of the seven steps.” The other
said: “The Work is accomplished in synchronicity with the expulsion of
lead through all Waters.”

