#+OPTIONS: toc:nil

** The evening of becoming geological

Welcome to the evening of becoming geological. We invite you to become
metal, to become earth and to become cosmic.

I'd like to thank Florian, Michel, Joke, Boris, Wilco, Richard, Marieke,
Dineke, Steffan and everyone at v2 and the artists and authors
involved, for this wonderful opportunity to collectively explore and
enter into the realms and foci of the multiple and diverse becomings
provoked by the becoming of the geological, that being.

Becoming metal: hosted by myself, Martin Howse (artist, curator with Florian,
editor of the book)

Becoming earth: Elaine Tam and Arthur Gouillart first encountered in
the compilation Subtexts in part edited by Elaine, their own text
Conduit therein - helping to ill define this new ahuman current of the
becoming geological. text Filth in publication.

Becoming cosmic: Patricia MacCormack. Author of the ahuman
manifesto. Invited to contribute text Becoming Geological: powerful From
(immoral) Anthropos to ethical geostratum:

To quote ... two worlds/strata in her world words:

It is as if two Earths overlay their strata. The one is the Earth as
it is, a dying modality of individual emergences and diminishments
which humans accelerate, the Earth where the human abides. The second
is the human geostrata of Earth made of use value and exploitation,
the Earth for the human.
[patricia]

I'd like to begin with a list of becomings which we can hopefully embrace:

becoming geological, becoming metal, becoming earth, becoming cosmic,
becoming resource, becoming contaminated, becoming dirt, becoming
mineral, becoming filth, becoming ethical geo-stratum, becoming
vulnerable, becoming dust, becoming turbulent, becoming
multi-plateaued nourishment for the earth, becoming resource for
unknown life, becoming historical, becoming colloidal

Important to recognise that is is both ourselves (whatever that might
mean) becoming geological, and the geological becoming us! ... that
these multiple becomings are also becomings into ourselves,
transforming ourselves materially and hesitatantly spiritually, that
we invite or invoke them, wilfully or unwillfully ingest them, always
take them inside us.

To say thankyou and welcome.

** Becoming metal

Frozen true to her wont she seems turned to stone. Face to the further
confines the eye closes in vain to see. At last they appear an
instant. North where she passes them always. Shroud of radiant
haze. Where to melt into paradise.
[Beckett. Ill seen Ill said - mention about quotes]

*** This inside and the outside

Geology and its double, the inside and the outside, both are places:
reality and its counterpoison, its pharmakon (poison and cure).

[...] the head is covered. No matter. No matter now. Such the
confusion now between real and – how say its contrary? No matter. That
old tandem. Such now the confusion between them once so twain. And
such the farrago from eye to mind. For it to make what sad sense of it
may. No matter now. Such equal liars both. Real and – how ill say its
contrary? The counter-poison.

the double: myself and my mined self, as a resource for others.

my body as both mine and as mined...

The Tiny Miner coils inwardly on her own little mined depths,
ouroboros worm-like, doubling back, an involuted mirror, on her own
interior, but to one side, a greened dwelling-gut which is elsewhere,
strangely, an oozing and lacking dream inside a dream. One is doubled
but not as a human of light and phosporescence, and of darkness, the
alien, the pagan, the nomad, this final, odd symmetry. We are both
material shades.

Perhaps the geological implies the very figure of the tiny, filleted
double, against the day, the figures of reason and the unconscious;
this strange twin of the becoming geological and the anti-geological,
it cannot be anything but double in not being able to bear a full
light, a full realisation of death always, of what this life stands
against.

"I contain my outside" 

[...] and this wrong side out will be his real place [artaud!]

*** a series of dreams

A dream which eludes your recollection – like a rock in which some
enchantress dwells which every now and then assumes the appearance of a
portal machicolated and then again is barren rock.  [Thomas Beddoes]

If the descent into the mine, into the earth, a hole to hidden and
forgotten hells, is viewed as a journey towards a dark interior, into
the unconscious, into and as a disturbed dream, or inside that old
fossil, the profound soul, then what does it mean when that interior
is mine, a fantastic voyage, into and by myself? And when both this
dream descent, and its becoming interior, folding, are historically
provoked by the excavation and opening of the earth, by extraction for
technological extension of those guts and intestines.

I'd like to present a series of mundane dreams for you to excavate and
mine, to finally ingest and to digest: dreams of gold, of silver and
of copper. These are also recipes, or protocols, algorithms to be
followed or undertaken now or in the future

We will ingest and dream futures of gold, silver and copper in the
following three sections...

** 1- The dream of gold - becoming colloidal

A man emerges from a bog or swamp, being welcomed by
a winged angel bearing a red or purple coat. The man is black, his
outstretched arm is white, his foremost arm is red, and his head is
enveloped in a ruby red glass bubble - some kind of apparatus. These colours
describe three stages in the alchemical process, three colours of the
philosopher's stone. The first, black stage which the figure and his
emergence describe is fermentation, putrefaction, darkness or
decay. This stage can also refer to the Prima Materia, the first
matter of this material or exo-spiritual action. This is the Crow's
head. The second stage is white and is called Albedo. It is associated
with purification and perhaps with a separation of elements.

The final stage is called rubedo, a reddening or purpling perhaps of a
dawn. The red powder multiplies all gold, all dawns, and the purple
robe allows ascendance to eternal life.

*** The process

I'd like to start by trying to make colloidal gold, a nano particle suspension of gold, for us to drink.

****  explain colloidal process step by step:

what is a colloidal suspension - connection of colloidal gold with glass making

The electrolytic process (electrolysis) consists of placing two
electrodes in a solution containing an electrolyte, and passing
electrical current through the electrodes and solution.

In this process, gold will be removed from the anode (the positive
electrode made of gold) and enter the solution as gold chloride, and
then be converted to gold particles by a reducing agent.

1) eletrolyte - pre-prepare sodium chloride solution (NaCl - pure salt) 0.3g in 100ml distilled water
2) reducing agent - sodium citrate 1.47g in 100ml distilled water (pre-prep?)

3) Bring 500ml distilled water to boil with stirrer and electrodes in/ 500mL beaker. no power. already done...

4) Add 30ml stock NaCl
5) Add 10ml stock sodium citrate

6) Power on. We should see bubbles - more on the cathode

7) Observe till we have red tint.

8) Maintain 500ml level.

*** Gold is freed from other metals. freed, liberated from its fixed forms.

Historically within the production of ruby red glass, or of aurum
potabile, drinkable gold.

Gold is dissolved in aqua regia, a mixture of hydrochloric and nitric
acids, then precipitated from gold chrloride as metallic gold
nanoparticles by a mixture of stannic and stannous chloride.

These were secret procedures - Werner Herzog’s movie dating to 1976,
Heart of Glass (in German: Herz aus Glas): in a Bavarian village in the
late eighteenth century, a glassmaker dies and takes to his grave the secret
of his ruby glass. The glass factory owner goes mad trying to unearth the
formula. As he goes mad, so does the village.

A fragment of seventeenth-century ruby red glass found in the remains
of Johannes Kunckel’s factory at Peacock island) was studied - the
Gold concentration was 160 ppm, that of tin oxide was 525 ppm, and the
gold particles displayed a cubo-octahedral morphology and had the
right sizes (∼40 nm) to provoke the proper red colour through the
phenomenon of surface plasmon resonance.

Gold nanoparticles were used to make the beautiful red and purple
colors in stained glass found in the Medieval Churches. According to
Professor Zhu Huai Yong of Queensland University, gold stained glass
windows are able to purify the air as well as look pleasing to the
eye.

The right arm, neck, and head is drooping blood red. The hosted head
is a port and a pipe. He holds his right hand over his right thigh
towards and as if to cover his red nakedness.

After the fact, the embrace which unites the mud human and the glass
angel makes of them a double being, able to be transported through the
pipes, upwards into the world of Light.

Thus says the moral, take this scorned transport layer, which you mess
under your feet without seeing it, if not you will have to climb out
of the world without a ladder and you are sure to fall upside down.

To establish and to isolate a global connection, we are all made to be
made of glass for a glossy session layer. I stand with my right side
towards us both and on my profile is seen a circular transparent glass
globe, just covering my head all but in profile, and through this
globe are to be seen on the organ of Self-esteem, the right cheek
bone, and over the right eye, three luminous spots, in each of which
is seen a small red cross. The Queen seems to be encouraging and
sympathising with us. A landscape with lake is seen in the
distance. Walled city, chateaux, various enclosures, with islands
subtending in the extreme distance. My head is filled with the red
condensation of throaty cinnabar, dripping and spotting mercury
memories on the server side, red glassy drops from the
forgetting-full-flashy-flask hoard.

And, it was indeed that very rare gold-ruby glass, this Hertzian of
Glass. He calls it a two-phase system comprising discrete tiny
particles of sunny excited metallic gold which are dispersed in a
silicate glass matrix.

The inside of each drip is red, the head of the swimming blood drop,
the outer shell of this drop is white and the surrounding atom circle
is finally black. We are beckoning all traffic towards its
annihilation and disappearance. A singular addressed port and pipe
emerges from the ruby red flask piping and pied, singing red, black
and white. 

This red skull signals every day as a day of the dead, nulling that
this process is psychic, of the mind and of words. The red skull
enlarges until it breaks and shatters the glass container, and breaks
the earth. Black fumes break out first, white powders, red smokes
emerge from the plastic pipes, deterring angry flies and wasps to shed
out across the lawns.

How it is freed alchemically (Valentine?) - mercury and antimony

If you would operate by means of our bodies, take a fierce grey wolf,
which, though on account of its name it be subject to the sway of
warlike Mars, is by birth the offspring of ancient Saturn, and is
found in the valleys and mountains of the world, where he roams about
savage with hunger. Cast to him the body of the King, and when he has
devoured it, burn him entirely to ashes in a great fire. By this
process the King will be liberated; and when it has been performed
thrice the Lion has overcome the wolf, and will find nothing more to
devour in him. Thus our Body has been rendered fit for the first stage
of our work.

Know that this is the only right and legitimate way of purifying our
substance: for the Lion purifies himself with the blood of the wolf,
and the tincture of its blood agrees most wonderfully with the
tincture of the Lion, seeing that the two liquids are closely akin to
each other. When the Lion's hunger is appeased, his spirit becomes
more powerful than before, and his eyes glitter like the Sun. His
internal essence is now of inestimable value for the removing of all
defects, and the healing of all diseases. He is pursued by the ten
lepers, who desire to drink his blood; and all that are tormented with
any kind of sickness are refreshed with this blood.

For whoever drinks of this golden fountain, experiences a renovation
of his whole nature, a vanishing of all unhealthy matter, a fresh
supply of blood, a strengthening of the heart and of all the vitals,
and a permanent bracing of every limb. For it opens all the pores, and
through them bears away all that prevents the perfect health of the
body, but allows all that is beneficial to remain therein unmolested.
[basil valentine - first key in twelve keys]

*** optional // as we drink (but it will be very hot, can be diluted?) : chinese recipe for imbibing of gold:

**** FORMULA FOR MAKING GOLD ELIXIR - from Tan Ching Yao Chuen (“Great Secrets of Alchemy”), probably by Sun Ssu-miao (AD 581–after 673).

Gold 8 liang File to powder. 

Quicksilver 8 liang 

The above powdered gold and mercury are stirred over-night to
change them to the consistency of a mortar. 

Realgar 1 chin 
Orpiment 1 chin 

The previously enumerated realgar and orpiment are ground fine as
flour and then mixed. All the ingredients are placed in a reaction
vessel made of earthenware [thickly plastered inside and out with]
six-one [lute and then dried]. The vessel is sealed tight and roasted
over a charcoal fire for nine days and nights. Cool it for two
days. Scrape out and collect the sublimed essence.

Have a tube ready. Make a mortar of fortified vinegar and minium and
plaster the inside of the tube with it. Allow the tube to become
extremely dry. Then mix vinegar and the sublimed essence to the
consistency of soft clay. Pack the mixture into the tube. Put a copper
cover on the open end of the tube and plaster the joint with six-one
lute. Prepare an iron hook and suspend the tube so that its bottom is
two or three ts'un from the ground. Warm it over a fire fueled with
manure in such a way that the bottom of the tube is always just warm,
for sixty to seventy days. Cool it, open it, and collect the
medicine. If it be of the same red color as cinnabar, it is
finished. 

Grind it again and mix it with jujube pulp to form pills, each the
size of a red mung bean. One pill is taken at sun-rise with the first
water drawn from the well, as you face the sun. After seven days
fairies will come to serve you; in two hundred days you will be able
to "summon the mobile kitchen"; at the end of three hundred days you
will become as immortal as sky and earth.

** 2- dream of silver - drink from pre-bought silver colloid. full moon tommorrow evening.

green glass...

I have only seen this place in dreams but now I am there, at the
crossroads, in the rain. The priest, all grey with frozen dew, leads
us from his house crammed with artefacts from a burnt-out church,
crispated altar paintings, out into the yard. Uncooped chickens, run
wildly at our feet, slyly drenched in the thunder storm. Opens a stout
metal gate set into the knolled hillside one corner of the muddy yard,
inside the enclosure, and takes us into the narrow, dully shining
adit, leading us with the light from one phone into the coffined
irregularity of the ancient, hewn walls. 16th century silver mine.

A stage-set wooden museum mine, the geologist in stout boots, tells us that
the main ore vein is cursed, that all of the evil over so many years
existing in the mountain mining town comes from this ore body. He
translates its glowing name as drift or drifting. It is always
moving. He says that the one who lives in this sort of disorder, mined
like a sewer, spreads it around them like an infectious disease, a
nebulous miasma.

His tannery dog, middle aged, crowned hat, vomits old silver coins and
terse liquid on his boots. He brought it up again, this colloidal and
dewy morning.

This dream of silver is a place in the zone of stones. There was a
time when she did not appear in the zone of stones. A long time.

Of striking effect in the light of the moon these millions of little
sepulchres.

This opinion, in its general form, was that of the sentience of all
vegetable things. But, in his disordered fancy, the idea had assumed a
more daring character, and trespassed, under certain conditions, upon
the kingdom of inorganization. [...]

The conditions of the sentience had been here, he imagined, fulfilled
in the method of collocation of these stones – in the order of their
arrangement, as well as in that of the many fungi which overspread
them, and of the decayed trees which stood around – above all, in the
long undisturbed endurance of this arrangement, and in its
reduplication in the still waters of the tarn.

Its evidence – the evidence of the sentience – was to be seen, he
said, (and I here started as he spoke,) in the gradual yet certain
condensation of an atmosphere of their own about the waters and the
walls. The result was discoverable, he added, in that silent, yet
importunate and terrible influence which for centuries had moulded the
destinies of his family, and which made him what I now saw him – what
he was.  [Edgar Allen Poe. The Fall of the House of Usher]

Ill seen ill said:

And from it as from an evil core that the what is the wrong word the
evil spread.

[Stones increasingly abound. Ever scanter even the rankest
weed. Meagre pastures hem it round on which it slowly gains. With none
to gainsay. To have gainsaid. As if doomed to spread. How come a cabin
in such a place? How came? Careful. Before replying that in the far
past at the time of its building there was clover growing to its very
walls. Implying furthermore that it the culprit. And from it as from
an evil core that the what is the wrong word the evil spread. And none
to urge – none to have urged its demolition. As if doomed to
endure. Question answered. Chalkstones of striking effect in the light
of the moon. Let it be in opposition when the skies are clear. Quick
then still under the spell of Venus quick to the other window to see
the other marvel rise. How whiter and whiter as it climbs it whitens
more and more the stones. Rigid with face and hands against the pane
she stands and marvels long.]

She is drawn to a certain spot. At times. There stands a stone. It it
is draws her. Rounded rectangular block three times as high as
wide. Four. Her stature now. Her lowly stature. When it draws she must
to it. She cannot see it from her door. Blindfold she could find her
way. With herself she has no more converse. Never had much. Now
none. As had she the misfortune to be still of this world. But when
the stone draws then to her feet the prayer, Take her. Especially at
night when the skies are clear. With moon or without. They take her
and halt her before it. There she too as if of stone. But
black. Sometimes in the light of the moon. Mostly of the stars
alone. Does she envy it?


A protocol for tomorrow's full moon - Lili Kolisko process: examining
the influence of the moon on silver, and of other planets on solutions
of other metals

Handle silver nitrate and solutions with plastic gloves provided

Dissolve 1g of silver nitrate in 100mL of distilled water

Add solutions of other metals, or urine (during and after chelation) or sweat samples

Pour 30mL into a glass dish (preferably 6cm high and 8cm diameter)

Either roll up filter paper or suspend flat paper and place as deep as possible into the dish

Choose to leave this paper in the dish either in a dark room or a room with daylight for 12 hours.

Photograph, scan or otherwise record the results

Repeat this process with the same solution the following day...

On the other hand, if we think of the experiments with filter paper
we see that silver is a metal which has in itself a hidden power
of formative force which we do not find in any of the other metals in
the same strength. 

Each day produces another picture, full moon and new
moon have specific characteristic expressions and if the experiments
are extended over many years, we find that even the years are
different in their effect on the silver solution.  

If we bring together the immense amount of material we gathered
through many years of incessant study day and night, all the
constellations of Sun and moon, Mars and moon, Saturn and moon,
Jupiter and moon, Venus and moon, Mercury and moon and all the other
qualities of this metal which we mentioned above, then perhaps we
might be allowed to say: the silver acts in such a way that it
represents what lives in the light, it produces pictures of what acts
in the light. 

And if we find that this is connected especially with the moon, it may
be justified to say: the silver behaves like the moon in the
cosmos. The moon itself has the strange quality that it continually
reflects the light which comes from the sun and all the other
planets. The moon is the great photographer of the universe, it
continually brings us back pictures.

** 3- dream of copper - home made...  Visions of Zosimos - the first vision

“The composition of the Waters – the dance, the growth, the flowering
and decay of the corporeal, the separation and the conjunction of
spirit and body, these are not the result of discrete natures but of a
single nature acting upon itself, a uniform quality such as the
solidity of metals or the moisture of plants. Within this single
system of many colors, the quest, shimmering and myriad, is
preserved. In accord with time’s measured rhythm, it synchronizes with
the waxing and waning of the moon as Nature flows through itself in
cycles of contraction and expansion.”

After I uttered these words, I fell into a trance and saw before me a
sacrificial hierophant perched atop a broad, bowl-shaped altar. A
ladder of fifteen steps climbed to its top. The hierophant arose and a
voice from above addressed me: “I have accomplished the descent of the
fifteen steps of night and have ascended the fifteen steps of
illumination. The one who sacrifices me also revives me through
casting aside the heavy sediment of the body. And since by the will of
necessity I am an initiated hierophant, I become spirit.”

I listened to the words of the one atop the bowl-shaped altar then
asked him who he was. He answered me in a quavering voice: “I am Ion,
hierophant of the innermost sanctuary and I have endured unbearable
violence. At dawn, I was overtaken and dismembered by one wielding a
sword. He chopped me apart according to the strictures of harmony. He
gripped his blade, scalped me, and gathered together my bones and
flesh. Then he burned them in the numinous fire until I learned to
become spirit through transformation of the body.” 

I compelled him and after he spoke these words his eyes turned
blood-red and he vomited up all of his flesh. I saw him as a deformed,
tiny homunculus, gnashing at himself with his own teeth while he
disintegrated.

And even as he said these things to me and I forced him to speak, it
was as if his eyes turned to blood and he vomited up all his
flesh. And I saw him as a mutilated image of a little man and he was
tearing at his flesh and falling away. Blood crusts down his t-shirt
from the corners of his eyes. I pick him up and place him awkwardly in
the bed, scratching his forehead and it also starts to bleed. Blood is
also on his collar now. I am not sure if he is mine. The lake is in
the secret fountain under the shrine, inside the mine. The station is
with neither end nor beginning in its construction. It is the
circulatory vessel within which nine vessels are depicted as being
linked by gold chains and each link describes a certain process within
the vessel.

I awoke in terror and wondered if this was the composition of the
Waters. I thought I had understood it well and fell back into a
trance. I saw the same bowl-shaped altar filled with boiling
water. There were many people, infinite in number, within it, but
there was no one outside of the altar that I could question. I moved
in closer for a better look at this sight and noticed an aged
homunculus barber, who questioned me about what I saw. I said that I
was astounded by the boiling water and the people in it who were
cooking and yet still alive. He answered: “This is where the act of
preservation takes place. Those who hope to master the Art arrive here
and, through shedding the body, become spirit.” So I said: “Are you a
spirit?” And he answered: “A spirit and a guardian of spirits.”

As we spoke, the water continued to boil and the people screamed. I
saw a man made of copper who held a lead tablet in his hand. He stared
at the tablet and proclaimed: “I command all those who suffer to be
calm, to take up a tablet and write with their own hand. Turn your
face to the sky and keep your mouth open till your uvula is swollen.”
The act followed the word and the lord of the house said to me: “You
have seen. Craning your neck upwards, you have seen what is
accomplished. This man of copper is the sacrificial hierophant and the
sacred offering. It is he who vomited his own flesh. The power over
this Water and those who suffer was given to him.” After experiencing
this vision, I awoke again and asked myself: “How to interpret this?
Is this the white and yellow water, boiling and divine?”

I found that I understood it correctly and I said that it was
beautiful to speak and lovely to hear. Beautiful to give and to
receive, lovely to be rich and to be poor. How does Nature learn to
give and to receive? The man of copper gives and the water-stone
receives. Metals give and plants receive. The stars give and flowers
receive. The sky gives and the earth receives. Thunder yields flashing
fire. All things are interwoven and unravel. All things mingle and
fuse. All things mingle and disperse. All things moisten and dry. All
things flower and bloom in the bowl-shaped altar. For each, the
conjunction and separation of all occurs through method, measure and
the weight of the four elements. There is no chain of being without
this method. Inhalation and exhalation are the method of Nature. The
order of the method is preserved through expansion and
contraction. Simply, when all things unite and separate in harmony and
no part of the method is neglected, then Nature is transformed. Nature
rotates and cycles back upon itself. This is the chain of being and
the nature of the Art for the whole cosmos.

Light. In one treacherous word. Dazzling haze. Light in its might at
last. Where no more to be seen. To be said. Gently gently.

