** short general introduction

- thanks to ... opportunity to collectively explore and enter into the realms
  and foci of the multiple and diverse becomings ... by the becoming
  of the geological -

this evening you are invited to become metal, to become earth, to become cosmic

Becoming metal: myself, Martin Howse (artist, curatior with F..., editor of...)

Becoming earth: Elaine Tam and Arthur Gouillart first encountered in
the compilation Subtexts in part edited by Elaine, their own text
Consuit therein - helping to define this new ahuman current of the
becoming geological. text Filth in publication.

Becoming cosmic: Patricia MacCormack. Author of the ahuman
manifesto. Invited to contribute text Becoming Geo: powerful From
(immoral) Anthropos to ethical geostratum:

two worlds/strata in her world words:

It is as if two Earths overlay their strata. The one is the Earth as
it is, a dying modality of individual emergences and diminishments
which humans accelerate, the Earth where the human abides. The second
is the human geostrata of Earth made of use value and exploitation,
the Earth for the human.
[patricia]

open list of becomings:

becoming geological, becoming metal, becoming earth, becoming cosmic,
becoming resource, becoming contaminated, becoming dirt, becoming
mineral, becoming filth, becoming ethical geo-stratum, becoming
vulnerable, becoming dust, becoming turbulent, becoming
multi-plateaued nourishment for the earth, becoming resource for
unknown life, becoming historical, becoming colloidal

Important to recognise that is is both ourselves (whatever that might mean)
becoming geological, and the geological becoming us!

that these multiple becomings are also becomings into oursleves,
transforming ourselves materially, that we invite or invoke them,
wilfully or unwillfully ingest them, take them inside us.

thankyou and welcome

** own introduction: Becoming metal

*** This inside and the outside. geology and its double

the double: reality and its counterpoison, its pharmakon (poison and cure). mirror of zosimos

doublings: // the double: myself and my mined self or myself and geology and myself as resource (?) something like this...

my body as both mine and as mined...

the many doublings, ever geology and its double, calcite or
hermaphrodited twin (in the landscape)

of inside and outside. those inside and the others outside. 

and the outside turns in on itself: inside out. inside in. - to become a strange loop inside. mirrors outside or in mirroring the outside the outside is in.

contained view | dream
isolated | darkness
muted | permuted cores

doubles from intro:

The Tiny Miner coils inwardly on her own little mined depths,
ouroboros worm-like, doubling back, an involuted mirror, on her own
interior, but to one side, a greened dwelling-gut which is elsewhere,
strangely, an oozing and lacking dream inside a dream. One is doubled
but not as a human of light and phosporescence, and of darkness, the
alien, the pagan, the nomad, this final, odd symmetry. We are both
material shades.

Perhaps the geological implies the very figure of the tiny, filleted
double, against the day, the figures of reason and the unconscious;
this strange twin of the becoming geological and the anti-geological,
it cannot be anything but double in not being able to bear a full
light, a full realisation of death always, of what this life stands
against.

The human of copper who you have seen is the sacrificial priestess and
the sacrifice and she who vomited out her own metals; a vomiting tiny
miner, expelling the prima materia, unable to digest the "planet's
magmic inorganic depths" and thus her "Spirit developed the ulcer we
now call the Unconscious."

"I contain my outside" implies that this outside, my becoming-sentient
outside, is within me, as a floating, rocky island bloated by a sudden
burst of available and ethically-obscure nutrients.

and this wrong side out will be his real place - artaud!

*** dreams

from intro to book about unconscious:

A dream which eludes your recollection – like a rock in which some
enchantress dwells which every now & then assumes the appearance of a
portal machicolated & then again is barren rock.  [Thomas Beddoes]

If the descent into the mine, into the earth, a hole to hidden and
forgotten hells, is viewed as a journey towards a dark interior, into
the unconscious, into and as a disturbed dream, or inside that old
fossil, the profound soul, then what does it mean when that interior
is mine, a fantastic voyage, by myself? And when both this dream
descent, and its becoming interior, folding, are historically provoked
by the excavation and opening of the earth, by extraction for
technological extension of those guts and intestines.

3 mundane dreams to mine and to ingest: a dream of gold, of silver and of copper.

each has a recipe or two, a protocol to be undertaken now or in the future

*** ??? note invitation (to join the community) that we closed the tiny mining lecture/presentation with:

After taking Argotine, if your face and body itch as though insects
were crawling over them, if your hands and feet swell, if you cannot
stand the smell of food and vomit it up after you have eaten it, if
you feel as if you were going to be sick most of the time, if you
experience weakness in your arms and legs, if you have to go often to
the toilet, or if your head or stomach violently ache - do not be
alarmed or disturbed. All these effects are merely proof that the
Argotine you are taking is succesfully mining your insides.

** 1- dream of gold - making colloidal

key image: splendor solis swamp man:

The image shows a man emerging from a bog or swamp, being welcomed by
a winged angel bearing a red or purple coat. The man is black, his
outstretched arm is white, his foremost arm is red, and his head is
enveloped in a ruby red glass bubble - some kind of apparatus. These colours
describe three stages in the alchemical process, three colours of the
philosopher's stone. The first, black stage which the figure and his
emergence describe is fermentation, putrefaction, darkness or
decay. This stage can also refer to the Prima Materia, the first
matter of this material or exo-spiritual action. This is the Crow's
head. The second stage is white and is called Albedo. It is associated
with purification and perhaps with a separation of elements.

The final stage is called rubedo, a reddening or purpling perhaps of a
dawn. The red powder multiplies all gold, all dawns, and the purple
robe allows ascendance to eternal life.


*** The process + how gold is freed

for the production of glass - aqua regia: 

produced gold chloride by dissolving gold in aqua regia, a mixture of
hydrochloric and nitric acids.

the paternity of the purple gold precipitate used for colouring
glass, the so-called Purple of Cassius, has been attributed to Andrea
Cassius. As described earlier, the preparation involves gold being
dissolved in aqua regia, then its precipitation as metallic gold
nanoparticles by a mixture of stannic and stannous chloride.

This is illustrated by the Werner Herzog’s movie dating to 1976,
Heart of Glass (in German: Herz aus Glas): in a Bavarian village in the
late eighteenth century, a glassmaker dies and takes to his grave the secret
of his ruby glass. The glass factory owner goes mad trying to unearth the
formula. As he goes mad, so does the village.

A fragment of seventeenth-century ruby red glass found in the remains
of Kunckel’s factory at Peacock island (see Section 1.2.5.2) was stud-
ied by Fredrickx et al.59 Gold concentration was 160 ppm, that of tin
oxide was 525 ppm, and the gold particles displayed a cubo-octahedral
morphology and had the right sizes (∼40 nm) to provoke the proper red
colour through the phenomenon of surface plasmon resonance (Chap-
ter 3). Iron-containing particles, mostly α-Fe2O3 were abundantly found
in the glass matrix and were supposed to have an influence on the
colour.

how it is freed alchemically (Valentine?) - mercury and antimony

If you would operate by means of our bodies, take a fierce grey wolf,
which, though on account of its name it be subject to the sway of
warlike Mars, is by birth the offspring of ancient Saturn, and is
found in the valleys and mountains of the world, where he roams about
savage with hunger. Cast to him the body of the King, and when he has
devoured it, burn him entirely to ashes in a great fire. By this
process the King will be liberated; and when it has been performed
thrice the Lion has overcome the wolf, and will find nothing more to
devour in him. Thus our Body has been rendered fit for the first stage
of our work.

Know that this is the only right and legitimate way of purifying our
substance: for the Lion purifies himself with the blood of the wolf,
and the tincture of its blood agrees most wonderfully with the
tincture of the Lion, seeing that the two liquids are closely akin to
each other. When the Lion's hunger is appeased, his spirit becomes
more powerful than before, and his eyes glitter like the Sun. His
internal essence is now of inestimable value for the removing of all
defects, and the healing of all diseases. He is pursued by the ten
lepers, who desire to drink his blood; and all that are tormented with
any kind of sickness are refreshed with this blood.

For whoever drinks of this golden fountain, experiences a renovation
of his whole nature, a vanishing of all unhealthy matter, a fresh
supply of blood, a strengthening of the heart and of all the vitals,
and a permanent bracing of every limb. For it opens all the pores, and
through them bears away all that prevents the perfect health of the
body, but allows all that is beneficial to remain therein unmolested.
[basil valentine - first key]

aurum potabile - drinkable gold (see also recipes in Bartlett)

ruby red - Johan Kunckel, pfaueninsel

Gold nanoparticles were used to make the beautiful red and purple
colors in stained glass found in the Medieval Churches. According to
Professor Zhu Huai Yong of Queensland University, gold stained glass
windows are able to purify the air as well as look pleasing to the
eye.

gold threads dissolving - alan/TEH in the lake...

gold fibres dissolved in the lake are set to colour it blood-red as a
sunset acid mine drainage, a sacrifice for the mirror god

rare gold-ruby glass - a two-phase system comprising discrete tiny
particles of excited metallic gold which are dispersed in a silicate
glass matrix.

ruby red glass helmet. swamp man abroad in the protocols, striding into the stone circle

our own colloidal, becoming colloidal.

***  explain colloidal process step by step:

what is a colloidal suspension - connection of colloidal gold with glass making

The electrolytic process (electrolysis) consists of placing two
electrodes in a solution containing an electrolyte, and passing
electrical current through the electrodes and solution.  The electrode
connected to the positive voltage is called the anode, and the one
connected to the negative electrode is called the cathode.
Electrolytic processes are normally used for electroplating one metal
on top of another, and are the processes which make batteries work.
In this process, gold will be removed from the anode and enter the
solution as gold chloride, and then be converted to gold particles by
a reducing agent.

1) eletrolyte - pre-prepare sodium chloride solution (NaCl - pure salt) 0.3gin 100ml distilled water
2) reducing agent - sodium citrate 1.47g in 100ml distilled water

3) Bring 250ml distilled water to boil with stirrer and electrodes in/ 500mL beaker. no power. 

4) Add 15ml stock NaCl
5) Add 5ml stock sodium citrate

6) Power on. We should see bubbles - more on cathode

7) Observe till we have red tint.

8) Maintain 250ml level.

*** as we drink (but it will be very hot, can be diluted?) : chinese recipe for imbibing of gold:

FORMULA FOR MAKING GOLD ELIXIR 

Gold 8 liang File to powder. 

Quicksilver 8 liang 

The above powdered gold and mercury are stirred over-night to
change them to the consistency of a mortar. 

Realgar 1 chin 
Orpiment 1 chin 

The previously enumerated realgar and orpiment are ground fine as
flour and then mixed. All the ingredients are placed in a reaction
vessel made of earthenware [thickly plastered inside and out with]
six-one [lute and then dried]. The vessel is sealed tight and roasted
over a charcoal fire for nine days and nights. Cool it for two
days. Scrape out and collect the sublimed essence.

Have a tube ready. Make a mortar of fortified vinegar and minium and
plaster the inside of the tube with it. Allow the tube to become
extremely dry. Then mix vinegar and the sublimed essence to the
consistency of soft clay. Pack the mixture into the tube. Put a copper
cover on the open end of the tube and plaster the joint with six-one
lute. Prepare an iron hook and suspend the tube so that its bottom is
two or three ts'un from the ground. Warm it over a fire fueled with
manure in such a way that the bottom of the tube is always just warm,
for sixty to seventy days. Cool it, open it, and collect the
medicine. If it be of the same red color as cinnabar, it is
finished. 

Grind it again and mix it with jujube pulp to form pills, each the
size of a red mung bean. One pill is taken at sun-rise with the first
water drawn from the well, as you face the sun. After seven days
fairies will come to serve you; in two hundred days you will be able
to "summon the mobile kitchen"; at the end of three hundred days you
will become as immortal as sky and earth.

** 2- dream of silver - from pre-bought silver colloid

key image: we are in the "zone of stones". white moonlight on the stones.

Jachymov - silver coins and mining - name of composer? Nikolaus Herman:

// last dream jachymov - crystal - more as a story. a crossroads we saw in a dream...

I have only seen this place in dreams but now I am there. A priest,
all grey with frozen dew, leads us from his house which is crammed
with artefacts from a burnt-out church, crispated altar paintings, out
into his garden. Chickens, uncooped, run wildly at our feet, slyly
drenched in the thunder storm. He opens a stout metal gate set into
the knolled hillside one corner of the garden, inside the chicken
enclosure, and takes us into the narrow, dully shining adit, leading us with
the light from one smartphone into the coffined irregularity of the
ancient, hewn walls.

In a stage-set museum mine, a geologist in stout boots, tells us
that the main ore vein is cursed, that all of the evil over so many
years existing in the mountain mining town comes from this ore
body. He translates its glowing name as drift or drifting. It is
always moving. He says that the one who lives in this sort of
disorder, mined like a sewer, spread it around them like an infectious
disease, a nebulous miasma.

His tannery dog, middle aged, crowned hat, vomits old silver coins and
terse liquid on his boots. He brought it up again, this colloidal and
dewy morning.

evil in a place - Poe:

This opinion, in its general form, was that of the sentience of all
vegetable things. But, in his disordered fancy, the idea had assumed a
more daring character, and trespassed, under certain conditions, upon
the kingdom of inorganization. [...]

The conditions of the sentience had been here, he imagined, fulfilled
in the method of collocation of these stones – in the order of their
arrangement, as well as in that of the many fungi which overspread
them, and of the decayed trees which stood around – above all, in the
long undisturbed endurance of this arrangement, and in its
reduplication in the still waters of the tarn.

Its evidence – the evidence of the sentience – was to be seen, he
said, (and I here started as he spoke,) in the gradual yet certain
condensation of an atmosphere of their own about the waters and the
walls. The result was discoverable, he added, in that silent, yet
importunate and terrible influence which for centuries had moulded the
destinies of his family, and which made him what I now saw him – what
he was.  [Edgar Allen Poe. The Fall of the House of Usher]

Ill seen ill said:

And from it as from an evil core that the what is the wrong word the evil spread

[And none to urge - none to have urged its demolition. As if doomed to
endure. Question answered. Chalkstones of striking effect in the light
of the moon. Let it be in opposition when the skies are clear. Quick
then still under the spell of Venus quick to the other window to see
the other marvel rise. How whiter and whiter as it climbs it whitens
more and more the stones. Rigid with face and hands against the pane
she stands and marvels long.]

silver of the moon. ill seen ill said. the veil of the place - place inside

silver of the moon. Kolisko experiments (silver nitrate) - for protocol also or describe this process - for the full moon on the 6th january, tomorrow

Lili Kolisko process: examining the influence of the moon on silver, and of other planets on solutions of other metals

Handle silver nitrate and solutions with plastic gloves provided
Dissolve 1g of silver nitrate in 100mL of distilled water
Add solutions of other metals, or urine (during and after chelation) or sweat samples
Pour 30mL into a glass dish (preferably 6cm high and 8cm diameter)
Either roll up filter paper or suspend flat paper and place as deep as possible into the dish
Choose to leave this paper in the dish either in a dark room or a room with daylight for 12 hours.
Photograph, scan or otherwise record the results
Repeat this process with the same solution the following day

On the other hand, if we think of the experiments with filter paper
[3] we see that silver is a metal which has in itself a hidden power
of formative force which we do not find in any of the other metals in
the same strength.Each day produces another picture, full moon and new
moon have specific characteristic expressions and if the experiments
are extended over many years, we find that even the years are
different in their effect on the silver solution.  The silver helps to
reveal the formative forces of other metal salts which are not so
easily found by using them alone. The strong reproductive and
formative power of silver helps all the other metals to reveal their
specific forms. If we bring together the immense amount of material we
gathered through many years of incessant study day and night, all the
constellations of Sun and moon, Mars and moon, Saturn and moon,
Jupiter and moon, Venus and moon, Mercury and moon and all the other
qualities of this metal which we mentioned above, then perhaps we
might be allowed to say: the silver acts in such a way that it
represents what lives in the light, it produces pictures of what acts
in the light. And if we find that this is connected especially with
the moon, it may be justified to say: the silver behaves like the moon
in the cosmos. The moon itself has the strange quality that it
continually reflects the light which comes from the sun and all the
other planets. The moon is the great photographer of the universe, it
continually brings us back pictures.

ill seen ill said: the moon see below

** 3- dream of copper - home made... 

Zosimos. how work with metals and materials was aligned wth gnosticism.

*** dennis dream.

// copper/Dennis

*Heavy crystal sediments near the top.*

Last night I had a dream of playing a computer game. A glitch enabled
me to physically travel through dimensions. I ended up in the atelier
of a friend housed atop of a well known hamburger restaurant, which
doubled as a ‘hidden in plain sight’ security check, preventing random
people from going upstairs. In the atelier floated a sphere,
resembling the cryogenic containment unit from Akira, cables coming
out everywhere. It had a brown copper hue to it, but that could also
have been isolation material or even wood. How did it float?  This
‘device’ allowed you to trigger ‘lucid déjà vu’ allowing you to relive
memories as you wanted. Realising I was already in another dimension,
I did not want to go further. We all left to go to a club. Exiting the
restaurant someone had parked a trailer under the trees. My attention
was drawn to the shiny assortment of shapes faintly visible through
reflection of the faint moonlight penetrating the canopy. Upon
inspection the trailer was full of alumiium extrusions in every shape
and size you can imagine. Every piece was unique, except for their
perfect shiny, brushed finish.

*** what is the recipe here, what it could be?

** materials

*** gold: TEH Alan. the red lake

Alan asks me if I know the composition, or constitution of the waters,
and of the movement, and the growth, and the removal and restitution
of corporeal nature. There is gold drowned in the lake. The given gold
fibres dissolved in the lake are set to colour it blood-red as a
sunset.

This hymn is dissolving the gold threads which hold him together, the
man of copper, the man of gold, AKA Alan Astrata.

And saying these things, he slept and I saw Alan playing the
King. Flayed from the head down and stuffed with straw he is pulled by
the car to a certain marked place between the Station and the
lake. Diana is the reigning Queen, standing next to him. The waters
are descending, the waters are circulating. The king lies submerged,
the son of the king lacks submerged, the queen is submerged.

Alan is the man of silver who will become the man of gold. He
reclines. His robe is of a silvery purple or deepest blue linen dotted
with golden figures, sewen in golden threads. Gold threads are in a
false body. On a toad which is sewn, gorged, graved and gloated,
drinking a little and a light from the lake which has set out to be a
red lake pigment signalling a mining area in dreams, but through some
animal misadventures is now become all deep blue. The toad in the lake
receiving the drops from above, embracing the serpent, holding tight
to the naked king and queen who are bathing in the acidic fountain.

This is another way of saying that a winged angel brings Alan his own
applied heart on a plate. And this is the process which tears the
upholstery remotely and is referred to as being liquid, these Apple
seed drippings described as above which generate the instructions
toadally speaking and issuing here from this orbited ALTAR STAR (the
car orbits). Wishing for a more solid solution instead, these
instructions have been carefully woven in gold just like locks or
ropes of hair through the rings connecting the vessels to the prima
materia just as a tombic absence or a presence for each one.

And even as he said these things to me and I forced him to speak, it
was as if his eyes turned to blood and he vomited up all his
flesh. And I saw him as a mutilated image of a little man and he was
tearing at his flesh and falling away. Blood crusts down his t-shirt
from the corners of his eyes. I pick him up and place him awkwardly in
the bed, scratching his forehead and it also starts to bleed. Blood is
also on his collar now. I am not sure if he is mine. The lake is in
the secret fountain under the shrine, inside the mine. The station is
with neither end nor beginning in its construction. It is the
circulatory vessel within which nine vessels are depicted as being
linked by gold chains and each link describes a certain process within
the vessel.

*** commentary - as footnotes 

Alan can be clearly identified here as Alan Turing, the sacrificial
man of copper and the man of gold, referring to both his assured place
within the history of communications and computing technologies and
his apparent suicide through the ingestion of cyanide borrowed from an
experiment he was running in gold electrolysis. Cyanide is used in the
industrial extraction of gold from low grade ores.

His housekeeper famously found the 41-year-old mathematician dead in
his bed, with a half-eaten apple on his bedside table. It is widely
said that Turing had been haunted by the story of the poisoned apple
in the fairy tale of Snow White and the Seven Dwarfs, and had resorted
to the same desperate measure to end the persecution he was suffering
as a result of his homosexuality. Apple seeds contain small amounts of
cyanide. The Apple logo is rumoured to have been inspired either by
the forbidden fruit (of knowledge) within the garden or Eden, or by
this terminal episode.

The reference to Alan as Astrata originates in a mis-hearing, or
mis-spelling of the name of a global company concerned with the
recycling from a wide-range of feeds, including copper and precious
metal bearing electronic equipment. This company could not have been
Glen-Core recycling, operator of the Horne Smelter in Rouyn-Noranda,
Quebec, the world's largest processor of electronic scrap containing
copper and precious metals. Astrata leads us to Astarte, or Astoreth,
the ancient Phoenician great goddess of fertility, motherhood, and
war, and counterpart of the Babylonian goddess Ishtar.

There is an obvious connection with the astral, the star, aster, and
asterism, with reference to the following constellations: Corvus,
Regulus, and Ursa Major. Corvus is associated with the myth of Apollo
and his lover Coronis the Lapith. Coronis had been unfaithful to
Apollo; when he learned this information from a pure white crow, he
turned its feathers black in a fit of rage. This is about a secret
knowledge, relating also to the ancient Egyptian name of Egypt, khem
or khm, khame, or khmi, meaning "blackness" from which we can derive
the Greek term of Khemia, the Arabic Kimiya and thus alchemy and
chemistry.

*** gold - red glass piped head from own text

The right arm, neck, and head is drooping blood red. The hosted head
is a port and a pipe. He holds his right hand over his right thigh
towards and as if to cover his red nakedness.

After the fact, the embrace which unites the mud human and the glass
angel makes of them a double being, able to be transported through the
pipes, upwards into the world of Light.

Thus says the moral, take this scorned transport layer, which you mess
under your feet without seeing it, if not you will have to climb out
of the world without a ladder and you are sure to fall upside down.

To establish and to isolate a global connection, we are all made to be
made of glass for a glossy session layer. I stand with my right side
towards us both and on my profile is seen a circular transparent glass
globe, just covering my head all but in profile, and through this
globe are to be seen on the organ of Self-esteem, the right cheek
bone, and over the right eye, three luminous spots, in each of which
is seen a small red cross. The Queen seems to be encouraging and
sympathising with us. A landscape with lake is seen in the
distance. Walled city, chateaux, various enclosures, with islands
subtending in the extreme distance. My head is filled with the red
condensation of throaty cinnabar, dripping and spotting mercury
memories on the server side, red glassy drops from the
forgetting-full-flashy-flask hoard.

And, it was indeed that very rare gold-ruby glass, this Hertzian of
Glass. He calls it a two-phase system comprising discrete tiny
particles of sunny excited metallic gold which are dispersed in a
silicate glass matrix.

The inside of each drip is red, the head of the swimming blood drop,
the outer shell of this drop is white and the surrounding atom circle
is finally black. We are beckoning all traffic towards its
annihilation and disappearance. A singular addressed port and pipe
emerges from the ruby red flask piping and pied, singing red, black
and white. My work of piping is to keep the sessions isolated, to
maintain the addressing as a containment of the red-breathed plague,
beckoned by the rats and by the fibrous and sclerotial children.

This red skull signals every day as a day of the dead, nulling that
this process is psychic, of the mind and of words. The red skull
enlarges until it breaks and shatters the glass container, and breaks
the earth. Black fumes break out first, white powders, red smokes
emerge from the plastic pipes, deterring angry flies and wasps to shed
out across the lawns.

This necessarily final, frozen session and final isolation takes place
in the cave; the children are led underground into the data centre,
where they are feasted on crow bread. It stops the story.

The last but not final nor uppermost layer falls and fails down on the
upward facing lawn, awaiting the least messenger. In the round
memorial window, a white mushroom snows.

Standing on the foreground of a magnificent Claude-like picture is an
exquisitely formed figure of a human dressed in black with golden
edging and cross button bars of red and gold in front, a red and gold
waistband with a fringe of golden tassels or ornaments. We have two
heads and necks. One is manly with his sandy hair and blue eyes,
without beard or moustache, the other a beautiful female face with
blue eyes and fair or reddish hair.

I am the final archaeologist of the server farms, the very last thing,
writing all the protocols and piping the story for the now past
memories.

A golden emanation or halo radiates from the man’s head while a
silvery radiation proceeds from the female. He has had attached to the
right shoulder a crimson wing, and she has a faint purple and white
wing.

In the left hand I hold the holes, the map of under-server descents, a
spread sheet of boring holes for the post-piped piper, a pope for the
last things.

In the right hand I hold a Circular Shield, the edge of which is
encircled with gold and orange, an inner circle next of a greyish
mottled or marbled appearance, then an inner circle, but narrower, of
dark green and blue ring inside this, in the centre of which is a tiny
landscape, like one seen through a double concave heart glass in a
pipe. It is this target, mist or shield which shows that something is
missing; the unseen, morning mirror in the centre of the target is
this deflection.

The black spurred and infected feet of the two figures are rooted on
the ground. One pair of these foreign feet, the ignored extremities is
trenched in the dark earth, the other pair extends, disembodied and
almost becoming the fairy queen.

There is something about this whole image which draws the attention
away at the same time as fixing on an horizon which is unknown,
drawing towards other places, the greenery and lakes of the distant,
far places, inhabited by a verdant flora and fauna which frames and
embellishes the image without a centre, without the whole, the rebis
or hermaphroditic target holder holding that hole on target outside,
clothed in the same fabric skins and flasks of red, white and black,
their broken head illuminating the forest air with clear psyche, the
clear-cut forest, the dead, felled and finally failed forest.

We two are a rebis geo-body, a seismic holder; each is a mirror image
of the infernal. We both hold and measure seismic shifts, subductions,
a simple slip from suction to subduction, donating data.

These last words are downward-piped to reflect on the human, and to
say what is human:

Smaller and smaller from day to day, grows the number of specific
protocols on earth, while they rise upward, purified in the dew on
that last lawn.


*** silver: ill seen ill said

From where she lies she sees Venus rise. On. From where she lies when the skies are clear she sees Venus rise followed by the sun. Then she rails at the source of all life. On. At evening when the skies are clear she savours its star’s revenge. At the other window. Rigid upright on her old chair she watches for the radiant one. Her old deal spindlebacked kitchen chair. It emerges from out the last rays and sinking ever brighter is engulfed in its turn. On. She sits on erect and rigid in the deepening gloom. Such helplessness to move she cannot help. Heading on foot for a particular point often she freezes on the way. Unable till long after to move on not knowing whither or for what purpose. Down on her knees especially she finds it hard not to remain so forever. Hand resting on hand on some convenient support. Such as the foot of her bed. And on them her head. There then she sits as though turned to stone face to the night. Save for the white of her hair and faintly bluish white of face and hands all is black. For an eye having no need of light to see. All this in the present as had she the misfortune to be still of this world.

The cabin. Its situation. Careful. On. At the inexistent centre of a formless place. Rather more circular than otherwise finally. Flat to be sure. To cross it in a straight line takes her from five to ten minutes. Depending on her speed and radius taken. Here she who loves to – here she who now can only stray never strays. Stones increasingly abound. Ever scanter even the rankest weed. Meagre pastures hem it round on which it slowly gains. With none to gainsay. To have gainsaid. As if doomed to spread. How come a cabin in such a place? How came? Careful. Before replying that in the far past at the time of its building there was clover growing to its very walls. Implying furthermore that it the culprit. And from it as from an evil core that the what is the wrong word the evil spread. And none to urge – none to have urged its demolition. As if doomed to endure. Question answered. Chalkstones of striking effect in the light of the moon. Let it be in opposition when the skies are clear. Quick then still under the spell of Venus quick to the other window to see the other marvel rise. How whiter and whiter as it climbs it whitens more and more the stones. Rigid with face and hands against the pane she stands and marvels long.

The two zones form a roughly circular whole. As though outlined by a trembling hand. Diameter. Careful. Say one furlong. On an average. Beyond the unknown. Mercifully. The feeling at times of being below sea level. Especially at night when the skies are clear. Invisible nearby sea. Inaudible. The entire surface under grass. Once clear of the zone of stones. Save where it has receded from the chalky soil. Innumerable white scabs all shapes and sizes. Of striking effect in the light of the moon. In the way of animals ovines only. After long hesitation. They are white and make do with little. Whence suddenly come no knowing nor whither as suddenly gone. Unshepherded they stray as they list. Flowers? Careful. Alone the odd crocus still at lambing time. And man? Shut of at last? Alas no. For will she not be surprised one day to find him gone? Surprised no she is beyond surprise. How many? A figure come what may. Twelve. Wherewith to furnish the horizon’s narrow round. She raises her eyes and sees one. Turns away and sees another. So on. Always afar. Still or receding. She never once saw one come toward her. Or she forgets. She forgets. Are they always the same? Do they see her? Enough.

A moor would have better met the case. Were there a case better to meet. There had to be lambs. Rightly or wrongly. A moor would have allowed of them. Lambs for their whiteness. And for other reasons as yet obscure. Another reason. And so that there may be none. At lambing time. That from one moment to the next she may raise her eyes to find them gone. A moor would have allowed of them. In any case too late. And what lambs. No trace of frolic. White splotches in the grass. Aloof from the unheeding ewes. Still. Then a moment straying. Then still again. To think there is still life in this age. Gently gently.

She is drawn to a certain spot. At times. There stands a stone. It it is draws her. Rounded rectangular block three times as high as wide. Four. Her stature now. Her lowly stature. When it draws she must to it. She cannot see it from her door. Blindfold she could find her way. With herself she has no more converse. Never had much. Now none. As had she the misfortune to be still of this world. But when the stone draws then to her feet the prayer, Take her. Especially at night when the skies are clear. With moon or without. They take her and halt her before it. There she too as if of stone. But black. Sometimes in the light of the moon. Mostly of the stars alone. Does she envy it?

To the imaginary stranger the dwelling appears deserted. Under constant watch it betrays no sign of life. The eye glued to one or the other window has nothing but black drapes for its pains. Motionless against the door he listens long. No sound. Knocks. No answer. Watches all night in vain for the least glimmer. Returns at last to his own and avows, No one. She shows herself only to her own. But she has no own. Yes yes she has one. And who has her.

There was a time when she did not appear in the zone of stones. A long time. Was not therefore to be seen going out or coming in. When she appeared only in the pastures. Was not theref
ore to be seen leaving them. Save as though by enchantment. But little by little she began to appear. In the zone of stones. First darkly. Then more and more plain. Till in detail she could be seen crossing the threshold both ways and closing the door behind her. Then a time when within her walls she did not appear. A long time. But little by little she began to appear. Within her walls. Darkly. Time truth to tell still current. Though she within them no more. This long time.

Yes within her walls so far at the window only. At one or the other window. Rapt before the sky. And only half seen so far a pallet and a ghostly chair. Ill half seen. And how in her faint comings and goings she suddenly stops dead. And how hard set to rise up from off her knees. But there too little by little she begins to appear more plain. Within her walls. As well as other objects. Such as under her pillow – such as deep in some recess this still shadowy album. Perhaps in time be by her when she takes it on her knees. See the old fingers fumble through the pages. And what scenes they can possibly be that draw the head down lower still and hold it in thrall. In the meantime who knows no more than withered flowers. No more!

But quick seize her where she is best to be seized. In the pastures far from shelter. She crosses the zone of stones and is there. Clearer and clearer as she goes. Quick seeing she goes out less and less. And so to say only in winter. Winter in her winter haunts she wanders. Far from shelter. Head bowed she makes her slow wavering way across the snow. It is evening. Yet again. On the snow her long shadow keeps her company. The others are there. All about. The twelve. Afar. Still or receding. She raises her eyes and sees one. Turns away and sees another. Again she stops dead. Now the moment or never. But something forbids. Just time to begin to glimpse a fringe of black veil. The face must wait. Just time before the eye cast down. Where nothing to be seen in the grazing rays but snow. And how all about little by little her footprints are effaced.

What is it defends her? Even from her own. Averts the intent gaze. Incriminates the dearly won. Forbids divining her. What but life ending. Hers. The other’s. But so otherwise. She needs nothing. Nothing utterable. Whereas the other. How need in the end? But how? How need in the end?

Times when she is gone. Long lapses of time. At crocus time it would be making for the distant tomb. To have that on the imagination! On top of the rest. Bearing by the stem or round her arm the cross or wreath. But she can be gone at any time. From one moment of the year to the next suddenly no longer there. No longer anywhere to be seen. Nor by the eye of flesh nor by the other. Then as suddenly there again. Long after. So on. Any other would renounce. Avow, No one. No one more. Any other than this other. In wait for her to reappear. In order to resume. Resume the – what is the word? What the wrong word?

Riveted to some detail of the desert the eye fills with tears. Imagination at wit’s end spreads its sad wings. Gone she hears one night the sea as if afar. Plucks up her long skirt to make better haste and discovers her boots and stockings to the calf. Tears. Last example the flagstone before her door that by dint by dint her little weight has grooved. Tears.

Before left for the stockings the boots have time to be ill buttoned. Weeping over as weeping will see now the buttonhook larger than life. Of tarnished silver pisciform it hangs by its hook from a nail. It trembles faintly without cease. As if here without cease the earth faintly quaked. The oval handle is wrought to a semblance of scales. The shank a little bent leads up to the hook the eye so far still dry. A lifetime of hooking has lessened its curvature. To the point at certain moments of its seeming unfit for service. Child’s play with a pliers to restore it. Was there once a time she did? Careful. Once once in a way. Till she could no more. No more bring the jaws together. Oh not for weakness. Since when it hangs useless from the nail. Trembling imperceptibly without cease. Silver shimmers some evenings when the skies are clear. Close-up then. In which in defiance of reason the nail prevails. Long this image till suddenly it blurs.

She is there. Again. Let the eye from its vigil be distracted a moment. At break or close of day. Distracted by the sky. By something in the sky. So that when it resumes the curtain may be no longer closed. Opened by her to let her see the sky. But even without that she is there. Without the curtain’s being opened. Suddenly open. A flash. The suddenness of all! She still without stopping. On her way without starting. Gone without going. Back without returning. Suddenly it is evening. Or dawn. The eye rivets the bare window. Nothing in the sky will distract it from it more. While she from within looks her fill. Pfft occulted. Nothing having stirred.

Already all confusion. Things and imaginings. As of always. Confusion amounting to nothing. Despite precautions. If only she could be pure figment. Unalloyed. This old so dying woman. So dead. In the madhouse of the skull and nowhere else. Where no more precautions to be taken. No precautions possible. Cooped up there with the rest. Hovel and stones. The lot. And the eye. How simple all then. If only all could be pure figment. Neither be nor been nor by any shift to be. Gently gently. On. Careful.


Here to the rescue two lights. Two small skylights. Set in the high-pitched roof on either side. Each shedding dim light. No ceiling therefore. Necessarily. Otherwise with the curtains closed she would be in the dark. Day and night in the dark. And what of it? She is done with raising her eyes. Nearly done. But when she lies with them open she can just make out the rafters. In the dim light the skylights shed. An ever dimmer light. As the panes slowly dimmen. All in black she comes and goes. The hem of her long black skirt brushes the floor. But most often she is still. Standing or sitting. Lying or on her knees. In the dim light the skylights shed. Otherwise with the curtains closed for preference she would be in the dark. In the dark day and night.


Next to emerge from the shadows an inner wall. Only slowly to dissolve in favour of a single space. East the bed. West the chair. A place divided by her use of it alone. How more desirable in every way an interior of a piece. The eye breathes again but not for long. For slowly it emerges again. Rises from the floor and slowly up to lose itself in the gloom. The semigloom. It is evening. The buttonhook glimmers in the last rays. The pallet scarce to be seen.

Weary of the inanimate the eye in her absence falls back on the twelve. Out of her sight as she of theirs. Alone turn where she may she keeps her eyes fixed on the ground. On the way at her feet where it has come to a stop. Winter evening. Not to be precise. All so bygone. To the twelve then for want of better the widowed eye. No matter which. In the distance stiff he stands facing front and the setting sun. Dark greatcoat reaching to the ground. Antiquated block hat. Finally the face caught full in the last rays. Quick enlarge and devour before night falls.


Having no need of light to see the eye makes haste. Before night falls. So it is. So itself belies. Then glutted – then torpid under its lid makes way for unreason. What if not her do they ring around? Careful. She who looks up no more looks up and sees them. Some among them. Still or receding. Receding. Those too closely seen who move to preserve their distance. While at the same time others advance. Those in the wake of her wandering. She never once saw one come toward her. Or she forgets. She forgets. Now some do. Toward but never nearer. Thus they keep her in the centre. More or less. What then if not her do they ring around? In their ring whence she disappears unhindered. Whence they let her disappear. Instead of disappearing in her company. So the unreasoning goes. While the eye digests its pittance. In its private dark. In the general dark.

As hope expires of her ever reappearing she reappears. At first sight little changed. It is evening. It will always be evening. When not night. She emerges at the fringe of the pastures and sets forward across them. Slowly with fluttering step as if wanting mass. Suddenly still and as suddenly on her way again. At this rate it will be black night before she reaches home. Home! But time slows all this while. Suits its speed to hers. Whence from beginning to end of her course no loss or but little of twilight. A matter at most of a candle or two. Bearing south as best she can she casts toward the moon to come her long black shadow. They come at last to the door holding a great key. At the same instant night. When not evening night. Head bowed she stands exposed facing east. All dead still. All save hanging from a finger the old key polished by use. Trembling it faintly shimmers in the light of the moon.


Wooed from below the face consents at last. In the dim light reflected by the flag. Calm slab worn and polished by agelong comings and goings. Livid pallor. Not a wrinkle. How serene it seems this ancient mask. Worthy those worn by certain newly dead. True the light leaves to be desired. The lids occult the longed-for eyes. Time will tell them washen blue. Where tears perhaps not for nothing. Unimaginable tears of old. Lashes jet black remains of the brunette she was. Perhaps once was. When yet a lass. Yet brunette. Skipping the nose at the call of the lips these no sooner broached are withdrawn. The slab having darkened with the darkening sky. Black night henceforward. And at dawn an empty place. With no means of knowing whether she has gone in or under cover of darkness her ways again.

White stones more plentiful every year. As well say every instant. In a fair way if they persist to bury all. First zone rather more extensive than at first sight ill seen and every year rather more. Of striking effect in the light of the moon these millions of little sepulchres. But in her absence but cold comfort. From it then in the end to the second miscalled pastures. Leprous with white scars where the grass has receded from the chalky soil. In contemplation of this erosion the eye finds solace. Everywhere stone is gaining. Whiteness. More and more every year. As well say every instant. Everywhere every instant whiteness is gaining.


The eye will return to the scene of its betrayals. On centennial leave from where tears freeze. Free again an instant to shed them scalding. On the blest tears once shed. While exulting at the white heap of stone. Ever heaping for want of better on itself. Which if it persist will gain the skies. The moon. Venus.

From
the stones she steps down into the pastures. As from one tier of a circus to the next. A gap time will fill. For faster than the stones invade it the other ground upheaves its own. So far in silence. A silence time will break. This great silence evening and night. Then all along the verge the muffled thud of stone on stone. Of those spilling their excess on those emergent. Only now and then at first. Then at ever briefer intervals. Till one continuous din. With none to hear. Decreasing as the levels draw together to silence once again. Evening and night. In the meantime she is suddenly sitting with her feet in the pastures. Were it not for the empty hands on the way who knows to the tomb. Back from it then more likely. On the way back from the tomb. Frozen true to her wont she seems turned to stone. Face to the further confines the eye closes in vain to see. At last they appear an instant. North where she passes them always. Shroud of radiant haze. Where to melt into paradise.

The long white hair stares in a fan. Above and about the impassive face. Stares as if shocked still by some ancient horror. Or by its continuance. Or by another. That leaves the face stone-cold. Silence at the eye of the scream. Which say? Ill say. Both. All three. Question answered.

Seated on the stones she is seen from behind. From the waist up. Trunk black rectangle. Nape under frill of black lace. White half halo of hair. Face to the north. The tomb. Eyes on the horizon perhaps. Or closed to see the headstone. The withered crocuses. Endless evening. She lit aslant by the last rays. They make no difference. None to the black of the cloth. None to the white hair. It too dead still. In the still air. Voidlike calm as always. Evening and night. Suffice to watch the grass. How motionless it droops. Till under the relentless eye it shivers. With faintest shiver from its innermost. Equally the hair. Rigidly horrent it shivers at last for the eye about to abandon. And the old body itself. When it seems of stone. Is it not in fact ashiver from head to foot? Let her but go and stand still by the other stone. It white from afar in the pastures. And the eye go from one to the other. Back and forth. What calm then. And what storm. Beneath the weeds’ mock calm.

Not possible any longer except as figment. Not endurable. Nothing for it but to close the eye for good and see her. Her and the rest. Close it for good and all and see her to death. Unremittent. In the shack. Over the stones. In the pastures. The haze. At the tomb. And back. And the rest. For good and all. To death. Be shut of it all. On to the next. Next figment. Close it for good this filthy eye of flesh. What forbids? Careful.

Such – such fiasco that folly takes a hand. Such bits and scraps. Seen no matter how and said as seen. Dread of black. Of white. Of void. Let her vanish. And the rest. For good. And the sun. Last rays. And the moon. And Venus. Nothing left but black sky. White earth. Or inversely. No more sky or earth. Finished high and low. Nothing but black and white. Everywhere no matter where. But black. Void. Nothing else. Contemplate that. Not another word. Home at last. Gently gently.

Panic past pass on. The hands. Seen from above. They rest on the pubis intertwined. Strident white. Their faintly leaden tinge killed by the black ground. Suspicion of lace at the wrists. To go with the frill. They tighten then loosen their clasp. Slow systole diastole. And the body that scandal. While its sole hands in view. On its sole pubis. Dead still to be sure. On the chair. After the spectacle. Slowly its spell unbinding. On and on they keep. Tightening and loosening their clasp. Rhythm of a labouring heart. Till when almost despaired of gently part. Suddenly gently. Spreading rise and in midair palms uppermost come to rest. Behold our hollows. Then after a moment as if to hide the lines fall back pronating as they go and light flat on head of thighs. Within an ace of the crotch. It is now the left hand lacks its third finger. A swelling no doubt – a swelling no doubt of the knuckle between first and second phalanges preventing one panic day withdrawal of the ring. The kind called keeper. Still as stones they defy as stones do the eye. Do they as much as feel the clad flesh? Does the clad flesh feel them? Will they then never quiver? This night assuredly not. For before they have – before the eye has time they mist. Who is to blame? Or what? They? The eye? The missing finger? The keeper? The cry? What cry? All five. All six. And the rest. All. All to blame. All.

Winter evening in the pastures. The snow has ceased. Her steps so light they barely leave a trace. Have barely left having ceased. Just enough to be still visible. Adrift the snow. Whither in her head while her feet stray thus? Hither and thither too? Or unswerving to the mirage? And where when she halts? The eye discerns afar a kind of stain. Finally the steep roof whence part of the fresh fall has slid. Under the low lowering sky the north is lost. Obliterated by the snow the twelve are there. Invisible were she to raise her eyes. She on the contrary immaculately black. Not having received a single flake. Nothing needed now but for them to start falling again which therefore they do. First one by one here and there. Then thicker and thicker plumb through the still air. Slowly she disappears. Together with the trace of her steps and that of the distant roof. How find her way home? Home! Even as the homing bird. Safe as the saying is and sound.

All dark in the cabin while she whitens afar. Silence but for the imaginary murmur of flakes beating on the roof. And every now and then a real creak. Her company. Here without having to close the eye sees her afar. Motionless in the snow under the snow. The buttonhook trembles from its nail as if a night like any other. Facing the black curtain the chair exudes its solitude. For want of a fellow-table. Far from it in a corner see suddenly an antique coffer. In its therefore no lesser solitude. It perhaps that creaks. And in its depths who knows the key. The key to close. But this night the chair. Its immovable air. Less than the – more than the empty seat the barred back is piteous. Here if she eats here she sits to eat. The eye closes in the dark and sees her in the end. With her right hand as large as life she holds the edge of the bowl resting on her knees. With her left the spoon dipped in the slop. She waits. For it to cool perhaps. But no. Merely frozen again just as about to begin. At last in a twin movement full of grace she slowly raises the bowl toward her lips while at the same time with equal slowness bowing her head to join it. Having set out at the same instant they meet halfway and there come to rest. Fresh rigor before the first spoonful slobbered largely back into the slop. Others no happier till time to part lips and bowl and slowly back with never a slip to their starting points. As smooth and even fro as to. Now again the rigid Memnon pose. With her right hand she holds the edge of the bowl. With her left the spoon dipped in the slop. So far so good. But before she can proceed she fades and disappears. Nothing now for the staring eye but the chair in its solitude.

One evening she was followed by a lamb. Reared for slaughter like the others it left them to follow her. In the present to conclude. All so bygone. Slaughter apart it is not like the others. Hanging to the ground in matted coils its fleece hides the little shanks. Rather than walk it seems to glide like a toy in tow. It halts at the same instant as she. At the same instant as she strays on. Stock-still as she it waits with head like hers extravagantly bowed. Clash of black and white that far from muting the last rays amplify. It is now her puniness leaps to the eye. Thanks it would seem to the lowly creature next her. Brief paradox. For suddenly together they move on. Hither and thither toward the stones. There she turns and sits. Does she see the white body at her feet? Head haught now she gazes into emptiness. That profusion. Or with closed eyes sees the tomb. The lamb goes no further. Alone night fallen she makes for home. Home! As straight as were it to be seen.

Was it ever over and done with questions? Dead the whole brood no sooner hatched. Long before. In the egg. Long before. Over and done with answering. With not being able. With not being able not to want to know. With not being able. No. Never. A dream. Question answered.

What remains for the eye exposed to such conditions? To such vicissitude of hardly there and wholly gone. Why none but to open no more. Till all done. She done. Or left undone. Tenement and unreason. No more unless to rest. In the outward and so-called visible. That daub. Quick again to the brim the old
nausea and shut again. On her. Till she be whole. Or abort. Question answered.

The coffer. Empty after long nocturnal search. Nothing. Save in the end in a cranny of dust a scrap of paper. Jagged along one edge as if torn from a diary. On its yellowed face in barely legible ink two letters followed by a number. Tu 17. Or Th. Tu or Th 17. Otherwise blank. Otherwise empty.

She reemerges on her back. Dead still. Evening and night. Dead still on her back evening and night. The bed. Careful. A pallet? Hardly if head as ill seen when on her knees. Praying if she prays. Pah she has only to grovel deeper. Or grovel elsewhere. Before the chair. Or the coffer. Or at the edge of the pastures with her head on the stones. A pallet then flat on the floor. No pillow. Hidden from chin to foot under a black covering she offers her face alone. Alone! Face defenceless evening and night. Quick the eyes. The moment they open. Suddenly they are there. Nothing having stirred. One is enough. One staring eye. Gaping pupil thinly nimbed with washen blue. No trace of humour. None any more. Unseeing. As if dazed by what seen behind the lids. The other plumbs its dark. Then opens in its turn. Dazed in its turn.

Incontinent the void. The zenith. Evening again. When not night it will be evening. Death again of deathless day. On the one hand embers. On the other ashes. Day without end won and lost. Unseen.

On resumption the head is covered. No matter. No matter now. Such the confusion now between real and – how say its contrary? No matter. That old tandem. Such now the confusion between them once so twain. And such the farrago from eye to mind. For it to make what sad sense of it may. No matter now. Such equal liars both. Real and – how ill say its contrary? The counter-poison.

Still fresh the coffer fiasco what now of all things but a trapdoor. So cunningly contrived that even to the lidded eye it scarcely shows. Careful. Raise it at once and risk another rebuff? No question. Simply savour in advance with in mind the grisly cupboard its conceivable contents. For the first time then wooden floor. Its boards in line with the trap’s designed to conceal it. Promising this flagrant concern with camouflage. But beware. Question by the way what wood of all woods? Ebony why not? Ebony boards. Black on black the brushing skirt. Stark the skeleton chair death-paler than life.

While head included she lies hidden time for a turn in the pastures. No shock were she already dead. As of course she is. But in the meantime more convenient not. Still living then she lies hidden. Having for some reason covered her head. Or for no reason. Night. When not evening night. Winter night. No snow. For the sake of variety. To vary the monotony. The limp grass strangely rigid under the weight of the rime. Clawed by the long black skirt how if but heard it must murmur. Moonless star-studded sky reflected in the erosions filmed with ice. The silence merges into music infinitely far and as unbroken as silence. Ceaseless celestial winds in unison. For all all matters now. The stones gleam faintly afar and the cabin walls seen white at last. Said white. The guardians – the twelve are there but not at full muster. Well! Above all not understand. Simply note how those still faithful have moved apart. Such ill seen that night in the pastures. While head included she lies hidden. Under on closer inspection a long greatcoat. A man’s by the buttons. The buttonholes. Eyes closed does she see him?

White walls. High time. White as new. No wind. Not a breath. Unbeaten on by all that comes beating down. And mystery the sun has spared them. The sun that once beat down. So east and west sides the required clash. South gable no problem. But the other. That door. Careful. Black too? Black too. And the roof. Slates. More. Small slates black too brought from a ruined mansion. What tales had they tongues to tell. Their long tale told. Such the dwelling ill seen ill said. Outwardly. High time.

Changed the stone that draws her when revisited alone. Or she who changes it when side by side. Now alone it leans. Backward or forward as the case may be. Is it to nature alone it owes its rough-hewn air? Or to some too human hand forced to desist? As Michelangelo’s from the regicide’s bust. If there may not be no more questions let there at least be no more answers. Granite of no common variety assuredly. Black as jade the jasper that flecks its whiteness. On its what is the wrong word its uptilted face obscure graffiti. Scrawled by the ages for the eye to solicit in vain. Winter evenings on her doorstep she imagines she can see it glitter afar. When from their source in the west-south-west the last rays rake its averse face. Such ill seen the stone alone where it stands at the far fringe of the pastures. On her way out with the flowers as unerring as best she can she lingers by it. As on her way back with empty hands. Lingers by it a while on her way on. Toward the one or other abode. As unerring as best she can.

See them again side by side. Not quite touching. Lit aslant by the latest last rays they cast to the east-north-east their long parallel shadows. Evening therefore. Winter evening. It will always be evening. Always winter. When not night. Winter night. No more lambs. No more flowers. Empty-handed she shall go to the tomb. Until she go no more. Or no more return. So much for that. Undistinguishable the twin shadows. Till one at length more dense as if of a body better opaque. At length more still. As faintly at length the other trembles under the staring gaze. Throughout this confrontation the sun stands still. That is to say the earth. Not to recoil on until the parting. Then on its face over the pastures and then the stones the still living shadow slowly glides. Lengthening and fading more and more. But never quite away. Under the hovering eye.


Close-up of a dial. Nothing else. White disc divided in minutes. Unless it be in seconds. Sixty black dots. No figure. One hand only. Finest of fine black darts. It advances by fits and starts. No tick. Leaps from dot to dot with so lightning a leap that but for its new position it had not stirred. Whole nights may pass as may but a fraction of a second or any intermediate lapse of time soever before it flings itself from one degree to the next. None at any moment overleaping in all fairness be it said. Let it when discovered be pointing east. Having thus covered after its fashion assuming the instrument plumb the first quarter of its latest hour. Unless it be its latest minute. Then doubt certain – then despair certain nights of its ever attaining the last. Ever regaining north.

She reappears at evening at her window. When not night evening. If she will see Venus again she must open it. Well! First draw aside the curtain and then open. Head bowed she waits to be able. Mindful perhaps of evenings when she was able too late. Black night fallen. But no. In her head too pure wait. The curtain. Seen closer thanks to this hiatus it reveals itself at last for what it is. A black greatcoat. Hooked by its tails from the rod it hangs sprawling inside out like a carcass in a butcher’s stall. Or better inside in for the pathos of the dangling arms. Same infinitesimal quaver as the buttonhook and passim. Another novelty the chair drawn up to the window. This to raise the line of sight on the fair prey loftier when first sighted than at first sight ill seen. What empty space henceforward. For long pacing to and fro in the gloom. Suddenly in a single gesture she snatches aside the coat and to again on a sky as black as it. And then? Careful. Have her sit? Lie? Kneel? Go? She too vacillates. Till in the end the back and forth prevails. Sends her wavering north and south from wall to wall. In the kindly dark.


She is vanishing. With the rest. The already ill seen bedimmed and ill seen again annulled. The mind betrays the treacherous eyes and the treacherous word their treacheries. Haze sole certitude. The same that reigns beyond the pastures. It gains them already. It will gain the zone of stones. Then the dwelling through all its chinks. The eye will close in vain. To see but haze. Not even. Be itself but haze. How can it ever be said? Quick how ever ill said before it submerges all. Light. In one treacherous word. Dazzling haze. Light in its might at last. Where no more to be seen. To be said. Gently gently.


The face yet again in the light of the last rays. No loss of pallor. None of cold. Suspended on the verge for this sight the westering sun. That is the eastering earth. The thin lips seem as if never again to part. Peeping from their join a suspicion of pulp. Unlikely site of olden kisses given and received. Or given only. Or received only. Impressive above all the corners imperceptibly upcurved. A smile? Is it possible? Ghost of an ancient smile smiled finally once and for all. Such ill half seen the mouth in the light of the last rays. Suddenly they leave it. Rather it leaves them. Off again to the dark. There to smile on. If smile is what it is.

Reexamined rid of light the mouth changes. Unexplainably. Lips as before. Same closure. Same hint of extruding pulp. At the corners same imperceptible laxness. In a word the smile still there if smile is what it is. Neither more nor less. Less! And yet no longer the same. True that light distorts. Particularly sunset. That mockery. True too that the eyes then agaze for the viewless planet are now closed. On other viewlessness. Of which more if ever anon. There the explanation at last. This same smile established with eyes open is with them closed no longer the same. Though between the two inspections the mouth unchanged. Utterly. Good. But in what way no longer the same? What there now that was not there? What there no more that was? Enough. Away.

Back after many winters. Long after in this endless winter. This endless heart of winter. Too soon. She as when fled. Where as when fled. Still or again. Eyes closed in the dark. To the dark. In their own dark. On the lips same minute smile. If smile is what it is. In short alive as she alone knows how neither more nor less. Less! Compared to true stone. Within as sadly as before all as at first sight ill seen. With the happy exception of the lights’ enhanced opacity. Dim the light of day from them were day again to dawn. Without on the other hand some progress. Toward unbroken night. Universal stone. Day no sooner risen fallen. Scrapped all the ill seen ill said. The eye has changed. And its drivelling scribe. A

bsence has changed them. Not enough. Time to go again. Where still more to change. Whence back too soon. Changed but not enough. Strangers but not enough. To all the ill seen ill said. Then back again. Disarmed for to finish with it all at last. With her and her rags of sky and earth. And if again too soon go again. Change still more again. Then back again. Barring impediment. Ah. So on. Till fit to finish with it all at last. All the trash. In unbroken night. Universal stone. So first go. But first see her again. As when fled. And the abode. That under the changed eye it too may change. Begin. Just one parting look. Before all meet again. Then go. Barring impediment. Ah.

But see she suddenly no longer there. Where suddenly fled. Quick then the chair before she reappears. At length. Every angle. With what one word convey its change? Careful. Less. Ah the sweet one word. Less. It is less. The same but less. Whencesoever the glare. True that the light. See now how words too. A few drops mishaphazard. Then strangury. To say the least. Less. It will end by being no more. By never having been. Divine prospect. True that the light.

Suddenly enough and way for remembrance. Closed again to that end the vile jelly or opened again or left as it was however that was. Till all recalled. First finally by far hanging from their skirts two black greatcoats. Followed by the first hazy outlines of what possibly a hutch when suddenly enough. Remembrance! When all worse there than when first ill seen. The pallet. The chair. The coffer. The trap. Alone the eye has changed. Alone can cause to change. In the meantime nothing wanting. Wrong. The buttonhook. The nail. Wrong. There they are again. Still. Worse there than ever. Unchanged for the worse. Ope eye and at them to begin. But first the partition. It rid they too would be. It less they by as much.


It of all the properties doubtless the least obdurate. See the instant see it again when unaided it dissolved. So to say of itself. With no help from the eye. Not till long after to reappear. As if reluctantly. For what reason? For one not far to seek. For others then said obscure. One other above all. One other still far to seek. Analogy of the heart? The skull? Hear from here the howls of laughter of the damned.

Enough. Quicker. Quick see how all in keeping with the chair. Minimally less. No more. Well on the way to inexistence. As to zero the infinite. Quick say. And of her? As much. Quick find her again. In that black heart. That mock brain.

The sheet. Between tips of trembling fingers. In two. Four. Eight. Old frantic fingers. Not paper any more. Each eighth apart. In two. Four. Finish with the knife. Hack into shreds. Down the plughole. On to the next. White. Quick blacken.

Alone the face remains. Of the rest beneath its covering no trace. During the inspection a sudden sound. Startling without consequence for the gaze the mind awake. How explain it? And without going so far how say it? Far behind the eye the quest begins. What time the event recedes. When suddenly to the rescue it comes again. Forthwith the uncommon common noun collapsion. Reinforced a little later if not enfeebled by the infrequent slumberous. A slumberous collapsion. Two. Then far from the still agonizing eye a gleam of hope. By the grace of these modest beginnings. With in second sight the shack in ruins. To scrute together with the inscrutable face. All curiosity spent.

Later while the face still unyielding another sound of fall but this time sharp. Heightening the fond illusion of general havoc in train. Here a great leap into what brief future remains and summary puncture of that puny balloon. Far ahead to the instant when the coats will have gone from their rods and the buttonhook from its nail. And been hove the sigh no more than that. Sigh upon sigh till all sighed quite away. All the fond trash. Destined before being to be no more than that. Last sighs. Of relief.

Quick beforehand again two mysteries. Not even. Mild shocks. Not even. In such abeyance the mind then. And from then on. First the curtains gone without loss of dark. Sweet foretaste of the joy at journey’s end. Second after long hesitation no trace of the fallen where they fell. No trace of all the ado. Alone on the one hand the rods alone. A little bent. And alone on the other most alone the nail. Unimpaired. All set to serve again. Like unto its glorious ancestors. At the place of the skull. One April afternoon. Deposition done.

Full glare now on the face present throughout the recent future. As seen ill seen throughout the past neither more nor less. Less! Collated with its cast it lives beyond a doubt. Were it only by virtue of its imperfect pallor. And imperceptible tremor unworthy of true plaster. Heartening on the other hand the eyes persistently closed. No doubt a record in this position. Unobserved at least till now. Suddenly the look. Nothing having stirred. Look? Too weak a word. Too wrong. Its absence? No better. Unspeakable globe. Unbearable.

Ample time none the less a few seconds for the iris to be lacking. Wholly. As if engulfed by the pupil. And for the sclerotic not to say the white to appear reduced by half. Already that much less at least but at what cost. Soon to be foreseen save unforeseen two black blanks. Fit ventholes of the soul that jakes. Here reappearance of the skylights opaque to no purpose henceforward. Seeing the black night or better blackness pure and simple that limpid they would shed. Blackness in its might at last. Where no more to be seen. Perforce to be seen.

Absence supreme good and yet. Illumination then go again and on return no more trace. On earth’s face. Of what was never. And if by mishap some left then go again. For good again. So on. Till no more trace. On earth’s face. Instead of always the same place. Slaving away forever in the same place. At this and that trace. And what if the eye could not? No more tear itself away from the remains of trace. Of what was never. Quick say it suddenly can and farewell say say farewell. If only to the face. Of her tenacious trace.

Decision no sooner reached or rather long after than what is the wrong word? For the last time at last for to end yet again what the wrong word? Than revoked. No but slowly dispelled a little very little like the last wisps of day when the curtain closes. Of itself by slow millimetres or drawn by a phantom hand. Farewell to farewell. Then in that perfect dark foreknell darling sound pip for end begun. First last moment. Grant only enough remain to devour all. Moment by glutton moment. Sky earth the whole kit and boodle. Not another crumb of carrion left. Lick chops and basta. No. One moment more. One last. Grace to breathe that void. Know happiness.


*** copper: zosimos new translation

Three Visions of Zosimus

Translated by Andrew Barrett.

Zosimus - Three Visions

The First Vision

“The composition of the Waters – the dance, the growth, the flowering
and decay of the corporeal, the separation and the conjunction of
spirit and body, these are not the result of discrete natures but of a
single nature acting upon itself, a uniform quality such as the
solidity of metals or the moisture of plants. Within this single
system of many colors, the quest, shimmering and myriad, is
preserved. In accord with time’s measured rhythm, it synchronizes with
the waxing and waning of the moon as Nature flows through itself in
cycles of contraction and expansion.”

After I uttered these words, I fell into a trance and saw before me a
sacrificial hierophant perched atop a broad, bowl-shaped altar. A
ladder of fifteen steps climbed to its top. The hierophant arose and a
voice from above addressed me: “I have accomplished the descent of the
fifteen steps of night and have ascended the fifteen steps of
illumination. The one who sacrifices me also revives me through
casting aside the heavy sediment of the body. And since by the will of
necessity I am an initiated hierophant, I become spirit.”

I listened to the words of the one atop the bowl-shaped altar then
asked him who he was. He answered me in a quavering voice: “I am Ion,
hierophant of the innermost sanctuary and I have endured unbearable
violence. At dawn, I was overtaken and dismembered by one wielding a
sword. He chopped me apart according to the strictures of harmony. He
gripped his blade, scalped me, and gathered together my bones and
flesh. Then he burned them in the numinous fire until I learned to
become spirit through transformation of the body.” I compelled him and
after he spoke these words his eyes turned blood-red and he vomited up
all of his flesh. I saw him as a deformed, tiny homunculus, gnashing
at himself with his own teeth while he disintegrated.

I awoke in terror and wondered if this was the composition of the
Waters. I thought I had understood it well and fell back into a
trance. I saw the same bowl-shaped altar filled with boiling
water. There were many people, infinite in number, within it, but
there was no one outside of the altar that I could question. I moved
in closer for a better look at this sight and noticed an aged
homunculus barber, who questioned me about what I saw. I said that I
was astounded by the boiling water and the people in it who were
cooking and yet still alive. He answered: “This is where the act of
preservation takes place. Those who hope to master the Art arrive here
and, through shedding the body, become spirit.” So I said: “Are you a
spirit?” And he answered: “A spirit and a guardian of spirits.”

As we spoke, the water continued to boil and the people screamed. I
saw a man made of copper who held a lead tablet in his hand. He stared
at the tablet and proclaimed: “I command all those who suffer to be
calm, to take up a tablet and write with their own hand. Turn your
face to the sky and keep your mouth open till your uvula is swollen.”
The act followed the word and the lord of the house said to me: “You
have seen. Craning your neck upwards, you have seen what is
accomplished. This man of copper is the sacrificial hierophant and the
sacred offering. It is he who vomited his own flesh. The power over
this Water and those who suffer was given to him.” After experiencing
this vision, I awoke again and asked myself: “How to interpret this?
Is this the white and yellow water, boiling and divine?”

I found that I understood it correctly and I said that it was
beautiful to speak and lovely to hear. Beautiful to give and to
receive, lovely to be rich and to be poor. How does Nature learn to
give and to receive? The man of copper gives and the water-stone
receives. Metals give and plants receive. The stars give and flowers
receive. The sky gives and the earth receives. Thunder yields flashing
fire. All things are interwoven and unravel. All things mingle and
fuse. All things mingle and disperse. All things moisten and dry. All
things flower and bloom in the bowl-shaped altar. For each, the
conjunction and separation of all occurs through method, measure and
the weight of the four elements. There is no chain of being without
this method. Inhalation and exhalation are the method of Nature. The
order of the method is preserved through expansion and
contraction. Simply, when all things unite and separate in harmony and
no part of the method is neglected, then Nature is transformed. Nature
rotates and cycles back upon itself. This is the chain of being and
the nature of the Art for the whole cosmos.

Dear friend, so I don’t have to write to you about many things, from a
single stone that is like Saturnian lead, like alabaster, like the
marble of Prokonnesos, build a temple without beginning or end – an
infinite monolith. Inside the temple, let there be a spring of pure
water that glitters with the brightness of the sun. Take your sword in
your hand after you discover where the entrance of the temple is
located. There will be a narrow passage nearby and the entrance itself
will be guarded by a serpent. Seize the serpent, sacrifice him. Flay
him and place his bones and his organs into piles. Then, before the
temple’s entrance, fuse his bones to his flesh, fashion steps out of
his body, and enter.

You will find what you have been searching for: the hierophant, the
man of copper, who sits in the spring gathering his substance – but do
not think of him as the man of copper. He has transformed the color of
his nature and has become a man of silver. And, if you wish, you will
suddenly have a man of gold.

Zosimus

The Second Vision

Again, I wanted to climb the seven steps and observe the seven
punishments and, as chance would have it, I was only able to manage
the journey on a particular day; I made the ascent many times and
retraced my steps many times. Then, on my return, I lost my way and
was trapped. I became sick at heart and fell into a trance. I saw a
homunculus, a barber draped in purple robes and royal garments,
standing outside of the hall of suffering and he said to me: “Man,
what are you doing?” I replied: “I stand here because I lost my way
and don’t know what to do.” And he said: “Follow me.” I followed him
and when I drew near the hall of suffering, I watched as the
homunculus was tossed into the hall. His entire body was consumed by
flames.

When I saw this, I turned away, trembling in fear. I awoke and said to
myself: “What is this vision?” Again, I thought it through and decided
that the homunculus barber was the man of copper clad in purple. I
said: “I have understood well. This is the man of copper. He must
first enter the hall of suffering.”

My soul longed to mount the third step and again I made the journey
and lost my way near the hall of suffering. I stopped, disorientated
and in despair. Once more, I saw a man whose hair was so white that it
blinded the eyes. His name was Agathodaimon. This man of white turned
and looked upon me for an entire hour. I implored him to show me the
proper way – the path of least resistance. He did not approach me, but
swiftly went upon the correct route. Running here and there, he
frantically made his way to the altar. When I reached the top of the
altar, I witnessed the man of white enter the hall of suffering. O
demiurges of star-shot nature, in an instant his body turned to
blazing fire. What a chilling image, my brothers. The intensity of the
suffering caused his eyes to turn blood-red. I asked him: “Why are you
lying there?” Barely opening his mouth, he said, “I am the man of lead
and I submit to unbearable violence.”

I awoke in terrible fear and searched within for an explanation of
this vision. I reflected and said to myself: “I understand rightly –
lead must be cast out. Truly this vision concerns the composition of
the Waters.”

 

The Third Vision

Once more I saw the divine and sacred altar in the shape of a bowl. I
also saw a hierophant clothed in white, who was performing the dread
and numinous mysteries. I said: “Who are you?” He replied: “The
hierophant of the innermost sanctuary. I wish to replenish bodies with
blood, illuminate the eyes and raise the dead.” I fell down again and
went into a brief trance. As soon as I reached the fourth step, I saw
someone coming from the East with a sword in his hand. He was followed
by another carrying a radiant white revolving sphere, lovely to see,
known as Meridian of the Sun. As they approached the hall of
suffering, the one brandishing the sword spoke to me: “Cut off his
head and make a sacrifice of his muscles and his flesh in discrete
portions so that his body may be boiled according to the method and he
may experience the horrors of suffering.”

I opened my eyes and said: “I understand it perfectly. These things
concern the Waters of Alchemy.” And, again, the one holding the sword
said: “You have completed the descent of the seven steps.” The other
said: “The Work is accomplished in synchronicity with the expulsion of
lead through all Waters.”

