* Becoming Geologucal: Mining dreams?

Yes, reader, countless are the mysterious hand-writings of grief or
joy which have inscribed themselves successively upon the palimpsest
of your brain; and, like the annual leaves of aboriginal forests, or
the un-dissolving snows on the Himalaya, or light falling upon light,
the endless strata have covered up each other in forgetfulness.
[Thomas de Quincey. The Palimpsest of the Human Brain]

** 1. On the surface ...

On the surface, we have always been and will always be dirty and
harshly geological. This is the self evidence of a material
witnessing.

Geology defines and authors the human; our psyches encode millions of
years of spinal deposition and extrusion. Geopoesis is both origin and
destiny, as wilfully or necessarily inhaled and ingested matter, as
both medicine and poison or dose, as a divine or sublime power, and as
godly adornment and technological extension. We are forever involved
in its lithic cycles and in its dusty destinies.

This rotting, crystal world is not outside us as a study, survey or
prospect. We incorporate its own geophagic timescales of
incorporation. Geology endlessly defines the human, and the
realisation of both this "mineral becoming us" and our own becoming
geological is rendered by the technological and by extraction
itself. Minerals are us, our desires.

** 2. Excavations ...

Excavations tunnel into and disturb a dark and poisonous world,
creating new anthropogenic and non-anthropogenic cycles of
lengthy incorporation and extraction, of radical in-human consumption.

We literally inhale and ingest our own anthropogenic indicators;
particulate exhalations of burning forests, as isotopes from nuclear
testing, as metallic dust from global extraction and recovery. These
novel geo-cycles extend themselves, adit or tube-like and strangely
looping back to the main shaft.

Mercury ores, such as cinnabar, a sulphide or mercury, are extracted
by underground mining methods, heating the ore to liberate a vapour
which is subsequently cooled and condenses as liquid. During cremation
of human corpses, this death, which enters as a miasmic or vaporous
and mineral breath into the living, alongside heavy metals and
particulate matter, is further liberated (from dental amalgams,
immortal medical devices), returned to the earth, or inhaled in
further cycling. There is no decay, and all remediation is
recursive. Decay or becoming earth opens the black hole of the
geo-logic, swallowing and eating its deep-timed self, so lively.

Native copper ores are excavated from the earth, refined and use in
underground cables, carrying human bound screen signals decoded,
finally rendered obsolescent and later un-earthed and recovered. In
this smelting operationm, making use of the same refining plants as
above, particulate copper and other matters are released which are
then inhaled or ingested, entering active and passive species
including humans. Technology is thus extracted from the environment or
landscape at the same time as being an extension into that landscape,
reaching into and grabbing, and equally providing a means of
representation of that exhausted landscape; the anthopocene is
depicted using the very materials of its glossed becoming.

** 3. In dreams...

They are called *little miners*, because of their dwarfish stature,
which is about two feet. They are venerable looking and are clothed
like miners in a filleted garment with a leather apron about their
loins. This kind does not often trouble the miners, but they idle
about in the shafts and tunnels and really do nothing ...
[de re metallica trans hoover etc.]

A new form of mining prospect, a list of deposits or resources ripe
for low cost exploitation, is produced by the German company Medivere,
during the Tiny Mining collective sweatshop; a prospectus which is
useful in determining which portion of a mineral can be considered as
an exploitable ore reserve.

A ritual cycle of incorporation, followed by chelation and finally
extraction, or purgation, miming those long tails and tailings above,
begins with the new moon and lasts one lunar month. Hard scientific
tests for the presence of heavy metals, including colorific tests on
hair and urine, and voltametric tests on urine accompanies a
reflection on bodily impressions, feeling, thoughts and dreams over
the course of the sweatshop.

These early attempts from the collective to mine certain metals from
within their own bodies brought forth monstrous visions. What should
have remained hidden (the secret life and genesis of metals for each
individual) was exposed to their light and unearthed.

But the presence of so many soldiers and military vehicles, and the
wan-faced townsfolk evacuating their homes, ensured that the little
enclave of the transfigured forest – by comparison the remainder of
the Everglades basin seemed a drab accumulation of peat, muck and
marls – would soon be obliterated, the crystal trees dismembered and
carried away to a hundred antiseptic laboratories.
[J.G. Ballard, 'The Illuminated Man', in The Terminal Beach, London:
Phoenix, (1964) 1992, p.81]

and/or:

A priest, all grey with frozen dew, leads us from his house which is
crammed with artefacts from a burnt-out church, crispated altar
paintings, into his garden. Chickens, uncooped, run wildly at our
feet. The priest is tall, with long matted wet hair, and a long white
beard, crinkled and smally curled. He opens a stout metal gate set
into the knolled hillside one corner of the garden, inside the chicken
enclosure, and takes us into the narrow, shining adit. As a giant
guides a troupe of dwarfs, leading us with the light from one
smartphone into the coffined irregularity of the ancient, hewn walls.

Outside a larger mine entrance, the geologist in stout boots, tells us
that the main ore vein is cursed, that all of the evil over so many
years existing in the mountain mining town comes from this vein. He
translates its glowing name as drift or drifting. It is always
moving. He says that people who live in this sort of disorder, a sort
of moral and physical depth, they spread it around them like an
infectious disease. His tanner's dog vomits old silver coins and terse
liquid on his boots. He brought it up again, this colloidal and dewy
morning.

** We have to go much further, much further back. And faster.

Novel thermophilic heterotrophic bacteria were isolated from the
subsurface of the volcanic island Surtsey off the south coast of
Iceland. The strains were isolated from tephra core and borehole fluid
samples collected below 70 m depth. 
[https://matis.is/en/news/thermophilic-bacterium-isolated-from-the-basaltic-subsurface-of-the-volcanic-island-surtsey/]

If the descent into the mine, into the earth, a hole to hell, is
viewed as a journey towards a dark interior, into the unconscious,
into and as a disturbed dream, or inside that old fossil, the profound
soul, then what does it mean when that interior is mine, a fantastic
voyage, by myself? And when both this dream descent, and its becoming
interior, folding, are historically provoked by the excavation and
opening of the earth, by extraction for technological extension of
those guts and intestines.

The Tiny Miner coils inwardly on her own little mined depths,
ouroboros or worm- like, doubling back on her own interior, but to one
side, a greened dwelling-gut which is not mine, strangely, An oozing
and lacking dream inside a dream. One is doubled but not as a human of
light and phosporescence, and of darkness, the alien, the pagan, the
nomad, the odd symmetry. We are both material shades.

vision of zosimos

This descent is also a retrogression in time. As Moynihan writes in
Spinal Catastrophism, a geo-gnostic work which is precisely concerned
with this internal depth as geotrauma, "depth is time."

Steno was the first to note explicitly that stratigraphic succession
corresponds with temporal succession. In other words, that /depth is
time/. (Hence, centuries later, McPhee's coinage of '*deep
time*'). This marked the inception of the notion of /depth as mnemonic
and temporal retrogression/ that would later be so vital to
psychoanalysis or so-called 'depth psychology' (Tiefenpsychologie).
[Spinal Cat p86]

Historically speaking, I contain my outside. This is what time does to
a body, as we shall see in tracing out this Secret History. The lesson
is clear: psychosomatic containment of oneself, when percolated
through Grandest History, equals hypogene alienation — the alienation of
a body riddled with time. It is this realisation that is inaugural of
the phylogenetic phantasy that is Spinal Catastrophism.
[p50,51]

"I contain my outside" implies that this outside, my outside is
within, as an island. 

** Coagulated time

This opinion, in its general form, was that of the sentience of all
vegetable things. But, in his disordered fancy, the idea had assumed a
more daring character, and trespassed, under certain conditions, upon
the kingdom of inorganization. [...]

The conditions of the sentience had been here, he imagined, fulfilled
in the method of collocation of these stones – in the order of their
arrangement, as well as in that of the many fungi which overspread
them, and of the decayed trees which stood around – above all, in the
long undisturbed endurance of this arrangement, and in its
reduplication in the still waters of the tarn.

Its evidence – the evidence of the sentience – was to be seen, he said,
(and I here started as he spoke,) in the gradual yet certain
condensation of an atmosphere of their own about the waters and the
walls. The result was discoverable, he added, in that silent, yet
importunate and terrible influence which for centuries had moulded the
destinies of his family, and which made him what I now saw him – what
he was.  
[Edgar Allen Poe. The Fall of the House of Usher]


"[A]ll space and body is itself nothing but coagulated time" 87 moyn

The sublimated body is a pharmaceutical resource, for itself, for the
others, packaged as synthetic products, and with associated
manufacturing fumes, inhaled. The body is a metal, particulate in
spreading over a landscape. A crystalline, sparse clay mud of various
sulphides, arsenic, lead and iron, smears across the SUV's interior of
Polypropylene (PP), Acrylonitrile-butadiene-styrene (ABS), Styrene
maleic anhydride (SMA), Polyphenylene Ether (PPE), and Polycarbonate
(PC). We gaze with dull eyes at the distant volcanic peaks, resting in
the glazed claustrophobia of the undergrounds. These places
externalise me. The gold fibres dissolved in the lake's acid mine
drainage are set to colour it blood-red as a sunset. A container
subjects itself to a descriptive dissolution, to the recursive effects
of its own signs. Hardware dissolves itself as a function or extent of
its own functions, as a necessity. It is and is not a palimpsest.

Inside the mine workings, the body can now become any landscape, a
prospect with associated legal frameworks and permissions, an island
of waste, a rosy site of tailings, a suburb, a logistics centre on the
outskirts of a small town, between motorways, an overgrown heap of
rubbish grazed now by sheep, a new mountain amidst the dykes and
drainage canals. This boggy body is depicted, scanned and stretched,
and re-skinned, inhaled as image, incorporated. Geology is said to be
the biography or history of a earthy body.

/////

- being a landscape, a mine and finally a planet // planets become metals. connective threads, filaments between the earth and the cosmos, we are made of these threads.

The geopoetic body informs and enabled of articulations, formations,
ingestions of inhalations of particulate matter, uranium-235,
conduits, fracking, descents, carbon dating, deep time, metals, the
cut, bedrocks, cavities, caves, chasms, tailings, leachings,
radiometric dating, orogenesis, dumps, lithologies, stratigraphies,
mineral resources, extractions, boundaries, outcrops, chronologies,
leachates, sulphides, percolations

Spinal: p220 ****

planet as a body

Oken noted that the ‘[e]arthly organs must correspond to animal
organs’: or, the ‘mountains, rocky terrain, [and] cliffs’ must find
their analogues in our own innards. If teeth are nails, then nails are
just stalactites. ‘Just as the animal body is finally composed of
these organs, so the composition of rocky terrain must produce a
terrestrial body, which is the planet’, Oken pronounced.13 

From Ritter to Kielmeyer, Schubert to Steffens, the Naturphilosophen
were in agreement on this: ‘[i]norganic matters and activities pass
parallel [to] the anatomical formations and functions’, as Oken put
it.14 He went so far as to say that ‘[o]rganism is what individual
planet is’ (because the ‘primary vesicle’ of the embryo, in its
globular form, is but a repetition of the forces that ‘produce’ the
planet itself).15 Steffens summed all this up adequately when he wrote
that, given these principles, every animal, plant, crystal, and
mineral represents a ‘stage of [terrestrial] development’: the
totality of which, taken together as one goliath constellation, would
thus provide the ‘true history of earth’.16 

Seismic upheavals in the mind disrupt the cosmic island.


- sentience of a place, becoming sentient and also in reverse... usher in reverse

/// inferior/interior astronomy. inverted astrology as finale

Inferior astronomy is another way of naming transformative methods for
working with plants and with metals. Astronomical discourses are
re-interpreted as referring to the terrestrial; planets become
metals. It’s an historic analogy, a set of identities or
transformations which help to make sense of certain early texts
treating the planets in mineral and muddy terms and as, at odds with
the celestial, undergoing earthy and earthly process.
 
Inferior geology seeks to further these transmutations, resting
equally on a magical closeness to the key phrase of “interior
geology.” If inferior astronomy brings the planets down to earth,
within the primacy of substitution which is called occult and is
recognised as such (this spiritual work with matter was always already
astronomy, inferior astronomy just marks that connection within the
realm of metaphor), then what substitution is being pointed at as
already having happened in thinking the geological as always inferior?
That it is rendered earthy? That it becomes of bodies and of
circulations without reference to marked, measured and seriously
differing time scales?

from the earth considered as something exterior, that which is acted
upon by humans, a laboratory planet - to the earth and geology as
something incorporeal, incorporated and interior

idea of interior or internal geology, a fantastic voyage from
*inferior geology*, the underneath, vast dripping caves and mines
supplying energy for the server farms above ground to interior geology
(informed by the discipline of medical geology).

[note: In the concentric circles of his “lower Astronomy,” this
diagram Ripley provided a terrestrial analogue for the planetary
spheres: encoding his alchemical ingredients as planets that orbited
the earthly elements at the core of the work.]

*bringing the planets down to earth as metals ripe for extraction*



** questions 20/9/2022

of what we need to mention -> theory we have, bog bodies, bezoar,
miasma we have, tears - thread more of content into the above!
