** remains

*** BG

BG invokes artistic, practical and theoretical responses to this new
inner nature, from the history of close bodily contacts between human
beings and geology, the discipline of medical geology, medical
anthropology, and new dark ecological theory to speculative
bio-fictions.


*** generic TM 

Tiny Mining (TM) is an open source mineral exploration co-operative
and resource specialist committed to the potential exploitation of the
interior of the living human body for rare earth and other mineral
resources in the interests of human and planetary health.

We have always been and will always be geological.

Humankind has always been dirty and geological, through intentional
incorporation of earthly and thus cosmic elements (as diet or as part
of medicinal or spiritual practices), and within a direct connection
with a slowly changing earthly and cosmic environment. We can also
think of kidney stones, of crystals formed in urine and of iron in the
blood and tissues. We incorporate the earth and its minerals, becoming
sedimentary.

But there is more to it than this, as we tunnel into, disturb and
create new non-anthropogenic and anthropogenic cycles of incorporation
and extraction, of radical consumption.

*** cyclings:

With the arrival of the questionable era of the anthropocene, marking
another entry point into the planetary geological, a new “natural”
cycle is initiated - we literally inhale and ingest our own
anthropogenic indicators (for example, as the particulate exhalations
of burning forests, as isotopes from nuclear testing, as metallic dust
from global extractions). These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms. Understanding this new nature for
humankind involves a close examination and potential embrace of a
“becoming geological”, becoming a-human.

illustrated by for example, the extraction of native copper ores from
the earth, their refinement and use in underground cables, carrying
human bound screen signals decoded, their later un-earthing and
recovery, a smelting operation releasing particulate copper and other
matters which is then inhaled or ingested, entering active and passive
species including humans. 

inhale mercury fumes from crematorium stacks - mercury is extracted by
heat? from its ore cinnabar

These cycles are solely meditative and illustrative... they are too
material, too logical and explained, they are merely a recursive
apparatus flip-flopping betwixt the knowing anthropogenic and the
imagined lithic? a recursion which admits only itself, no others, 

remediation as recursion

technology is extracted from the environment or landscape at the same
time as being an extension into that landscape, reaching into and
equally providing a means of representation of that exhausted
landscape

that the anthopocene is depicted using the very materials of its becoming

these double movements - we extract in order to extend into, to blanket and logicise


invitation:

After taking Argotine, if your face and body itch as though insects
were crawling over them, if your hands and feet swell, if you cannot
stand the smell of food and vomit it up after you have eaten it, if
you feel as if you were going to be sick most of the time, if you
experience weakness in your arms and legs, if you have to go often to
the toilet, or if your head or stomach violently ache - do not be
alarmed or disturbed. All these effects are merely proof that the
Argotine you are taking is successfully mining your insides.

*** we have always been/are

Humankind is and has always been geological; as both origin and
destiny, as inhaled and ingested matter, as medicine and willing
poison, as a divine or sublime power, or as adornment and
technological extension. We are forever involved in its cycles and its
(destiny?)

the geologic is our fixated, addictive and necessarily obscured or
covered up logic (steganography, stratigraphy...) - our beginning
 and our end.

important - as origin, as conditioning us. as determining us, our living conditions, as our unconscious, to go backwards, as our depth and setting

*it defines us*

Humankind can be defined as always incorporating the earth: as food,
as pharmakon and as media and this incorporation can be defined as
geological. We can catalogue a history and a "bestiary" of an inner
geology with its bezoars, otoliths, gallstones and
gastroliths. Geology is not outside us; various timescales must be
compared and contrasted (of lives and deaths, eating and shitting, of
deep time and geological formation).

humankind has always been harshly geological, authored by geology, sedimentary beings, the result of million years of spinal deposition. 


*** trondheim

a new form of mining prospect, a list of deposits or resources ripe
for low cost exploitation, produced by the German company Medivere,
during our first Tiny Mining collective sweatshop.

A prospectus, which as such is useful in determining which portion of
a mineral can be considered as an exploitable ore reserve.

Environmental concerns are no longer out there, in a controlled and
surveyed landscape of "nature"; to be protected. The dread-ful
"anthropocene" is now an internal story written within interior
geologies and in the deep time of ingestion and digestion. Saving the
planet is now a matter of looking into ourselves.
 
The symptoms of a muddy embrace of the becoming geological were
explored and exacerbated in the first of a series of sweatshops.

These include:

SWEATSHOPS:

An attention to the moon and planetary phases and orbits - the cycle
of extraction begins with the new moon and lasts one lunar month. The
first sweatshop commenced with the new moon, following a cycle of
ingestion (a diet rich in the specific metal assigned to the sweatshop
participant), followed by chelation (the use of medicinal plants and
pharmaceuticals to bring metals out of tissues), and extraction or
purgation.

An examination of co-relation between diet, dreams and
reveries. Participants reflected on bodily impressions, feeling,
thoughts and recorded all dreams during the sweatshop.

Hard scientific tests for the presence of heavy metals: colorific
tests on hair and urine, voltametric tests on urine.

Exploring one’s affinity with the various metals (such as antimony,
gold, silver, arsenic, lead, iron and mercury), their physical
properties, historical and mythical qualities and an awareness of the
connection of bodily routines and sentiments with these properties.

New developments post sweatshops - we are currently working with a
Chinese pharmaceutical company based in Beijing on the (open source)
development and manufacture of Argotine, the primary extractive agent
alongside “natural” chelators and supplements. Argotine incorporates a
synthetic chelating agent (DMPS), sets of nano “collectors” or
“farmers”, and finally an emetic or purgative element based on
traditional Chinese medicinal or alchemical recipes (for flight and
immortality) such as Elixir of Ascent into the Roseate Clouds making
use of arsenic and mercury bearing ores.

*We become bio-markers, indicators of earthly or planetary health.* 

How much can we extract from the earth, and return to the
earth? I offset what I take from the earth, and the damage I cause the
earth, through this giving back. We try to get to know our own cycles,
of excess, of regulation and of deficiency.”

Rather than prioritising the sense of purity and sustainability as the
ecological act of resisting the earth’s extraction and simply using
human bodies for a similar purpose, the goal is to become sensitive by
dismantling what Patricia MacCormack named as “human privilege.” AGN

It is through working at the faces of the deep implications within
these contradictions that we can begin to understand what is at stake
within the daily ascetic practice of Tiny Mining and within the wider
current or vein of the Becoming Geological. And we need to understand
that these contradictions are themselves embedded in consumption or
incorporation of the other and in extractive practices. The
contradiction is within incorporation, becoming a geological body
through the incorporation of geological time scales.

We begin to realise that all geology is geophagy (consumption of
earthy substances).  The alchemists would say that nature loves to
hide, we say that nature loves to eat.


To return to this duality of incorporation and extraction we can see
that just as the chinese alchemists extracted arsenic and mercury from
the earth (as orpiment, cinnabar and realgar) to incorporate these
materials in their bodies as agents of immortality.

So today we extract copper, tantalum and so on towards an extra-bodily
incorporation, an exteriorisation of bodies in and as technology

Our become dispersed as techno-prostheses is a form of
incorporation. Incorporation and extraction are as the pharmakon of
dosage: lack and abundance, deficiency and toxicity.

Other communities such as transhumanists and biohackers now seek a
"real" incorporation of metals and technology - to upgrade and replace
the flesh or meat suit with immortal components - subject only to
obsolescence and eternal internal upgrades.

Mercury and copper are extracted from the earth and placed into the
human body in order to preserve it. Transhumanism is about material
augmentation, flesh is replaced by metal and mineral which is
(apparently) a renewable resource.

Tiny miners go in reverse direction - becoming mineral and purging
oneself of the metal, the mineral.

This reminds us of the practices of self mummification parallel to the
use of elixirs of immortality for bodily preservation:

As Joseph Needham writes in this context: The adept towards the end of
his life abstains for a long time from all cereal food, living only on
plant material such as chestnuts, Torreya nuts, pine-tree bark and the
roots of grasses; then just before death he may claim the distinction
of being buried alive. After death has occurred the corpse is dried
over charcoal fires and smoked with the fumes of incense, then when
fully dessicated lacquered all over or used as the base for a statue
of dried clay or plaster.

*** machines will watch us die interview

smog as a contemporary, geological
media binding the (photo)-chemistries of screens, bodies, cities and
planet.

At the same time it becomes clear that these machinic processes are
very much linked to some process of mummification (as Robert Smithson
wrote, "the medium is the mummy"); to a kind of deathly or spectral
preservation which could be considered as immortality. This is what I
mean by enshrouding, by enveloping in veils of screens and smog, and
by the ingestion of earthly and technological minerals and machined
synthetics. We become geological. In the sense that the digital
outlives us, as earthly trace, as cloudy storage and as toxic
memorial, machines will watch us die, record our deaths (as loss of
resources) and assist in forming a spectral community of the un-dead.


*** epub

Tiny Mining: A handbook for internal extraction brings together the
multiple strata informing the Tiny Mining project: making connection
between bioethics, posthumanism, the history of close bodily contacts
between human beings and the geological, the discipline of medical
geology, medical anthropology, and new dark ecological theory.

The Tiny Mining community was founded in November 2019, during an
expert meeting in Brussels. This open community consists of a diverse
group of chemists, geologists, artists and alternative medicine
practitioners. In November 2020, a small group of community users took
part in the first remote sweatshop dedicated to the exploration of
experimental protocols for improving extractive yields and
facilitating testing procedures for the wider community. We also
explored the construction of alternative belief systems, facilitating
the adoption of Tiny Mining as a widespread cultural practice. A metal
or element was assigned to each sweatshop participant for reflection
and extraction. In order of elements the participants were: Theun
Karelse, v2_labs, Dennis de Bel, Kat Austen, Martin Howse, Aniara
Rodado and Alfonso Borragan. The results of the first remote sweatshop
are documented here.

*** IMM

This idea of a sensitivity to planetary and bodily health underwrites
the Tiny Mining project with the Anthropocene viewed as both
symptomatic and as psychosomatic.

The focus of the project is on the transitional interior and inferior
geologies of media and communications. The notion of interior geology
refers also to the circulatory system of an earth addiction
encompassing extraction (of precious metals, of radioactive minerals),
transport/circulation and consumption (the ingestion of earth-derived
energies, materialities and earth-bound pharmaceutical products) and
return or excretion (traces of isotopes and pollution elements in the
body).

Matter, like media are both purposefully ingested and accidentally
absorbed, forming new internal, circulatory and transitional
geologies.

Tiny Mining explores these multiple links and circulations between
technology, the environment and the human body and psyche. It's
important in times of climate disruption and environmental destruction
that we begin to think and work deeply within these relationships and
within the histories of media such as scientific discourse,
pharmacological matters and medical geology; to think an alien,
potentially geological post-nature.

ARGOTINE:

The parasite, named Argotine (with reference to the rich history and
folklore of the ergot fungus) is designed as an assemblage of
nanoscopic units, each of them measuring around 10nm, that have
specific compositions and electrical charges corresponding to the
desired mining process.

The different nanomachines create bonds, communicate and form larger
structures (up to 100 micrometers) similar to fungi's mineral mining
hyphae. Once injected into the bloodstream, they travel and stick to
the affected/healthy cells where the extraction begins.

This micro/tiny mining process, as in the case of soil mineral
extractions performed by plants, fungi and microorganisms is
facilitated thanks to bioleaching (the process of extracting metals
from their ores through the use of living organisms) through
chelation. The process is highly efficient for lead, arsenic,
antimony, molybdenum, gold, silver and cobalt extractions.

Our thesis here is that the in-corporation of the earth, the becoming
geological of the human body, meaning that geological time-scales and
processes can now be considered as corporeal: that these ideas are at
play within the community of Tiny Mining and relate heavily to an
anthropology or history of the preservation and immortality of bodies
and their extensible or extended environments (prostheses or tool
culture) which leads abruptly to contemporary trans-humanist practice.

What is shih chieh? (from a Taoist catechism p301 - Li Shu-Huan)

After the death of an adept seeking immortality, the form and skeleton
remain behind while the immortal goes away; this is what is meant by
shih chieh. When one is ready to rise up as an immortal, one leaves
behind the malodorous house of clay, hence the expession "corpse"
(shih) from which the hsien is "liberated".

The Chu Hsien Lu says "When the appearance is like that of a living
person - that is (proof of) shih chieh. When the feet have not turned
bluish in colour, and the skin not shrunk - that is shih chieh. When
the light in the eyes has not gone dull, and looks like that of a
person still alive - that again (shows) shih chieh. There are also
those who have become alive once more after being dead; and some whose
bodies have disappeared altogether before being encoffined; and others
who have ascended, leaving only their hair behind - all these things
are called shih chieh. 

*Those who effect their liberation during the light of day become
immortals of the higher category, those who do so at night join the company of the lower.*

We can see that just as the chinese extracted arsenic and mercury from
the earth (as orpiment, cinnabar and realgar) to incorporate these
materials in their bodies as agents of immortality.

So we extract copper, tantalum and so on towards an extra-bodily
incorporation, an exteriorisation of bodies.

Our become dispersed as techno-prostheses is a form of
incorporation. Incorporation and extraction are as the pharmakon of
dosage: lack and abundance, deficiency and toxicity.

Transhumanists and biohackers now seek a "real" incorporation of
metals and technology - to upgrade and replace the flesh or meat suit
with immortal components - subject only to obsolescence and eternal
internal upgrades.

EXTRACTION:

Extraction is about storage the memorial, the support for an archive.

Mercury and copper are extracted from the earth and placed into the
human body in order to preserve it. Transhumanism is about material
augmentation, flesh is replaced by metal and mineral which is
(apparently) a renewable resource.

Tiny miners go in reverse direction - becoming mineral and purging
oneself of the metal, the mineral. Again the dual blade of the
pharmakon.

Mind uploading or brain upload can also be seen as a form of
extraction, extropian data mining; discard the flesh suit and extract
that valuable mind.

There is this twin movement in TM of wanting to incorporate the earth
in order to be able to mine, but also extracting and freeing oneself
of the earth (inside) and of any attachment to the earth. Going way
beyond the Gnosticism inherent in Transhumanism.

internal gnosticism


** inferior geology/other essays? sonic acts 2021. peter. finland bog reader but that is about cycles...

*** inferior

idea of interior/inferior...

Inferior astronomy is another way of naming transformative methods for
working with plants and with metals. Astronomical discourses are
re-interpreted as referring to the terrestrial; planets become
metals. It’s an historic analogy, a set of identities or
transformations which help to make sense of certain early texts
treating the planets in mineral and muddy terms and as, at odds with
the celestial, undergoing earthy and earthly process.
 
Inferior geology seeks to further these transmutations, resting
equally on a magical closeness to the key phrase of “interior
geology.” If inferior astronomy brings the planets down to earth,
within the primacy of substitution which is called occult and is
recognised as such (this spiritual work with matter was always already
astronomy, inferior astronomy just marks that connection within the
realm of metaphor), then what substitution is being pointed at as
already having happened in thinking the geological as always inferior?
That it is rendered earthy? That it becomes of bodies and of
circulations without reference to marked, measured and seriously
differing time scales?

Inferior geology naturally also refers to a geology which is
“inferior” to some officially defined geology, less stratified
perhaps, more psychically re-churned and de-sedimented. I’m trying to
think of the peat, of the mud mind transmuted into the bog mind, of
Beckett’s “All is noise, unending suck of black sopping peat, surge of
giant ferns, heathery gulfs of quiet where the wind drowns, my life
and its old jingles” jangling within applied and applicated, sewn and
freshly black fibrous science. Inferior geology could also refer to
seismology, with its Love waves and Rayleigh waves, other forms of
faster application, disrespecting deep geological time. Inferior also,
in an original sense, as a breathing beneath, the earth evaporating
beneath the moon and the stars, sinking deeper into the sucking, and
slowly shattering.

*** sonic acts

immersion and contact in the earth - describe arsenic and cyanide muds
caking clothes, skin and car interior, paranoia about what could be
described as EXPOSURE

from the earth considered as something exterior, that which is acted
upon by humans, a laboratory planet - to the earth and geology as
something incorporeal, incorporated and interior

idea of interior or internal geology, a fantastic voyage from
*inferior geology*, the underneath, vast dripping caves and mines
supplying energy for the server farms above ground to interior geology
(informed by the discipline of medical geology).

[note: In the concentric circles of his “lower Astronomy,” this
diagram Ripley provided a terrestrial analogue for the planetary
spheres: encoding his alchemical ingredients as planets that orbited
the earthly elements at the core of the work.]

*bringing the planets down to earth as metals ripe for extraction*

enacted as a series of now online sweatshops - meditations on metals
and elements (each participant is assigned an element which they work
with) 

ingestion, chelation, testing and extraction following planetary and
elemental cycles

*** arsenic eaters

XX mining gnomes - 

They are called *little miners*, because of their dwarfish stature,
which is about two feet. They are venerable looking and are clothed
like miners in a filleted garment with a leather apron about their
loins. This kind does not often trouble the miners, but they idle
about in the shafts and tunnels and really do nothing, although they
pretend to be busy in all kinds of labour, sometimes digging ore, and
sometimes putting into buckets that which has been dug. [...] The
mining gnomes are especially active in the workings where metal has
already been found, or where there are hopes of discovering it,
because of which they do not discourage the miners, but on the
contrary stimulate them and cause them to labour more vigorously.

de re metallica trans hoover etc.

quote:

The arsenic eaters prevailed over poison by surrendering to it,
overcame death by submitting to it. When graves were exhumed in order
to create new burial plots, it was found that the bodies of the
arsenic eaters had hardly decayed ...
xxix

** Notes so far/notebook:

*** TM intro/start of all - new notebook 16/8+

core themes: 
- decay, death, preservation // bog bodies, immortality (immortality of athropocene)...
- origins (Moynihan)
- dis-articulation (of logical strata). dislocation of landscape -in dreams, of body, of a representation - a frame?island
- particulate matter

BG fronts and confronts death; the death of oneself as an individual,
the death of others, the death of a pig, the ends of worlds and the
death which enters as a miasmic or vaporous and mineral breath into the living.

strange loops and feedback loops: These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms.

that geology writes us, that we feedback on this geology - also mackay
in intro....

that the place is sentient - how to divine the sentience of a place

that we are this place - we are a landscape. an internal landscape,
flipfloppings of ballardian

If the descent into the mine, into the earth, a hole to hell, is
viewed as a journey towards a dark interior, into the unconscious,
into dreams, or inside that old fossil, the profound soul, then what
does it mean when that interior is mine, a fantastic voyage, with me
or by myself. Ouroboros-like I double back on my own interior, but to
one side, an interior which is not mine, strangely, An oozing and
lacking dream inside a dream. We are doubled but not as a human of
light and of darkness. We are both shades. // shades as a
material. phos/Zosimos... leads into the vision - man of light

The feedback loops crossing ... tighten, becoming internalised and
fault-line stressed.

That this descent is also a retrogression in time. As Moynihan writes
in Spinal Catastrophism (an essential complement to the essay here), a
geognostic work which is precisely concerned with this internal depth
as geotrauma, "depth is time." 

"Steno was the first to note explicitly that stratigraphic succession
corresponds with temporal succession. In other words, that /depth is
time/. (Hence, centuries later, McPhee's coinage of '*deep
time*'). This marked the inception of the notion of /depth as mnemonic
and temporal retrogression/ that would later be so vital to
psychoanalysis or so-called 'depth psychology' (Tiefenpsychologie).

[p86]

The Tiny Miner coils inwardly on her own inward mined depths. 

Further "Steno's Stratigraophic Law [implies] that all space and body
is itself nothing but coagulated time" 87 -> Ballard crystal world as
a further manual for BG

Spinal cat:

But when one’s past is a story of quakes and perturbations, the
internality implied by ‘one’s own history’ begins to
unravel. Ultimately, discovering finitude entailed discovering that
thought is functionally internal to itself, but self-containment
becomes problematic when modulated through the dimension of Grand
History. Here, ‘internality’ and ‘inclusion’ are reconstituted as a medium of
ancestral selfabruption rather than telescoping self-similarity and
ownership. What is at stake, then, is the realisation that the
historical vanishing point of selfcontainment just is self-exclusion:
in other words, depth. Historically speaking, I contain my
outside. This is what time does to a body, as we shall see in tracing
out this Secret History. The lesson is clear: psychosomatic
containment of oneself, when percolated through Grandest History,
equals hypogene alienation—the alienation of a body riddled with
time. It is this realisation that is inaugural of the phylogenetic
phantasy that is Spinal Catastrophism.

p50,51

For Ballard, a consistently nonconforming Kantian in his approach to
spacetime, temporality becomes a global secretion of the CNS

p77

Indeed, Ballard prophesies that, at the lowest spinal-neuronic
levels, organic self-inclusion completely evaginates into the
‘inhospitality of the mineral world’, its ‘inorganic growths’, its
‘profound anguish’, as in The Crystal World, where the deepest
entropic future leaks backwards into the present.21 Time bends into
itself, cephalopod-like: accelerative lurch into the entropic future
is nothing but thoracic drop into the preorganic past.

p102

mackay p2 - the descent takes on the character of a disturbed dream

At the same time it is essential to note, as Mackay observes that
this subterranean descent, this romantic or sublime path of soul-full
healing, "a healing return to the matrix of an all-encompassing
earth-process and thus to a more profound soul, dark double of the
self condemned to surface dealings" arises "precisely in parallel with
those other compulsions that were beginning to exert their cosmetic
dominion over the face of the planet. It is the shaping and hauling
and digging and layering of infernal machines that opened up new
breaches and passageways through which the other soul could pass."

- how this could parallel with contemporary situation of becoming
  geological... we become this planet and earth process, descend into
  our own more profound soul...

[p1. subtexts] Mackay - cryptolithic passions (intro to compilation of geopoetics - elaine)

Geology is the study and enabling of articulations, formations,
ingestions of inhalations of particulate matter, uranium-235,
conduits, fracking, descents, carbon dating, deep time, metals, the
cut, bedrocks, cavities, caves, chasms, tailings, leachings,
radiometric dating, orogenesis, dumps, lithologies, stratigraphies,
mineral resources, extractions, boundaries, outcrops, chronologies,
leachates, sulphides, percolations

becoming dump - list all these becomings also as suggested by Agnieszka

becoming geological is to become as these and many others

planet as body - becoming cosmic

body as planet

Spinal: p220

Oken noted that the ‘[e]arthly organs must correspond to animal
organs’: or, the ‘mountains, rocky terrain, [and] cliffs’ must find
their analogues in our own innards. If teeth are nails, then nails are
just stalactites. ‘Just as the animal body is finally composed of
these organs, so the composition of rocky terrain must produce a
terrestrial body, which is the planet’, Oken pronounced.13 From Ritter
to Kielmeyer, Schubert to Steffens, the Naturphilosophen were in
agreement on this: ‘[i]norganic matters and activities pass parallel
[to] the anatomical formations and functions’, as Oken put it.14 He
went so far as to say that ‘[o]rganism is what individual planet is’
(because the ‘primary vesicle’ of the embryo, in its globular form, is
but a repetition of the forces that ‘produce’ the planet itself).15
Steffens summed all this up adequately when he wrote that, given these
principles, every animal, plant, crystal, and mineral represents a
‘stage of [terrestrial] development’: the totality of which, taken
together as one goliath constellation, would thus provide the ‘true
history of earth’.16 History is just the decryption of the relations
of body parts; body parts are just a matter of encrypted history

226 **important

If the planet is a brain, only a vanishingly small amount of its
trillion-cubic-kilometre volume is not lithified and dead. And, as
intimated above, it was in attempting to internalize —or digest—the
planet’s magmic inorganic depths that Spirit developed the ulcer we
now call the Unconscious. In other words, Recapitulation’s attempt to
retain Identity through Natural History’s temporal torsion ended up
sacrificing idealism’s Law of Continuity (at every psychic and somatic
level): the self-identical telescopic inclusions of Leibniz’s prior
‘fractal vitalism’ now became internal heterogeneity and layered
self-exclusions (or, stratification: the internal trace of Grand
Time). Idealist containment spectacularly intussuscepted into a
layer-cake of internalised self-exclusion: this was the invention of
philosophical Depth, or the evagination of telescoping self-inclusion
into invaginated and stratigraphic self-exclusion. And so, this is how
Schopenhauer could finally state that consciousness ‘is the mere
surface of the mind, and of this, as of the globe, we do not know the
interior, but only the crust’.

253 Mineralization streaks through organic form: from basic examples
like ‘Shells’ to ‘Mother-of-Pearl’ and ‘egg’ up to ‘cartilage’ and the
chitinous carapaces of ‘Lobster-Claws’; ‘still higher, Zoophytes
[i.e. corals] repeat the process’; and, at ‘the summit’, ‘Bone’ and
‘Teeth’ conclude the conservation, or reuptake, of the geological into
the biological.24 In a vision arguably even more fevered than that of
Kubla Khan, fColeridge thus witnessed lithic externality snaking its
way throughout organic inner time: he noted that annelids ‘deposit a
calcareous stuff’ as if they have to ‘drag about’ a piece of the
planet’s ‘gross mass’ whilst also observing that, in the ‘insect’,
this mineral ‘residuum’ has ‘refined itself’ into a carapace; in
‘fishes and amphibians it is driven back or inward’ into an
endoskeleton; and, at the pinnacle, this inwardification of stone
climaxes in humanity’s grand ‘osseous structure’.



key of becoming earth. becoming a landscape:

- dreams/magic - geology as inverted astrology, divination (Mackay p.2
  novalis) -

  also 
- becoming/being a landscape
- decay/death/immortality
- off planet
- digital extension/post-humanism
- material/core

** from talk with tm people 0609.

that all these issues - of extraction, of pollution, of climate
catastrophy, of the becoming pharmaceutical - are now brought inside
(where they already were, hiding, a dark consciousness) - they are not
implicit in that hidden way, to be probed or divined, but experienced
directly. these questions become embodied. We reflect on these inside,
from another quite radical position,,, (not the spectacle of the
anthropocene as an outside - that which is a bearing towards something
other or exterior. we inhale our own markers - feedback loops

effects on the psyche...

try to define internal feedback loops

in terms of:

implied by inferior/interior geology, astronomy, astrology

where these are also... this telescoping inwards, turning inside/out -
where we read of this? in subtexts???

feedback loops: extraction and burial, cycles of apparatus/extension,
of inhalation...

the lithic - we eat stones, stones measure our time, 

becoming acephalic - Marder...  Instead of reinventing the
hierarchical head, one must chop it off, so as to come up with an
acephalic (I would say, vegetal) configuration.

I am the Headless Daimon with sight in my feet, the Mighty One who possesses the immortal fire.
I am the Truth who hates the fact that unjust deeds are done in the world.
I am the one who causes lightning and thunder.
I am the one whose sweat is the heavy rain which falls upon the earth that it might be inseminated.
I am the one whose mouth burns completely.
I am the one who begets and creates.
I am the Favor of the Aiōn,
my name is a heart encircled by a serpent.
Come forth and follow.

PGM. The original Greek from PGM V.96—172, formally titled “Στήλη τοῦ Ἰέου τοῦ Ζωγρ εἰς τὴν ἐπιστολήν” (Stēlē toû Iéou toû Zōgr. eis tḕn epistolḗn) or “The Stele of Ieu the Hieroglyphist in His Letter” 

bataille; 2 Shamefully, We Get Life from Putrefaction, and Death,
Which Reduces Us to Putrefaction, Is No Less
Ignoble than Birth 

geophagy - eating the earth, eating oneself, itself

mistake of thinking that the earth, the cosmos is outside us, not to say that we are "one" with these others but....

