** authors/artists notes/quotes

link of decay

images? pharm packagings???

what is woven in the geological, a lie, a word, a dressed up mineral
shop for souls, for puppets, end of the world, mined like a sewer.



*** Patricia

*** Marder

geology and its doubles - calcite, iceland spar, surtsey

passionate/particulate articulations

Marder in .... defines two modes of the contemporary becoming
geological which are pitted against each other. He specifies these as
the ancient and ever present gradual decomposition of all bodies,
becoming earth, and the encrustation of the "byproducts of industrial
technobodies" both in geological strata, and equally in all living
bodies; these latter are the familiar and dreadful terms, marks and
shifting registers of the anthropocene.

The are the two incompatible modes of the becoming geological, geology
and its double - an articulation and a dis-articulation of the earth,
and indeed, of the very terms of geology's meaning, a p-articulate
refining of gelogy and the anti-geological. that the doubling is
always there to question itself, in this feedback loop.

Yet we can see that one mode is materially embedded within the other,
it is inside. All bodies inhale and ingest anthropogenic indicators,
particulate exhalations of burning forests, isotopes from nuclear
testing, metallic dust from global extractions. Marder ... that this
embedding, makes of our decay, that which was historically more of a
becoming earth, into this strange twin of the becoming geological and
the anti-geological, between an articulation of the earth and heavens
or cosmos and a dis-articulation.

Decay or becoming earth opens this necessarily black hole of the
geo-logic, swallowing and eating itself, so lively.

patricia - becoming-strata for the Earth and [of] the soil!

2 strata of becoming geo: God is a Lobster, or a double pincer, a
double bind - to have done with the judgement or geo-logic of god?

Marder: the anti-becoming of anthropogenic debris is both geological and
anti-geological, since, in its being added to the planetary strata, in
its articulation with other layers of the earth, it disarticulates the
earth both internally, with respect to itself, and externally, for
example, with regard to the atmosphere and the oceans.



[older:
also transition from the feedback loop of:

With the arrival of the questionable era of the anthropocene, marking
another entry point into the planetary geological, a new “natural”
cycle is initiated - we literally inhale and ingest our own
anthropogenic indicators (for example, as the particulate exhalations
of burning forests, as isotopes from nuclear testing, as metallic dust
from global extractions). These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms. Understanding this new nature for
humankind involves a close examination and potential embrace of a
“becoming geological”, becoming a-human.

towards the entry of decay - that our decay is more of a becoming
earth, but the entry of the anthrop makes our (non) decay and
techno-fossilisation more of a becoming geo - how to express this more cleanly?
]

also opening of a place gone mad

acephalic

*inside itself*

facing of heaven and earth, cutting in two:

In Meso-American traditions, particularly in Aztec cosmologies,
Tlaltecuhtli is a giant creature, who swam in cosmic waters until the
serpent god Quetzalcoatl and his brother, the smoking mirror god
Tezcatlipoca, “cut Tlaltecuhtli in two. The lower half became the
heavens and stars, and the upper half became the earth.”i

elaine - As above, so below: loving are the astral bodies that hold court over
the repose of our tortured flesh.

as above so below. emerald tablet Arabic:[22] إن الأعلى من الأسفل والأسفل من الأعلى

rending of this god, unity that never existed, pre-existed - the
singular thread or filament of Thomas M - 

The delirious and filthy protaganist Elaine ... equally situates this
primordial rending which is within and is the double heart of the BG:

But in and among these I discovered one interpretation, which held for
me especially convincing, for how sensibly it conferred with our
to-date scientific speculations about the budding youth of the
universe – of a compact, energetic singularity from which all life
would unfurl.

*** Thomas

*** Filth



** dreams

** segments to fill in

*** places/place gone mad

*** insides - tiny mining // doubles - the inside is down inside... to descend is to go inside

*** geophagy - eating itself, feedback loops

*** islands of decay

*** dreams

** quotes

*** Artaud

No more fruit, no more trees, no more vegetables, no more plants pharmaceutical or otherwise
and consequently no more food, but synthetic products to satiety, amid the fumes, amid the
special humors of the atmosphere, on the particular axes of atmospheres wrenched violently and
synthetically from the resistances of a nature which has known nothing of war except fear.
[Antonin Artaud. To have done with the Judgement of God.]

*** Poe - for place gone mad

*** decay decomposition island

*** sturtsey

** notes to above as we write

*** surtsey decomposition

Sudhaus, W., Rehfeld, K., Schlüter, D. & Schweiger J.
1988: Beziehungen zwischen nematoden, coleopteren und
dipteren in der sukzession beim abbau von kuhfladen. (The
interaction between nematodes, beetles and flies in the succession during decomposition of cow pats.) Pedobiologia
31, 305–322.

The patchy spatial distribution of the nematodes (note the ranges in
Table 4) presumably reflects a distribution of the nematode habitats
(food sources) in “hot spots”. These are most likely related to bird
droppings, food spills or bird cadavers, which offer a sudden burst of
available nutrients of a low C:N ratio. However, the “hot spots” will
change radically during decomposition and must be considered a very
unstable resource, and hence be a typical habitat of
r-strategists. Protorhabditis cf. oxyuroides, Mesorhabditis
monhystera, some Panagrolaimus species and A. nanus are r-strategists,
i.e. habitat generalists with good reproduction potentials (Sohlenius
1973; Sudhaus 1976) typically found in such habitats. 

feathers are shed and corpses of birds that die decompose
