* xx

** about the book

One pill is taken at sunset with the first water drawn from the well,
as you face the sun. After seven days fairies will come to serve you;
in two hundred days you will be able to "summon the mobile kitchen";
at the end of three hundred days you will become as immortal as sky
and earth.
[Sivin p186]

Becoming Geological is a manual, or guide for a new relation of the
human, invoking “becoming geological”, “becoming dirt” and “becoming
cosmic” as potential new modes of existance and active philosophies of
the earth; a manual for how to live and die within new earthly and
cosmic techno-cycles.

Becoming Geological de-stratifies the history of close bodily contacts
between human beings and geology, forming aggregates of the disciplines
of medical geology, medical anthropology, new dark ecological theory,
ethical geo-stratum, geo-poesis.

Becoming Geological functions as a guide sets of internally gnostic exercises,
(artistic) therapies for universal geo-trauma provoked by the
‘inhospitality of the mineral world’(ballard), invocations for taking
the earth with us, for leaving the earth behind, for a mysterious
world, a poison garden.


** we have always been geological, on the surface

We have always been and will always be dirty and harshly
geological. 

at least it appears so - the self evidence of a material witnessing

Geology defines and authors the human; our psyches encode
millions of years of spinal deposition and extrusion. It is both
origin and destiny, as wilfully or necessarily inhaled and ingested
matter, as medicine and willing poison, as a divine or sublime power,
or as adornment and technological extension. We are forever involved
in its cycles and its destiny.

The crystal world is not outside us, we incorporate its geophagic
timescales of incorporation. Geology endlessly defines the human, and
the realisation of this "mineral becoming us" is in and of technology. 

Agn: Tiny Mining exposes is not only that minerals are part of our
technological histories and future desires but they actually are these
technologies already, and they condition our lives in the most
intimate and crucial way by becoming us, or rather, by us becoming
mineral.

MOYN:

"produced by a planet"

we are contigent on and authored by the geological

a deep recognition, an acknowledgement of a shared, deep planetary
past and a responsibility for the future based on this contigency:

a "singular and shared origination", a tiny island



** cycles

... excavate, tunnel into, disturb and create new
non-anthropogenic and anthropogenic cycles of incorporation and
extraction, of radical consumption.

With the arrival of the questionable era of the anthropocene, marking
another entry point into the planetary geological, a new “natural”
cycle is initiated - we literally inhale and ingest our own
anthropogenic indicators (for example, as the particulate exhalations
of burning forests, as isotopes from nuclear testing, as metallic dust
from global extractions). These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms. Understanding this new nature for
humankind involves a close examination and potential embrace of a
“becoming geological”, becoming a-human.

illustrated by for example, the extraction of native copper ores from
the earth, their refinement and use in underground cables, carrying
human bound screen signals decoded, their later un-earthing and
recovery, a smelting operation releasing particulate copper and other
matters which is then inhaled or ingested, entering active and passive
species including humans. 

inhale mercury fumes from crematorium stacks - mercury is extracted by
heat? from its ore cinnabar - these do not decay, remain in the grounds - link here to decay

Our death will see a return to the geological, as particulate
matter (mercury  stacks crematorium bit). decay


remediation as recursion

technology is extracted from the environment or landscape at the same
time as being an extension into that landscape, reaching into and
equally providing a means of representation of that exhausted
landscape; the anthopocene is depicted using the very materials of its becoming

these double movements - we extract in order to extend into, to
blanket and logicise

Environmental concerns are no longer out there, in a controlled and
surveyed landscape of "nature"; to be protected. The dread-ful
"anthropocene" is now an internal story written within interior
geologies and in the deep time of ingestion and digestion. Saving the
planet is now a matter of looking into ourselves.

The focus of the project is on the transitional interior and inferior
geologies of media and communications. The notion of interior geology
refers also to the circulatory system of an earth addiction
encompassing extraction (of precious metals, of radioactive minerals),
transport/circulation and consumption (the ingestion of earth-derived
energies, materialities and earth-bound pharmaceutical products) and
return or excretion (traces of isotopes and pollution elements in the
body).

Matter, like media are both purposefully ingested and accidentally
absorbed, forming new internal, circulatory and transitional
geologies.

All bodies inhale and ingest anthropogenic indicators,
particulate exhalations of burning forests, isotopes from nuclear
testing, metallic dust from global extractions. Marder ... that this
embedding, makes of our decay, that which was historically more of a
becoming earth, into this strange twin of the becoming geological and
the anti-geological, between an articulation of the earth and heavens
or cosmos and a dis-articulation.

Decay or becoming earth opens this necessarily black hole of the
geo-logic, swallowing and eating itself, so lively.

how these cycles provide an entry into decay

** sweatshop

a new form of mining prospect, a list of deposits or resources ripe
for low cost exploitation, produced by the German company Medivere,
during our first Tiny Mining collective sweatshop.

A prospectus, which as such is useful in determining which portion of
a mineral can be considered as an exploitable ore reserve.

The symptoms of a muddy embrace of the becoming geological were
explored and exacerbated in the first of a series of sweatshops.

These include:

SWEATSHOPS:

An attention to the moon and planetary phases and orbits - the cycle
of extraction begins with the new moon and lasts one lunar month. The
first sweatshop commenced with the new moon, following a cycle of
ingestion (a diet rich in the specific metal assigned to the sweatshop
participant), followed by chelation (the use of medicinal plants and
pharmaceuticals to bring metals out of tissues), and extraction or
purgation.

An examination of co-relation between diet, dreams and
reveries. Participants reflected on bodily impressions, feeling,
thoughts and recorded all dreams during the sweatshop.

Hard scientific tests for the presence of heavy metals: colorific
tests on hair and urine, voltametric tests on urine.

Exploring one’s affinity with the various metals (such as antimony,
gold, silver, arsenic, lead, iron and mercury), their physical
properties, historical and mythical qualities and an awareness of the
connection of bodily routines and sentiments with these properties.

ingestion, chelation, testing and extraction following planetary and
elemental cycles


** plan

- what is becoming geo about - on the surface

- TM sweatshops/dreams

a new form of mining prospect, a list of deposits or resources ripe
for low cost exploitation, produced by the German company Medivere,
during our first Tiny Mining collective sweatshop.


- unconscious/descent

- a place gone mad

Places gone mad: about mines and places visited - the Abitibi-Témiscamingue gold-mining region of Quebec /// see also TEH

Quebec
erzgebirge - Anna Buchholz?
sillamae
jachymov
lava tubes
car interiors
TEH as crystalline mud
car interiors -> quebec, jachymov - what is materiality of that?


A crystalline, sparse clay mud of various sulphides, arsenic, lead and
iron, smears across an interior of Polypropylene (PP),
Acrylonitrile-butadiene-styrene (ABS), Styrene maleic anhydride (SMA),
Polyphenylene Ether (PPE), and Polycarbonate (PC). 

same dashboard after lava tubes, one holder for uranium glass, the
other for a chunk of raw uranium ore. we can break it, being careful
not to inhale any particles...


Becoming geological has its deep roots of ore genesis in the
experience of vermilion cyanide pools  ... of
... , and finally in the little mine which I am.

places gone mad - Marder ->

These multiple sites slowly become our insides. And in the first of a
series of strange loops or registers of the becoming geological, these
places externalise our selves.


- being a landscape, a mine and finally a planet // planets become metals. connective threads, filaments between the earth and the cosmos, we are made of these threads.

- sentience of a place, becoming sentient and also in reverse... usher in reverse

/// inferior/interior astronomy. inverted astrology

Inferior astronomy is another way of naming transformative methods for
working with plants and with metals. Astronomical discourses are
re-interpreted as referring to the terrestrial; planets become
metals. It’s an historic analogy, a set of identities or
transformations which help to make sense of certain early texts
treating the planets in mineral and muddy terms and as, at odds with
the celestial, undergoing earthy and earthly process.
 
Inferior geology seeks to further these transmutations, resting
equally on a magical closeness to the key phrase of “interior
geology.” If inferior astronomy brings the planets down to earth,
within the primacy of substitution which is called occult and is
recognised as such (this spiritual work with matter was always already
astronomy, inferior astronomy just marks that connection within the
realm of metaphor), then what substitution is being pointed at as
already having happened in thinking the geological as always inferior?
That it is rendered earthy? That it becomes of bodies and of
circulations without reference to marked, measured and seriously
differing time scales?

immersion and contact in the earth - describe arsenic and cyanide muds
caking clothes, skin and car interior, paranoia about what could be
described as EXPOSURE

from the earth considered as something exterior, that which is acted
upon by humans, a laboratory planet - to the earth and geology as
something incorporeal, incorporated and interior

idea of interior or internal geology, a fantastic voyage from
*inferior geology*, the underneath, vast dripping caves and mines
supplying energy for the server farms above ground to interior geology
(informed by the discipline of medical geology).

[note: In the concentric circles of his “lower Astronomy,” this
diagram Ripley provided a terrestrial analogue for the planetary
spheres: encoding his alchemical ingredients as planets that orbited
the earthly elements at the core of the work.]

*bringing the planets down to earth as metals ripe for extraction*



* Becoming Geologucal: Mining dreams?

or is this for sweatshop intro!

Yes, reader, countless are the mysterious hand-writings of grief or
joy which have inscribed themselves successively upon the palimpsest
of your brain; and, like the annual leaves of aboriginal forests, or
the un-dissolving snows on the Himalaya, or light falling upon light,
the endless strata have covered up each other in forgetfulness.
[Thomas de Quincey. The Palimpsest of the Human Brain]

** intro sweatshops

In November 2020, a small group of artists, chemists and geologists,
made a first attempt to collectively mine certain minerals (list) from
within their own bodies. These actions brought forth monstrous
visions. What should have remained hidden (the secret life and genesis
of metals for each individual) was exposed to their light and
unearthed.

** dreams

*** dream/s of TM: 

1. the blue light. sweatshop dreams. // TM // mining - toad/earth - Becoming metals -  becoming as antimony, as arsenic, as copper, as iron, as lead, as mercury, as silver, // becoming earth

1. TM dreams. colours of burning metals - tests

We have to go much further, much further back! And faster.


// copper/Dennis

*Heavy crystal sediments near the top.*

Last night I had a dream of playing a computer game. A glitch enabled
me to physically travel through dimensions. I ended up in the atelier
of a friend housed atop of a well known hamburger restaurant, which
doubled as a ‘hidden in plain sight’ security check, preventing random
people from going upstairs. In the atelier floated a sphere,
resembling the cryogenic containment unit from Akira, cables coming
out everywhere. It had a brown copper hue to it, but that could also
have been isolation material or even wood. How did it float?  This
‘device’ allowed you to trigger ‘lucid déjà vu’ allowing you to relive
memories as you wanted. Realising I was already in another dimension,
I did not want to go further. We all left to go to a club. Exiting the
restaurant someone had parked a trailer under the trees. My attention
was drawn to the shiny assortment of shapes faintly visible through
reflection of the faint moonlight penetrating the canopy. Upon
inspection the trailer was full of alumiium extrusions in every shape
and size you can imagine. Every piece was unique, except for their
perfect shiny, brushed finish.

// lead/martin

In the first I’m pissing into a toilet and each stream is accompanied by an intense blue
light – like a gas light, and maybe even the smell of gas as if there could be an explosion. This
could relate to the use of flame spectroscopy to analyze heavy metals in organic matters (such
as hair). The blue would correspond to the colour of a certain metal – such as lead itself or
arsenic.

In the second fragment we go past a kiosk (in Cologne) with two fresh fish stalls nearby,
run by Vietnamese people. Outside one of these stalls there are two older men, scruffily
dressed and with red, bruised faces, looking a bit like old English standup comedians. They
are there to entice people to come and see/buy the fish. At first they hold up the fish but
later they bite pieces of fish and then spit them out, catching them and spreading them on
their faces, to make a new face. 

They lay blue pieces over their eyebrows and other features, making
their faces more bruised and blue looking. This relates to the seafood
diet for the first three days of the sweatshop. Again a metallic,
bruisy blue colour.


*** dream of Iceland turf house - bog bodies, representation, being covered in earth. buried in handfuls of peat warmed by geothermal waters collected right next to the tarmac

turf house as a car dashboard

2. Iceland turf house - bog bodies, representation, being covered in earth. buried in handfuls of peat warmed by geothermal waters collected right next to the tarmac


2. the turf house, the front and back of the house, grave, entry and exit. off-world // theory theory - wings eagle // becoming cosmic - origins. *leaving the planet*

//iceland notes

turf house as a /relation?/ VEHICLE for becoming geological. house of earth and volcanic stones/lava

traditional - the front of the house, wooden gable, girls greeting tourists (bus engine left running) in threadbare costumes from a hundred years ago, ghost photographs

from the front windows, low wooden desk looks out on graveyard, on the church, the mound of earth covering the farmer's body

behind the house - the earth, new habits, new language (also behind Wolf Vostell sculpture, and recent dream with icon/crucifix/jesus... 

last house - the life support system of pipes, air conditioning, the last breath... (Teemu)

turf house as a grave

- conversations with Judith: Surtsey, subsurface bacteria
  there. portals, also geology which is neither living nor dead -
  outside these categories... nodes of life and death, outside these
  terms

*patricia also mentions leaving earth behind...where?*

between geology and biology, neither nor

iceland spar man - geological cheese (peter) - ref. bacteria for icelandic porcelain. spar/binary of calcite, polarisation of light

iceland as mostly geologically young...

golden circle. shit circle (Salo)

antii subsurface glitches... orbital turf house...

Lying on my back, the turf of the house walls feels cold against damp
skin. I am slowly buried in dense and muddy peat, heated by the
geothermal waters collected right next to the tarmac, mixed by
hands. My face is the last to be covered, I feel the heat of the sun,
the red glow behind closed fluttering eye lids. By looking inside, I
see outwards. By looking outwards, I see inside.


*** dream of Jachymov - that this could be the body as a landscape. entering the mine/body - that which is kept hidden

But the presence of so many soldiers and military vehicles, and the
wan-faced townsfolk evacuating their homes, ensured that the little
enclave of the transfigured forest – by comparison the remainder of
the Everglades basin seemed a drab accumulation of peat, muck and
marls – would soon be obliterated, the crystal trees dismembered and
carried away to a hundred antiseptic laboratories.
 
J.G. Ballard, 'The Illuminated Man', in The Terminal Beach, London: Phoenix, (1964) 1992, p.81

The minerals on the other hand she buries far beneath in the depth of
the ground; therefore, they should not be sought. But they are dug out
by wicked men who, as the poets say, are the products of the Iron
Age.

Georgius Agricola, De Re Metallica, 1556, Book I,(Trans. H & L Hoover), New York: Dover, 1950, p. 6-7.


[3. of the re-presentation of the bog bodies in the museum. the gold around the bezoar. margarita of austria's room // art art - snake // becoming mineral? becoming earth - re-presentation]notsomuch

world as will and representation. how are these global changes present
for us, how does becoming geological come to be represented as a
vision, as a mind, as an image or set of images, as a representation "for" who...

how is extraction and the extractive landscape re-presented ? modes of presentation of the geologic body


3. jachymov - uranium cross. immortality, the afterlife of Elaine/Arthur

as a dream and include the vomiting dogs

In the third dream a priest, all grey with frozen dew, leads us from
his house which is crammed with artefacts from a burnt-out church,
crispated altar paintings, into his garden. Chickens, uncooped, run
wildly at our feet. The priest is tall, with long matted wet hair, and
a long white beard, crinkled and smally curled. He opens a stout metal
gate set into the knolled hillside one corner of the garden, inside
the chicken enclosure, and leads us deep into the narrow mine
shaft. As a giant leads a troupe of dwarfs, leading us deeper with
only the light from one phone into the coffin shapped irregularity of
the hewn walls.

Outside the cave, the geologist in stout boots, tells us that the main
ore vein is cursed, that the evil in the town comes from this vein, he
translates its name as drift or drifting. It is always moving. He says
that people who live in this sort of disorder, a sort of moral and
physical mine, they spread it around them like an infectious disease.


His dog vomits silver coins and terse liquid on his boots. 

brought it up again, the morning


drunken tanners dogs


** body as landscape

where does this lead, this body as a mine, as a resources, as a metal,
copper body, man of copper, what are the consequences of these actions
for thought, for being what we are when we say what it is to be human,
or what comes before this saying (patricia), for the world - the
dystopia of tiny mining, final frontier -> visions of zosimos -
natural way of doing things

that a body can now be any landscape, a body as a site of tailings, as
a suburb, as a logistics centre on the outskirts of a small town,
between motorways, as a overgrown heap of rubbish grazed now by sheep,
a new mountain amidst the dykes and drainage canals 

a body as landscape, depicted, scanned and stretched, re-skinned, 

bog body is a landscape

if the body can become a mine, a prospect with associated legal
frameworks and permissions, with its waste piles and tailings, its
slag heaps, its .... to be inhaled, incorporated....

body as jachymov - that history, 

geology is the biography or history of a body, drunken tanners dogs vomitting (reference?)

becoming geo means to become a resource, a reserve, to take on and
into one's own body and self that which is enacted on a landscape, to
provide the technological gems and accoutrrements, the extensions of
that body, to become literally that body

becoming geo is to start with this cosmic island

Seismic upheavals in the mind disrupt the cosmic island.

** places/place gone mad

mining sites - but also above

gold fibres dissolved in the lake are set to colour it blood-red as a sunset

AMD acid mine drainage

container subjecting itself to a descriptive dissolution, to the recursive effects of its own signs

hardware dissolves itself as a function or extent of its own functions, as a necessity. it is and is not a palimpsest


** for image/text collages

*** 0 TM related

They are called *little miners*, because of their dwarfish stature,
which is about two feet. They are venerable looking and are clothed
like miners in a filleted garment with a leather apron about their
loins. This kind does not often trouble the miners, but they idle
about in the shafts and tunnels and really do nothing, although they
pretend to be busy in all kinds of labour, sometimes digging ore, and
sometimes putting into buckets that which has been dug. [...] The
mining gnomes are especially active in the workings where metal has
already been found, or where there are hopes of discovering it,
because of which they do not discourage the miners, but on the
contrary stimulate them and cause them to labour more vigorously.
[de re metallica trans hoover etc.]

*** 1

No more fruit, no more trees, no more vegetables, no more plants pharmaceutical or otherwise
and consequently no more food, but synthetic products to satiety, amid the fumes, amid the
special humors of the atmosphere, on the particular axes of atmospheres wrenched violently and
synthetically from the resistances of a nature which has known nothing of war except fear.
[Antonin Artaud. To have done with the Judgement of God.]

*** 2

This opinion, in its general form, was that of the sentience of all
vegetable things. But, in his disordered fancy, the idea had assumed a
more daring character, and trespassed, under certain conditions, upon
the kingdom of inorganization. I lack words to express the full
extent, or the earnest abandon of his persuasion. The belief, however,
was connected (as I have previously hinted) with the gray stones of
the home of his forefathers. 

The conditions of the sentience had been here, he imagined, fulfilled
in the method of collocation of these stones – in the order of their
arrangement, as well as in that of the many fungi which overspread
them, and of the decayed trees which stood around – above all, in the
long undisturbed endurance of this arrangement, and in its
reduplication in the still waters of the tarn.

Its evidence –the evidence of the sentience – was to be seen, he said,
(and I here started as he spoke,) in the gradual yet certain
condensation of an atmosphere of their own about the waters and the
walls. The result was discoverable, he added, in that silent, yet
importunate and terrible influence which for centuries had moulded the
destinies of his family, and which made him what I now saw him – what
he was.  
[Edgar Allen Poe. The Fall of the House of Usher]

*** 3

“Our art rather requires us to familiarize ourselves closely with the
earth; it is almost as though a subterranean fire drives the miner
on.” The hermit replies, “You are almost inverted
astrologers. Astrologers observe the heavens and their immeasurable
spaces; you turn your gaze toward the ground and explore its
construction. They study the power and influence of the stars, and you
examine the powers of the rocks and mountains and the many and diverse actions of soil and
rock strata. For astrologers the heavens are the book of the future, whereas the
earth shows you monuments of the primeval world.”22->

22. Novalis 1802/1987, p. 86f. Novalis. Heinrich von Ofterdingen: Ein nachgelassener Roman. Berlin: Buchhandlung der
Realschule, 1802. Reprint, Stuttgart: Reclam, 1987. trans???
Zielinski? he also talks about kirchner and inverted astronomy in deep
time book

*** 4

The porous rock towers of Tenerife exposed the first spinal landscape
[...] clinker-like rock towers suspended above the silent swamp. In
the mirror of this swamp there are no reflections. Time makes no
concessions.
[Ballard. atrocity]

*** 5

Furthermore, if we consider the plane of consistency we note that
the most disparate of things and signs move upon it: a semiotic
fragment rubs shoulders with a chemical interaction, an electron
crashes into a language, a black hole captures a genetic message, a
crystalli- zation produces a passion, the wasp and the orchid cross a
letter... There is no "like" here, we are not saying "like an
electron," "like an interaction," etc. The plane of consistency is the
abolition of all metaphor; all that con- sists is Real. These are
electrons in person, veritable black holes, actual organites,
authentic sign sequences. It's just that they have been uprooted from
their strata, destratified, decoded, deterritorialized, and that is
what makes their proximity and interpenetration in the plane of
consistency possible p69


** pull from intromhedit

*** unconscious

Geology is an unconscious (not our unconscious - subtexts/mackay,
moynihan-spinal). Countering and contrary to contemporary opinion
ranging the history of science, the alchemists did probe these
material depths. The bog bodies are dreams and visions, which is why
the museums (Drent,etc) insist on their repeated re-presention - the
literal return of the repressed in a very real sense (the alien, the
pagan, the nomad, black death, the odd symettry of El Majusi - geomancy).  

We can begin our descent, We have to go much further, much further back! And faster.

That this descent is also a retrogression in time. As Moynihan writes
in Spinal Catastrophism (an essential complement to the essay here), a
geognostic work which is precisely concerned with this internal depth
as geotrauma, "depth is time." 

"Steno was the first to note explicitly that stratigraphic succession
corresponds with temporal succession. In other words, that /depth is
time/. (Hence, centuries later, McPhee's coinage of '*deep
time*'). This marked the inception of the notion of /depth as mnemonic
and temporal retrogression/ that would later be so vital to
psychoanalysis or so-called 'depth psychology' (Tiefenpsychologie).

[p86]

The Tiny Miner coils inwardly on her own inward mined depths. 


*** going deeper - descent // from dreams to descent to being a landscape to the sentience of a place (reverse Poe Usher) 

see parts of intromhedit

If the descent into the mine, into the earth, a hole to hell, is
viewed as a journey towards a dark interior, into the unconscious,
into dreams, or inside that old fossil, the profound soul, then what
does it mean when that interior is mine, a fantastic voyage, with me
or by myself. Ouroboros-like I double back on my own interior, but to
one side, an interior which is not mine, strangely, An oozing and
lacking dream inside a dream. We are doubled but not as a human of
light and of darkness. We are both shades. // shades as a
material. phos/Zosimos... leads into the vision - man of light



Historically speaking, I contain my outside. This is what time does to
a body, as we shall see in tracing out this Secret History. The lesson
is clear: psychosomatic containment of oneself, when percolated
through Grandest History, equals hypogene alienation—the alienation of
a body riddled with time. It is this realisation that is inaugural of
the phylogenetic phantasy that is Spinal Catastrophism.

p50,51


*** towards matter - finale that is the jachymov dream! where do we even write of that?

conclusion: *are words and images enough (question in jachymov), quest
for a materiality - tears of Anais which become an image* -> the plane
of consistency. the dream of jachymov


** fragments

invitation:

After taking Argotine, if your face and body itch as though insects
were crawling over them, if your hands and feet swell, if you cannot
stand the smell of food and vomit it up after you have eaten it, if
you feel as if you were going to be sick most of the time, if you
experience weakness in your arms and legs, if you have to go often to
the toilet, or if your head or stomach violently ache - do not be
alarmed or disturbed. All these effects are merely proof that the
Argotine you are taking is successfully mining your insides.

*We become bio-markers, indicators of earthly or planetary health.* 

We begin to realise that all geology is geophagy (consumption of
earthy substances).  The alchemists would say that nature loves to
hide, we say that nature loves to eat.

*Those who effect their liberation during the light of day become
immortals of the higher category, those who do so at night join the company of the lower.*

The Chu Hsien Lu says "When the appearance is like that of a living
person - that is (proof of) shih chieh. When the feet have not turned
bluish in colour, and the skin not shrunk - that is shih chieh. When
the light in the eyes has not gone dull, and looks like that of a
person still alive - that again (shows) shih chieh. There are also
those who have become alive once more after being dead; and some whose
bodies have disappeared altogether before being encoffined; and others
who have ascended, leaving only their hair behind - all these things
are called shih chieh. 

The arsenic eaters prevailed over poison by surrendering to it,
overcame death by submitting to it. When graves were exhumed in order
to create new burial plots, it was found that the bodies of the
arsenic eaters had hardly decayed ...
xxix

the death which enters as a miasmic or vaporous and mineral breath into the living.

"all space and body is itself nothing but coagulated time" 87 moyn

Geology is the study and enabling of articulations, formations,
ingestions of inhalations of particulate matter, uranium-235,
conduits, fracking, descents, carbon dating, deep time, metals, the
cut, bedrocks, cavities, caves, chasms, tailings, leachings,
radiometric dating, orogenesis, dumps, lithologies, stratigraphies,
mineral resources, extractions, boundaries, outcrops, chronologies,
leachates, sulphides, percolations

Spinal: p220 ****

Oken noted that the ‘[e]arthly organs must correspond to animal
organs’: or, the ‘mountains, rocky terrain, [and] cliffs’ must find
their analogues in our own innards. If teeth are nails, then nails are
just stalactites. ‘Just as the animal body is finally composed of
these organs, so the composition of rocky terrain must produce a
terrestrial body, which is the planet’, Oken pronounced.13 

From Ritter to Kielmeyer, Schubert to Steffens, the Naturphilosophen
were in agreement on this: ‘[i]norganic matters and activities pass
parallel [to] the anatomical formations and functions’, as Oken put
it.14 He went so far as to say that ‘[o]rganism is what individual
planet is’ (because the ‘primary vesicle’ of the embryo, in its
globular form, is but a repetition of the forces that ‘produce’ the
planet itself).15 Steffens summed all this up adequately when he wrote
that, given these principles, every animal, plant, crystal, and
mineral represents a ‘stage of [terrestrial] development’: the
totality of which, taken together as one goliath constellation, would
thus provide the ‘true history of earth’.16 

In a geological stratum, for example, the first articulation is the
process of "sedimentation," which deposits units of cyclic sediment
according to a statistical order: flysch, with its succession of
sandstone and schist. The second articulation is the "fold- ing" that
sets up a stable functional structure and effects the passage from
sediment to sedimentary rock. 41.

"veins and threads of shining and dull connective strata that will allow us to leave the earth behind" patr

turf house: the earth inside which we dwell, and "the human geostrata
of Earth mode of use value and exploitation, the Earth for the human


singular thread or filament

becoming-multi-plateaued nourishment for the earth and dying as part
of new strata forming, fuelling unthinkable futures beyond (and even
without) Anthropos. /patr

"becoming colloidal"

a p-articulate refining of gelogy and the anti-geological


