* structure // 6 pages - 6x400=2400 words 7 or 8 pages with images // 

Becoming geological is ...

or series of scenes - bog body, turf house rite etc.

Geology and its doubles...

not binaries, but unity of above and below - their rending (Marder)
... Filth: 

As above, so below: loving are the astral bodies that hold court over
the repose of our tortured flesh.

as above so below. emerald tablet Arabic:[22] إن الأعلى من الأسفل والأسفل من الأعلى

the other world of dreams, of the arsenic eaters and their Faustian
pact with geology, of the gnomes (also in arsenic)

It should come as no suprise to bear witness to all these doubles
summoned by a descent into both interior and
exterior mines and shafts, into the geological, birthed as our origin
from celestial energies, dust and vapours. Perhaps the geological
implies the very figure of the double, against the day, the figure of
reason and the unconscious. what of the rending?

also transition from the feedback loop of:

With the arrival of the questionable era of the anthropocene, marking
another entry point into the planetary geological, a new “natural”
cycle is initiated - we literally inhale and ingest our own
anthropogenic indicators (for example, as the particulate exhalations
of burning forests, as isotopes from nuclear testing, as metallic dust
from global extractions). These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms. Understanding this new nature for
humankind involves a close examination and potential embrace of a
“becoming geological”, becoming a-human.

towards the entry of decay - that our decay is more of a becoming
earth, but the entry of the anthrop makes our (non) decay and
techno-fossilisation more of a becoming geo - how to express this more cleanly?




what to call it - seperate intro. basic terms of what is about

then preface as in plant/marder...

notes: not so many statements... more narrative

BG is going much futher, much further back. And faster.

manifesto?

becoming metal: TM described as real, from POV of sweatshops
earth - decay, death and islands
comsic - breath and light

2 texts - one more of dreams also more for iceland people
one more theory

geology and the word - logos. key term of articulation

acephalic and geophagic feedback loops (nature loves to eat - do we ever explain
that? consuming itself)

geology and its double 1 2 3 though

** opening/intro

about mines and places visited - the Abitibi-Témiscamingue gold-mining region of Quebec /// see also TEH

Quebec
erzgebirge - Anna Buchholz?
sillamae
jachymov
lava tubes
car interiors
TEH as crystalline mud
car interiors -> quebec, jachymov - what is materiality of that?


A crystalline, sparse clay mud of various sulphides, arsenic, lead and
iron, smears across an interior of Polypropylene (PP),
Acrylonitrile-butadiene-styrene (ABS), Styrene maleic anhydride (SMA),
Polyphenylene Ether (PPE), and Polycarbonate (PC). 

same dashboard after lava tubes, one holder for uranium glass, the
other for a chunk of raw uranium ore. we can break it, being careful
not to inhale any particles...


Becoming geological has its deep roots of ore genesis in the
experience of vermilion cyanide pools  ... of
... , and finally in the little mine which I am.

places gone mad - Marder ->

The becoming geological of the soul in our era of the prevailing
disarticulation means not only that it becomes a cultural fossil of
sorts (a word, a concept, a thing that provokes a great deal of unease
and is replaced with mind even in certain English translations of
Aristotle’s psukhē or St. Augustine’s anima) but also that it is torn
apart, deranged, driven to the point of madness. In the same vein, a
place goes mad in a very literal sense, as I show in my readings of
works by Aldo Leopold and Gregory Bateson.ii The earth itself is out
of joint....

Like Plotinus before him and Gregory Bateson after him, Leopold considers
the locus of thinking to lie outside individual human beings, in the
interactive relation between the living and their environment.

poe quote

These multiple sites slowly become our insides. And in the first of a
series of strange loops or registers of the becoming geological, these
places externalise our selves.

inhalation etc. what is BG

But what do these veins offer up or uphold, in an eruption or failing,
sinking or sedimenting?

That we are always geological...

mineral vapours alchemy

from sonic acts bit: materials crystal world (mute)

immersion and contact in the earth - describe arsenic and cyanide muds
caking clothes, skin and car interior, paranoia about what could be
described as EXPOSURE

Humankind is and has always been geological; as both origin and
destiny, as inhaled and ingested matter, as medicine and willing
poison, as a divine or sublime power, or as adornment and
technological extension. We are forever involved in its cycles and its
(destiny?

what it is and how do we know enjoy, embrace, reject or unfurl through
this present or proposed (new) becoming - is this a becoming which we
have little choice but to be at drift within?

marder asks how in 21st century becoming geo... 2 clues ... becoming dump

becoming dust

what book does/sets out to do

- how we arrived here,,, by way of TM, body as a resource, cycles of ... awareness PITCH notes

mention sites and experiences of toxic mud - TEH/Montreal, Ezrgebirge, Simillae, volcanic tubes of various island formations where else? crystal world

I never imagined that becoming geological could become so
labyrinthine, so obscure, so buried in cyclings and feedback loops -
unending tunnels miring and undermining the sky and the mountainside,
in search always of different ores, everyday ores.

- what it is, why it is important - the geologic is our fixated,
  addictive and necessarily obscured or covered up logic
  (steganography, stratigraphy...) - our beginning and our end.

important - as origin, as conditioning us. as determining us, our living conditions, as our unconscious, to go backwards, as our depth and setting

as diet, as inhalation

cross-over a bit eg. cecilia in becoming metal // becoming as iron

** TM section. becoming as antimony, as arsenic, as copper, as iron, as lead, as mercury, as silver (Agn.)

dreams

matter of fact about the sweatshop

Agnieszka
Aaron
Ines - discipline of medical geology (expert meeting)

In her opening essay .... Agn. expertly ... Tiny Mining as a daily ...

how leads to BG. 

is BG active - a daily practice or is it something which we are always
within (what is that within, lodged between earth and cosmos,
decaying - elaine etc)... these are not mutually exclusive - to
exacerbate, react, embrace - to make a fiction of a situation we find
ourselves within...

 we can thus point to previosu such practices which had an obvious
influence on the Tiny Miners: withcraft, herbal ... and interaction
with cosmic forces, the work of alchemists such as Thomas Vaughan
fusing ..., inner and outer chinese alchemy (explain)...

We are always

** Theory section. becoming earth

- becoming/being a landscape, an island - or is that TM or lead in from/transition... latest bit

- depths - Marder also - heavens and earth

- decay/death/immortality - Elaine/Arthur

- origins - Thomas

- off planet - Patricia

** Artist section. becoming cosmic

in the gallery, in the museum, we are all bog bodies as intro

do we need to mention all artists?

sissel - bog
alfonso - body stones. magic
rosemary - lithium. questioning this external landscape
rosa - atmospherics and smell
anais - tears
cecilia - appendage/cast/iron becoming metal

- digital extension/post-humanism
- material/core

** conclusion/invitation to become geological ????

After taking Argotine, if your face and body itch as though insects
were crawling over them, if your hands and feet swell, if you cannot
stand the smell of food and vomit it up after you have eaten it, if
you feel as if you were going to be sick most of the time, if you
experience weakness in your arms and legs, if you have to go often to
the toilet, or if your head or stomach violently ache - do not be
alarmed or disturbed. All these effects are merely proof that the
Argotine you are taking is successfully mining your insides.

** other

conduit - elaine and arthur p.40

/Who/ of us should fear obsolescence, the /double/ bind being to
evolve or die? But is not the process of evolution itself - that is,
leaving behind one configuration and becoming another - always already
marked by death? Is one pollutant or catalyst? Is one contaminant. or
the contaminated? ... Can any single position be known to the One who
enters this raging theatre. No, no matter how diffuse, I sense the
others.

** becomings from agn

becoming resource

becoming as antimony, as arsenic, as copper, as iron, as lead, as
mercury, as silver

becoming with the cosmos, becoming cosmic

becoming (of the) earth

becoming contaminated

becoming (with) dirt

becoming mineral

finally geology becomes us. it is not a becoming for us, leading to
us, lead by us, not our holding forth of, our extracting of, our xxxx
of... (how better)

to which we can add becoming filth  becoming filthy - Elaine...

patricia:

becoming ethical Geo-stratum 

becoming-vulnerable, becoming-turbulent and becoming-multi-plateaued
nourishment for the earth and dying as part of new strata forming,
fuelling unthinkable futures beyond (and even without) Anthropos.

becoming stratum for the future - 

Becoming geological, becoming resource for unknown life is the ethical
future which foils the immoral Anthropos and interrogates the
genealogy of organic lives where we are one of many unlike and strange
Earth-fellows, not the only or the supreme life form.

 a willingness to becoming-strata for the Earth and of the soil

moyn:

becoming historical

filth:

becoming colloidal


