* Becoming Geologucal: Mining dreams?

or is this for sweatshop intro!

Yes, reader, countless are the mysterious hand-writings of grief or
joy which have inscribed themselves successively upon the palimpsest
of your brain; and, like the annual leaves of aboriginal forests, or
the un-dissolving snows on the Himalaya, or light falling upon light,
the endless strata have covered up each other in forgetfulness.
[Thomas de Quincey. The Palimpsest of the Human Brain]

** Sweatshop and dreams

*Heavy crystal sediments near the top.*

Last night I had a dream of playing a computer game. A glitch enabled
me to physically travel through dimensions. I ended up in the atelier
of a friend housed atop of a well known hamburger restaurant, which
doubled as a ‘hidden in plain sight’ security check, preventing random
people from going upstairs. In the atelier floated a sphere,
resembling the cryogenic containment unit from Akira, cables coming
out everywhere. It had a brown copper hue to it, but that could also
have been isolation material or even wood. How did it float?  This
‘device’ allowed you to trigger ‘lucid déjà vu’ allowing you to relive
memories as you wanted. Realising I was already in another dimension,
I did not want to go further. We all left to go to a club. Exiting the
restaurant someone had parked a trailer under the trees. My attention
was drawn to the shiny assortment of shapes faintly visible through
reflection of the faint moonlight penetrating the canopy. Upon
inspection the trailer was full of alumiium extrusions in every shape
and size you can imagine. Every piece was unique, except for their
perfect shiny, brushed finish.

// lead/martin

In the first I’m pissing into a toilet and each stream is accompanied by an intense blue
light – like a gas light, and maybe even the smell of gas as if there could be an explosion. This
could relate to the use of flame spectroscopy to analyze heavy metals in organic matters (such
as hair). The blue would correspond to the colour of a certain metal – such as lead itself or
arsenic.

In the second fragment we go past a kiosk (in Cologne) with two fresh fish stalls nearby,
run by Vietnamese people. Outside one of these stalls there are two older men, scruffily
dressed and with red, bruised faces, looking a bit like old English standup comedians. They
are there to entice people to come and see/buy the fish. At first they hold up the fish but
later they bite pieces of fish and then spit them out, catching them and spreading them on
their faces, to make a new face. 

They lay blue pieces over their eyebrows and other features, making
their faces more bruised and blue looking. This relates to the seafood
diet for the first three days of the sweatshop. Again a metallic,
bruisy blue colour.

*** intro sweatshops

In November 2020, a small group of artists, chemists and geologists,
made a first attempt to collectively mine certain minerals (list) from
within their own bodies. These actions brought forth monstrous
visions. What should have remained hidden (the secret life and genesis
of metals for each individual) was exposed to their light and
unearthed.


** for image/text collages

*** 1

No more fruit, no more trees, no more vegetables, no more plants pharmaceutical or otherwise
and consequently no more food, but synthetic products to satiety, amid the fumes, amid the
special humors of the atmosphere, on the particular axes of atmospheres wrenched violently and
synthetically from the resistances of a nature which has known nothing of war except fear.
[Antonin Artaud. To have done with the Judgement of God.]

*** 2

This opinion, in its general form, was that of the sentience of all
vegetable things. But, in his disordered fancy, the idea had assumed a
more daring character, and trespassed, under certain conditions, upon
the kingdom of inorganization. I lack words to express the full
extent, or the earnest abandon of his persuasion. The belief, however,
was connected (as I have previously hinted) with the gray stones of
the home of his forefathers. 

The conditions of the sentience had been here, he imagined, fulfilled
in the method of collocation of these stones – in the order of their
arrangement, as well as in that of the many fungi which overspread
them, and of the decayed trees which stood around – above all, in the
long undisturbed endurance of this arrangement, and in its
reduplication in the still waters of the tarn.

Its evidence –the evidence of the sentience – was to be seen, he said,
(and I here started as he spoke,) in the gradual yet certain
condensation of an atmosphere of their own about the waters and the
walls. The result was discoverable, he added, in that silent, yet
importunate and terrible influence which for centuries had moulded the
destinies of his family, and which made him what I now saw him – what
he was.  
[Edgar Allen Poe. The Fall of the House of Usher]

*** 3

“Our art rather requires us to familiarize ourselves closely with the
earth; it is almost as though a subterranean fire drives the miner
on.” The hermit replies, “You are almost inverted
astrologers. Astrologers observe the heavens and their immeasurable
spaces; you turn your gaze toward the ground and explore its
construction. They study the power and influence of the stars, and you
examine the powers of the rocks and mountains and the many and diverse actions of soil and
rock strata. For astrologers the heavens are the book of the future, whereas the
earth shows you monuments of the primeval world.”22->

22. Novalis 1802/1987, p. 86f. Novalis. Heinrich von Ofterdingen: Ein nachgelassener Roman. Berlin: Buchhandlung der
Realschule, 1802. Reprint, Stuttgart: Reclam, 1987. trans???
Zielinski? he also talks about kirchner and inverted astronomy in deep
time book


** pull form intromhedit

*** unconscious

Geology is an unconscious (not our unconscious - subtexts/mackay,
moynihan-spinal). Countering and contrary to contemporary opinion
ranging the history of science, the alchemists did probe these
material depths. The bog bodies are dreams and visions, which is why
the museums (Drent,etc) insist on their repeated re-presention - the
literal return of the repressed in a very real sense (the alien, the
pagan, the nomad, black death, the odd symettry of El Majusi - geomancy).  

We have to go much further, much further back! And faster.

*** going deeper - descent // from dreams to descent to being a landscape to the sentience of a place (reverse Poe Usher) 

see parts of intromhedit

If the descent into the mine, into the earth, a hole to hell, is
viewed as a journey towards a dark interior, into the unconscious,
into dreams, or inside that old fossil, the profound soul, then what
does it mean when that interior is mine, a fantastic voyage, with me
or by myself. Ouroboros-like I double back on my own interior, but to
one side, an interior which is not mine, strangely, An oozing and
lacking dream inside a dream. We are doubled but not as a human of
light and of darkness. We are both shades. // shades as a
material. phos/Zosimos... leads into the vision - man of light

Historically speaking, I contain my
outside. This is what time does to a body, as we shall see in tracing
out this Secret History. The lesson is clear: psychosomatic
containment of oneself, when percolated through Grandest History,
equals hypogene alienation—the alienation of a body riddled with
time. It is this realisation that is inaugural of the phylogenetic
phantasy that is Spinal Catastrophism.

p50,51
