* Becoming Geological: mining dreams // 

** authors/artists notes/quotes

link of decay

what is woven in the geological, a lie, a word, a dressed up mineral
shop for souls, for puppets, end of the world, mined like a sewer.

*** Patricia

a future without humans

becoming strata - first articulation and second articulation - 

Not only do strata come at least in pairs, but in a different way
each stratum is double (it itself has several layers). Each stratum
exhibits phenomena constitutive of double articulation. // 40: Geology of morals

In a geological stratum, for example, the first articulation is the
process of "sedimentation," which deposits units of cyclic sediment
according to a statistical order: flysch, with its succession of
sandstone and schist. The second articulation is the "fold- ing" that
sets up a stable functional structure and effects the passage from
sediment to sedimentary rock. 41.

we literally become geological, as a lost strata

leaving earth behind

opens on another articulation

strata->patricia...  we are not bodies, human and nonhuman, who occupy
the world, we are strata, connected within and between

The key to becoming-geological is the stickiness of the substance we
become. Irigaray speaks of the mucous which connects vulvic lips, the
lips of speech, the flesh of words with the sexuate politics of
angels.

ethics - 

... the chimeric materiality of our thought (knowledge without
metaphysical hubris) is within the substance of our body, the body
which is already embodied by many bodies. Within an ethics of
connectivity, our bodies are, according to Spinoza, our means of
ethical interaction through infinite connectivity, which does not
divide mind from body but does not exhaustively know either, in
perception or affect. Our task, our question, to becoming-geological,
is how do we connect with unlike substances?

again doubles - two earths:

It is as if two Earths overlay their strata. The one is the Earth as
it is, a dying modality of individual emergences and diminishments
which humans accelerate, the Earth where the human abides. The second
is the human geostrata of Earth made of use value and exploitation,
the Earth for the human.


ON TM:

Imagining futures where humans are resource, where we can be mined and
utilised as part of the many strata of the Earth is a vitalistic
understanding of extinction. 

Becoming-geological involves a rethinking and a celebration of the
materiality of the one certainty which our lives have but which we
continue to repudiate – Death.

ending:

the human’s adventure in becoming-geological will be part of the veins
and threads of shining and dull connective strata that will allow us
to leave the Earth behind, not in a phallic spaceship, but within the
soil and the stomachs of the other plateaux we have hitherto so
violently exploited.

*** Marder

geology and its doubles - calcite, iceland spar, surtsey

passionate/particulate articulations

Marder in .... defines two modes of the contemporary becoming
geological which are pitted against each other. He specifies these as
the ancient and ever present gradual decomposition of all bodies,
becoming earth, and the encrustation of the "byproducts of industrial
technobodies" both in geological strata, and equally in all living
bodies; these latter are the familiar and dreadful terms, marks and
shifting registers of the anthropocene.

The are the two incompatible modes of the becoming geological, geology
and its double - an articulation and a dis-articulation of the earth,
and indeed, of the very terms of geology's meaning, a p-articulate
refining of gelogy and the anti-geological. that the doubling is
always there to question itself, in this feedback loop.

Yet we can see that one mode is materially embedded within the other,
it is inside. All bodies inhale and ingest anthropogenic indicators,
particulate exhalations of burning forests, isotopes from nuclear
testing, metallic dust from global extractions. Marder ... that this
embedding, makes of our decay, that which was historically more of a
becoming earth, into this strange twin of the becoming geological and
the anti-geological, between an articulation of the earth and heavens
or cosmos and a dis-articulation.

Decay or becoming earth opens this necessarily black hole of the
geo-logic, swallowing and eating itself, so lively.

patricia - becoming-strata for the Earth and [of] the soil!

2 strata of becoming geo: God is a Lobster, or a double pincer, a
double bind - to have done with the judgement or geo-logic of god?

Marder: the anti-becoming of anthropogenic debris is both geological and
anti-geological, since, in its being added to the planetary strata, in
its articulation with other layers of the earth, it disarticulates the
earth both internally, with respect to itself, and externally, for
example, with regard to the atmosphere and the oceans.

[older:
also transition from the feedback loop of:

With the arrival of the questionable era of the anthropocene, marking
another entry point into the planetary geological, a new “natural”
cycle is initiated - we literally inhale and ingest our own
anthropogenic indicators (for example, as the particulate exhalations
of burning forests, as isotopes from nuclear testing, as metallic dust
from global extractions). These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms. Understanding this new nature for
humankind involves a close examination and potential embrace of a
“becoming geological”, becoming a-human.

towards the entry of decay - that our decay is more of a becoming
earth, but the entry of the anthrop makes our (non) decay and
techno-fossilisation more of a becoming geo - how to express this more cleanly?
]

also opening of a place gone mad

acephalic

*inside itself*

facing of heaven and earth, cutting in two:

In Meso-American traditions, particularly in Aztec cosmologies,
Tlaltecuhtli is a giant creature, who swam in cosmic waters until the
serpent god Quetzalcoatl and his brother, the smoking mirror god
Tezcatlipoca, “cut Tlaltecuhtli in two. The lower half became the
heavens and stars, and the upper half became the earth.”

elaine - As above, so below: loving are the astral bodies that hold court over
the repose of our tortured flesh.

as above so below. emerald tablet Arabic:[22] إن الأعلى من الأسفل والأسفل من الأعلى

rending of this god, unity that never existed, pre-existed - the
singular thread or filament of Thomas M - 

The delirious and not-so-filthy protaganist Elaine ... equally situates this
primordial rending which is within and is the double heart of the BG:

But in and among these I discovered one interpretation, which held for
me especially convincing, for how sensibly it conferred with our
to-date scientific speculations about the budding youth of the
universe – of a compact, energetic singularity from which all life
would unfurl.

*** Thomas

ethics of becoming geo

becoming geo is to ask "what it means to have been produced by a planet"

origins and future. key term of contingency

what is it to become geological - the deep recognition that have
become historical, that we are contigent on and authored by the
geological

a deep recognition, an acknowledgement of a shared, deep planetary
past and a responsibility for the future based on this contigency:

the longer the past precedent evidently required to produce any
entity, the deeper the grooves its present loss projects upon the
future, such that illumining the roots of one’s history is essential
to putting into relief the fragility of one’s future

It is "to acknowledge that the planet produced us, in the profounder, explanatory sense of having authored us."

a "singular and shared origination", a tiny island

Dependence on descent ties life to its place of birth, for obvious reasons. 

Here, then, is another way of becoming geological: not only to be
authored geologically, but to geologically author. - that this
authorship can be malign.

*** Filth

becoming pig

god and anthropos - link to patricia

that we still have not done with the judgement of god or anthropos,
all these dusty icons, this is key to a "new" becoming/ontogenesis of
the becoming geo - to have done with it finally as our origin and
destiny

god as oneness, god as anthropos - we never had a god, we were always geological

islands of decay, islands of new _____bacteria?

dreamy delire... nightly stupor, lashes beating like the wings fo flies.

times and philosphers past and now doubles:

The double movement of Filth is both the time of the past (the deep
time of creationist myth and memories of a more recent past), and the
questionable time of the present, where she is in a presumed state of
reflexive convalescence, alluded to by intermittent mentions of a
therapist.


they offer their own articulation and disarticulation. the remains of
rotting are the interpretation, the introduction

natural and the otherworldly

differentiate what is wretched from what is only dead

islands: The weepy leakage that ends the ‘bloated’ phase floods the
earth with nutrients, which conjure discrete islands of especially
fertile ground dotted around the corpse. Successive tides of cadaveric
fluids and bio-active substances has the once-patchy archipelago
joined up into verdant halo, and this is what Payne identified as the
‘cadaveric decomposition island’

// own raven island of putrefaction before the grass was mown.

Each cadaver acts as a specialised habitat for a particular suite of
organisms; the decomposition islands that issues from them are a
natural interference that can dramatically alter geology and
biodiversity on the surficial landscape for up to several decades. The
process of decomposition connects above- and below-ground communities,
representing vital pathways of carbon and nutrients in terrestrial
ecosystems. The heterogeneous distribution of cadaveric material in
soil facilitates niche provisions and, in each case, instantiates its
own special biodiversity – this cascade effect part of a cycle of
disturbance and recovery that has enriched ecosystems for eons. The
perverse mainstay of decomposition is an extensive world-building, a
geo-cosmic afterlife that attests to a circular exchange, a
transmutation of will, and that reintegration of the organism back
into the One.


I became mercurial...

ran from the fresh spring of the beginning to the muddied waters of
bitter ends. 

But to return to the outmoded god-form laden with the unfettered hopes
and burnished wishes of humankind was impossible

 smacking more of the judgement of men than it does the instruction of
 god. 

But in and among these I discovered one interpretation, which held for
me especially convincing, for how sensibly it conferred with our
to-date scientific speculations about the budding youth of the
universe – of a compact, energetic singularity from which all life
would unfurl. - see above

one-to-multiple creation anecdote

. We never had god; when god was pronounced dead, this was true but
not new, for it was only through god’s self-destruction that our world
could be born. 
 


** dreams

*** dream/s of TM: 

1. the blue light. sweatshop dreams. // TM // mining - toad/earth - Becoming metals -  becoming as antimony, as arsenic, as copper, as iron, as lead, as mercury, as silver, // becoming earth

// copper/Dennis

*Heavy crystal sediments near the top.*

Last night I had a dream of playing a computer game. A glitch enabled
me to physically travel through dimensions. I ended up in the atelier
of a friend housed atop of a well known hamburger restaurant, which
doubled as a ‘hidden in plain sight’ security check, preventing random
people from going upstairs. In the atelier floated a sphere,
resembling the cryogenic containment unit from Akira, cables coming
out everywhere. It had a brown copper hue to it, but that could also
have been isolation material or even wood. How did it float?  This
‘device’ allowed you to trigger ‘lucid déjà vu’ allowing you to relive
memories as you wanted. Realising I was already in another dimension,
I did not want to go further. We all left to go to a club. Exiting the
restaurant someone had parked a trailer under the trees. My attention
was drawn to the shiny assortment of shapes faintly visible through
reflection of the faint moonlight penetrating the canopy. Upon
inspection the trailer was full of alumiium extrusions in every shape
and size you can imagine. Every piece was unique, except for their
perfect shiny, brushed finish.

// lead/martin

In the first I’m pissing into a toilet and each stream is accompanied by an intense blue
light – like a gas light, and maybe even the smell of gas as if there could be an explosion. This
could relate to the use of flame spectroscopy to analyze heavy metals in organic matters (such
as hair). The blue would correspond to the colour of a certain metal – such as lead itself or
arsenic.

In the second fragment we go past a kiosk (in Cologne) with two fresh fish stalls nearby,
run by Vietnamese people. Outside one of these stalls there are two older men, scruffily
dressed and with red, bruised faces, looking a bit like old English standup comedians. They
are there to entice people to come and see/buy the fish. At first they hold up the fish but
later they bite pieces of fish and then spit them out, catching them and spreading them on
their faces, to make a new face. 

They lay blue pieces over their eyebrows and other features, making
their faces more bruised and blue looking. This relates to the seafood
diet for the first three days of the sweatshop. Again a metallic,
bruisy blue colour.


*** dream of Iceland turf house - bog bodies, representation, being covered in earth. buried in handfuls of peat warmed by geothermal waters collected right next to the tarmac

2. the turf house, the front and back of the house, grave, entry and exit. off-world // theory theory - wings eagle // becoming cosmic - origins. *leaving the planet*

//iceland notes

turf house as a /relation?/ VEHICLE for becoming geological. house of earth and volcanic stones/lava

traditional - the front of the house, wooden gable, girls greeting tourists (bus engine left running) in threadbare costumes from a hundred years ago, ghost photographs

from the front windows, low wooden desk looks out on graveyard, on the church, the mound of earth covering the farmer's body

behind the house - the earth, new habits, new language (also behind Wolf Vostell sculpture, and recent dream with icon/crucifix/jesus... 

last house - the life support system of pipes, air conditioning, the last breath... (Teemu)

turf house as a grave

- conversations with Judith: Surtsey, subsurface bacteria
  there. portals, also geology which is neither living nor dead -
  outside these categories... nodes of life and death, outside these
  terms

*patricia also mentions leaving earth behind...where?*

between geology and biology, neither nor

iceland spar man - geological cheese (peter) - ref. bacteria for icelandic porcelain. spar/binary of calcite, polarisation of light

iceland as mostly geologically young...

golden circle. shit circle (Salo)

antii subsurface glitches... orbital turf house...


*** dream of Jachymov - that this could be the body as a landscape. entering the mine/body - that which is kept hidden

But the presence of so many soldiers and military vehicles, and the
wan-faced townsfolk evacuating their homes, ensured that the little
enclave of the transfigured forest – by comparison the remainder of
the Everglades basin seemed a drab accumulation of peat, muck and
marls – would soon be obliterated, the crystal trees dismembered and
carried away to a hundred antiseptic laboratories.
 
J.G. Ballard, 'The Illuminated Man', in The Terminal Beach, London: Phoenix, (1964) 1992, p.81

The minerals on the other hand she buries far beneath in the depth of
the ground; therefore, they should not be sought. But they are dug out
by wicked men who, as the poets say, are the products of the Iron
Age.

Georgius Agricola, De Re Metallica, 1556, Book I,(Trans. H & L Hoover), New York: Dover, 1950, p. 6-7.


[3. of the re-presentation of the bog bodies in the museum. the gold around the bezoar. margarita of austria's room // art art - snake // becoming mineral? becoming earth - re-presentation]notsomuch

3. jachymov - uranium cross. immortality, the afterlife of Elaine/Arthur

as a dream and include the vomiting dogs

In the third dream a priest leads us from his house, crammed with
artefacts from a burnt-out church, crispated altar paintings, into his
garden. Chickens, uncooped, run wildly at our feet. The priest is
tall, with long dark grey matted wet hair, and a long white beard,
crinkled and slightly curled. He opens a stout metal gate set into the
hillside near the chicken house, one corner of the garden, and leads
us deep into the narrow mine shaft, into the evil. As a giant leads a
troupe of dwarfs.

// all grey with frozen dew - 

drunken tanners dogs


** segments to fill in

*** body as landscape

where does this lead, this body as a mine, as a resources, as a metal,
copper body, man of copper, what are the consequences of these actions
for thought, for being what we are when we say what it is to be human,
or what comes before this saying (patricia), for the world - the
dystopia of tiny mining, final frontier -> visions of zosimos -
natural way of doing things

that a body can now be any landscape, a body as a site of tailings, as
a suburb, as a logistics centre on the outskirts of a small town,
between motorways, as a overgrown heap of rubbish grazed now by sheep,
a new mountain amidst the dykes and drainage canals 

a body as landscape, depicted, scanned and stretched, re-skinned, 

bog body is a landscape

if the body can become a mine, a prospect with associated legal
frameworks and permissions, with its waste piles and tailings, its
slag heaps, its .... to be inhaled, incorporated....

body as jachymov - that history, biography of a body, drunken tanners dogs vomitting (reference?)


*** places/place gone mad

*** insides - tiny mining // doubles - the inside is down inside... to descend is to go inside

*** geophagy - eating itself, feedback loops

*** islands of decay

what an island is? running round, coursing round

*** dreams and doubles

In November 2020, a small group of artists, chemists and geologists,
made a first attempt to collectively mine certain minerals from within
their own bodies. These actions brought forth monstrous visions. What
should have remained hidden (the secret life and genesis of metals)
was exposed to the light, unearthed. 


describe the first sweatshop - from in time with new moon... 

dreams of blue light (lead), of giant bumble bees (antimony), of a
musical group and a metal mouthpiece (mercury), of aluminium extruded
realities (copper) ... extraction seems to engender giants, monsters
and visions.

copper man vision zosimos. metal as a body

Geology is an unconscious (not our unconscious - subtexts/mackay,
moynihan-spinal). Countering and contrary to contemporary opinion
ranging the history of science, the alchemists did probe these
material depths. The bog bodies are dreams and visions, which is why
the museums (Drent,etc) insist on their repeated re-presention - the
literal return of the repressed in a very real sense (the alien, the
pagan, the nomad, black death, the odd symettry of El Majusi - geomancy).  

We have to go much further, much further back! And faster.

*** towards matter - finale that is the jachymov dream! where do we even write of that?

conclusion: *are words and images enough (question in jachymov), quest
for a materiality - tears of Anais which become an image* -> the plane
of consistency. the dream of jachymov

** quotes


*** opening

Yes, reader, countless are the mysterious hand-writings of grief or
joy which have inscribed themselves successively upon the palimpsest
of your brain; and, like the annual leaves of aboriginal forests, or
the un-dissolving snows on the Himalaya, or light falling upon light,
the endless strata have covered up each other in forgetfulness.

[Thomas de Quincey. The Palimpsest of the Human Brain]

Old earth, no more lies, I've seen you, it was me, with my other ravening eyes, too late.
[Samuel Beckett fizzles]


*** Bataille

luxuries of life: quotes Bataille Reader

The history of life on earth is mainly the effect of a wild
exuberance; the dominant event is the development of luxury, the
production of increasingly burdensome forms of life.  

The Three Luxuries of Nature: Eating, Death and Sexuw Reproduction 
p192

Shamefully, We Get Life from Putrefaction, and Death, Which Reduces Us
to Putrefaction, Is No Less Ignoble than Birth 
p243



Death destroys, it reduces to NOTHING the individual who took
himself, and whom others took, for a thing identical to itself. Not
only was this individual integrated into the order of things but the
order of things had entered into him and, within him, had arranged
everything according to its principles. Like other things he had a
past, a present and a future and an identity through that past,
present and future. Death destroys what was to be, what has become a
present in ceasing to be.
p315

*** deleuze/G - THE GEOLOGY OF MORALS

*becoming geo is the plane of consistency, the body without organs*

The strata are judgments of God; stratification in general is the entire sys-
tem of the judgment of God (but the earth, or the body without organs, con-
stantly eludes that judgment, flees and becomes destratified, decoded,
deterritorialized). p40

A surface of stratification is a more compact plane of consistency
lying between two layers." The layers are the strata. They come at
least in pairs, one serving as substratum for the other.  The surface
of stratification is a machinic assemblage distinct from the
strata. The assemblage is between two layers, between two strata; on
one side it faces the strata (in this direction, the assemblage is an
interstratum), but the other side faces something else, the body
without organs or plane of consistency (here, it is a metastratum). In
effect, the body without organs is itself the plane of consistency
p40

To express is always to sing the glory of God.
p43

*KEY:* on this plane of consistency: 

Furthermore, if we consider the plane of con- sistency we note that
the most disparate of things and signs move upon it: a semiotic
fragment rubs shoulders with a chemical interaction, an electron
crashes into a language, a black hole captures a genetic message, a
crystalli- zation produces a passion, the wasp and the orchid cross a
letter... There is no "like" here, we are not saying "like an
electron," "like an interaction," etc. The plane of consistency is the
abolition of all metaphor; all that con- sists is Real. These are
electrons in person, veritable black holes, actual organites,
authentic sign sequences. It's just that they have been uprooted from
their strata, destratified, decoded, deterritorialized, and that is
what makes their proximity and interpenetration in the plane of
consistency possible p69

Challenger muttered that he was taking the earth with him, that he was
leaving for his mysterious world, his poison garden.
p73

*** Artaud

No more fruit, no more trees, no more vegetables, no more plants pharmaceutical or otherwise
and consequently no more food, but synthetic products to satiety, amid the fumes, amid the
special humors of the atmosphere, on the particular axes of atmospheres wrenched violently and
synthetically from the resistances of a nature which has known nothing of war except fear.
[Antonin Artaud. To have done with the Judgement of God.]

*** Poe - for place gone mad

This opinion, in its general form, was that of the sentience of all
vegetable things. But, in his disordered fancy, the idea had assumed a
more daring character, and trespassed, under certain conditions, upon
the kingdom of inorganization. I lack words to express the full
extent, or the earnest abandon of his persuasion. The belief, however,
was connected (as I have previously hinted) with the gray stones of
the home of his forefathers. The conditions of the sentience had been
here, he imagined, fulfilled in the method of collocation of these
stones –in the order of their arrangement, as well as in that of the
many fungi which overspread them, and of the decayed trees which stood
around –above all, in the long undisturbed endurance of this
arrangement, and in its reduplication in the still waters of the
tarn. Its evidence –the evidence of the sentience –was to be seen, he
said, (and I here started as he spoke,) in the gradual yet certain
condensation of an atmosphere of their own about the waters and the
walls. The result was discoverable, he added, in that silent, yet
importunate and terrible influence which for centuries had moulded the
destinies of his family, and which made him what I now saw him –what
he was.

[Edgar Allen Poe. The Fall of the House of Usher]

*** decay decomposition island

islands of decay in Elaine/arthur and in Ilana H book (felt events) p. 73 Jerry Zee

Flesh occasions stone, and the submerged corpse is a landmass in the
making [...] it is the core of a composire necromineralogical
thing. Its friction in the flow of petrifying water invites the
precipitation of islands: the skin's drag is a small obstruction where
dissolved mineral load builds up [...] The corpse harbours new land,
even as it gives itself over to earth. The skeleton, the organic stone
within the corpse, anticipates the rock that will form around it.

*** surtsey

surtsey inverted - surtsey as a novel island of decay, going backwards

https://matis.is/en/news/thermophilic-bacterium-isolated-from-the-basaltic-subsurface-of-the-volcanic-island-surtsey/

Novel thermophilic heterotrophic bacteria were isolated from the
subsurface of the volcanic island Surtsey off the south coast of
Iceland. The strains were isolated from tephra core and borehole fluid
samples collected below 70 m depth. The Gram-negative bacteria were
rod-shaped (0.3–0.4 widem wide, 1.5–7 longm long), aerobic,
non-sporulating and non-motile. Optimal growth was observed at 70 ° C,
at pH 7–7.5 and with 1% NaCl. Phylogenetic analysis identified the
strains as members of the genus Rhodothermus . The type strain,
ISCAR-7401T, was genetically distinct from its closest relatives
Rhodothermus marinus DSM 4252T and Rhodothermus profundi PRI 2902T
based on 16S rRNA gene sequence similarity (95.81 and 96.01%,
respectively), genomic average nucleotide identity (73.73 and 72.61%,
respectively) and digital DNA – DNA hybridization (17.6 and 16.9%,
respectively). The major fatty acids of ISCAR-7401T were iso-C17:0,
anteiso-C15:0, anteiso-C17:0 and iso-C15:0 (> 10 %). The major
isoprenoid quinone was MK-7 while phosphatidylethanolamine,
diphosphatidylglycerol, an unidentified aminophospholipid and a
phospholipid were the predominant polar lipid components. Based on
comparative chemotaxonomic, genomic and phylogenetic analyzes, we
propose that the isolated strain represents a novel species of the
genus Rhodothermus with the name Rhodothermus bifroesti sp. nov. The
type strain is ISCAR-7401T (= DSM 112103T= CIP 111906T).


** notes to above as we write

geotrauma

geopoesis

surtsey decomposition

Sudhaus, W., Rehfeld, K., Schlüter, D. & Schweiger J.
1988: Beziehungen zwischen nematoden, coleopteren und
dipteren in der sukzession beim abbau von kuhfladen. (The
interaction between nematodes, beetles and flies in the succession during decomposition of cow pats.) Pedobiologia
31, 305–322.

The patchy spatial distribution of the nematodes (note the ranges in
Table 4) presumably reflects a distribution of the nematode habitats
(food sources) in “hot spots”. These are most likely related to bird
droppings, food spills or bird cadavers, which offer a sudden burst of
available nutrients of a low C:N ratio. However, the “hot spots” will
change radically during decomposition and must be considered a very
unstable resource, and hence be a typical habitat of
r-strategists. Protorhabditis cf. oxyuroides, Mesorhabditis
monhystera, some Panagrolaimus species and A. nanus are r-strategists,
i.e. habitat generalists with good reproduction potentials (Sohlenius
1973; Sudhaus 1976) typically found in such habitats. 

feathers are shed and corpses of birds that die decompose

** more for blurb/curatorial statement

Does it feel self-evident or too obvious to claim that we are and have
always been geological; a truism? We acknowledge that we are
birthed by the geological, embedding *xxx trauma* deep in our
psyche. 

moynihan - authored by the planet in the full sense of our intellect
being a deeply contingent product, produced by protracted pathways of
chance, rather than by the shallow predetermination of optimality or
orthogenesis.

Our death will see a return to the geological, as particulate
matter (mercury). decay

We incorporate the earth and its minerals, as diet or as part of
medicinal or spiritial practices. We maintain a direct connection with
an ever-changing earthly and cosmic environment. The world is (made
of) dirt, and we are equally filthy. Mined like a sewer.

We tunnel into, disturb and create new non-anthropogenic and
anthropogenic cycles of incorporation and extraction, of radical
consumption. These are our media. All media which establish cuts
(Barad) and refinements across filth and not-so-crystalline death,....???Peter_text

This has been happening for a while. Yet it seems odd to suggest that
we are geological; conjuring a glazy Wunderkammer jar stock of kidney
stones, of gall stones, calculi and bezoars reminding of the
geological within. 


Does it feel self-evident or too obvious to claim that we are and have
always been geological; is this a truism?  Is this self-evidence the
geological, the insides, the depth - geology comes before us,
literally, geology is us. creates us. we are not it. so how do we
become geological? by recognising this coming before, and coming
after, for the dead of millenia, of every species.

Agn: Tiny Mining exposes is not only that minerals are part of our
technological histories and future desires but they actually are these
technologies already, and they condition our lives in the most
intimate and crucial way by becoming us, or rather, by us becoming
mineral.

finally geology becomes us. it is not a becoming for us, leading to
us, lead by us, not our holding forth of, our extracting of, our xxxx
of... (how better express)

geo-logic is an infra-logic, a writing in and of the stones which
comes before any us, renders us contigent on its non-self (Moynihan)... 

becoming? ontogenesis

//// from metamorf:

Humankind has always been dirty and geological, through intentional
incorporation of earthly and thus cosmic elements (as diet or as part
of medicinal or spiritual practices), and within a direct connection
with a slowly changing earthly and cosmic environment. We can also
think of kidney stones, of crystals formed in urine and of iron in the
blood and tissues. We incorporate the earth and its minerals, becoming
sedimentary.

But there is more to it than this, as we tunnel into, disturb and
create new non-anthropogenic and anthropogenic cycles of incorporation
and extraction, of radical consumption.

With the arrival of the questionable era of the anthropocene, marking
another entry point into the planetary geological, a new “natural”
cycle is initiated - we literally inhale and ingest our own
anthropogenic indicators (for example, as the particulate exhalations
of burning forests, as isotopes from nuclear testing, as metallic dust
from global extractions). These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms. Understanding this new nature for
humankind involves a close examination and potential embrace of a
“becoming geological”, becoming a-human.

Environmental concerns are no longer out there, in a controlled and
surveyed landscape of "nature"; to be protected. The dread-ful
"anthropocene" is now an internal story written within interior
geologies and in the deep time of ingestion and digestion. Saving the
planet is now a matter of looking into ourselves.

