* Becoming Geological: mining dreams // 

approaches of the bodily/interior, of the atmospheric (a between) and of the
digital (the outside, the projections from the inside - Ballardian),

all these becomings - becoming smog, becoming dust...

illustrations: argotine/other box designs with overlay of quotes

** pitch/other used notes/ cycles / presentation / whatever


*** TEH

gold fibres dissolved in the lake are set to colour it blood-red as a sunset

AMD acid mine drainage

container subjecting itself to a descriptive dissolution, to the recursive effects of its own signs

hardware dissolves itself as a function or extent of its own functions, as a necessity. it is and is not a palimpsest

*** surtsey inverted - surtsey as a novel island of decay, going backwards

https://matis.is/en/news/thermophilic-bacterium-isolated-from-the-basaltic-subsurface-of-the-volcanic-island-surtsey/

Novel thermophilic heterotrophic bacteria were isolated from the
subsurface of the volcanic island Surtsey off the south coast of
Iceland. The strains were isolated from tephra core and borehole fluid
samples collected below 70 m depth. The Gram-negative bacteria were
rod-shaped (0.3–0.4 widem wide, 1.5–7 longm long), aerobic,
non-sporulating and non-motile. Optimal growth was observed at 70 ° C,
at pH 7–7.5 and with 1% NaCl. Phylogenetic analysis identified the
strains as members of the genus Rhodothermus . The type strain,
ISCAR-7401T, was genetically distinct from its closest relatives
Rhodothermus marinus DSM 4252T and Rhodothermus profundi PRI 2902T
based on 16S rRNA gene sequence similarity (95.81 and 96.01%,
respectively), genomic average nucleotide identity (73.73 and 72.61%,
respectively) and digital DNA – DNA hybridization (17.6 and 16.9%,
respectively). The major fatty acids of ISCAR-7401T were iso-C17:0,
anteiso-C15:0, anteiso-C17:0 and iso-C15:0 (> 10 %). The major
isoprenoid quinone was MK-7 while phosphatidylethanolamine,
diphosphatidylglycerol, an unidentified aminophospholipid and a
phospholipid were the predominant polar lipid components. Based on
comparative chemotaxonomic, genomic and phylogenetic analyzes, we
propose that the isolated strain represents a novel species of the
genus Rhodothermus with the name Rhodothermus bifroesti sp. nov. The
type strain is ISCAR-7401T (= DSM 112103T= CIP 111906T).



*** crystal world/mute


I want you to bear in mind the trend of the ground, for some time,
sooner or later, we shall do well to have it in our mind's eye when we
are considering the ancient traditions and superstitions, and are
trying to find the RATIONALE of them. – Bram Stoker

This work (of language, of entropic, driven code accruing on the
Morlock command line), accreting, scattered across the floor, growing
upright, taped, being swept up, re-arranged, erased, compost writing;
tiny curled paper strips witness the remaindered packaging from a
transformer or other component, clustered burnt veined softwood
fragments, stuck clay mud, slow wormed cables, opened plugs and
punctured saucepans. It's a beginning, a slow and sticky pantheistic
adherence of geological language, scraping away the earth works and
words. A mud slide of diamonds for 'The Mind of Clay' (Robert
Smithson); the slow thuds of grey sludge, pulled down accretions
sluicing the eroded Jurassic cliff face, witnessed on the beach by
Black Ven. Twinned geologies, on the one side Llull-esque layers and
sediments, unseen, barely touched categories of the machinery used to
write this work, descending in a bell to the discarded leachate, the
holy substrate, incantations of the mess and lab, and in the other
direction a healthy, stumbling Poe-geology writing and interring
itself, to be dug out, a blind forensics, making sense where there is
no sense to be made. And these are not building blocks, abstract units
strapped together, application conduits always summoning factories of
code, but rather writing this enclosed place of a singular needle or
trap; a site of potential execution.

The crystal world is now underground, a fizzing fairy cavern of
paradise and leisure, yet blocked from above by a large, grey stone
which merges in form and colour with the floor of the functional
gallery space, The White Building, a rather more solid double for the
cardboard, stage-set words of Ballard's White Hotel description (The
Crystal World).

Snaking copper traces, streets etched, emerging from sheaths of acid,
connecting chunks of Hackney transistor geologies, are rendered active
and open to determined logic and language, to particular wormy
instruction sets, through the action of street lights, electromotive
forces, and lightning. Leaving the city, the circuit of self
reproduction snakes beyond Ballard's Mont Royal (The Crystal World),
wraps itself leisurely around Stoker's Doom Tower ('situated on an
eminence high up in the Peak'), and begins slowly to outpace a given
world of abstractions, breaking with plague language and with plague
containment, squeezing the castle walls, promoting feminine snake
promiscuity against dreamt-of serpent ecologies (synthesis: 'The
serpent that announces...') and loopy cybernetics, finally declaring,
in a poisonous snake-entwined coat-of-arms, an insignia etched on the
earth, a negative ecology which is nothing other than pure, pure
animism. 'Behind the hieroglyphic streets there would either be a
transcendent meaning, or only the earth.'

But the presence of so many soldiers and military vehicles, and the
wan-faced townsfolk evacuating their homes, ensured that the little
enclave of the transfigured forest – by comparison the remainder of
the Everglades basin seemed a drab accumulation of peat, muck and
marls – would soon be obliterated, the crystal trees dismembered and
carried away to a hundred antiseptic laboratories.8
 
J.G. Ballard, 'The Illuminated Man', in The Terminal Beach, London: Phoenix, (1964) 1992, p.81

The world, is nothing but a conspiracy coded in the earth itself and
executed on the flesh. A conspiracy unveiled as electromagnetic and
geophysical in the nineteenth century, cryptovolcanic faultlines
literally coding the exposure of both a Time Machine, and a writing
machine (named Bram Stoker). Dracula's less-than-divine earth
substrate announcing computational technology for a future Morlockian
OS (operating system); Stoker coded Persinger-style by Whitby's
geopsychedelics as he reveals years later in The Lair of the White
Worm, a shakey narrative driving the plague-bearing comet or dragon
back underground; a state transition into a fine well-poured,
lair-poured sand becoming now silicon substrate. A conspiracy
initiated when the blood ores (such as haematite) of the very first
metallic veins were explored and exploited; a conspiracy commemorated
by the radon-rich standing stones, circles, qouits and chambers
scattered across a now desolate, mined and exhumed landscape. And
finally a conspiracy founding and exacerbating technology as an
alien-descendant CPU, an earth computer, a crystal world, a grinding
block of language to turn bodies into dust or sand.

 

*** trondheim

Norway - Becoming Geological/Tiny Mining: interior geologies

I’d like to begin by framing Tiny Mining with a new form of mining
prospect, a list of deposits or resources ripe for low cost
exploitation, produced by the German company Medivere, during our
first Tiny Mining collective sweatshop.

A prospectus, which as such is useful in determining which portion of
a mineral can be considered as an exploitable ore reserve.

So what exactly is Tiny Mining for those of you who are unfamiliar
with this diverse group who've already garnered a good deal of press
attention.

Tiny Mining (TM) is an open source mineral exploration co-operative
and resource specialist committed to the potential exploitation of the
interior of the living human body for rare earth and other mineral
resources in the interests of human and planetary health.

It’s important to stress that Tiny Mining is both a mineral
exploration collective and an open source community.

To dig deeper into the nature of this community, our primary resource
is the Tiny Mining manifesto or mission statement.

We believe that the earth should remain as pristine and untouched
nature; we have no desire to carry on extracting resources from a
depleted world, polluting and laying waste to the landscape. Saving
the planet is now a matter of becoming sensitive to our own geological
being. In mining ourselves we gain knowledge of our own bodies, our
selves and the global environment. This is a final ecology for the end
days. Nature will remain and our technologies will now be sourced from
within; we will thus no longer be dependent on scarce and already
polluted environmental resources.

I’d thus like to situate the Tiny Miners within a wider global or
cosmic movement or moment which we could refer to as the Becoming
Geological.

We have always been and will always be geological.

As Thomas Nail write in his Theory of the Earth: The earth is not a
passive object or stage for human activity, nor is it a benevolent
subjective agent of life (Gaia). If anything, the earth is a process
of expenditure and death—more like Python than Gaia. Human animals do
not live on the earth. They are the earth.

Humankind has always been dirty and geological, through intentional
incorporation of earthly and thus cosmic elements (as diet or as part
of medicinal or spiritual practices), and within a direct connection
with a slowly changing earthly and cosmic environment. We can also
think of kidney stones, of crystals formed in urine and of iron in the
blood and tissues. We incorporate the earth and its minerals, becoming
sedimentary.

But there is more to it than this, as we tunnel into, disturb and
create new non-anthropogenic and anthropogenic cycles of incorporation
and extraction, of radical consumption.

With the arrival of the questionable era of the anthropocene, marking
another entry point into the planetary geological, a new “natural”
cycle is initiated - we literally inhale and ingest our own
anthropogenic indicators (for example, as the particulate exhalations
of burning forests, as isotopes from nuclear testing, as metallic dust
from global extractions). These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms. Understanding this new nature for
humankind involves a close examination and potential embrace of a
“becoming geological”, becoming a-human.

Environmental concerns are no longer out there, in a controlled and
surveyed landscape of "nature"; to be protected. The dread-ful
"anthropocene" is now an internal story written within interior
geologies and in the deep time of ingestion and digestion. Saving the
planet is now a matter of looking into ourselves.

In the words of the tiny miners:

We wish to be of the earth, and free of any reliance on the earth. We
celebrate our earthiness, as well as the wish to no longer depend on
the earth, no longer to extract and be attached, but simply to be
with. I don’t want to touch the earth. Nature doesn’t need our
ecology, our management.

So what are the symptoms of becoming geological
 
The symptoms of a muddy embrace of the becoming geological were
explored and exacerbated in the first of a series of sweatshops.

These include:

An attention to the moon and planetary phases and orbits - the cycle
of extraction begins with the new moon and lasts one lunar month. The
first sweatshop commenced with the new moon, following a cycle of
ingestion (a diet rich in the specific metal assigned to the sweatshop
participant), followed by chelation (the use of medicinal plants and
pharmaceuticals to bring metals out of tissues), and extraction or
purgation.

An examination of co-relation between diet, dreams and
reveries. Participants reflected on bodily impressions, feeling,
thoughts and recorded all dreams during the sweatshop.

Hard scientific tests for the presence of heavy metals: colorific
tests on hair and urine, voltametric tests on urine.

Exploring one’s affinity with the various metals (such as antimony,
gold, silver, arsenic, lead, iron and mercury), their physical
properties, historical and mythical qualities and an awareness of the
connection of bodily routines and sentiments with these properties.

New developments post sweatshops - we are currently working with a
Chinese pharmaceutical company based in Beijing on the (open source)
development and manufacture of Argotine, the primary extractive agent
alongside “natural” chelators and supplements. Argotine incorporates a
synthetic chelating agent (DMPS), sets of nano “collectors” or
“farmers”, and finally an emetic or purgative element based on
traditional Chinese medicinal or alchemical recipes (for flight and
immortality) such as Elixir of Ascent into the Roseate Clouds making
use of arsenic and mercury bearing ores.

what does becoming geological mean?

Theorist Agnieszka Anna Wołodźko studied the Tiny Mining sweatshop
cycle in her key essay Tiny Mining: Theory of the Earth from a
Sweatshop – On Practising Becoming Cosmic.

She starts to unpack the contradictions at play within the belief
systems of the Tiny Miners as evidenced in their practice and online
texts:

She argues that “they not only follow the existing desires of
unlimited access for resources but also expand the capitalist logic of
treating living bodies as a resource for the increase of capital,
joining such well-established practices as biopiracy, data mining and
human trafficking.”

And she goes on to write that:

In their initial statements in the “Tiny Mining Sweatshop Reader”, it
is argued that “we [tiny miners] believe that the earth should remain
as pristine and untouched nature. We have no desire to carry on
extracting resources from an ever-depleted world.” Here thus, tiny
miners seem to follow the capitalist logic of the radical difference
between what is considered as Nature and what is human. In their
pursuit of natural purity, they revitalise the romantic notion of
Nature as that which is separate from the human, the pure and
untouched, disavowing the implications of such a position for the
problems and violence it carries.

However, what seemingly starts as a continuation of the capitalist
logic of exploitation of bodies, taking a position of being outside of
whatever is understood by “nature”, quickly changes its tone. As they
write:

“What we do to the planet we should first do to ourselves, extract and
pollute. We need to get to know the doses - from deficiency to
toxicity - how much to extract from ourselves and how much to
ingest. 

*We become bio-markers, indicators of earthly or planetary health.* 

How much can we extract from the earth, and return to the
earth? I offset what I take from the earth, and the damage I cause the
earth, through this giving back. We try to get to know our own cycles,
of excess, of regulation and of deficiency.”

Rather than prioritising the sense of purity and sustainability as the
ecological act of resisting the earth’s extraction and simply using
human bodies for a similar purpose, the goal is to become sensitive by
dismantling what Patricia MacCormack named as “human privilege.”

It is through working at the faces of the deep implications within
these contradictions that we can begin to understand what is at stake
within the daily ascetic practice of Tiny Mining and within the wider
current or vein of the Becoming Geological. And we need to understand
that these contradictions are themselves embedded in consumption or
incorporation of the other and in extractive practices. The
contradiction is within incorporation, becoming a geological body
through the incorporation of geological time scales.

We begin to realise that all geology is geophagy (consumption of
earthy substances).  The alchemists would say that nature loves to
hide, we say that nature loves to eat.

Again from Thomas Nail in his Theory of the Earth:

“The earth is a cosmic exterior centripetally folded in on itself
through the vortical motion of nebular accretion. It is the interior
of an exterior. It is a fold. In other words, the earth is already
profoundly alien to itself. It is a hybrid monster composed of all the
motley stuff of nebular waste: a piece of shit stuck to a solar anus.”

We can view this through the often naive words of the Tiny Miners themselves:

I incorporate the other; the earth, the forest at night, the haunted
hedges, the poor wastelands. I incorporate the other only to vomit,
piss and shit it out as my value in the world, as my consumption and
my due. What I mine and refine belongs only to me, it comes from me,
it is mine, mined. I don't touch the earth. I leave it finally.

To return to this duality of incorporation and extraction we can see
that just as the chinese alchemists extracted arsenic and mercury from
the earth (as orpiment, cinnabar and realgar) to incorporate these
materials in their bodies as agents of immortality.

So today we extract copper, tantalum and so on towards an extra-bodily
incorporation, an exteriorisation of bodies in and as technology

Our become dispersed as techno-prostheses is a form of
incorporation. Incorporation and extraction are as the pharmakon of
dosage: lack and abundance, deficiency and toxicity.

Other communities such as transhumanists and biohackers now seek a
"real" incorporation of metals and technology - to upgrade and replace
the flesh or meat suit with immortal components - subject only to
obsolescence and eternal internal upgrades.

Mercury and copper are extracted from the earth and placed into the
human body in order to preserve it. Transhumanism is about material
augmentation, flesh is replaced by metal and mineral which is
(apparently) a renewable resource.

Tiny miners go in reverse direction - becoming mineral and purging
oneself of the metal, the mineral.

This reminds us of the practices of self mummification parallel to the
use of elixirs of immortality for bodily preservation:

As Joseph Needham writes in this context: The adept towards the end of
his life abstains for a long time from all cereal food, living only on
plant material such as chestnuts, Torreya nuts, pine-tree bark and the
roots of grasses; then just before death he may claim the distinction
of being buried alive. After death has occurred the corpse is dried
over charcoal fires and smoked with the fumes of incense, then when
fully dessicated lacquered all over or used as the base for a statue
of dried clay or plaster.

And following  Agnieszka Anna Wołodźko:

Tiny miners begin thus the process of learning how we are already
co-depended with non-living bodies, approaching the conditions and
constellations of expenditure that we need to practise to live
well. Because to live well, means to die and ensure others to die in
their multiple tiny ways, every day, by becoming cosmic.

I’d like you to accept thus a final invitation 

After taking Argotine, if your face and body itch as though insects
were crawling over them, if your hands and feet swell, if you cannot
stand the smell of food and vomit it up after you have eaten it, if
you feel as if you were going to be sick most of the time, if you
experience weakness in your arms and legs, if you have to go often to
the toilet, or if your head or stomach violently ache - do not be
alarmed or disturbed. All these effects are merely proof that the
Argotine you are taking is successfully mining your insides.

*** machines will watch us die interview

Execution describes both the actions of software in the world, when
the word becomes flesh (as Florian Cramer makes clear), and an
enforced death sentence which we lie under. The networked and
tentacled society of computational machines exists at this logical
junction of laws, actions and death or decay. There is a literal
enshrouding as the earth is mined and refined for the production of
pixellated screens and machines, and the byproduction of photochemical
smogs, and pollutants which in their turn mine and refine our
bodies. I'm writing these responses in Beijing where (with the Shift
Register project) we are examining smog as a contemporary, geological
media binding the (photo)-chemistries of screens, bodies, cities and
planet.

At the same time it becomes clear that these machinic processes are
very much linked to some process of mummification (as Robert Smithson
wrote, "the medium is the mummy"); to a kind of deathly or spectral
preservation which could be considered as immortality. This is what I
mean by enshrouding, by enveloping in veils of screens and smog, and
by the ingestion of earthly and technological minerals and machined
synthetics. We become geological. In the sense that the digital
outlives us, as earthly trace, as cloudy storage and as toxic
memorial, machines will watch us die, record our deaths (as loss of
resources) and assist in forming a spectral community of the un-dead.


*** epub

Tiny Mining is a mineral exploration co-operative and community
committed to the open source exploitation of the interior of the human
body for rare earth and other mineral resources. As a speculative,
interventionist artistic research and media project examining the
links between extractivism, pharmacology and medical or environmental
geology, Tiny Mining was developed over the course of the first Alex
Adriaansens Residency (DAAR) at V2__ in Rotterdam.

Tiny Mining: A handbook for internal extraction brings together the
multiple strata informing the Tiny Mining project: making connection
between bioethics, posthumanism, the history of close bodily contacts
between human beings and the geological, the discipline of medical
geology, medical anthropology, and new dark ecological theory.

Tiny Mining is a speculative, interventionist artistic research and
media project examining the links between extractivism, pharmacology
and medical or environmental geology. Tiny Mining began life as a
speculative dystopic fiction, projecting the corporate exploitation of
rare earth resources inwards, towards the human body. Over the course
of the one year v2/DAAR residency Tiny Mining developed into a
community initiative, exploring the culture of self mining through
group discussion, tutorials and collective sweatshops.  

The epub would aim to bring together the multiple strands informing
the Tiny Mining project: from the history of close bodily contacts
between human beings and geology, the discipline of medical geology,
medical anthropology, and new dark ecological theory to speculative
bio-fictions and the nature of scientific truth.

The Tiny Mining community was founded in November 2019, during an
expert meeting in Brussels. This open community consists of a diverse
group of chemists, geologists, artists and alternative medicine
practitioners. In November 2020, a small group of community users took
part in the first remote sweatshop dedicated to the exploration of
experimental protocols for improving extractive yields and
facilitating testing procedures for the wider community. We also
explored the construction of alternative belief systems, facilitating
the adoption of Tiny Mining as a widespread cultural practice. A metal
or element was assigned to each sweatshop participant for reflection
and extraction. In order of elements the participants were: Theun
Karelse, v2_labs, Dennis de Bel, Kat Austen, Martin Howse, Aniara
Rodado and Alfonso Borragan. The results of the first remote sweatshop
are documented here.

*** IMM

Tiny Mining explores the material basis of computational and
communications technology and infrastructures in relation to the human
body and asks what such a potential relationship could be in terms of
a closer connection between the material and environmental effects of
the extraction and return (planned obsolescence, e-waste) of
technology and the body could be. At the same time it explores and
asks questions about the practical and ethical nature of this proposed
new relationship.

Media, computation and communications have always been geological,
entering into material cycles through both extraction (mining, for
example, copper), and processing (for example, the reburial of copper
and fiber optic cables in the earth). What is perhaps new, in the
recent naming of the becoming-geological of humankind (as the
anthropocene or capitalocene), is the conjoined transformation and
awareness of humans and their home planet as at once media and matter,
information and geology. Industrial plastics, dust and radioactive
isotopes lodge within all kinds of bodies, equally marking all things
as geologic.

At the same time, humankind can be defined as always incorporating the
earth: as food, as pharmakon and as media and this incorporation can
be defined as geological. We can catalogue a history and a "bestiary"
of an inner geology with its bezoars, otoliths, gallstones and
gastroliths. Geology is not outside us; various timescales must be
compared and contrasted (of lives and deaths, eating and shitting, of
deep time and geological formation).

This idea of a sensitivity to planetary and bodily health underwrites
the Tiny Mining project with the Anthropocene viewed as both
symptomatic and as psychosomatic.

The focus of the project is on the transitional interior and inferior
geologies of media and communications. The notion of interior geology
refers also to the circulatory system of an earth addiction
encompassing extraction (of precious metals, of radioactive minerals),
transport/circulation and consumption (the ingestion of earth-derived
energies, materialities and earth-bound pharmaceutical products) and
return or excretion (traces of isotopes and pollution elements in the
body).

Matter, like media are both purposefully ingested and accidentally
absorbed, forming new internal, circulatory and transitional
geologies.

Tiny Mining explores these multiple links and circulations between
technology, the environment and the human body and psyche. It's
important in times of climate disruption and environmental destruction
that we begin to think and work deeply within these relationships and
within the histories of media such as scientific discourse,
pharmacological matters and medical geology; to think an alien,
potentially geological post-nature.


The parasite, named Argotine (with reference to the rich history and
folklore of the ergot fungus) is designed as an assemblage of
nanoscopic units, each of them measuring around 10nm, that have
specific compositions and electrical charges corresponding to the
desired mining process.

The different nanomachines create bonds, communicate and form larger
structures (up to 100 micrometers) similar to fungi's mineral mining
hyphae. Once injected into the bloodstream, they travel and stick to
the affected/healthy cells where the extraction begins.

This micro/tiny mining process, as in the case of soil mineral
extractions performed by plants, fungi and microorganisms is
facilitated thanks to bioleaching (the process of extracting metals
from their ores through the use of living organisms) through
chelation. The process is highly efficient for lead, arsenic,
antimony, molybdenum, gold, silver and cobalt extractions.

We believe that the earth should remain as pristine and untouched
nature; we have no desire to carry on extracting resources from a
depleted world, polluting and laying waste to the landscape. Saving
the planet is now a matter of becoming sensitive to our own geological
being. In mining ourselves we gain knowledge of our own bodies, our
selves and the global environment. This is a final ecology for the end
days. Nature will remain and our technologies will now be sourced from
within; we will thus no longer be dependent on scarce and already
polluted environmental resources.

Our thesis here is that the in-corporation of the earth, the becoming
geological of the human body, meaning that geological time-scales and
processes can now be considered as corporeal: that these ideas are at
play within the community of Tiny Mining and relate heavily to an
anthropology or history of the preservation and immortality of bodies
and their extensible or extended environments (prostheses or tool
culture) which leads abruptly to contemporary trans-humanist practice.

What is shih chieh? (from a Taoist catechism p301 - Li Shu-Huan)

After the death of an adept seeking immortality, the form and skeleton
remain behind while the immortal goes away; this is what is meant by
shih chieh. When one is ready to rise up as an immortal, one leaves
behind the malodorous house of clay, hence the expession "corpse"
(shih) from which the hsien is "liberated".

The Chu Hsien Lu says "When the appearance is like that of a living
person - that is (proof of) shih chieh. When the feet have not turned
bluish in colour, and the skin not shrunk - that is shih chieh. When
the light in the eyes has not gone dull, and looks like that of a
person still alive - that again (shows) shih chieh. There are also
those who have become alive once more after being dead; and some whose
bodies have disappeared altogether before being encoffined; and others
who have ascended, leaving only their hair behind - all these things
are called shih chieh. 

*Those who effect their liberation during the light of day become
immortals of the higher category, those who do so at night join the company of the lower.*

We can see that just as the chinese extracted arsenic and mercury from
the earth (as orpiment, cinnabar and realgar) to incorporate these
materials in their bodies as agents of immortality.

So we extract copper, tantalum and so on towards an extra-bodily
incorporation, an exteriorisation of bodies.

Our become dispersed as techno-prostheses is a form of
incorporation. Incorporation and extraction are as the pharmakon of
dosage: lack and abundance, deficiency and toxicity.

Transhumanists and biohackers now seek a "real" incorporation of
metals and technology - to upgrade and replace the flesh or meat suit
with immortal components - subject only to obsolescence and eternal
internal upgrades.

Extraction is about storage the memorial, the support for an archive.

Mercury and copper are extracted from the earth and placed into the
human body in order to preserve it. Transhumanism is about material
augmentation, flesh is replaced by metal and mineral which is
(apparently) a renewable resource.

Tiny miners go in reverse direction - becoming mineral and purging
oneself of the metal, the mineral. Again the dual blade of the
pharmakon.

Mind uploading or brain upload can also be seen as a form of
extraction, extropian data mining; discard the flesh suit and extract
that valuable mind.

There is this twin movement in TM of wanting to incorporate the earth
in order to be able to mine, but also extracting and freeing oneself
of the earth (inside) and of any attachment to the earth. Going way
beyond the Gnosticism inherent in Transhumanism.

*** invitation

After taking Argotine, if your face and body itch as though insects
were crawling over them, if your hands and feet swell, if you cannot
stand the smell of food and vomit it up after you have eaten it, if
you feel as if you were going to be sick most of the time, if you
experience weakness in your arms and legs, if you have to go often to
the toilet, or if your head or stomach violently ache - do not be
alarmed or disturbed. All these effects are merely proof that the
Argotine you are taking is successfully mining your insides.

*** BG pitch

Cycles/cyclical/circles: With the arrival of the questionable era of
the anthropocene, marking another entry point into the planetary
geological, a new “natural” cycle is initiated - we literally inhale
and ingest our own anthropogenic indicators (for example, as the
particulate exhalations of burning forests, as isotopes from nuclear
testing, as metallic dust from global extractions).

Humankind has always been dirty and geological, through intentional
incorporation of earthly and thus cosmic elements (as part of
medicinal or spiritual practices), and within a direct connection with
a slowly changing earthly and cosmic environment.

With the arrival of the questionable era of the anthropocene, marking
another entry point into the planetary geological, a new “natural”
cycle is initiated - we literally inhale and ingest our own
anthropogenic indicators (for example, as the particulate exhalations
of burning forests, as isotopes from nuclear testing, as metallic dust
from global extractions). These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms. Understanding this new nature for
humankind involves a close examination and potential embrace of a
“becoming geological”, becoming a-human.

BG marks, traces and unfolds these multiple cycles, within the
framework of both a major exhibition at v2, Rotterdam featuring new or
foundational artistic projects, and a book publication offering
diverse authorial perspectives. The exhibition will focus on geologies
of digital/infrastructures, bodies and atmospherics or particles.

The exhibition and publication function as manuals, or guides for this
new relation of the human, invoking “becoming geological”, “becoming
dirt” or “becoming cosmic” as potential new ways of life and
philosophies of the earth; a manual for how to live and die within new
earthly and cosmic techno-cycles.

BG invokes artistic, practical and theoretical responses to this new
inner nature, from the history of close bodily contacts between human
beings and geology, the discipline of medical geology, medical
anthropology, and new dark ecological theory to speculative
bio-fictions.

** collected quotes - smithson, beckett, poe, spinal catastrophism

The world is dirt.
[e fango è il mondo. A se stesso leopardi 1834]

 “All is noise, unending suck of black sopping peat, surge of giant
 ferns, heathery gulfs of quiet where the wind drowns, my life and its
 old jingles”  Beckett

// *maybe overlay as text on argotine*
No more fruit, no more trees, no more vegetables, no more plants pharmaceutical or otherwise
and consequently no more food, but synthetic products to satiety, amid the fumes, amid the
special humors of the atmosphere, on the particular axes of atmospheres wrenched violently and
synthetically from the resistances of a nature which has known nothing of war except fear.
[Antonin Artaud. To have done with the Judgement of God.]


*** smithson

...the medium is the mummy.

[Robert Smithson. The Artist as Site-Seer. The phrase is footnoted as follows: 58. Substance is excluded.]

The shapes of the chasms themselves become "verbal roots" that spell out
the difference between darkness and light. Poe ends his mental maze with
the sentence — "I have graven it within the hills and my vengeance upon
the dust within the rock."
[A Sedimentation of the Mind. Robert Smithson. 1966.]

In a 1972 letter to Allen Overton Jr., president of the American
Mining Congress, “regarding my relationship to the mining industry as
an artist,” Smithson grandiosely declaimed about his work’s
transformational nature: “I am developing an art consciousness for
today free from nostalgia and rooted in the processes of actual
production and reclamation.... Industry cannot afford to view my kind
of art as a luxury, but rather needs to view it as a necessary
resource. My earth sculptures are of primary concern, not secondary. A
dialogue between earth art and mining operations could lead to a whole
new consciousness.”

The following is a proposal for those who have leaky minds. It could
be thought of as The Mind of Mud, or in later stages, The Mind of
Clay.

https://holtsmithsonfoundation.org/sedimentation-mind-earth-projects

*** Poe

This opinion, in its general form, was that of the sentience of all
vegetable things. But, in his disordered fancy, the idea had assumed a
more daring character, and trespassed, under certain conditions, upon
the kingdom of inorganization. I lack words to express the full
extent, or the earnest abandon of his persuasion. The belief, however,
was connected (as I have previously hinted) with the gray stones of
the home of his forefathers. The conditions of the sentience had been
here, he imagined, fulfilled in the method of collocation of these
stones –in the order of their arrangement, as well as in that of the
many fungi which overspread them, and of the decayed trees which stood
around –above all, in the long undisturbed endurance of this
arrangement, and in its reduplication in the still waters of the
tarn. Its evidence –the evidence of the sentience –was to be seen, he
said, (and I here started as he spoke,) in the gradual yet certain
condensation of an atmosphere of their own about the waters and the
walls. The result was discoverable, he added, in that silent, yet
importunate and terrible influence which for centuries had moulded the
destinies of his family, and which made him what I now saw him –what
he was.

[Edgar Allen Poe. The Fall of the House of Usher]

** inferior geology/other essays? sonic acts 2021. peter. finland bog reader but that is about cycles...

*** inferior

idea of interior/inferior...

Inferior astronomy is another way of naming transformative methods for
working with plants and with metals. Astronomical discourses are
re-interpreted as referring to the terrestrial; planets become
metals. It’s an historic analogy, a set of identities or
transformations which help to make sense of certain early texts
treating the planets in mineral and muddy terms and as, at odds with
the celestial, undergoing earthy and earthly process.
 
Inferior geology seeks to further these transmutations, resting
equally on a magical closeness to the key phrase of “interior
geology.” If inferior astronomy brings the planets down to earth,
within the primacy of substitution which is called occult and is
recognised as such (this spiritual work with matter was always already
astronomy, inferior astronomy just marks that connection within the
realm of metaphor), then what substitution is being pointed at as
already having happened in thinking the geological as always inferior?
That it is rendered earthy? That it becomes of bodies and of
circulations without reference to marked, measured and seriously
differing time scales?

Inferior geology naturally also refers to a geology which is
“inferior” to some officially defined geology, less stratified
perhaps, more psychically re-churned and de-sedimented. I’m trying to
think of the peat, of the mud mind transmuted into the bog mind, of
Beckett’s “All is noise, unending suck of black sopping peat, surge of
giant ferns, heathery gulfs of quiet where the wind drowns, my life
and its old jingles” jangling within applied and applicated, sewn and
freshly black fibrous science. Inferior geology could also refer to
seismology, with its Love waves and Rayleigh waves, other forms of
faster application, disrespecting deep geological time. Inferior also,
in an original sense, as a breathing beneath, the earth evaporating
beneath the moon and the stars, sinking deeper into the sucking, and
slowly shattering.

*** finland

SR Hyytiälä reader narrative - now in reader outline/text:


Yes, reader, countless are the mysterious hand-writings of grief or
joy which have inscribed themselves successively upon the palimpsest
of your brain; and, like the annual leaves of aboriginal forests, or
the un-dissolving snows on the Himalaya, or light falling upon light,
the endless strata have covered up each other in forgetfulness.

[Thomas de Quincey. The Palimpsest of the Human Brain]

Within the frame of the Shift Register project, the workshop at
Hyytiälä was long conceived as an approach to how to start thinking
about and acting within non-linear geologies in relation to earth and
media. We wanted to seek alternatives to a (perhaps simplified and
necessarily fictional) perspective on geological time as linear, as
sedimentary and stratified, and to experience these alternatives
within both the environment and human media. A stratified view of
geology is bound up inextricably within the very culturing of notions
of the laboratory planet and the Anthropocene itself. The Anthropocene
concept which bears the tracing weight of the planetary laboratory is
a geological boundary condition defined more precisely as a potential
"Global Boundary Stratotype Section and Point (GSSP)" within a
stratified layering of geologic stages mapped out within geologic time
scales which are read within a linear history. In plastics and rocks,
bones and stones, reductions in biodiversity, changes in erosion and
deposition, in layers of trace elements such as black carbon and
excess of carbon-14, in these crystalline layers of spars, humans,
minds and memory reflect on an idea of nature and of environment. A
palimpsest of "endless strata [covering] up each other in
forgetfulness." De Quincey adopts a geological mind metaphor
pre-dating the mud mind of Robert Smithson.

We wish to have done with this mind-geology of God, as theological as
the creationism of the scriptural geologists. Yet, is or was geology
really quite so linear? We read of the literal unconformity of James
Hutton, the Scottish father of modern geology.

He famously concluded "The result, therefore, of our present enquiry
is, that we find no vestige of a beginning,–no prospect of an end."
Geologic time is deep, yet cyclical (rock cycles of uplift, exposure,
weathering and deposition), self-maintaining and infinite. An abyss of
time; this was Hutton and later Charles Lyell's uniformitarianism
which proposed a gradualism in contrast to a potentially linear
catastrophism suggested by successive and cataclysmic terrestrial and
extraterrestrial upheavals and impacts.



It is a living thing, which no more dies, but when used gives an
eternal increase.

I had visited the Hyytiälä forest research station as part of the
wonderful Climate Whirl workshop in 1025 organised by Ulla Taipele and
Janne Korhonen titled The Art of Measuring the Woods Workshop. We
learned how to study the growth of trees, cutting and analysing tree
rings with forest scientist Kourosh Kabiri, built chamber systems to
measure C02 and other gas exchanges with environmental and forestry
scientists Elisa Halmeenmäki and Janne Korhonen, and calculated the
albedo with artist Mari Keski-Korsu amongst many fruitful discussions
of climate change, time-scales and sauna-culture. At the same time the
laboratory forest is in evidence at Hyytiälä; snakes of pipes and
clusters of compartments, cables and sensors underpinning the forest
and hidden by the now-thawing snowfall, finally routed into Alpine
huts crammed with further measurement and data processing
equipment. The collected data, focussing on climate change indicators
within the laboratory planet, is further routed across global networks
and stored in universities and data centres. The experience of The Art
of Measuring, divided between meditation (drinking tree sap),and
scientific measurement across micro and macro time scales informs some
of the way of thinking about Shift Register and the laboratory planet.

We started talking to Ulla about organising a workshop at
Hyytiälä. During the first conversations we had, Ulla mentioned the
vast peatland which also forms part of the studies of the forest
research station (atmospheric exchange and carbon sourcing and
sinking), and which could form an interesting research location for a
workshop focusing on non-linear geologies and the experience of
cyclical time. In my mind was always an image from Splendor Solis a
16th century illuminated manuscript describing alchemical and
spiritual process. The image shows a man emerging from a bog or swamp,
being welcomed by a winged angel bearing a red or purple coat. The man
is black, his outstretched arm is white, his foremost arm is red, and
his head is enveloped in some kind of red alchemical bubble or
apparatus. These colours describe three stages in the alchemical
process, three colours of the philosopher's stone. The first, black
stage which the figure and his emergence describe is fermentation,
putrefaction, darkness or decay. This stage can also refer to the
Prima Materia, the first matter of this material or exo-spiritual
action. This is the Crow's head. The second stage is white and is
called Albedo. It is associated with purification and perhaps with a
separation of elements. In The Art of Measuring the Woods we measured
Albedo with Mari Keski-Korsu; she designed a range of clothing and
white cloaks to improve the earth’s Albedo - a scientific term
describing the measurement of how much light that hits a surface is
reflected without being absorbed. It is very important within studies
of global warming and climate change.

The final stage is called rubedo, a reddening or purpling perhaps of a
dawn. The red powder multiplies all gold, all dawns, and the purple
robe allows ascendance to eternal life. A few days later I could see
the original copy of the Splendor Solis manuscript in Berlin as part
of the Alchemie exhibition at Kulturforum. A few books such as Jorg
Vollnagel’s Splendor Solis: Studien zu einer deutschsprachigen
alchemistischen Bilderhandschrift and Paul Cowlan’s excellent Splendor
Solis: A consideration provide historical background and attempt
various decodings of the emblems and accompanying texts of Splendor
Solis.


Re peat

We have chosen to look at cycles and circulations across both
peatlands and ancient forest which offer timely experiences differing
from the stratifications and layerings of 19th century landscape and
geology which have perhaps informed scientific theologies of the 21st
century. We set bogology against geology and ask what a bogology of
contemporary media might look like, equally set against the layered
and networked sensors of the earth as living lab. In conversation with
Erich Berger peat becomes a churning layer compost of ideas. He talks
of:

Carbon cyclings.

Peat as interface - fed from both sides as in above (plants etc) and
below.

Peat sampling is used as a way to check out underlying geologies -
site assessment eg. looking at the concentration of minerals in the
peat as it breaks down geologies.

Peat as fossil fuel in the making.

Life in the peat - upper layers.

We could sieve and examine peat, burn peat.

Bogs as more about preservation (like salting food - bog butter, bog meat) - taking water out of cells.

Notion of enrichment in relation to carbon.

Bog iron and bog ore.

Peat forms a massy, ancient, living archive which is both decay and
preservation. Food like butter can be preserved for thousands of years
in the bogs, and there are folk myths concerning the peat bog as an
eternal giver of food or meat. Bodies are preserved in the bog; a
parallel living/dead population of hundreds of men and women stretches
back tens of thousands of years. They find another home in museums.

Peat is a carbon source and sink: in cyclings of decay and living
matter the peatland exhales and inhales carbon dioxide in
equilibrium. It was used for many years as a source of burning fuel
and it is the precursor of geological fossil fuels such as coal and it
is and is not geological. It is a living thing, which no more dies,
but when used gives an eternal increase. It is prima materia, first
matter, and this is carbon. It gives a peaty flavour to whiskey
through burning: torfig.

Splendor solis

And Splendor Solis is the splendour of the sun coming after the rising
dawn and emerging through an anthropocenic landscape under the emblem
of the black or oil sun. The image of the swamp man and the angel is
the eighth illustration in Splendor and it accompanies the fourth
parable which describes the philosophical background to the emergence
of the darkened man. "She clothed the man in a purple robe." This
short treatise ends with the sentence: "It is a living thing, which no
more dies, but when used gives an eternal increase." This becomes a
motto for the emblem and workshop. This image stands within a linear
sequence of 22 images, along with various parables and treatises which
describe the alchemical process. The book Splendor Solis (of which
there are 20 copies, with some translations from the original German
into French and English, stands within a cyclical history of written
alchemical practice spanning 2000 years, shifting across geographies,
theologies and cultures. Splendor Solis shows and unearths its own
roots in borrowing ideas and expression from earlier alchemical texts
and emblems, including the works of Zosimos of Panopolis writing in
third century Egypt. It borrows in particular many concepts and texts
from an earlier German translation of the work Aurora Consurgens, the
rising dawn, a curious blend of alchemical recipe and
Gnostic/theologic re-appropriation. The roots of the laboratory forest
run deep.

The swamp man and angel emblem is followed by the image of a royally
clothed hermaphrodite in the forest, holding in one hand a target and
in the other an egg. He has two wings, one white and one red. He
stands on a scattered white mould of soon sprouting mycelium at the
edge of the forest floor, close to the paths. The previous image
depicts a drowning king and a confused and newly risen world king
holding a golden orb. This is one beginning of the cycling work.

This reader (and perhaps the workshop) is structured around the
emblems, acts and theatre of putrefaction (nigredo), circulations and
prima materia.


interview with peat person?

Some paleoecological studies have been conducted, both already
published and some still ongoing work. In such studies, a peat core
from the surface to the bottom is taken. In such core, you typically
see if the peat is mainly composed of sedge remains or Sphagnum
mosses. One can also find rather well preserved plant parts: seeds,
pollen, leaf sheaths, branches, Sphagnum moss. Sometimes
paleoecologists can tell the exact species grown at the location
thousands of years ago, sometimes just the more general species group.
The main reason for plant parts to be conserved are the anoxic
conditions under the water table. In addition, many peatland plants
are resistant to decomposition, for example dwarf-shrubs (high
phenolic content) and many Sphagnum moss species.

*** sonic acts

immersion and contact in the earth - describe arsenic and cyanide muds
caking clothes, skin and car interior, paranoia about what could be
described as EXPOSURE

from the earth considered as something exterior, that which is acted
upon by humans, a laboratory planet - to the earth and geology as
something incorporeal, incorporated and interior

idea of interior or internal geology, a fantastic voyage from
*inferior geology*, the underneath, vast dripping caves and mines
supplying energy for the server farms above ground to interior geology
(informed by the discipline of medical geology).

[note: In the concentric circles of his “lower Astronomy,” this
diagram Ripley provided a terrestrial analogue for the planetary
spheres: encoding his alchemical ingredients as planets that orbited
the earthly elements at the core of the work.]

*bringing the planets down to earth as metals ripe for extraction*

immersion and contact in the earth - describe arsenic and cyanide muds
caking clothes, skin and car interior, paranoia about what could be
described as EXPOSURE

further projects soaking in the soft geologies of ancient peat bogs,
cleansing and energising effects of bathing in radon (radioactive)
water in abandoned uranium mines.

delving into the science of medical geology - what does the geological
realm have to do with (human) health - notions of planetary health

explain pharmakon /chart image/, idea of dosage (pharmakon - the
poiosn and the cure, Paracelsus, Derrida writing as pharmakon -
technology as pharmakon in instituting the cut, the refinement)

We believe that the earth should remain as pristine and untouched
nature; we have no desire to carry on extracting resources from a
depleted world, polluting and laying waste to the landscape. Saving
the planet is now a matter of becoming sensitive to our own geological
being. In mining ourselves we gain knowledge of our own bodies, our
selves and the global environment. This is a final ecology for the end
days. Nature will remain and our technologies will now be sourced from
within; we will thus no longer be dependent on scarce and already
polluted environmental resources.

enacted as a series of now online sweatshops - meditations on metals
and elements (each participant is assigned an element which they work
with) 

ingestion, chelation, testing and extraction following planetary and
elemental cycles

*** peter the cut and refining - 

where do we talk about that cut... how far we go into extraction and
refining....

In the case of the "solid" crystal which forms the detector, one
essential element within the construction of a crystal radio set,
rigged up recently as part of Peter's Crystal Weekender [ref], we
cannot point solely to the fine gold wire, or to the crystalline
mineral (such as leaden mined ore galena) with which it makes conatct
as prime operative agent in this focussed radio wave detection, rather
it is the un-narrowable point of flow and assymetric exchange between
these two cut and sometimes-refined earth mineralities, a flow which
extends and entrails outwards through all of the earth. The cut and
the division is the extension.

Thermal techniques are operations that produce "cuts" in this flux
(Barad 2007), tease out different material potentials, and shape
"solid" media out of geological substances.  
[Starosielski p295]

Commercial metallurgists relish in the torture of raw ores pulled
from the earth. 

In this fantasy, the cheese maker could also be a barbeque chef,
doping the pure silicon of meat with hickory smoke, and she could
equally be cast a mock sacrificial priest. The continuous extensible
bodies are cut, seperated, torn asunder, hewn like tree trunks,
slayed, divided and lead forth into the corruption of killed
bodies. Commercial metallurgists relish in the torture of raw ores pulled
from the earth. With reference to pasteurisation Bruno Latour talks of
the scientist as now being able to "starve the microbes, kill them
with antiseptics, make them eat anything, in short, torture them in
innumerable ways, in order to learn something about them each time"
[1988 the pasteurisation of france]. Fermentation is an "uncanny
figure of flourishing death via self-digestion [which] demonstrates
the limits of the assumed logic of cyclic repetition."  [p10 beregow]

drawing swiftly on the deepest foundations of geology, "to
consider [...] the globe of this earth as a machine, constructed on
chemical as well as mechanical principles."  [216?]

... it’s worth dwelling on the fact that the mass of once living
organisms that have returned to base matter has been estimated at
somewhere between a 1,000 and 10,000 times the mass of the Earth
itself (see Davis 1996, 73), while as far as scientists have been able
to ascertain, matter has only organised itself into life but once on
our planet. There is, then, something of an asymmetry between the
transition from base matter to life and the traffic that passes in the
inverse direction. 
p45 [**** Deep Shit. Nigel Clark Myra J. Hird]

For both Low Places (Hutton's geological foundation) and Sour Bodies
(Alexander Flemming'a antithesis) the liveliness of this earthy
machine depends on essential dissolution and decay, the grinding down
of rock to sand:

A solid body of land could not have answered the purpose of a
habitable world; for a soil is necessary to the growth of plants; and
a soil is nothing but the materials collected from the destruction of
the solid land. Therefore, the surface of this land, inhabited by man,
and covered with plants and animals, is made by nature to decay ...
[215]

Decay and dissolution are essential for the creation of this least
sour of all possible worlds, if solely to show us that it is not simply a
machine in its breathy running down into disrepair, a chilled-out heat
death and burial:

But is this world to be considered thus merely as a machine, to last no
longer than its parts retain their present position, their proper forms
and qualities? Or may it not be also considered as an organized body?
such as has a constitution in which the necessary decay of the machine
is naturally repaired, in the exertion of those productive powers by
which it had been formed.
[216] Hutton Theory of the Earth, Volume 1 (of 4)

Contrary to this running down, where does the power in "the exertion
of those productive powers" come from that enables a dough-like
raising up from the low places, if not from those heavily invested low
places? Where does this "necrological vitalism" [ref] spring up from
and how like SB+LP can we forge crystalline junctions between these
disparate matters, between coal, crystals and liveliness?

For eighteenth century protozoic geologists, this work of mountain
building, of upheaval, is produced by a “machine” using force “either
produced by steam, or by extremely thin and dry air.” [ref] The insatiable
birdie, dunking bird, drinky bird, water bird or dipping bird in
this case is the steam engine or difference engine. And what is the
source of heat which powers and does not define this engine?

... combustion of coal [...] each cycle forms new continents which produce
new forests; their destruction on turn forms new layers of coal."[ref
p.120]


*** arsenic eaters

XX mining gnomes

III deal with the devil

xxix living dead. submit to death - eating arsenic was an archaic way of staying alive.

the simulateneity of life and death

through arsenic's preservation they had become the living dead.

** 2 or 3 illustrations for intro

argotine box...

what else? sweatshop images - full pages - how long???

** Notes so far/notebook:

Old earth, no more lies, I've seen you, it was me, with my other ravening eyes, too late.
[Samuel Beckett fizzles]

We have always been geological.

beckett 1929 letters p152(252?) - on dew???? can't find Writing up the
day's events in his diary, Beckett suddenly confesses to be in the
'mood', and notes down two and half lines of poetry in his diary
(German Diary Notebook 4 [hereafter GD followed by notebook number],
7/2/1937)

Always elsewhere

In body also

The dew falls + the rain from

*Structure: 3 dreams and 3 sections TM, theory, artistic work*

1. the blue light. sweatshop dreams. // TM // mining - toad/earth - Becoming metals -  becoming as antimony, as arsenic, as copper, as iron, as lead, as mercury, as silver, // becoming earth
2. the turf house, the front and back of the house, grave, entry and exit. off-world // theory theory - wings eagle // becoming cosmic - origins. *leaving the planet*
3. of the re-presentation of the bog bodies in the museum. the gold around the bezoar. margarita of austria's room // art art - snake // becoming mineral? becoming earth - re-presentation

in the sweatshop
in the turf house
in the museum or gallery

// copper/Dennis

*Heavy crystal sediments near the top.*

Last night I had a dream of playing a computer game. A glitch enabled
me to physically travel through dimensions. I ended up in the atelier
of a friend housed atop of a well known hamburger restaurant, which
doubled as a ‘hidden in plain sight’ security check, preventing random
people from going upstairs. In the atelier floated a sphere,
resembling the cryogenic containment unit from Akira, cables coming
out everywhere. It had a brown copper hue to it, but that could also
have been isolation material or even wood. How did it float?  This
‘device’ allowed you to trigger ‘lucid déjà vu’ allowing you to relive
memories as you wanted. Realising I was already in another dimension,
I did not want to go further. We all left to go to a club. Exiting the
restaurant someone had parked a trailer under the trees. My attention
was drawn to the shiny assortment of shapes faintly visible through
reflection of the faint moonlight penetrating the canopy. Upon
inspection the trailer was full of alumiium extrusions in every shape
and size you can imagine. Every piece was unique, except for their
perfect shiny, brushed finish.

// lead/martin

In the first I’m pissing into a toilet and each stream is accompanied by an intense blue
light – like a gas light, and maybe even the smell of gas as if there could be an explosion. This
could relate to the use of flame spectroscopy to analyze heavy metals in organic matters (such
as hair). The blue would correspond to the colour of a certain metal – such as lead itself or
arsenic.

In the second fragment we go past a kiosk (in Cologne) with two fresh fish stalls nearby,
run by Vietnamese people. Outside one of these stalls there are two older men, scruffily
dressed and with red, bruised faces, looking a bit like old English standup comedians. They
are there to entice people to come and see/buy the fish. At first they hold up the fish but
later they bite pieces of fish and then spit them out, catching them and spreading them on
their faces, to make a new face. 

They lay blue pieces over their eyebrows and other features, making
their faces more bruised and blue looking. This relates to the seafood
diet for the first three days of the sweatshop. Again a metallic,
bruisy blue colour.

/// new beginnings

describe the first sweatshop - from in time with new moon... 

dreams of blue light (lead), of giant bumble bees (antimony), of a
musical group and a metal mouthpiece (mercury), of aluminium extruded
realities (copper) ... extraction seems to engender giants, monsters
and visions.

copper man vision zosimos. metal as a body

Geology is an unconscious (not our unconscious - subtexts/mackay,
moynihan-spinal). Countering and contrary to contemporary opinion
ranging the history of science, the alchemists did probe these
material depths. The bog bodies are dreams and visions, which is why
the museums (Drent,etc) insist on their repeated re-presention - the
literal return of the repressed in a very real sense (the alien, the
pagan, the nomad, black death, the odd symettry of El Majusi - geomancy).  

We have to go much further, much further back! And faster.

///

that it is not just about this new circulation/cycles - of:

With the arrival of the questionable era of the anthropocene, marking
another entry point into the planetary geological, a new “natural”
cycle is initiated - we literally inhale and ingest our own
anthropogenic indicators (for example, as the particulate exhalations
of burning forests, as isotopes from nuclear testing, as metallic dust
from global extractions). These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms.

illustrated by for example, the extraction of native copper ores from
the earth, their refinement and use in underground cables, carrying
human bound screen signals decoded, their later un-earthing and
recovery, a smelting operation releasing particulate copper and other
matters which is then inhaled or ingested, entering active and passive
species including humans. 

inhale mercury fumes from crematorium stacks

These cycles are solely meditative and illustrative... they are too
material, too logical and explained, they are merely a recursive
apparatus flip-flopping betwixt the knowing anthropogenic and the
imagined lithic? a recursion which admits only itself, no others, 

remediation as recursion

 but there is something else there - not just an authoring of the
earth (as Moynihan writes...) - crystal world bit in spinal - the lithic

becoming cosmic
becoming dirty
becoming geological

how to merge surtsey bacteria analysis and a dream/blue light?/sweatshop dreams: where is surstsey one: above

- leaving planet/attachment to a specific geology - moynihan - as origin, as psyche/geotrauma

also mining/own geo resources are more in need of conservation as we
mine for other resources in more hostile off-world environments (who
apart from aaron writes this? patricia?)

- artists and geo re-presentation. not so much about the anthropo-sublime but re-presentation of bog bodies. also in rosemary - showing this


a dwelling in the earth
in death we become as earth

iron snails in guardian

quote TM dream... blue light

TM->becoming geo-> contents here

bog bodies: what is they enable us to think ahead of time. providers from the past. idea of sacrifice. also idea of reflection, witnessing in that text... body and geology as witness (schuppli)


alfonso: all the action/narrative could be taking place in the cabinet/room of margarita!

The gold and cabinet encircling the bezoar are the not-wanting just this raw foreign thing!


as manifesto or statement

//iceland notes

turf house as a /relation?/ VEHICLE for becoming geological. house of earth and volcanic stones/lava

traditional - the front of the house, wooden gable, girls greeting tourists (bus engine left running) in threadbare costumes from a hundred years ago, ghost photographs

from the front windows, low wooden desk looks out on graveyard, on the church, the mound of earth covering the farmer's body

behind the house - the earth, new habits, new language (also behind Wolf Vostell sculpture, and recent dream with icon/crucifix/jesus... 

last house - the life support system of pipes, air conditioning, the last breath... (Teemu)

turf house as a grave

- conversations with Judith: Surtsey, subsurface bacteria
  there. portals, also geology which is neither living nor dead -
  outside these categories... nodes of life and death, outside these
  terms

*patricia also mentions leaving earth behind...where?*

between geology and biology, neither nor

iceland spar man - geological cheese (peter) - ref. bacteria for icelandic porcelain. spar/binary of calcite, polarisation of light

iceland as mostly geologically young...

golden circle. shit circle (Salo)

antii subsurface glitches... orbital turf house...

*** TM intro/start of all - new notebook 16/8+

In November 2020, a small group of artists, chemists and geologists,
made a first attempt to collectively mine certain minerals from within
their own bodies. These actions brought forth monstrous visions. What
should have remained hidden (the secret life and genesis of metals)
was exposed to the light, unearthed. 

where does this lead, this body as a mine, as a resources, as a metal,
copper body, man of copper, what are the consequences of these actions
for thought, for being what we are when we say what it is to be human,
or what comes before this saying (patricia), for the world - the
dystopia of tiny mining, final frontier -> visions of zosimos -
natural way of doing things

that a body can now be any landscape, a body as a site of tailings, as
a suburb, as a logistics centre on the outskirts of a small town,
between motorways, as a overgrown heap of rubbish grazed now by sheep,
a new mountain amidst the dykes and drainage canals 

a body as landscape, depicted, scanned and stretched, re-skinned, 

bog body is a landscape

if the body can become a mine, a prospect with associated legal
frameworks and permissions, with its waste piles and tailings, its
slag heaps, its .... to be inhaled, incorporated....

body as jachymov - that history, biography of a body, drunken tanners dogs vomitting (reference?)

humankind has always been harshly geological, authored by geology, sedimentary beings, the result of million years of spinal deposition. 

what is new now - entry into new cycles - new way of living and dying, artistic approaches??? (marder)

islands of decay in Elaine/arthur and in Ilana H book (felt events) p. 73 Jerry Zeeee

Flesh occasions stone, and the submerged corpse is a landmass in the
making [...] it is the core of a composire necromineralogical
thing. It friction in the flow of petrifying water invites the
precipitation of islands@ the skin's drag is a small obstruction where
dissolved mineral load builds up [...] The corpse harbours new land,
even as it gives itself over to earth. The skeleton, the organic stone
within the corpse, anticipates the rock that will form around it.

becoming geo is to start with the cosmic island

core themes: 
- decay, death, preservation // bog bodies, immortality (immortality of athropocene)...
- origins (Moynihan)
- dis-articulation (of logical strata). dislocation of landscape -in dreams, of body, of a representation - a frame?island
- particulate matter

Smithson - mud mind, Beckett 

miasma vapours

* how to structure

dream, diary

or: dream, vague introduction/a scene, more specifically relating to the contents 

1. TM dreams. colours of burning metals - tests

2. Iceland turf house - bog bodies, representation, being covered in earth. buried in handfuls of peat warmed by geothermal waters collected right next to the tarmac

Judith:

3. jachymov - uranium cross. immortality, the afterlife of Elaine/Arthur

as a dream and include the vomiting dogs

In the third dream a priest leads us from his house, crammed with
artefacts from a burnt-out church, crispated altar paintings, into his
garden. Chickens, uncooped, run wildly at our feet. The priest is
tall, with long dark grey matted wet hair, and a long white beard,
crinkled and slightly curled. He opens a stout metal gate set into the
hillside near the chicken house, one corner of the garden, and leads
us deep into the narrow mine shaft, into the evil. As a giant leads a
troupe of dwarfs.

// all grey with frozen dew - 

drunken tanners dogs

what we want to say in each case.

series of dream and their interpretations - eg. dennis dream as the logic of metals, colours of other dreams...

** 0. general intro...

Humankind is and has always been geological; as both origin and
destiny, as inhaled and ingested matter, as medicine and willing
poison, as a divine or sublime power, or as adornment and
technological extension. We are forever involved in its cycles and its
(destiny?)

what it is and how do we know enjoy, embrace, reject or unfurl through
this proposed new becoming

marder asks how in 21st

what book does/sets out to do

- how we arrived here,,, by way of TM, body as a resource, cycles of ... awareness PITCH notes

i never imagines that becoming geological could become so
labyrinthine, so obscure, so buried in cyclings and feedback loops -
unending tunnels miring and undermining the sky and the mountainside,
in search always of different ores, everyday ores.

- what it is, why it is important - the geologic is our fixated,
  addictive and necessarily obscured or covered up logic
  (steganography, stratigraphy...) - our beginning and our end.

important - as origin, as conditioning us. as determining us, our living conditions, as our unconscious, to go backwards, as our depth and setting

as diet, as inhalation

what are the strata (cosmic, atmospheric, earthy, geologic) we probe, explore, dwell in and dream in, that we ingest...

** 1. Becoming metal. TM. mining dreams

dreams and describe sweatshop - importance of visions and dreams -
p.239 spinal - de quincey palmipsest and dreams

Yes, reader, countless are the mysterious handwritings of grief or joy
which have inscribed themselves successively upon the palimpsest of
your brain; and, like the annual leaves of aboriginal forests, or the
undissolving snows on the Himalaya, or light falling upon light, the
endless strata have covered up each other in forgetfulness. But by the
hour of death, but by fever, but by the searchings of opium, all these
can revive in strength. 

We have to go much further, much further back! And faster.

acknowledge Agnieszka

** 2. Becoming earth. theory. death and decay.

begin with Marder definition/statement of what it means to become
geological in the 21st century - or to do this in general intro

to live and die every day... Agnieszka - that we are dying

islands of death and decay - Elaine/Arthur and Patricia. quote from Halperin

the idea of origins Moynihan and the becoming cosmic

that in the face of climate disaster and anthropogenic global change -
rethink the terms of this "in the face of" - that it is not about
finding solutions but...

marder - place gone mad, poe/usher...

becoming geo means to become a resource, a reserve, to take on and
into one's own body and self that which is enacted on a landscape, to
provide the technological gems and accoutrrements, the extensions of
that body, to become literally that body

where we write elsewhere? - technology is extracted from the
environment or landscape at the same time as being an extension into
that landscape, reaching into and providing a means of representation of that exhausted landscape

these double movements - we extract in order to extend into, to blanket and logicise

** 3. Becoming cosmic. artists. re-presentation and incantations. data. atmospheres. body and earth.

world as will and representation. how are these global changes present
for us, how does becoming geological come to be represented as a
vision, as a mind, as an image or set of images, as a representation "for" who...

how is extraction and the extractive landscape re-presented ? modes of presentation of the geologic body

** where/death/what we want to say?

BG fronts and confronts death; the death of oneself as an individual,
the death of others, the death of a pig, the ends of worlds and the
death which enters as a breath into the living.

strange loops and feedback loops: These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms.

that geology writes us, that we feedback on this geology - also mackay
in intro....

that the place is sentient - how to divine the sentience of a place

that we are this place - we are a landscape. an internal landscape,
flipfloppings of ballardian

If the descent into the mine, into the earth, a hole to hell, is
viewed as a journey towards a dark interior, into the unconscious,
into dreams, or inside that old fossil, the profound soul, then what
does it mean when that interior is mine, a fantastic voyage, with me
or by myself. Ouroboros-like I double back on my own interior, but to
one side, an interior which is not mine, strangely, An oozing and
lacking dream inside a dream. We are doubled but not as a human of
light and of darkness. We are both shades. // shades as a
material. phos/Zosimos... leads into the vision - man of light

The feedback loops crossing ... tighten, becoming internalised and
fault-line stressed.

journey into volcanic tubes, the screen, giving light... always
scanning (the cover image)...

That this descent is also a retrogression in time. As Moynihan writes
in Spinal Catastrophism (an essential complement to the essay here), a
geognostic work which is precisely concerned with this internal depth
as geotrauma, "depth is time." 

"Steno was the first to note explicitly that stratigraphic succession
corresponds with temporal succession. In other words, that /depth is
time/. (Hence, centuries later, McPhee's coinage of '*deep
time*'). This marked the inception of the notion of /depth as mnemonic
and temporal retrogression/ that would later be so vital to
psychoanalysis or so-called 'depth psychology' (Tiefenpsychologie).

[p86]

The Tiny Miner coils inwardly on her own inward mined depths. 

Further "Steno's Stratigraophic Law [implies] that all space and body
is itself nothing but coagulated time" 87 -> Ballard crystal world as
a further manual for BG

Spinal cat:

But when one’s past is a story of quakes and perturbations, the
internality implied by ‘one’s own history’ begins to
unravel. Ultimately, discovering finitude entailed discovering that
thought is functionally internal to itself, but self-containment
becomes problematic when modulated through the dimension of Grand
History. Here, ‘internality’ and ‘inclusion’ are reconstituted as a medium of
ancestral selfabruption rather than telescoping self-similarity and
ownership. What is at stake, then, is the realisation that the
historical vanishing point of selfcontainment just is self-exclusion:
in other words, depth. Historically speaking, I contain my
outside. This is what time does to a body, as we shall see in tracing
out this Secret History. The lesson is clear: psychosomatic
containment of oneself, when percolated through Grandest History,
equals hypogene alienation—the alienation of a body riddled with
time. It is this realisation that is inaugural of the phylogenetic
phantasy that is Spinal Catastrophism.

p50,51

For Ballard, a consistently nonconforming Kantian in his approach to
spacetime, temporality becomes a global secretion of the CNS

p77

Indeed, Ballard prophesies that, at the lowest spinal-neuronic
levels, organic self-inclusion completely evaginates into the
‘inhospitality of the mineral world’, its ‘inorganic growths’, its
‘profound anguish’, as in The Crystal World, where the deepest
entropic future leaks backwards into the present.21 Time bends into
itself, cephalopod-like: accelerative lurch into the entropic future
is nothing but thoracic drop into the preorganic past.

p102

mackay p2 - the descent takes on the character of a disturbed dream

At the same time it is essential to note, as Mackay observes that
this subterranean descent, this romantic or sublime path of soul-full
healing, "a healing return to the matrix of an all-encompassing
earth-process and thus to a more profound soul, dark double of the
self condemned to surface dealings" arises "precisely in parallel with
those other compulsions that were beginning to exert their cosmetic
dominion over the face of the planet. It is the shaping and hauling
and digging and layering of infernal machines that opened up new
breaches and passageways through which the other soul could pass."

- how this could parallel with contemporary situation of becoming
  geological... we become this planet and earth process, descend into
  our own more profound soul...

[p1. subtexts] Mackay - cryptolithic passions (intro to compilation of geopoetics - elaine)

Geology is the study and enabling of articulations, formations,
ingestions of inhalations of particulate matter, uranium-235,
conduits, fracking, descents, carbon dating, deep time, metals, the
cut, bedrocks, cavities, caves, chasms, tailings, leachings,
radiometric dating, orogenesis, dumps, lithologies, stratigraphies,
mineral resources, extractions, boundaries, outcrops, chronologies,
leachates, sulphides, percolations

becoming dump - list all these becomings also as suggested by Agnieszka

becoming geological is to become as these and many others

planet as body - becoming cosmic

body as planet

Spinal: p220

Oken noted that the ‘[e]arthly organs must correspond to animal
organs’: or, the ‘mountains, rocky terrain, [and] cliffs’ must find
their analogues in our own innards. If teeth are nails, then nails are
just stalactites. ‘Just as the animal body is finally composed of
these organs, so the composition of rocky terrain must produce a
terrestrial body, which is the planet’, Oken pronounced.13 From Ritter
to Kielmeyer, Schubert to Steffens, the Naturphilosophen were in
agreement on this: ‘[i]norganic matters and activities pass parallel
[to] the anatomical formations and functions’, as Oken put it.14 He
went so far as to say that ‘[o]rganism is what individual planet is’
(because the ‘primary vesicle’ of the embryo, in its globular form, is
but a repetition of the forces that ‘produce’ the planet itself).15
Steffens summed all this up adequately when he wrote that, given these
principles, every animal, plant, crystal, and mineral represents a
‘stage of [terrestrial] development’: the totality of which, taken
together as one goliath constellation, would thus provide the ‘true
history of earth’.16 History is just the decryption of the relations
of body parts; body parts are just a matter of encrypted history

226 **important

If the planet is a brain, only a vanishingly small amount of its
trillion-cubic-kilometre volume is not lithified and dead. And, as
intimated above, it was in attempting to internalize —or digest—the
planet’s magmic inorganic depths that Spirit developed the ulcer we
now call the Unconscious. In other words, Recapitulation’s attempt to
retain Identity through Natural History’s temporal torsion ended up
sacrificing idealism’s Law of Continuity (at every psychic and somatic
level): the self-identical telescopic inclusions of Leibniz’s prior
‘fractal vitalism’ now became internal heterogeneity and layered
self-exclusions (or, stratification: the internal trace of Grand
Time). Idealist containment spectacularly intussuscepted into a
layer-cake of internalised self-exclusion: this was the invention of
philosophical Depth, or the evagination of telescoping self-inclusion
into invaginated and stratigraphic self-exclusion. And so, this is how
Schopenhauer could finally state that consciousness ‘is the mere
surface of the mind, and of this, as of the globe, we do not know the
interior, but only the crust’.

253 Mineralization streaks through organic form: from basic examples
like ‘Shells’ to ‘Mother-of-Pearl’ and ‘egg’ up to ‘cartilage’ and the
chitinous carapaces of ‘Lobster-Claws’; ‘still higher, Zoophytes
[i.e. corals] repeat the process’; and, at ‘the summit’, ‘Bone’ and
‘Teeth’ conclude the conservation, or reuptake, of the geological into
the biological.24 In a vision arguably even more fevered than that of
Kubla Khan, fColeridge thus witnessed lithic externality snaking its
way throughout organic inner time: he noted that annelids ‘deposit a
calcareous stuff’ as if they have to ‘drag about’ a piece of the
planet’s ‘gross mass’ whilst also observing that, in the ‘insect’,
this mineral ‘residuum’ has ‘refined itself’ into a carapace; in
‘fishes and amphibians it is driven back or inward’ into an
endoskeleton; and, at the pinnacle, this inwardification of stone
climaxes in humanity’s grand ‘osseous structure’.



key of becoming earth. becoming a landscape:

- dreams/magic - geology as inverted astrology, divination (Mackay p.2
  novalis) -

“Our art rather requires us to familiarize ourselves closely with the
earth; it is almost as though a subterranean fire drives the miner
on.” The hermit replies, “You are almost inverted
astrologers. Astrologers observe the heavens and their immeasurable
spaces; you turn your gaze toward the ground and explore its
construction. They study the power and influence of the stars, and you
examine the powers of the rocks and mountains and the many and diverse actions of soil and
rock strata. For astrologers the heavens are the book of the future, whereas the
earth shows you monuments of the primeval world.”22->

22. Novalis 1802/1987, p. 86f. Novalis. Heinrich von Ofterdingen: Ein nachgelassener Roman. Berlin: Buchhandlung der
Realschule, 1802. Reprint, Stuttgart: Reclam, 1987. trans???
Zielinski? he also talks about kirchner and inverted astronomy in deep
time book

also

Despiciendo suspicio - Suspiciendo despicio.

By looking down, I see upward. By looking up, I see downward.

[Tycho Brahe (1546–1601)]

By looking inside, I see outwards. By looking outwards, I see inside. 

Lying on my back, the turf of the house walls feels cold against damp
skin. I am slowly buried in dense and muddy peat, heated by the
geothermal waters collected right next to the tarmac, mixed by
hands. My face is the last to be covered, I feel the heat of the sun,
the red glow behind closed fluttering eye lids.



Contemporary observatories for non-visible-light cosmic and deep-space
phenomena are located in the blindness of the undergrounds.

  also 
- becoming/being a landscape
- decay/death/immortality
- off planet
- digital extension/post-humanism
- material/core

BG is not something that one needs to find a reason for, it is not a
choice, a mission or willed for state that one needs to extend oneself
towards. We are already there, inside that becominhg, enveloped and
enclosed in these islands.

** from talk with tm people 0609.

that all these issues - of extraction, of pollution, of climate
catastrophy, of the becoming pharmaceutical - are now brought inside
(where they already were, hiding, a dark consciousness) - they are not
implicit in that hidden way, to be probed or divined, but experienced
directly. these questions become embodied. We reflect on these inside,
from another quite radical position,,, (not the spectacle of the
anthropocene as an outside - that which is a bearing towards something
other or exterior. we inhale our own markers - feedback loops

effects on the psyche...

try to define internal feedback loops

in terms of:

implied by inferior/interior geology, astronomy, astrology

where these are also... this telescoping inwards, turning inside/out -
where we read of this? in subtexts???

feedback loops: extraction and burial, cycles of apparatus/extension,
of inhalation...

the lithic - we eat stones, stones measure our time, 

becoming acephalic - Marder...  Instead of reinventing the
hierarchical head, one must chop it off, so as to come up with an
acephalic (I would say, vegetal) configuration.

I am the Headless Daimon with sight in my feet, the Mighty One who possesses the immortal fire.
I am the Truth who hates the fact that unjust deeds are done in the world.
I am the one who causes lightning and thunder.
I am the one whose sweat is the heavy rain which falls upon the earth that it might be inseminated.
I am the one whose mouth burns completely.
I am the one who begets and creates.
I am the Favor of the Aiōn,
my name is a heart encircled by a serpent.
Come forth and follow.

PGM. The original Greek from PGM V.96—172, formally titled “Στήλη τοῦ Ἰέου τοῦ Ζωγρ εἰς τὴν ἐπιστολήν” (Stēlē toû Iéou toû Zōgr. eis tḕn epistolḗn) or “The Stele of Ieu the Hieroglyphist in His Letter” 

dump: The dump penetrates the very fibres of our being, the processes and
events that make us who we are: our humanity, animality, and
vegetality, our reasoning and organicity, sensation and perception,
nutritive, emotive, and discerning capacities. Becoming entrenched in
multiple registers of existence, it scrambles them, reproducing the
effects it has had on the environmental elements

bataille; 2 Shamefully, We Get Life from Putrefaction, and Death,
Which Reduces Us to Putrefaction, Is No Less
Ignoble than Birth 

geophagy - eating the earth, eating oneself, itself

mistake of thinking that the earth, the cosmos is outside us, not to say that we are "one" with these others but....

This text has been modernised by Adam McLean from the 1591 edition of The Compound of Alchymy. 

THE FIFTH GATE - PUTREFACTION

Now we begin the chapter of Putrefaction,
Without which pole no seed may multiply,
Which must be done only by continual action,
Of heat in the body, moist not manually.
For bodies else may not be altered naturally,
Since Christ doth witness, unless the grain of wheat die in the ground,
Increase may thou not get.

And likewise unless the matter putrefy,
It may in no way truly be altered,
Neither may thy elements be divided kindly,
Nor the conjunction of them perfectly celebrated,
That thy labour therefore be not frustrated,
The privitie of our putrefying well understand,
Before ever you take this work in hand.

And Putrefaction may thus be defined, after philosophers sayings,
To be the slaying of bodies,
And in our compound a division of things three,
Leading forth into the corruption of killed bodies,
And after enabling them unto regeneration,
For things being in the earth, without doubt,
Be engendered of rotation in the heavens about.
