* structure // 6 pages - 6x400=2400 words 7 or 8 pages with images // 




** TM section. becoming as antimony, as arsenic, as copper, as iron, as lead, as mercury, as silver (Agn.)

dreams

matter of fact about the sweatshop

Agnieszka
Aaron
Ines - discipline of medical geology (expert meeting)

In her opening essay .... Agn. expertly ... Tiny Mining as a daily ...

how leads to BG. 

is BG active - a daily practice or is it something which we are always
within (what is that within, lodged between earth and cosmos,
decaying - elaine etc)... these are not mutually exclusive - to
exacerbate, react, embrace - to make a fiction of a situation we find
ourselves within...

we can thus point to previous such practices which had an obvious
influence on the Tiny Miners: withcraft, herbal ... and interaction
with cosmic forces, the work of alchemists such as Thomas Vaughan
fusing ..., inner and outer chinese alchemy (explain)...

We are always

** Theory section. becoming earth

- becoming/being a landscape, an island - or is that TM or lead in from/transition... latest bit

- depths - Marder also - heavens and earth

- decay/death/immortality - Elaine/Arthur

- origins - Thomas

- off planet - Patricia

** Artist section. becoming cosmic

in the gallery, in the museum, we are all bog bodies as intro

do we need to mention all artists?

sissel - bog
alfonso - body stones. magic
rosemary - lithium. questioning this external landscape
rosa - atmospherics and smell
anais - tears
cecilia - appendage/cast/iron becoming metal

- digital extension/post-humanism
- material/core

** conclusion/invitation to become geological ????

After taking Argotine, if your face and body itch as though insects
were crawling over them, if your hands and feet swell, if you cannot
stand the smell of food and vomit it up after you have eaten it, if
you feel as if you were going to be sick most of the time, if you
experience weakness in your arms and legs, if you have to go often to
the toilet, or if your head or stomach violently ache - do not be
alarmed or disturbed. All these effects are merely proof that the
Argotine you are taking is successfully mining your insides.

** other

conduit - elaine and arthur p.40

/Who/ of us should fear obsolescence, the /double/ bind being to
evolve or die? But is not the process of evolution itself - that is,
leaving behind one configuration and becoming another - always already
marked by death? Is one pollutant or catalyst? Is one contaminant. or
the contaminated? ... Can any single position be known to the One who
enters this raging theatre. No, no matter how diffuse, I sense the
others.

