* Becoming Geologucal: Mining dreams?

Yes, reader, countless are the mysterious hand-writings of grief or joy which have inscribed themselves successively upon the palimpsest of your brain; and, like the annual leaves of aboriginal forests, or the un-dissolving snows on the Himalaya, or light falling upon light, the endless strata have covered up each other in forgetfulness.  [Thomas de Quincey. The Palimpsest of the Human Brain]

** 1. On the surface ... intro

On the surface of these endless strata, within beads of ever dissolving sweat or breath, we have always been and will always be dirty and harshly geological. This is the condensing, self evidence of a material witnessing; iron within, crystals of urine, calculi and bezoars.

Geology defines and authors the contingent human; our psyches encode millions of years of spinal deposition and extrusion. Geology is both local origin and destiny, as wilfully or necessarily inhaled and ingested matter, as both medicine and necessary poison or dose, as a divine or sublime power, and as god-treated adornment and technological extension. We are forever involved in its lithic cycles and in its dusty destinies.

What does it mean "to have been produced by a planet?"[Thomas] and what does that production imply for logic?

This rotting, crystal world is not outside us as a study, survey or prospect. Just as nature loves to hide, it loves to eat (itself). We embody its own geophagic and wormy timescales of incorporation. Geology endlessly defines the human, and the realisation of both this "mineral becoming us" and our own becoming geological is uncannily rendered by way of extraction itself, which leads/directs/guides us to the technological as some destiny. Minerals are us, our desires, extending under and cutting in to ourselves in a strange, moribund and algorithmic loop.

** 2. Excavations ... descent

Excavations tunnel into and disturb a dark and poisonous world, creating new anthropogenic and non-anthropogenic cycles of lengthy incorporation and extraction, of radical in-human consumption.

We literally inhale and ingest our own anthropogenic indicators; particulate exhalations of burning forests, as isotopes from nuclear testing, as metallic dust from global extraction and recovery. These novel geo-cycles extend themselves, adit or tube-like and strangely looping back to the main shaft.

Mercury ores, such as cinnabar, a sulphide or mercury, are extracted by underground mining methods, heating the ore to liberate a vapour which is subsequently cooled and condenses as liquid. During cremation of human corpses, this death which enters as a miasmic or vaporous and mineral breath into the living, alongside heavy metals and particulate matter, is further liberated (from dental amalgams, immortal medical devices), returned to the earth, or inhaled in further cycling. There is no loss, and all living remediation is acephalic-recursive; hyperaccumulating grass such as Imperata cylindrica, are used to re-mine contaminated earths. Decay or becoming earth opens the black hole of the geo-logic, swallowing and eating its deep-timed self, so lively.

Native copper ores are excavated from the earth, refined and plainly used in underground cables, carrying human and insect-bound screen signals to be decoded, finally rendered obsolescent and later un-earthed and recovered. In this smelting operation, making use of the same refining plants as for early extraction, re-purposing, particulate copper and other matters are released which are then inhaled or ingested, entering active and passive species including humans. Technology is thus extracted from the environment at the same time as being an extension into that landscape, reaching into and grabbing, and equally providing a means of representation of that exhausted space; the anthopocene is depicted using the materials of its glossed becoming.

** 3. They are called little miners - become metal

They are called little miners, because of their dwarfish stature, which is about two feet. They are venerable looking and are clothed like miners in a filleted garment with a leather apron about their loins. This kind does not often trouble the miners, but they idle about in the shafts and tunnels and really do nothing ...  [de re metallica trans hoover etc.]

A new form of mining prospect, a list of deposits or resources ripe for low cost exploitation, is produced by the German company Medivere, during the Tiny Mining collective sweatshop; a prospectus which is useful in determining which portion of a mineral can be considered as an exploitable ore reserve.

A daily, ritual cycle of incorporation, followed by chelation and finally extraction, or purgation, miming those prospective long adit-tails and tailings, begins with the new moon and lasts one lunar month. Hard scientific tests for the presence of heavy metals, including colorific tests on hair and urine, and voltametric tests on urine accompanies a reflection on bodily impressions, feeling, thoughts and dreams over the course of the sweatshop.

These early attempts from the collective to mine certain metals from within their own bodies brought forth monstrous visions. What should have remained hidden (the secret life and genesis of metals for each individual, the strange and hidden things which define the geological) was exposed to their light and unearthed:

In the atelier floated a sphere, resembling the cryogenic containment unit from Akira, cables coming out everywhere. It had a brown copper hue to it, but that could also have been isolation material or even wood. How did it float?  This ‘device’ allowed you to trigger ‘lucid déjà vu’ allowing you to relive memories as you wanted.

I have only seen this place in dreams but now I am there. A priest, all grey with frozen dew, leads us from his house which is crammed with artefacts from a burnt-out church, crispated altar paintings, into his garden. Chickens, uncooped, run wildly at our feet. The priest is tall, with long matted wet hair, and a long white beard, crinkled and smally curled. He opens a stout metal gate set into the knolled hillside one corner of the garden, inside the chicken enclosure, and takes us into the narrow, shining adit. As a giant guides a troupe of dwarfs, leading us with the light from one smartphone into the coffined irregularity of the ancient, hewn walls.

Outside a larger mine entrance, the geologist in stout boots, tells us that the main ore vein is cursed, that all of the evil over so many years existing in the mountain mining town comes from this vein. He translates its glowing name as drift or drifting. It is always moving. He says that the one who lives in this sort of disorder, mined like a sewer, spread it around them like an infectious disease, a nebulous miasma.

** We have to go much further, much further back. And faster. // become earth

A dream which eludes your recollection – like a rock in which some enchantress dwells which every now & then assumes the appearance of a portal machicolated & then again is barren rock.  [Beddoes]

If the descent into the mine, into the earth, a hole to hidden and forgotten hells, is viewed as a journey towards a dark interior, into the unconscious, into and as a disturbed dream, or inside that old fossil, the profound soul, then what does it mean when that interior is mine, a fantastic voyage, by myself? And when both this dream descent, and its becoming interior, folding, are historically provoked by the excavation and opening of the earth, by extraction for technological extension of those guts and intestines.

[Mackay note: It is the shaping and hauling and digging and layering of infernal machines that opened up new breaches and passageways through which the other soul could pass. p2 subtexts - much of this intro is indebted]

The Tiny Miner coils inwardly on her own little mined depths, ouroboros or worm-like, doubling back on her own interior, but to one side, a greened dwelling-gut which is not mine, strangely, An oozing and lacking dream inside a dream. One is doubled but not as a human of light and phosporescence, and of darkness, the alien, the pagan, the nomad, the odd symmetry. We are both material shades. The human of copper who you have seen is the sacrificial priestess and the sacrifice and she who vomited out her own metals.

[Thomas/p226 spinal*** - could be footnote

... it was in attempting to internalize —or digest—the planet’s magmic inorganic depths that Spirit developed the ulcer we now call the Unconscious.

... this is how Schopenhauer could finally state that consciousness ‘is the mere surface of the mind, and of this, as of the globe, we do not know the interior, but only the crust’.  ]

This descent is also a retrogression in time. As Moynihan writes in Spinal Catastrophism, a geo-gnostic work which is precisely concerned with this internal depth as geotrauma, "depth is time."

Steno was the first to note explicitly that stratigraphic succession corresponds with temporal succession. In other words, that /depth is time/. (Hence, centuries later, McPhee's coinage of '*deep time*'). This marked the inception of the notion of /depth as mnemonic and temporal retrogression/ that would later be so vital to psychoanalysis or so-called 'depth psychology' (Tiefenpsychologie).  [Spinal Cat p86]

Historically speaking, I contain my outside. This is what time does to a body, as we shall see in tracing out this Secret History. The lesson is clear: psychosomatic containment of oneself, when percolated through Grandest History, equals hypogene alienation — the alienation of a body riddled with time. It is this realisation that is inaugural of the phylogenetic phantasy that is Spinal Catastrophism.  [p50,51]

"I contain my outside" implies that this outside, my becoming-sentient outside, is within me, as a floating, rocky island bloated by a sudden burst of available and ethically-obscure nutrients.

** Sublimated time

This opinion, in its general form, was that of the sentience of all vegetable things. But, in his disordered fancy, the idea had assumed a more daring character, and trespassed, under certain conditions, upon the kingdom of inorganization. [...]

The conditions of the sentience had been here, he imagined, fulfilled in the method of collocation of these stones – in the order of their arrangement, as well as in that of the many fungi which overspread them, and of the decayed trees which stood around – above all, in the long undisturbed endurance of this arrangement, and in its reduplication in the still waters of the tarn.

Its evidence – the evidence of the sentience – was to be seen, he said, (and I here started as he spoke,) in the gradual yet certain condensation of an atmosphere of their own about the waters and the walls. The result was discoverable, he added, in that silent, yet importunate and terrible influence which for centuries had moulded the destinies of his family, and which made him what I now saw him – what he was.  [Edgar Allen Poe. The Fall of the House of Usher]

The porous rock towers of Tenerife exposed the first spinal landscape [...] clinker-like rock towers suspended above the silent swamp. In the mirror of this swamp there are no reflections. Time makes no concessions.  [Ballard. atrocity]

Eating itself and un-conceding, condensed time again, loving or hating it, both adits or entrances, exit and entry ways, scarred in white moulded spots by dragging knuckles. The body is a pharmaceutical resource, for itself, and for the others, packaged as a synthetic product, and with associated manufacturing and exit fumes, to be inhaled or sublimated within and by other bodies, other earths. Let the waters above the heavens fall and the earth will yield its fruit.

The body is a metallic ore, particulate in its spreading over a landscape. A crystalline, sparse clay mud of various sulphides, arsenic, lead and iron, smears across the SUV's interior dsiplay of Polypropylene (PP), Acrylonitrile-butadiene-styrene (ABS), Styrene maleic anhydride (SMA), Polyphenylene Ether (PPE), and Polycarbonate (PC). We gaze with dull eyes at the distant volcanic peaks, resting after the glazed claustrophobia of the tight undergrounds. These places externalise.

I am the revealer of secrets; in me are marvels of wisdom and strange and hidden things.  But I have spread out the surface of my face out of humility, and have prepared it as a substiture for earth.  [islamic geomancy device poem]

Inside the mine workings, the body can now thanklessly become any landscape; a prospect with associated legal frameworks and permissions, an island of waste, a rosy site of tailings, a swamp in which there are no reflections, a vast dreamt suburb, a gas-exhaling oracular chasm (rich in CO2-H2S discharges), a rocky place or dump of dissolved refuse going mad, a logistics centre on the outskirts of a small town betwixt sliproads, an overgrown heap of rubbish grazed now by sheep, a new mountain amidst the dykes and drainage canals, "a drab accumulation of peat, muck and marls."[Ballard-see remains] This becoming landscape, and of andscape becoming me/mine is pure techno-pharmaceutical.
 
the forgetful, boggy body is depicted, scanned and stretched, exhibited and re-skinned, inhaled as image, incorporated. Geology is always said to be the biography or history of an earthy body. Seismic upheavals in the mind disrupt this cosmic, hairy island; inverted burial pits in this mirrored, calcite swamp. A geological sentience becomes us, as a crystalline, sublime flowering of sublimation and deposition, under the sun. "[A]ll space and body is itself nothing but coagulated time [...]"  [87 moyn]

** Astral bodies WORKINGS - becoming cosmic

“Our art rather requires us to familiarize ourselves closely with the earth; it is almost as though a subterranean fire drives the miner on.”

The hermit replies, “You are almost inverted astrologers. Astrologers observe the heavens and their immeasurable spaces; you turn your gaze toward the ground and explore its construction. They study the power and influence of the stars, and you examine the powers of the rocks and mountains and the many and diverse actions of soil and rock strata. For astrologers the heavens are the book of the future, whereas the earth shows you monuments of the primeval world.”

[22. Novalis 1802/1987, p. 86f. Novalis. Heinrich von Ofterdingen: Ein nachgelassener Roman. Berlin: Buchhandlung der Realschule, 1802. Reprint, Stuttgart: Reclam, 1987. trans???]

Astral bodies, those cosmic waters of the tarn, were primordially rended from the terrestrial body, our filthy prima materia by the mirror god. Marder - becoming geo holds this as an axiom, this opposing of that which is not entirely other. Geology is opened to divination (inverted astrology, lower astronomy, the encoding of alchemical elements as planets), to geomantics, hydromancy (gazing into lakes), necromancy. The terrestrial parts rise to the upper area of the vessel, giving wings to the earth.

mirror - in the lake?

how we go from inverted astrology - sunk in the lake, to the fumes, entry to hell and prophecy, to exhaling chasm - a gas-exhaling oracular chasm

sissel lake:

bathtub-shaped burial pits, similar to those often holding bog bodies. Looking into these water-filled pits, she says, you see yourself reflected in the water’s surface, along with the sky above. Archaeologists have found horse skeletons in there, along with pieces of white quartz, and you can only imagine the magic of the stars above reflecting on the surface of the water, while the quartz glitters back at you from the bottom of the pit. In order to understand the logic of a society wholly dependent on what they are able to receive from nature, these sensory encounters with the landscape are precious to an archaeologist, she says. It helps her to imagine what might have happened, to understand the spiritual significance of the bog, and perhaps also the beauty of something that might otherwise seem brutal to us. A ritual where the blood of the cut throat runs from the living body into the waters that gives the community life and sustenance. The blood and the body is given to the gods through the portal of the bog.

blood-red glass of gold - gold fibres dissolved in the lake are set to colour it blood-red as a sunset acid mine drainage

rare gold-ruby glass - a two-phase system comprising discrete tiny particles of excited metallic gold which are dispersed in a silicate glass matrix.

the lake as important - list these lakes... doublings, doubles - the 2 worlds in patricia and how this might relate to the book - to finally get there talking about that

the many doublings, ever geology and its double, calcite or hermaphrodited twin (in the landscape)

Perhaps the geological implies the very figure of the double, against the day, the figure of reason and the unconscious. what of the rending?

marder - this strange twin of the becoming geological and the anti-geological


it cannot be anything but double in not being able to bear a full light, a full realisation of death always, of what this life stands against.

each p-articulated and dis-articulated stratum is double

It is as if two Earths overlay their strata. The one is the Earth as it is, a dying modality of individual emergences and diminishments which humans accelerate, the Earth where the human abides. The second is the human geostrata of Earth made of use value and exploitation, the Earth for the human.  [patricia]

lakes:

- sunset lake from TEH - vermilion cyanide pool -
- engendering and reflecting crystal blooms
- swampy lake of ballard
- tarn of poe
- lake as burial pool in Sissel
- lakes of tears

body is celestial - the celestial comes before

descends

under the sun

what does it mean to be blossoming under the sun,

That which is above is not just like or acting as a metaphor for that which is below. They have been uprooted but are veritably inversions of each other, mirrors. ???

translation of the Arabic:[24] That which is above is from that which is below, and that which is below is from that which is above.

our destinies are dictated astrally, by an ascending or descending sentience, but this particular starry outside is mucally involuted inside and outside the flesh of words (Zosimos fumes, TM ending)

fumes are the sacrifices, astral fumes, demons

However, the demons of place/location did not fulfil even the false promises that they had made. But when there had resulted a complete change-round of the /klimata/ and the region was devastated by war and the human race disappeared from it. When the temples of /daimons/ were nothing but a desert and their sacrifices were neglected, they began to flatter the surviving men and persuaded them by dream, on account of their falsity, and by many presages, to adhere to the sacrifices. And as they renewed their false promises of non-natural tinctures, all the unhappy men, devoted to pleasure and ignorant, were filled with rejoicing.

They want to do all this to you too, woman, through the intervention of their pseudo-prophet. These local /daimons/ flatter you; for they hungry not only for sacrifices, but also for your soul.

When the [daimonic] guardians are driven off from the great men they [the daimons] deliberate as to how they may lay claim to our natural tinctures, so as not to be driven away by men, but venerated and invoked, and nourished with sacrifices. This is what they did. They concealed all the natural and self-regulating tinctures (ta physika kai automata), not only out of envy, but giving heed also to their own sustenance, so that they would not be whipped, chased away, and punished with hunger through the cessation of the sacrifices. They acted as follows. They hid the natural tincture and introduced their non-natural tincture, and gave these to their priests; and if the common people were neglectful of the sacrifices, they hindered them even in attaining the non-natural tinctures (Fest. p. 366, ll. 18-26)35.

Fraser p.141

[the daimon's] pneumatic part grows fat, for it lives on vapours and exhalations, in a complex fashion and from complex sources, and it draws power from the smoke that rises from industrial chimneys and server farms.

[Porphyry. On Abstinence]

//

also fumes:

Something is rotten here - from Delphi article: The rotting of the
snake is the source of the site's original name Pytho (=rotten). The
serpent was said to have lived in the sacred chasm that became her
garve and the mantic vapours derived from her corpse. [Geomythology at
Delphi]




** questions 20/9+ and addings/endings

nebula nebulous

mined like a sewer

/////

we need 2300 words for 5 pages, 2700 for 6 ... with two images on extra page

what of footnotes also...




