* Becoming Geological: Mining dreams?

Yes, reader, countless are the mysterious hand-writings of grief or
joy which have inscribed themselves successively upon the palimpsest
of your brain; and, like the annual leaves of aboriginal forests, or
the un-dissolving snows on the Himalaya, or light falling upon light,
the endless strata have covered up each other in forgetfulness.
[Thomas de Quincey. The Palimpsest of the Human Brain]

** Surfacing

On the surface of these endless strata, within beads of ever
dissolving sweat or breath, we have always been and will always be
harshly geological and dirty. This is the condensing, self evidence of
a material witnessing; strictly much more than hydroxyapatite in
bones, iron within blood, triple phosphate crystals in urine, and the
painful struvite stones of calculi.

Cosmic geology defines and produces the contingent being; a singular
psyche encodes millions of years of spinal depositions and other
planetary trusions and extrusions. Geology is both local origin and
earthy destiny, as wilfully or necessarily inhaled and ingested
matter, as both medicine and necessary poison or dose, as a divine or
sublime power, and as god-treated adornment and technological
extension. Being and thinking are forever involved in its lithic
cycles and in its dusty futures.

This rotting, crystal world is not outside one as a study, survey or
prospect. Just as nature loves to hide, it loves to eat (itself). We
embody its own geophagic and wormy timescales of
incorporation. Geology endlessly defines the human, and the
realisation of both this "mineral becoming us" (which others us
always) and our own becoming geological is uncannily rendered by way
of extraction itself, which divines us towards the technological as
some fumed destiny. Minerals are us, our desires, extending,
undercutting ourselves in a strange, moribund and algorithmic loop.

This book asks questions of what becoming geological means for our
sense and our ethics.

** Excavation

These excavations tunnel into and disturb a dark and poisonous world,
creating new anthropogenic and non-anthropogenic cycles of
lengthy incorporation and extraction, of radical in-human consumption.

We literally embed, inhale and ingest our own anthropogenic
indicators; as particulate exhalations of burning forests, as isotopes
from nuclear testing, as metallic dust from global extraction and
recovery. These novel geo-cycles extend themselves, adit or worm-like,
strangely looping back.

Ores, such as cinnabar, a sulphide or mercury, are extracted by
underground mining methods, heating the ore to liberate a poisonous
vapour which is subsequently cooled and condenses as liquid
mercury. During cremation of human corpses, this death which enters as
a miasmic, mecurial mineral breath into the living, alongside heavy
metals and particulate matter, is further liberated (from dental
amalgams, immortal medical devices), returned to the earth, or inhaled
in further cycling. There is no loss, and all living remediation is
acephalic-recursive; hyperaccumulating grass such as Imperata
cylindrica[cecilia], are used to re-mine contaminated earths. Aside
from this recursion, decay or becoming earth opens one side of the
black hole of the geo-logic, swallowing and eating its deep-timed
self, so lively.

Native copper ores are excavated from beneath the earth, refined in
smelting plants and plainly re-buried as filamentous underground
cables, carrying human-decoded and insect-attracting screen signals,
finally rendered obsolescent and later un-earthed and recovered. In
this second, remembered smelting operation, deemed recycling,
particulate copper and other matters are released which are then
inhaled or ingested, entering active and passive species including
humans.

** 3. They are called little miners

They are called little miners, because of their dwarfish stature,
which is about two feet. They are venerable looking and are clothed
like miners in a filleted garment with a leather apron about their
loins. This kind does not often trouble the miners, but they idle
about in the shafts and tunnels and really do nothing ...
[de re metallica trans hoover etc.]

A new form of mining prospect, a list of deposits or resources ripe
for low cost exploitation, is produced by the German company Medivere,
during the Tiny Mining collective sweatshop; a prospectus which is
useful in determining which portion of a mineral can be considered as
an exploitable ore reserve.

A daily, ritual cycle of incorporation, followed by chelation and
finally extraction, or purgation, miming those prospective long
adit-tails and tailings, begins with the new moon and lasts one lunar
month. Hard scientific tests for the presence of heavy metals,
including colorific tests on hair and urine, and voltametric tests on
urine accompanies a reflection on bodily impressions, feeling,
thoughts and dreams over the course of the sweatshop.

These early attempts from the collective to mine certain metals from
within their own bodies brought forth monstrous visions. What should
have remained hidden (the secret life and genesis of metals for each
individual, the strange and hidden things which define the geological)
was exposed to their light and unearthed:

In the atelier floated a sphere, resembling the cryogenic containment
unit from Akira, cables coming out everywhere. It had a brown copper
hue to it, but that could also have been isolation material or even
wood. How did it float?  This ‘device’ allowed you to trigger ‘lucid
déjà vu’ allowing you to relive memories as you wanted.[footnote de bel]

** We have to go much further, much further back. And faster. 

A dream which eludes your recollection – like a rock in which some
enchantress dwells which every now & then assumes the appearance of a
portal machicolated & then again is barren rock.
[Beddoes]

If the descent into the mine, into the earth, a hole to hidden and
forgotten hells, is viewed as a journey towards a dark interior, into
the unconscious, in a disturbed dream, or inside that old
fossil, the profound soul, then what does it mean when that interior
is mine, a fantastic voyage, into myself? And when both this dream
descent, and its becoming interior, in-folding, are historically provoked
by the excavation and opening of the earth, by extraction for
technological extension of those guts and intestines.

[Mackay note: It is the shaping and hauling and digging and layering
of infernal machines that opened up new breaches and passageways
through which the other soul could pass. p2 subtexts - much of this
intro is indebted]

The Tiny Miner coils inwardly on her own little mined depths,
ouroboros worm-like, doubling back, an involuted mirror, on her own
interior, but to one side, a greened dwelling-gut which is elsewhere,
strangely, an oozing and lacking dream inside a dream. One is doubled
but not as a human of light and phosporescence, and of darkness, the
alien, the pagan, the nomad, this final, odd symmetry. We are both
material shades.

Perhaps the geological implies the very figure of the double, against
the day, the figures of reason and the unconscious; this strange twin
of the becoming geological and the anti-geological, it cannot be
anything but double in not being able to bear a full light, a full
realisation of death always, of what this life stands against.

The human of copper who you have seen is the sacrificial priestess and
the sacrifice and she who vomited out her own metals; a vomiting tiny
miner, expelling the prima materia, unable to digest the "planet's
magmic inorganic depths" and thus her "Spirit developed the ulcer we
now call the Unconscious."

This crustal descent is also a retrogression in time. As Moynihan
writes in Spinal Catastrophism, a geo-gnostic work which is precisely
concerned with this internal depth as geotrauma, "depth is time."
Further on,

Historically speaking, I contain my outside. This is what time does to
a body, as we shall see in tracing out this Secret History. The lesson
is clear: psychosomatic containment of oneself, when percolated
through Grandest History, equals hypogene alienation — the alienation of
a body riddled with time. It is this realisation that is inaugural of
the phylogenetic phantasy that is Spinal Catastrophism.
[p50,51]

"I contain my outside" implies that this outside, my becoming-sentient
outside, is within me, as a floating, rocky island bloated by a sudden burst of
available and ethically-obscure nutrients.

** Sublimated time

This opinion, in its general form, was that of the sentience of all
vegetable things. But, in his disordered fancy, the idea had assumed a
more daring character, and trespassed, under certain conditions, upon
the kingdom of inorganization. [...]

The conditions of the sentience had been here, he imagined, fulfilled
in the method of collocation of these stones – in the order of their
arrangement, as well as in that of the many fungi which overspread
them, and of the decayed trees which stood around – above all, in the
long undisturbed endurance of this arrangement, and in its
reduplication in the still waters of the tarn.

Its evidence – the evidence of the sentience – was to be seen, he said,
(and I here started as he spoke,) in the gradual yet certain
condensation of an atmosphere of their own about the waters and the
walls. The result was discoverable, he added, in that silent, yet
importunate and terrible influence which for centuries had moulded the
destinies of his family, and which made him what I now saw him – what
he was.  
[Edgar Allen Poe. The Fall of the House of Usher]

"[A]ll space and body is itself nothing but coagulated time
[...]"  [87 moyn]

Eating itself and un-conceding, condensed time again, loving or hating
it, both adits or entrances, exit and entry ways, scarred in white
mouldy spots by dragging knuckles. The body is a pharmaceutical
resource, for itself, and for the others, packaged as a synthetic
product, and with associated manufacturing and exit fumes, to be
inhaled or sublimated within and by other bodies, other earths. Let
the waters above the heavens fall and the earth will yield its fruit.

The body is a metallic ore, particulate in its spreading over a landscape. A
crystalline, sparse clay mud of various sulphides, arsenic, lead and
iron, smears across the SUV's interior dsiplay of Polypropylene (PP),
Acrylonitrile-butadiene-styrene (ABS), Styrene maleic anhydride (SMA),
Polyphenylene Ether (PPE), and Polycarbonate (PC). We gaze with dull
eyes at the distant volcanic peaks, resting after the glazed
claustrophobia of the tight undergrounds. These places externalise. 

The forgetful, boggy body or inner mine is depicted, scanned and
stretched, exhibited and re-skinned, inhaled as image, incorporated
again. Geology is always said to be the biography or screened history
of an earthy body.

Inside the mine workings, the body can now thanklessly become any
landscape; a prospect with associated legal frameworks and
permissions, an island of waste, a rosy site of tailings, a swamp in
which there are no reflections, a vast dreamt suburb, a gas-exhaling
oracular chasm (rich in CO2-H2S discharges), a rocky place or dump of
dissolved refuse going mad, a logistics centre on the outskirts of a
small town betwixt sliproads, an overgrown heap of rubbish grazed now
by sheep, a new mountain amidst the dykes and drainage canals, "a drab
accumulation of peat, muck and marls."[Ballard-see remains] This
becoming landscape, and of landscape becoming +me+ is purely
diluted, techno-pharmaceutical.

** Astral bodies

“Our art rather requires us to familiarise ourselves closely with the
earth; it is almost as though a subterranean fire drives the miner
on.” The hermit replies, “You are almost inverted
astrologers. Astrologers observe the heavens and their immeasurable
spaces; you turn your gaze toward the ground and explore its
construction. They study the power and influence of the stars, and you
examine the powers of the rocks and mountains and the many and diverse actions of soil and
rock strata. For astrologers the heavens are the book of the future, whereas the
earth shows you monuments of the primeval world.”22->

22. Novalis 1802/1987, p. 86f. Novalis. Heinrich von Ofterdingen: Ein nachgelassener Roman. Berlin: Buchhandlung der
Realschule, 1802. Reprint, Stuttgart: Reclam, 1987. trans???

I am the revealer of secrets; in me are marvels
of wisdom and strange and hidden things.
But I have spread out the surface of my face out of humility,
and have prepared it as a substiture for earth.
[islamic geomancy device poem]

Becoming geological is a divination which comes before, in a distant
past; the marks in the earth of geomancy or ilm al-raml (the science
of the sand) signifying solitude, exile or gathering, hydromancy
staring into the disturbed waters as gold fibres dissolved in the lake
are set to colour it blood-red, the miasma of mantic vapours released
from the undergrounds sheltering the rotting corpse of the slain
serpent (source of the original name of the oracle of Delphi).

Within this interior divining, for possible and fragile contigent
futures, which this publication sets out, the celestial and the earthy
are not rended by the mirror or boggy judgement of god; all divination
is inverted astrology[ref], and all geology is mirrored
divination. The astral bodies, those cosmic waters of the tarn, are
our filthy prima materia, mucally involuted inside and outside the
flesh of angelic knowledge.
