* Becoming Geological: mining dreams // further back and faster

** contents/orderings

becoming as inter-titles/seperators...

Becoming metals -  becoming as antimony, as arsenic, as copper, as iron, as lead,
as mercury, as silver,

Becoming cosmic

Becoming earth

Becoming mineral

*** mining - toad/earth - Becoming metals -  becoming as antimony, as arsenic, as copper, as iron, as lead, as mercury, as silver, // becoming earth

order?
1. becoming cosmic - agnieszka
2. Ines interview
3. aaron
4. user
5. metals 

*** theory - wings eagle // becoming cosmic - origins. leaving the planet

1. patricia
2. moynihan
3. marder?
4. elaine

*** art - snake // becoming mineral? becoming earth - re-presentation

sissel - bog bodies
rosa - smell
rosemary - re-presentation ground as data
alfonso - bezoars

anais? descent
cecilia?? data... technical. cycle of remediation

** pitch/other used notes/ cycles / presentation

** inferior geology/other essays?

** illustrations for intro

argotine box...

** Notes so far/notebook:

Old earth, no more lies, I've seen you, it was me, with my other
ravening eyes, too late.
[Samuel Beckett fizzles]

We have always been geological.

beckett 1929 letters p152(252?) - on dew

*Structure: 3 dreams and 3 sections TM, theory, artistic work*

1. the blue light. sweatshop dreams. // TM // mining - toad/earth - Becoming metals -  becoming as antimony, as arsenic, as copper, as iron, as lead, as mercury, as silver, // becoming earth
2. the turf house, the front and back of the house, grave, entry and exit. off-world // theory theory - wings eagle // becoming cosmic - origins. *leaving the planet*
3. of the re-presentation of the bog bodies in the museum. the gold around the bezoar. margarita of austria's room // art art - snake // becoming mineral? becoming earth - re-presentation

in the sweatshop
in the turf house
in the museum or gallery

// copper/Dennis

*Heavy crystal sediments near the top.*

Last night I had a dream of playing a computer game. A glitch enabled me to physically
travel through dimensions. I ended up in the atelier of a friend housed atop of a well known
hamburger restaurant, which doubled as a ‘hidden in plain sight’ security check, preventing

random people from going upstairs. In the atelier floated a sphere,
resembling the cryogenic containment unit from Akira, cables coming
out everywhere. It had a brown copper hue to it, but that could also
have been isolation material or even wood. How did it float?  This
‘device’ allowed you to trigger ‘lucid déjà vu’ allowing you to relive
memories as you wanted. Realising I was already in another dimension,
I did not want to go further. We all left to go to a club. Exiting the
restaurant someone had parked a trailer under the trees. My attention
was drawn to the shiny assortment of shapes faintly visible through
reflection of the faint moonlight penetrating the canopy. Upon inspection the
trailer was full of alumin- ium extrusions in every shape and size you
can imagine. Every piece was unique, except for their perfect shiny,
brushed finish.

// lead/martin

In the first I’m pissing into a toilet and each stream is accompanied by an intense blue
light – like a gas light, and maybe even the smell of gas as if there could be an explosion. This
could relate to the use of flame spectroscopy to analyze heavy metals in organic matters (such
as hair). The blue would correspond to the colour of a certain metal – such as lead itself or
arsenic.

In the second fragment we go past a kiosk (in Cologne) with two fresh fish stalls nearby,
run by Vietnamese people. Outside one of these stalls there are two older men, scruffily
dressed and with red, bruised faces, looking a bit like old English standup comedians. They
are there to entice people to come and see/buy the fish. At first they hold up the fish but
later they bite pieces of fish and then spit them out, catching them and spreading them on
their faces, to make a new face. They lay blue pieces over their eyebrows and other features,
making their faces more bruised and blue looking. This relates to the seafood diet for the
first three days of the sweatshop. Again a metallic, bruisy blue colour.

/// new beginnings

describe the first sweatshop - from in time with new moon... 

dreams of blue light (lead), of giant bumble bees (antimony), of a
musical group and a metal mouthpiece (mercury), of aluminium extruded
realities (copper) ... extraction seems to engender giants, monsters
and visions.

copper man vision zosimos. metal as a body

Geology is an unconscious (not our unconscious - subtexts/mackay,
moynihan-spinal). Countering and contrary to contemporary opinion
ranging the history of science, the alchemists did probe these
material depths. The big bodies are dreams and visions, which is why
the museums (Drent,etc) insist on their repeated re-presention - the
literal return of the repressed in a very real sense (the alien, the
pagan, the nomad, black death, the odd symettry of El Majusi - geomancy).  

We have to go much further, much further back! And faster.

///

that it is not just about this new circulation/cycles - of:

With the arrival of the questionable era of the anthropocene, marking
another entry point into the planetary geological, a new “natural”
cycle is initiated - we literally inhale and ingest our own
anthropogenic indicators (for example, as the particulate exhalations
of burning forests, as isotopes from nuclear testing, as metallic dust
from global extractions). These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms.

illustrated by for example, the extraction of native copper ores from
the earth, their refinement and use in underground cables, carrying
human bound screen signals decoded, their later un-earthing and
recovery, a smelting operation releasing particulate copper and other
matters which is then inhaled or ingested, entering active and passive
species including humans. 

inhale mercury fumes from crematorium stacks

These cycles are solely meditative and illustrative... they are too
material, too logical and explained, they are merely a recursive
apparatus flip-flopping betwixt the knowing anthropogenic and the
imagined lithic? a recursion which admits only itself, no others, 

remediation as recursion

 but there is something else there - not just an authoring of the
earth (as Moynihan writes...) - crystal world bit in spinal - the lithic

becoming cosmic
becoming dirty
becoming geological

how to merge surtsey bacteria analysis and a dream/blue light?/sweatshop dreams

- leaving planet/attachment to a specific geology - moynihan - as origin, as psyche/geotrauma

also mining/own geo resources are more in need of conservation as we
mine for other resources in more hostile off-world environments (who
apart from aaron writes this? patricia?)

- artists and geo re-presentation. not so much about the anthropo-sublime but re-presentation of bog bodies. also in rosemary - showing this


a dwelling in the earth
in death we become as earth

iron snails in guardian

quote TM dream... blue light

TM->becoming geo-> contents here

bog bodies: what is they enable us to think ahead of time. providers from the past. idea of sacrifice. also idea of reflection, witnessing in that text... body and geology as witness (schuppli)


alfonso: all the action/narrative could be taking place in the cabinet/room of margarita!

The gold and cabinet encircling the bezoar are the not-wanting just this raw foreign thing!


as manifesto or statement

//iceland notes

turf house as a /relation?/ VEHICLE for becoming geological. house of earth and volcanic stones/lava

traditional - the front of the house, wooden gable, girls greeting tourists (bus engine left running) in threadbare costumes from a hundred years ago, ghost photographs

from the front windows, low wooden desk looks out on graveyard, on the church, the mound of earth covering the farmer's body

behind the house - the earth, new habits, new language (also behind Wolf Vostell sculpture, and recent dream with icon/crucifix/jesus... 

last house - the life support system of pipes, air conditioning, the last breath... (Teemu)

turf house as a grave

- conversations with Judith: Surtsey, subsurface bacteria
  there. portals, also geology which is neither living nor dead -
  outside these categories... nodes of life and death, outside these
  terms

*patricia also mentions leaving earth behind...where?*

between geology and biology, neither nor

iceland spar man - geological cheese (peter) - ref. bacteria for icelandic porcelain. spar/binary of calcite, polarisation of light

iceland as mostly geologically young...

golden circle. shit circle (Salo)

antii subsurface glitches... orbital turf house...

*** TM intro/start of all - new notebook

In November 2020, a small group of artists, chemists and geologists,
made a first attempt to collectively mine certain minerals from within
their own bodies. These actions brought forth monstrous visions. What
should have remained hidden (the secret life and genesis of metals)
was brought to the light, unearthed. 

where does this lead, this body as a mine, as a resources, as a metal,
copper body, man of copper, what are the consequences of these actions
for thought, for being what we are when we say what it is to be human,
or what comes before this saying (patricia), for the world - the
dystopia of tiny mining, final frontier -> visions of zosimos -
natural way of doing things

that a body can now be any landscape, a body as a site of tailings, as
a suburb, as a logistics centre on the outskirts of a small town,
between motorways, as a overgrown heap of rubbish grazed now by sheep,
a new mountain amidst the dykes and drainage canals 

a body as landscape, depicted, scanned and stretched, re-skinned, 

bog body is a landscape
