** remains

These cycles are solely meditative and illustrative... they are too
material, too logical and explained, they are merely a recursive
apparatus flip-flopping betwixt the knowing anthropogenic and the
imagined lithic? a recursion which admits only itself, no others, 

New developments post sweatshops - we are currently working with a
Chinese pharmaceutical company based in Beijing on the (open source)
development and manufacture of Argotine, the primary extractive agent
alongside “natural” chelators and supplements. Argotine incorporates a
synthetic chelating agent (DMPS), sets of nano “collectors” or
“farmers”, and finally an emetic or purgative element based on
traditional Chinese medicinal or alchemical recipes (for flight and
immortality) such as Elixir of Ascent into the Roseate Clouds making
use of arsenic and mercury bearing ores.

How much can we extract from the earth, and return to the
earth? I offset what I take from the earth, and the damage I cause the
earth, through this giving back. We try to get to know our own cycles,
of excess, of regulation and of deficiency.”

To return to this duality of incorporation and extraction we can see
that just as the chinese alchemists extracted arsenic and mercury from
the earth (as orpiment, cinnabar and realgar) to incorporate these
materials in their bodies as agents of immortality.

So today we extract copper, tantalum and so on towards an extra-bodily
incorporation, an exteriorisation of bodies in and as technology

Our become dispersed as techno-prostheses is a form of
incorporation. Incorporation and extraction are as the pharmakon of
dosage: lack and abundance, deficiency and toxicity.

Other communities such as transhumanists and biohackers now seek a
"real" incorporation of metals and technology - to upgrade and replace
the flesh or meat suit with immortal components - subject only to
obsolescence and eternal internal upgrades.

Mercury and copper are extracted from the earth and placed into the
human body in order to preserve it. Transhumanism is about material
augmentation, flesh is replaced by metal and mineral which is
(apparently) a renewable resource.

Tiny miners go in reverse direction - becoming mineral and purging
oneself of the metal, the mineral.

This reminds us of the practices of self mummification parallel to the
use of elixirs of immortality for bodily preservation:

As Joseph Needham writes in this context: The adept towards the end of
his life abstains for a long time from all cereal food, living only on
plant material such as chestnuts, Torreya nuts, pine-tree bark and the
roots of grasses; then just before death he may claim the distinction
of being buried alive. After death has occurred the corpse is dried
over charcoal fires and smoked with the fumes of incense, then when
fully dessicated lacquered all over or used as the base for a statue
of dried clay or plaster.

*** machines will watch us die interview

smog as a contemporary, geological
media binding the (photo)-chemistries of screens, bodies, cities and
planet.

At the same time it becomes clear that these machinic processes are
very much linked to some process of mummification (as Robert Smithson
wrote, "the medium is the mummy"); to a kind of deathly or spectral
preservation which could be considered as immortality. This is what I
mean by enshrouding, by enveloping in veils of screens and smog, and
by the ingestion of earthly and technological minerals and machined
synthetics. We become geological. In the sense that the digital
outlives us, as earthly trace, as cloudy storage and as toxic
memorial, machines will watch us die, record our deaths (as loss of
resources) and assist in forming a spectral community of the un-dead.

*** IMM

This idea of a sensitivity to planetary and bodily health underwrites
the Tiny Mining project with the Anthropocene viewed as both
symptomatic and as psychosomatic.


Tiny Mining explores these multiple links and circulations between
technology, the environment and the human body and psyche. It's
important in times of climate disruption and environmental destruction
that we begin to think and work deeply within these relationships and
within the histories of media such as scientific discourse,
pharmacological matters and medical geology; to think an alien,
potentially geological post-nature.

ARGOTINE:

The parasite, named Argotine (with reference to the rich history and
folklore of the ergot fungus) is designed as an assemblage of
nanoscopic units, each of them measuring around 10nm, that have
specific compositions and electrical charges corresponding to the
desired mining process.

The different nanomachines create bonds, communicate and form larger
structures (up to 100 micrometers) similar to fungi's mineral mining
hyphae. Once injected into the bloodstream, they travel and stick to
the affected/healthy cells where the extraction begins.

This micro/tiny mining process, as in the case of soil mineral
extractions performed by plants, fungi and microorganisms is
facilitated thanks to bioleaching (the process of extracting metals
from their ores through the use of living organisms) through
chelation. The process is highly efficient for lead, arsenic,
antimony, molybdenum, gold, silver and cobalt extractions.

Our thesis here is that the in-corporation of the earth, the becoming
geological of the human body, meaning that geological time-scales and
processes can now be considered as corporeal: that these ideas are at
play within the community of Tiny Mining and relate heavily to an
anthropology or history of the preservation and immortality of bodies
and their extensible or extended environments (prostheses or tool
culture) which leads abruptly to contemporary trans-humanist practice.

What is shih chieh? (from a Taoist catechism p301 - Li Shu-Huan)

After the death of an adept seeking immortality, the form and skeleton
remain behind while the immortal goes away; this is what is meant by
shih chieh. When one is ready to rise up as an immortal, one leaves
behind the malodorous house of clay, hence the expession "corpse"
(shih) from which the hsien is "liberated".

The Chu Hsien Lu says "When the appearance is like that of a living
person - that is (proof of) shih chieh. When the feet have not turned
bluish in colour, and the skin not shrunk - that is shih chieh. When
the light in the eyes has not gone dull, and looks like that of a
person still alive - that again (shows) shih chieh. There are also
those who have become alive once more after being dead; and some whose
bodies have disappeared altogether before being encoffined; and others
who have ascended, leaving only their hair behind - all these things
are called shih chieh. 

We can see that just as the chinese extracted arsenic and mercury from
the earth (as orpiment, cinnabar and realgar) to incorporate these
materials in their bodies as agents of immortality.

So we extract copper, tantalum and so on towards an extra-bodily
incorporation, an exteriorisation of bodies.

Our become dispersed as techno-prostheses is a form of
incorporation. Incorporation and extraction are as the pharmakon of
dosage: lack and abundance, deficiency and toxicity.

Transhumanists and biohackers now seek a "real" incorporation of
metals and technology - to upgrade and replace the flesh or meat suit
with immortal components - subject only to obsolescence and eternal
internal upgrades.

EXTRACTION:

Extraction is about storage the memorial, the support for an archive.

Mercury and copper are extracted from the earth and placed into the
human body in order to preserve it. Transhumanism is about material
augmentation, flesh is replaced by metal and mineral which is
(apparently) a renewable resource.

Tiny miners go in reverse direction - becoming mineral and purging
oneself of the metal, the mineral. Again the dual blade of the
pharmakon.

Mind uploading or brain upload can also be seen as a form of
extraction, extropian data mining; discard the flesh suit and extract
that valuable mind.

There is this twin movement in TM of wanting to incorporate the earth
in order to be able to mine, but also extracting and freeing oneself
of the earth (inside) and of any attachment to the earth. Going way
beyond the Gnosticism inherent in Transhumanism.

internal gnosticism


** inferior geology/other essays? sonic acts 2021. peter. finland bog reader but that is about cycles...

*** inferior

idea of interior/inferior...

Inferior astronomy is another way of naming transformative methods for
working with plants and with metals. Astronomical discourses are
re-interpreted as referring to the terrestrial; planets become
metals. It’s an historic analogy, a set of identities or
transformations which help to make sense of certain early texts
treating the planets in mineral and muddy terms and as, at odds with
the celestial, undergoing earthy and earthly process.
 
Inferior geology seeks to further these transmutations, resting
equally on a magical closeness to the key phrase of “interior
geology.” If inferior astronomy brings the planets down to earth,
within the primacy of substitution which is called occult and is
recognised as such (this spiritual work with matter was always already
astronomy, inferior astronomy just marks that connection within the
realm of metaphor), then what substitution is being pointed at as
already having happened in thinking the geological as always inferior?
That it is rendered earthy? That it becomes of bodies and of
circulations without reference to marked, measured and seriously
differing time scales?

Inferior geology naturally also refers to a geology which is
“inferior” to some officially defined geology, less stratified
perhaps, more psychically re-churned and de-sedimented. I’m trying to
think of the peat, of the mud mind transmuted into the bog mind, of
Beckett’s “All is noise, unending suck of black sopping peat, surge of
giant ferns, heathery gulfs of quiet where the wind drowns, my life
and its old jingles” jangling within applied and applicated, sewn and
freshly black fibrous science. Inferior geology could also refer to
seismology, with its Love waves and Rayleigh waves, other forms of
faster application, disrespecting deep geological time. Inferior also,
in an original sense, as a breathing beneath, the earth evaporating
beneath the moon and the stars, sinking deeper into the sucking, and
slowly shattering.

*** sonic acts


enacted as a series of now online sweatshops - meditations on metals
and elements (each participant is assigned an element which they work
with) 


*** arsenic eaters

XX mining gnomes - 

They are called *little miners*, because of their dwarfish stature,
which is about two feet. They are venerable looking and are clothed
like miners in a filleted garment with a leather apron about their
loins. This kind does not often trouble the miners, but they idle
about in the shafts and tunnels and really do nothing, although they
pretend to be busy in all kinds of labour, sometimes digging ore, and
sometimes putting into buckets that which has been dug. [...] The
mining gnomes are especially active in the workings where metal has
already been found, or where there are hopes of discovering it,
because of which they do not discourage the miners, but on the
contrary stimulate them and cause them to labour more vigorously.

de re metallica trans hoover etc.

quote:


** Notes so far/notebook:

*** TM intro/start of all - new notebook 16/8+

core themes: 
- decay, death, preservation // bog bodies, immortality (immortality of athropocene)...
- origins (Moynihan)
- dis-articulation (of logical strata). dislocation of landscape -in dreams, of body, of a representation - a frame?island
- particulate matter

BG fronts and confronts death; the death of oneself as an individual,
the death of others, the death of a pig, the ends of worlds and the
death which enters as a miasmic or vaporous and mineral breath into the living.

strange loops and feedback loops: These cycles are embedded in complex
feedback loops involving climate catastrophe, tense ecological
conditions and complex algorithms.

that geology writes us, that we feedback on this geology - also mackay
in intro....

that the place is sentient - how to divine the sentience of a place

that we are this place - we are a landscape. an internal landscape,
flipfloppings of ballardian


The feedback loops crossing ... tighten, becoming internalised and
fault-line stressed.

That this descent is also a retrogression in time. As Moynihan writes
in Spinal Catastrophism (an essential complement to the essay here), a
geognostic work which is precisely concerned with this internal depth
as geotrauma, "depth is time." 


Further "Steno's Stratigraophic Law [implies] that all space and body
is itself nothing but coagulated time" 87 -> Ballard crystal world as
a further manual for BG

Spinal cat:

But when one’s past is a story of quakes and perturbations, the
internality implied by ‘one’s own history’ begins to
unravel. Ultimately, discovering finitude entailed discovering that
thought is functionally internal to itself, but self-containment
becomes problematic when modulated through the dimension of Grand
History. Here, ‘internality’ and ‘inclusion’ are reconstituted as a medium of
ancestral selfabruption rather than telescoping self-similarity and
ownership. What is at stake, then, is the realisation that the
historical vanishing point of selfcontainment just is self-exclusion:
in other words, depth. Historically speaking, I contain my
outside. This is what time does to a body, as we shall see in tracing
out this Secret History. The lesson is clear: psychosomatic
containment of oneself, when percolated through Grandest History,
equals hypogene alienation—the alienation of a body riddled with
time. It is this realisation that is inaugural of the phylogenetic
phantasy that is Spinal Catastrophism.

p50,51

For Ballard, a consistently nonconforming Kantian in his approach to
spacetime, temporality becomes a global secretion of the CNS

p77

Indeed, Ballard prophesies that, at the lowest spinal-neuronic
levels, organic self-inclusion completely evaginates into the
‘inhospitality of the mineral world’, its ‘inorganic growths’, its
‘profound anguish’, as in The Crystal World, where the deepest
entropic future leaks backwards into the present.21 Time bends into
itself, cephalopod-like: accelerative lurch into the entropic future
is nothing but thoracic drop into the preorganic past.

p102

mackay p2 - the descent takes on the character of a disturbed dream

At the same time it is essential to note, as Mackay observes that
this subterranean descent, this romantic or sublime path of soul-full
healing, "a healing return to the matrix of an all-encompassing
earth-process and thus to a more profound soul, dark double of the
self condemned to surface dealings" arises "precisely in parallel with
those other compulsions that were beginning to exert their cosmetic
dominion over the face of the planet. It is the shaping and hauling
and digging and layering of infernal machines that opened up new
breaches and passageways through which the other soul could pass."

- how this could parallel with contemporary situation of becoming
  geological... we become this planet and earth process, descend into
  our own more profound soul...

[p1. subtexts] Mackay - cryptolithic passions (intro to compilation of geopoetics - elaine)


becoming dump - list all these becomings also as suggested by Agnieszka

becoming geological is to become as these and many others

planet as body - becoming cosmic

body as planet


History is just the decryption of the relations of body parts; body
parts are just a matter of encrypted history

226 **important

If the planet is a brain, only a vanishingly small amount of its
trillion-cubic-kilometre volume is not lithified and dead. And, as
intimated above, it was in attempting to internalize —or digest—the
planet’s magmic inorganic depths that Spirit developed the ulcer we
now call the Unconscious. In other words, Recapitulation’s attempt to
retain Identity through Natural History’s temporal torsion ended up
sacrificing idealism’s Law of Continuity (at every psychic and somatic
level): the self-identical telescopic inclusions of Leibniz’s prior
‘fractal vitalism’ now became internal heterogeneity and layered
self-exclusions (or, stratification: the internal trace of Grand
Time). Idealist containment spectacularly intussuscepted into a
layer-cake of internalised self-exclusion: this was the invention of
philosophical Depth, or the evagination of telescoping self-inclusion
into invaginated and stratigraphic self-exclusion. And so, this is how
Schopenhauer could finally state that consciousness ‘is the mere
surface of the mind, and of this, as of the globe, we do not know the
interior, but only the crust’.

253 Mineralization streaks through organic form: from basic examples
like ‘Shells’ to ‘Mother-of-Pearl’ and ‘egg’ up to ‘cartilage’ and the
chitinous carapaces of ‘Lobster-Claws’; ‘still higher, Zoophytes
[i.e. corals] repeat the process’; and, at ‘the summit’, ‘Bone’ and
‘Teeth’ conclude the conservation, or reuptake, of the geological into
the biological.24 In a vision arguably even more fevered than that of
Kubla Khan, fColeridge thus witnessed lithic externality snaking its
way throughout organic inner time: he noted that annelids ‘deposit a
calcareous stuff’ as if they have to ‘drag about’ a piece of the
planet’s ‘gross mass’ whilst also observing that, in the ‘insect’,
this mineral ‘residuum’ has ‘refined itself’ into a carapace; in
‘fishes and amphibians it is driven back or inward’ into an
endoskeleton; and, at the pinnacle, this inwardification of stone
climaxes in humanity’s grand ‘osseous structure’.



key of becoming earth. becoming a landscape:

- dreams/magic - geology as inverted astrology, divination (Mackay p.2
  novalis) -

  also 
- becoming/being a landscape
- decay/death/immortality
- off planet
- digital extension/post-humanism
- material/core

** from talk with tm people 0609.

that all these issues - of extraction, of pollution, of climate
catastrophy, of the becoming pharmaceutical - are now brought inside
(where they already were, hiding, a dark consciousness) - they are not
implicit in that hidden way, to be probed or divined, but experienced
directly. these questions become embodied. We reflect on these inside,
from another quite radical position,,, (not the spectacle of the
anthropocene as an outside - that which is a bearing towards something
other or exterior. we inhale our own markers - feedback loops

effects on the psyche...

try to define internal feedback loops

in terms of:

implied by inferior/interior geology, astronomy, astrology

where these are also... this telescoping inwards, turning inside/out -
where we read of this? in subtexts???

feedback loops: extraction and burial, cycles of apparatus/extension,
of inhalation...

the lithic - we eat stones, stones measure our time, 

becoming acephalic - Marder...  Instead of reinventing the
hierarchical head, one must chop it off, so as to come up with an
acephalic (I would say, vegetal) configuration.

I am the Headless Daimon with sight in my feet, the Mighty One who possesses the immortal fire.
I am the Truth who hates the fact that unjust deeds are done in the world.
I am the one who causes lightning and thunder.
I am the one whose sweat is the heavy rain which falls upon the earth that it might be inseminated.
I am the one whose mouth burns completely.
I am the one who begets and creates.
I am the Favor of the Aiōn,
my name is a heart encircled by a serpent.
Come forth and follow.

PGM. The original Greek from PGM V.96—172, formally titled “Στήλη τοῦ Ἰέου τοῦ Ζωγρ εἰς τὴν ἐπιστολήν” (Stēlē toû Iéou toû Zōgr. eis tḕn epistolḗn) or “The Stele of Ieu the Hieroglyphist in His Letter” 

bataille; 2 Shamefully, We Get Life from Putrefaction, and Death,
Which Reduces Us to Putrefaction, Is No Less
Ignoble than Birth 

geophagy - eating the earth, eating oneself, itself

mistake of thinking that the earth, the cosmos is outside us, not to say that we are "one" with these others but....

