** back cover

becoming geological, becoming metal, becoming earth, becoming cosmic,
becoming resource, becoming contaminated, becoming dirt, becoming
mineral, becoming filth, becoming ethical geo-stratum, becoming
vulnerable, becoming dust, becoming turbulent, becoming
multi-plateaued nourishment for the earth, becoming resource for
unknown life, becoming historical, becoming colloidal, becoming
geological


Alfonso Borragan
Arthur Gouillart
Martin Howse
Cecilia Jonsson
Rosemary Lee
Patricia MacCormack
Michael Marder
Thomas Moynihan
Dr. Aaron Parkhurst
Elaine Tam 
Ines Tomašek
Anais Tondeur
Sissel Marie Tonn
Rosa Whiteley
Agnieszka Anna Wołodźko

** inside front // p2 facing contents

No more fruit, no more trees, no more vegetables, no more plants pharmaceutical or otherwise
and consequently no more food, but synthetic products to satiety, amid the fumes, amid the
special humors of the atmosphere, on the particular axes of atmospheres wrenched violently and
synthetically from the resistances of a nature which has known nothing of war except fear.

[Antonin Artaud. To have done with the Judgement of God.]

** about the book // unused - could be inside back cover

Becoming Geological functions as a manual for a new relation of the
human with the earth and with the cosmos, invoking becoming metal,
becoming earth and becoming cosmic as potential and multiple ways of
being and as active philosophies of the earth; a guide for how to live
and die within new planetary and cosmic techno-cycles.

Becoming Geological de-stratifies the history of close contacts
between living beings and geology, forming shiny and dull aggregates
of the matters of medical geology, medical anthropology,
geo-philosophy, occulted ecological theory, ethical geo-stratum, and
geo-poetics.
