** back cover

becoming as metal, becoming cosmic, becoming (of the) earth, becoming
contaminated, becoming (with) dirt, becoming mineral, becoming colloidal

or:

becoming geological, becoming resource, becoming as antimony, as
arsenic, as copper, as iron, as lead, as mercury, as silver, as gold,
becoming cosmic, becoming earth, becoming contaminated, becoming dirt,
becoming mineral, becoming filth, becoming ethical geo-stratum,
becoming-vulnerable, becoming dust, becoming turbulent and becoming
multi-plateaued nourishment for the earth, becoming resource for
unknown life, becoming historical, becoming colloidal


Alfonso Borragan
Arthur Gouillart
Martin Howse
Cecilia Jonsson
Rosemary Lee
Patricia MacCormack
Michael Marder
Thomas Moynihan
Dr. Aaron Parkhurst
Elaine Tam 
Ines Tomašek
Anais Tondeur
Sissel Marie Tonn
Rosa Whiteley
Agnieszka Anna Wołodźko

** inside front // p2 facing contents

No more fruit, no more trees, no more vegetables, no more plants pharmaceutical or otherwise
and consequently no more food, but synthetic products to satiety, amid the fumes, amid the
special humors of the atmosphere, on the particular axes of atmospheres wrenched violently and
synthetically from the resistances of a nature which has known nothing of war except fear.

[Antonin Artaud. To have done with the Judgement of God.]

** about the book // unused - could be inside back cover

Becoming Geological functions a manual for a new relation of the
human, invoking “becoming geological”, “becoming dirt” and “becoming
cosmic” as potential modes of becoming and as active philosophies of
the earth; a manual for how to live and die within new earthly and
cosmic techno-cycles.

Becoming Geological de-stratifies the history of close bodily contacts
between human beings and geology, forming aggregates of medical
geology, medical anthropology, occulted ecological theory, ethical
geo-stratum, and geo-poetics. //what else?

Becoming Geological functions as a guide sets of internally gnostic exercises,
(artistic) therapies for universal geo-trauma provoked by the
‘inhospitality of the mineral world’(ballard), invocations for taking
the earth with us, for leaving the earth behind, for a mysterious
world, a poison garden.

