* notebook notes

** 2024

Phrases/text remarked by Deleuze in The Exhausted

It is midnight. The rain is beating on the windows ... Then I went
back into the house and wrote, It is midnight. The rain is beating on
the windows. It was not midnight. It was not raining.

opening of Molloy...

somehow is early morning dreaming of different versions of this... He said... I said

coincidences of the observer, the writer, the observed, the instructed, the writer of the algorithm, the actors, the potential actors...

** 2022/2023 notebook notes

*** 12/2021

Consecutive narrators (as in book)

why and how and under what circumstances theyt can narrate

eg. my hands are tied, I wasn't there, I don't exist, My words are false, I lie

*** 1/2022

she accepts the new bit and passes on the old one - remembering the
old one. how does she remember? how does the gate remember?

memory is a feedback loop, a circulation, a return...

As memoried of phenomena are extinguished by death, the nature of these phenomena is connected with death. 

observed crows return in compression. expose technologically compression.

*** 3/2022

porn logic levels

0) permutations of actors and descriptions -n actors names details eg. X a Y light blond form? Ballard, Vaughan, Diana ... + permute desc
1) Beckett-Gray code -> entry into action, stage

[beckett gray =
- enter and exit one at a time
- all subsets
- actor who leaves is always rhe one who entered earliest (has been there longest)

2) series of actions - what are constraints for permutations of:

actions

[X does Y to Z]

X and Z series of Y actions. one way action

eg. X must do Y to every Z.

further Beckett Gray code - for each action. or actions overlaps? or every possible permutation 

Constraints: male/female, possible simultaneous orifices...

what these actions are? from Ballard (collect verbs) does Y to...

Actor X verb desc actor Y

3) how these actions are described? Translate action into Ballardian mode

*** 5/2022

examples of recursion in the real world...?

promoting absolute generics for recursion.

- how a generic function could look in the real world?

(an abstraction)

that which has its specificity applied to it (a sexual act. a generic sexual function)

that the description can be generic. but the action is specific

- is a generic function just a potential. a situation is set up. no
  actors/empty stage with props. where do the specifications come to
  be attached. We provide the possibilities for that attachment.

generic dockings of attachments.

*** 9/2022

Segments as a story/acts of people

4 people are connected. roles: observer/reporter, fucker etc...

- how to begin to translate that... or to go both ways

To translate what could be in acts/actions/dictations/descriptions/a play/a script/a narrative

[are these instructions?]
observations of acts
observations of acts based on a series of instructions generated by ... give by ...

+ recursions of these kinds of meta-descriptions on themselves (how?)

inner and outer:
- outer is a set of parameters, a script
- inner is the way of interpreting the script // slide across interpreters

what was generated, what do we experience. (one of the people describes how these instructions were generated)

4 actors/people/ each communicates with/has some control with another/talks to/feels/script orders

4 shift registers: each feeds into another, passes information, there is an order of operations, inner/outer function

on level of words and of actions described by words

*** 5/2023

QUAD:
- stage begins and ends empty (cyclic)
- n actors enter and exit one at a time
- all 2N subsets of actors
- actor who leaves is always the one who stayed longest

pornographic version:
- that subsets can repeat
- that every act must be performed on/by each actor
- who is on stage?
- male/female acts - both/either/or

FIFO: first in first out queue

//

computer memory (can be) (is like) a dream (why?)
                          is a map
                             a star map / a maze map
                             an ephemeris

the reality of computer memory compared to other forms of "storage",  of recording, of inscription

vs. astronomy as space-time transforms

//

Towards multiples of 18.6 year permutational text cycle
- computer memory
- operations which underly permutations
- permutations of code at lower levels

TODO:
- transcribe earlier observer texts (where?)
- revisit permutations of contiguity and how these could merge with planet, sun, moon alignments
- QUAD softwares - permutations with constraints (eg. simple recursive quad)
-> who is on stage, who is in the room

(that each is open to be permuted eg. theit identity is not absolute eg. 1 can be 4/3. 4 can be 1 etc...

The work is a documentation including code and materials of the
construction of this system - of dictation, of instructions to be
provided to reconstruct this system. 

the system of these logics, of this disconnect

format as a ring binder of images, documentation code

- a machine to be burnt
- a machine which dictates 18.6 years of actions

series of observers and programmers

observer watches the programmer who codes a program to generate instructions to be performed by X, Y, Z names...

An adventure game, a maze, a memory implemented in language X (Zork, M
language) which runs in layers on hardware Z ... what are these
elements, these layers and how can an element of the adventure (a
journey forward in time which is also a journey back, the bridge
underpass as a portal...

what sense can one layer make of another. a shoe

///

RG project for a revolution

- observer X is off/on [stage] / in the room / watching from outside

one side                                                              | on the other side
                                                                      | - a text adventure that can be permuted and interrogated
eg Zork code -> MTL interpreter -> machine with states and registers  | -  script which can be performed and the peformance can be observed by another

+ the commentary on this set of layers and structures


 [zork]code to be interpreted
 | // potential mismatch
  V
 interpreter 
  | // potential mismatch
  V
 low level (machine code/substrate)
 -> back to top // code - is this ouroboros possible (as layers of simulation?)

That these are all texts. or at least can be described/

lowest level: realm of diagrams and data sheets

larger diagrams...

Where do we place things like - the room in which the computer is
sitting - which may not be the same room where the player is
located. That the computer and player can be within the adventure
script itself - the programmer's revenge

- the programmer's tragedy...

- where do we place the residue, the material structures (data sheets)
  of the room or theatre (is it rehearsal in another space for an
  event which will be held in another space and perhaps using
  different actors) (eg also a tour or remote production, each theatre piece is played by different actors)

- texts such as Beckett Ill Seen Ill said - the outside, moon, changing of seasons, time passing. All Strange Away - an interior.

- collect names, places, structures, revisit contiguity permutations

- what constraints are: QUAD enter/exit "stage" of actions
all possible permutations of actions (male/female constraints/of each on others/themselves)

+ synonyms of actions and names

//

0 mined
1 refined
2 fabrication
3 assembly
4 coding - by hand of the interpreter and the language - bootstraps
5 running code -> 0
6 performing the script/actions output - which are these steps here
7 destroying the computer -> the script says to destroy the computer

the script says to mine the copper

- an order of operations
1. the instructions are given to the interpreter by the human
2. the interpreter outputs a series of instructions for a human 1->x
3. the machine burns

a reverse order:
3. the machine burns
2.5 performance 2.5 performed by human...
3 x->1 instructions are emitted
1. the instructions are given to the interpreter

The locations
The passing of time - solar, lunar and stellar cycles
- a sequence of events (120 days of)
- memory / storage/recall

Beckett- what is the sequence of events? they are remembered.

The future informs the past. Time operates in reverse, moon rising and setting in reverse (stand stills)

location, time, materials ++ the sound of ...

- which is devised first - the interpreter, that which is interpreted, the machine which it runs on?

that which is interpreted = a kind of script, how do we position this file (on the skin?) coded in a language solely determined by the interpreter,
potentially as esoteric as can be...

//

That one text is instructions for another (a program, an interpreter)
which then delivers another text - a set of actions to be performed (a
script) which is then observed by A.

->

A writes a text which is interpreted by a text coded by B which then
delivers a set of actions to be performed by C and observed and
described by D (which is in its turn a text which is interpreted by a text coded by E)

in a ?cycle? leading back to A!

(new note: that A can also observe the actions of C and comment on
these in the knowledge that he supplied the text or prompts for the
interpreter)

permute these: "interpreted" = burnt etc... incised, (a vocabulary, a set of characters),,, vocab collected from ...

//

logic of sense 
p40. if the verses of the song were composed in accordance with the events, or the events in accordance with the verses

do they describe it. 
do they script it for a later describing/observing

[both at the same time? could that work?]

//

In reverse:
- review
- after party (crew, actors)
- curtain down
- crashed car lowered onto stage ??
- play (permutational)
- rehearsals
- instructions generated for the actors (other versions of that play watched by the actors, reading and learning the script)
- programmer writes program to generate instructions

different observers: the writer, the actors, the audience, the crew + material witnesses // chance witnesses

*** 8/2023

In the form of an interview which is disintegrating // the object of the interview...

- a tape recording of the interview is fading, becoming noisy, mouldy, crispy
- a printout of the transcription (badly made) is fading, the ink is running out. the printer is breaking down.
- tape recorder stalls, slows down, the band is breaking, stretching, mouldy, brittle
- printout is getting wet, muddy, damp, running inbk
- the objects being described are failing... eg, the TV flashes on very brightly and then dies. Afterimage fading. Eyes in inverse after the flash
- the assembly code printout to be keyed in/translated into machine code is fading. The pen to annotate the code with opcodes has dried up
- the keypad of the KIM1 to enter the machine code opcodes only works intermittently

*** 12/2023

Understanding layers of AI training eg. aitextgen, pytorch etc.

- TTS training crow voice
- line drawing training
- holes or leaks in GPU/neural net memory

That a process can take place in another memory space/place  ... (external memory)

Revisit observation/older texts: The code programs a series of actions
which are (to be) performed by actors and which (have been) observed
by a set of observers (permutations of this) 

eg.  Coder programs the actions of a set of observers who observe the
chance activities of a group of actors who are rehearsing a series of
revolutionary acts (they pretend to be actors)...

///

Leaking memory - that it is not refreshed at the correct rate so parts of it fade away ...

how does a process work with that memory?>

- that these kind of software questions become part of the observation text.

- what is the equivalent of the process memory?>

- a system of notation which helps in the executio of an action or a series of actions
- schedule or table
- a list of actions

[ what is kept in memory:
- temporary storage/stack
- where we left off, where we are at in time
- storage of variables. eg, how many of X have we sorted, fucked]


////////////////////

[see also new.org]

towards an adventure game...

** 19/4/2022

Diana - text for circulation of fluids and binary interpretation - Thomas Vaughan, milk of diana

That the instructions to complete the circulation and to interpret the fluids have been conveyed in binary by these same methods.

[also some notes before to fill in below:]

- only copy in when the receiver has made one circulation
[stories for each: ]
when you have circulated, i will copy in. 

when i have acknowledged that you have circulated you can copy in

what does it mean - when you have circulated...

** 15/10 2021???

he accepts the new bit and passes on the old one - remembers the old
one. how this memory works - how does he remember? how does the gate
remember?

logic records itself (the results) - the record is the logic...

logic of observers, of participants. 1-2
outputs. gates. splitters. passers-on. lick, penetrate or...

rewrite datasheet of a shift register for pornographic logic

diagrams/camera - 2 people -> 1 person / 1 out. they observe each
other. agree on what is a 1 or 0

1 person as logical structure

active low

** 20/12

1. strictly permutational texts - eg following beckett gray codes or
   slabs work X does Y to Z [constraints on ordering]

enters/receives - penetrates/withdraws - her/his/their

2. part of speech substitution. Ballardian and other analyzed
   phrasings - see latest

3. textgenrnn crossings

4. handwritten - logic of observer, of participants

// code which can execute = across platforms as active, between a
pill, a module, a cartridge, a text/piece of writing/broken down

traditional - compiler, assembler in one direction. disassembler in
the other.

consecutive narrators (as in a book) why and how and under what
circumstances they can narrate eg. my hands are tied, I wasn't
there. My words are made up. This is not how it happened.

8 bit hybrids of pornlogic/ergot/cartridges/tinymining/planets/metals
SCRAMs source, in code, in graphics, in hardware and slab instructions

logic/geomancy/usb combinatorials

towards -> combine adventure game and nltk/porn merges

as a real game which can be used to construct ideas/productions

open to the outside/embedded

divination game inside out

