* logic/recursive process

logic or a process records itself and the record becomes/is the logic

lays itself down, writes itself [in smoke, in fire, un the body,
in/as writing, a system of notation, as an operation]

bear spell...

a process or rather a logic which creates a record which is (its own) logic...?

[from darmstadt] The creation a series of material objects which bear
witness to these material interactions (of particles, raidation,
extractive materials), alongside a documentation of a process
involving particles (such as heavy ion collision or the detection of
muons passing through matter, of decay) in which the means of
recording (a camera or specialized detector) is implicated in the
process which is being documented.

The recording device is part of the process and is subjected to
material/atomic processes and interactions. 

what examples can we find? eg. fukushima camera on robot which records
the environment and ha its sensors destroyed by that environment...

from other notes/also starting with contiguity...[large notebook]

how documentation becomes part of/is the process eg. dissolution in
the earth of a recording device. thinking how this could relate to
*side channel attacks* - revealing of an underground or hidden process
in  order to gain entry into this process. how can recursion be
applied here?

----------------------
V                    |
recording -of- process

------------------
V                |
process <- measure

not the same- feedback of small material changes effect the
calculations of planetary, solar, astral events for that location -
time shifts...

translations of micro changed (dew) into other realms (finance)

we did: computation of temperature changes temp of computed/measured
environment [difference to fukushima example]

* void works

void smoke work

lava emptying/burning... burning leaves a void

VOIDT videos to finish

** VOID GPS work 

- GPS antenna, tcxo 0.5ppm ref!

** island/VOID work

where is the void located? on a server which proves its existence somehow...

see tech_notes

certificate - yves klein

Yves Klein, Zone de sensibilité picturale immatérielle (1959). 

zones of empty space

Klein offered his collectors the choice to participate in a
performance that involved burning the receipt and throwing half the
gold into the Seine. This act was meant to “rebalance the natural
order” that had been disrupted by the sale in the first place.

https://ipfs.io/ipfs/QmcdKPjcJgYX2k7weqZLoKjHqB9tWxEV5oKBcPV6L8b5dD

https://github.com/mitchellfchan/IKB

ERC 721

Solidity - smart contracts - examples???

wallet? which ones we have?

* other works/ideas

- ergot, storage, cartridges, ROM
- ouroboric pyrotechnics - connection of metals to pyro/ usb fuses
  //particle cases
- slabs/crypto work
- elixir

* pornographic logic

- porn cpu, alu, shift register, basic gates towards the adder

** machine learning now in testing.ipynb to pull out/edit 

now storyof0.ipynb

- TODO: how we could work per chapter on this////

** re-visiting dianacrash materials and code

*** ballardmatcher.py

collated NPs with new working code but we can't seem to match: pagetlatestNP001

maybe new tagger is different?

(replacing:tag1= nltk.data.load(nltk.tag._POS_TAGGER)

tags = nltk.pos_tag(tokenized)
    print(tags)

NP: {<DT>?<N.*|JJ.*><IN|N.*|VBN><VBN|IN|N.*><JJ.*|N.*><N.*>} # from crash wounds text
NP: {<DT>?<N.*|JJ.*>+<IN|N.*|VBN>+<VBN|IN|N.*>?<JJ.*|N.*>?<N.*>}
NP: {<DT>?<JJ.*>*<N.*>*<N.*>}
NP: {<JJ.*>?<CC>?<JJ.*>?<INJ><V.*>?<IN>?<V.*|JJ.*|N.*>+<V.*|JJ.*|CC|POS|IN|N.*>+}
NP: {<COL|INJ|CHR><DT|V.*|JJ.*|CC|POS|IN|NN.*|PRP.*|COL|TO|,>+}  =*****
NP: {<JJ.*>?<VBD|N.*>?<IN|VBD>?<NN>?<N.*>} # dt jj nn = the adjective noun 
NP: {<JJ|NN>?<NN><MD|R.*|WDT||V.*|JJ.*|CC|P.*|TO|DT|IN|NN.*|NN|COL|CHR>+}
NP: {<JJ.*>?<VBD|N.*>?<IN|VBD>?<NN>?<N.*>} # dt jj nn = the adjective noun 
NP: {<DT>?<JJ>?<NN|NNS>+<IN>?<JJ>?<NN|NNS>?<CC>?<JJ|NN>?<IN>?<NNS>}

new code in try2.py:

Attempt to:

- Classify sentences DONE
- Take first Noun phrase (NP) with X or more words from first sentence // question of waht o do with fullstop: ignore full stop?
- Count how many times this occurs in the full text?
- Output NP and maybe convert to grammar

 grammar = "NP: {<NN><NN>}  # Chunk two consecutive nouns"

- Take next NP (shift one? until we hit end of sentence?)

or try to match whole sentence?


** shift register

for SR we need D flip flops (or possible edge triggered otherwise how we stop a 1 going through all flipflops)

https://electronics.stackexchange.com/questions/561971/cascaded-flip-flops-and-shift-register-timing

file://f3La8.png

To understand it, consider first a gated D-Latch which is level
sensitive which means that the input is applied to the output as long
as the gate (E) is active, otherwise the last state is maintained:

Now one way to implement an edge triggered D-FlipFlop is by using two
D-Latches in a master-slave configuration:


When the clock is low the first latch (the master) is activated and
its output follows the D input but the second latch (slave) retains
its last state.

When the clock switches to 1, the master holds the state available at
the rising edge and then the slave will be active and its output
follows the maintained output of the master. This value will remian
until the next clock edge.

Now if you consider the successive D-FlipFlops of your circuit:

Before the clock rising edge, the master of each Flipflop is connected
to the state held by the slave of the previous Flipflop at the
previous clock edge .  At the rising edge of the clock, it is this
maintained value that will be latched by the master of each Flipflop
which is the status at the previous clock edge. this maintained value
will be applied to the output of the D-Flipflop after the rising edge.

** is porn logic using mechanics and bodies/prosthetics or just bodies?

** full adder

9 NAND gates

half adder would be 5 NAND gates

or

2x XOR, 1x OR, 2x AND - total of 5 gates/people (plus one or two output participants)

** beckett/gray code for pornographic logic

- all possible combinations without repeating
- FIFO - one who leaves has been there longest
- at each period one of x actors enters or leaves the stage

fucker x performs y on z. 3 sets of beckett/gray code for n=upto7

** older notes

how text becomes subject to logical operations (maybe revisit
grading/summary of text, OR or XOR of texts: two inputs (two subjects
writing), one output which then is one of the two inputs for the next
set of gates … recursive

star charts as entries to graphical shift registers (and plot some of
our own from SEGs)


