* 16/5/2022

- trashed pi sd with misplaced diode - so - re-install for VOID003

what was usv setup? what did we install on pi and run...

http://downloads.s-usv.de/files/pdf/SUSV_Manual_Industrial_Rev2_0_EN.pdf

: sudo apt-get install python-smbus i2c-tools

enable i2c in raspi-config

: wget http://downloads.s-usv.de/files/software/susvd-en-2.40-systemd-pi.tar.gz

tar zxvf / dpkg -i

: sudo ./susvd -start 

: sudo ./susv -timer 10

-status 
 



* 13/5/2022

- 1n4007 as protection diode across solenoid fixes errors on pi (serial urb issues) from interference)
[plus of diode towards plus supply] 

sep supplies tho. try same supply FINE

* 10/5/2022

/etc/network/interfaces on pi with cosmicwatch:

source-directory /etc/network/interfaces.d

allow-hotplug enxb827eb0ace62
allow-hotplug wlan0  

iface enxb827eb0ace62 inet static
address 192.168.1.10  
netmask 255.255.255.0
network 192.168.1.0
broadcast 192.168.1.255

iface wlan0 inet dhcp
   wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf


* 5/5/2022

- access to atari working with: 

: wine RespeQt/RespeQt.exe

but some atr/exe images crash computer...

* 19/4/2022

- erdsir_wormversion.c - how to reprogram?

also problems with island2 compilation/segfaults below - move towards new void - how we can prove it?

printings/dot matrix - epson 9 pin OKI_DATA_CORP_ML186 in cups - but doesn;t print pdf only test, libreoffice, for just plain text:

: cat /root/Downloads/test > /dev/usb/lp2

* 7/10/2021

- beckett codes and new pornographic logic

- revisiting island2 (root) - we re-made with new makefile:

: obj-m += island.o
: all
:	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
:
:clean:
:	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

now compile and we use kzalloc to zero the data,,,

we can check it with:

: hexdump -C -s 0x10000000 /dev/mem | head

* 5.10.2021

** archidoxa prints and cutouts

https://digital.staatsbibliothek-berlin.de/werkansicht?PPN=PPN645230227&PHYSID=PHYS_0048&DMDID=DMDLOG_0004

- scale to 320mm

- thershold/colour

- for backsides we need to flip and then rotate to match

- gimp despeckle for outlines/cuts to get svg

- in inkscape we trace bitmap

* 29.9.2021

- for transmission ecologies radio transmission broadcast:

: python meminping.py

- access to /dev/mem (using kernel module ->  https://github.com/ozgunawesome/devmem-full-access

- insmod module

- sending data in ICMP packets - using USRP and gnuradio companion to
  receive - we tuned to 2.4GHz with -1.8M seek (fmradio2.grc file),
  gain at 66 and RX2 antenna

- in audacity we open data as 32 bit float...

* 28.9.2021

- to zip files from dired in emacs:

mark with m, then ! (operation), then: zip -r yourfile.zip *

- to automate processing of materials eg. text, audio, gps/geographic...

for text:

: e2ps -af Helvetica -p -nh -size 24 -line 120 2709_slab2logic.txt > 2709slab2.ps

: ps2pdf 2709slab2.ps

: pdfnup 2709slab2.pdf --nup 4x4 --no-landscape

(or other options. then to change size to A0 we need to open and print-to-file in evince)

* 21.9.2021

- alignment for cuttings (but not sure how we made it!)

align.svg

- shifted slab3 - invocation/instruction code to:

  /root/notes_and_projectsNOW/contiguity_res/software/slab3_invocation_instruction

// quick note that we had to reduce number of instructions as was
over-writing bootloader (which we had to reprogram from arduino app)

Slab 3-Invocation/instruction

Slab 3 is a USB storage device which is activated by the data receiver
(on plugging into the slab) and which presents a changing invocation
or set of instructions which are dependent on the position of the moon at
that time and at that specific location. The instructions are based on
the invocation of the Bear asterism (Ursa Major) from ancient Greek papyri.

A sample instruction/invocation might read as follows (not to be interpreted):

Cohere In A Conglomerate
Feed On Filth
Be The One Which Shows Forth
Lead Those In The Underworld
Gain Information Regarding Characteristics Not Yet To Be Seen
Send Researchers To The Fire
Reveal The Minutes
Hold The Whole Cinnabar
Hand Off The Centre
Fore-Think
Lurk In The Nooks And Crannies Of Houses
Bring  Attackers
Sex Transistors
Pin Data
Punish Ratings
Dream Of Sunless Leakage
Hold Memories Of The Heart
Route Within Eternal Boundaries
Be Ignorant Of The Golden Attention Of The Forest



* 7/9/2021

- working file/fat fake virtual FATFS is in: 

  /root/notes_and_projectsNOW/contiguity_res/software/enstix/sources:

- moon etc. astro arduino software:

* 27/8/2021

https://rhodesmill.org/pyephem/quick.html#phases-of-the-moon

https://gist.github.com/jgrocha/11259d44e2906bfc8bc0

https://michelanders.blogspot.com/2011/01/moon-phases-with-pyephem.html

* 16/8/2021

- altered arduino code for contiguity residency - self measurement code so that via serial we have commands:

l for list sd card, d and then type number of file to dump!

- for particles/target processor (we need to add pt100 sensor to
  atmega) we have kimuno code on atmega328 16MHz and we want to upload
  code for kim to the processor (eventually over hardware serial
  using commands in particle_control.ino but for now we test on
  minicom

seem able to send (with 20msec delay for char and 200msec for line0

commands in 6502
TAB - get into terminal mode
L - to load
[S in minicom - send software]
0200 (or start) + SPC
G - to run 

but doesn't print correctly - or software not set for serial but in
other display mode is also odd...

but microchess at 0c000 in kimuno rom seems to display ok, also loads
from ptp but then runs without stop

///

TODO: how to assemble/compile code to ptp / papertape files:

http://retro.hansotten.nl/6502-sbc/kim-1-manuals-and-software/kim-replicas-and-clones/load-papertape-format/

arduino code to set serial settings and send code on soft serial
to target (and how to test if is running on target - call and response)

2,3 RX, TX... to 11,10 in example code for softwareserial seems to work 

- TODO: try loading code and see if temperature changes on running code...

* 12/8/2021

we measure temperature of atmega328u in atmega board - measuring itself...

set terminal png
set output "test.png"
plot "owntempmeasured12082021" with lines

"upload with programmer" in arduino was key!

* 10/8/2021

: jupyter notebook --allow-root

copy sections for plotting, what we can plot and how (eg. space between)

librecad is for dxf

* 5/8/2021+

- using many_solstices.py (in contiguity/software) to load locations
  from csv and output x years of solstice horizon alignments

- for qgis we use python panel to load a full directory of the generated csv,s:

#+BEGIN_SRC python 
import os.path, glob
layers=[]
for file in glob.glob('/root/notes_and_projectsNOW/contiguity_res/software/results/*'): # Change this base path
  uri = "file:///" + file + "?type=csv&delimiter=%7C&useHeader=No&wktField=field_2&spatialIndex=no&subsetIndex=no&watchFile=no&crs=epsg:4326"
  vlayer = QgsVectorLayer(uri, os.path.basename(file), "delimitedtext")
  vlayer.addAttributeAlias(0,'X')
  vlayer.addAttributeAlias(1,'Y')
  layers.append(vlayer)

QgsMapLayerRegistry.instance().addMapLayers(layers)
#+END_SRC
