See general set up and installation images to get an idea of the layout:

Main elements are:

- the 2 meter long sliding rail which the head with pipes and electronics will slide along - there are two clear perspex sides
- the head with pipes and electronics which moves back and forth
- a plastic pulley which is attached to the motor on the back of the head and with each send bolted to the perspex sides
- a pump board which has three sets of pipes going to the 3 bottles (below)
- sand, rocks, scrap e-waste the length of the rail underneath the head
- desktop PC, keyboard and screen connected to USB cable from head and with bootable USB operating system
- three 5litre pastic bottles - 2 with chemistry, one with distilled water
- lab power supply for motors and pumps
- ceramic object placed on PC or nearby
- books to be placed nearby

* 1 - carefully remove head and pump assembly from case and spread out elements

* 2 - take out rail and place on long table - raise a bit to avoid scratches


* 2.1 - slide head carefully on to rail

place pump assembly behind the rail in the middle of the table area at the back

you may need to loosen the four bits on the underside of the metal sliding head 

avoid scratching the rail - the head should slide very smoothly up and down the rail

the two switches should make contact with the ends of the rail


* 2.5 attach perspex sides to the rail at each end with bolts

the four holes on each side should be towards the back of the rail!

you need to place some heavy bricks either side of the perspex sides to keep things steady. make sure these don't get in the way of the head


* 4 - thread pulley through motor and attach to perspex sides at each end of the rail

the assembly should still move up and down freely by hand - it should not be too loose or tight

it can easily be adjusted at any time

* 5- mix chemistry and distilled water

one 5l bottle - mix 250g Ferric ammonium citrate (green) with 1.5 litres distilled water

in another 5l bottle - mix 100g Potassium ferricyanide with 1.5 litres distilled water

in third bottle - 5l distilled water

place these near the pump board.

the pipe attached to LIGHT pump should go all the way into the
distilled water bottle, the other two pipes into the two other
bottle. it doesn't matter which. the two chemical bottles should be
completely covered in foil or black wrap to keep the light out.

* 6- hook up power supply

red wire to red (right hand connector), black to black (left hand connector)

plug in power supply, pi power supply (from head) to power strip

do not plug power strips to mains power

* 6.5 - visual check all

visual check - check all wires and pipes - does anything look loose or
unconnected. if it is not covered here then please call me before
proceeding further

* 7- test motors and pump

make sure the head is positioned in the middle of the rail

with all power plugged in and switched on, plug in the usb cable from the head into a laptop/computer

using arduino software:

- open arduino software
- select tools->serial port and choose arduino serial port 
- select tools->serial monitor

a new window should open - if it doesn't and there is an error go back and select a different serial port

- in the top send portion 

type: R (followed by return) - the head should move right

L (followed by return) - the head should move left

- check by moving the head with these commands that it moves smoothly to each end of the rail

- type E (followed by return) - the light pump should pump

repeat this step until water drips from the head

- type E (followed by return) - the light pump should pump

repeat this step until water drips from the head

- type W (followed by return) - the other 2 pumps should pump

repeat this step until dark chemistry drips from the head

switch off all power. Check for any leaks and if necessary re-attach any pipes and tighten any connections.

* 8- attach PC

plug power into power strip. do not attach to mains or turn on

attach usb cable to head

with computer powered but nothing else, switch on and check that it
boots from the USB stick. If not you will need to maybe enter the BIOS
and change any boot settings. A Raspberry PI is supplied which can
also function instead of the PC if necessary.

* 9- calibration box placed and sand etc arranged

Place the calibration box to the right of the leftmost rail side and
make sure that with the head far left a black square is under the
camera of the head

place first a layer of sand, rocks, e-waste spread out across all the way that the head will follow 

check that the head is not stopped in its movement by anything

* 10- boot up computer with all power on

after a while the head should move far left, it should slowly perform
calibration and then a display will open on the PC screen and the
program will start - head moving back and forth and water and
chemistry dripping on to the sand and rocks and so on

* 11- final adjustments

stop the computer, turn off power and adjust (only if necessary) - adjusts maybe to tightness of pulley, smooth motion.

* 12- arrange books, ceramic object nearby

* 13- exhibition start up and shut down each day

STARTUP:

- Check that nothing looks broken, weird(?) or that no leaks appear
  (liquid on floor or around electronics). If there appear to be
  problems please do NOT start.

- switch on the computer and check it powers up
- switch on all power/power supply (red lights up) 
- check for smooth movement and startup

If there are strange noises or leaks then please SHUTDOWN all power immediately!


SHUTDOWN:

- switch off power supply
- turn off computer
- turn off all power
