* Older

Hutton/steam engine and Needham

the analogy he saw with a “machine” using force “either produced by
steam, or by extremely thin and dry air.” This model is interesting
because it ... History of Geology

"fermenting is rotting with style" - reddit

Peter delights in transforming often abstract social concepts into
mechanisms - for example party beer crate suspended by stretchy
bungees from the ceiling - easy to reach when the supply is plentiful,
weight 

how could we manifest notions such as "forced obscolescence" through
mechanics or through other lively systems - could a particular
packaged ferment overrun our smart-phone within a planned length of time.

the exception and the cut; the vessel is the cut...

what is the exception? to raise an exception

sinking below - returning into, giving up energy, becoming coal or...

we internalize and em-body all these exceptions, all of these outdoor
microbes and bacteria become hard-working parts of these
body-machines - these exceptions are now en-ceptions, endo-ceptions

-cept, the taking in towards one self

the exception is no longer from the outside, blown by the winds of
ill-fate, but a part of us, of our bubble

*define an exception, what is an exception?* a paradox - 

exception handling is the process of responding to the occurrence of
exceptions – anomalous or exceptional conditions requiring special
processing - during the execution of a program.

exception or *trap* - trapped in a swamp

Exception handling is a ”can of worms” 

** TODO/notes

 ///spontaneous generation and pasteur

needham - and geology? coal-fired mountain building heat theme

https://www.biodiversitylibrary.org/item/109054#page/13/mode/1up




We no longer need to avoid placing our bookshelves to
the south or west; the ill winds hopefully will not bring roosting bookworms. [Vitruvius.]

[Flemming - When I woke up just after dawn on September 28, 1928, I
certainly didn't plan to revolutionize all medicine by discovering the
world's first antibiotic, or bacteria killer. But I suppose that was
exactly what I did.]

Technology is that other wilful exception that makes a cut ... and
allows us to say "this is a mountain, this is a steam engine, a lump
of cheddar." And to create these devices. To distinguish and to
instigate more cuts in the material world which are cuts as symbols
and as sabotage, sluggish, cold words, as language, as magic spells
which force a looking back (Dante - condemned soothsayers)

 “Ah earth you old extinguisher.”
Samuel Beckett, Happy Days 

Cold earth, no more lies.

hardware exception - as steam engine in 19c cosmology - needham - to
computer cosmology - to that which can be simulated and shown - the game of
life is a contagion - 

exception is natural but is not the cut also nature? what do we mean
by this...

sandy mouth or a sour pickle

low places/sour bodies invokes a binary decision tree - either
or/earth or, the exception or the cut. The ... or the pickle - a
recipe deciding. Spontaneous generation or pasteurisation, life or
death.

pick your cosmology - lively spont gen of geo and... or pasteurised
sinking sand worlds, raising mountains prefiguring heat death, raising
spirited exceptions from the decaying or the dead, buckets kicked up.

https://en.wikipedia.org/wiki/Spontaneous_generation

In 1745, John Needham performed a series of experiments on boiled
broths. Believing that boiling would kill all living things, he showed
that when sealed right after boiling, the broths would cloud, allowing
the belief in spontaneous generation to persist. His studies were
rigorously scrutinized by his peers and many of them agreed.[39]

In 1837, Charles Cagniard de la Tour, a physicist, and Theodor
Schwann, one of the founders of cell theory, published their
independent discovery of yeast in alcoholic fermentation. They used
the microscope to examine foam left over from the process of brewing
beer. Where Leeuwenhoek described "small spheroid globules", they
observed yeast cells undergo cell division. Fermentation would not
occur when sterile air or pure oxygen was introduced if yeast were not
present. This suggested that airborne microorganisms, not spontaneous
generation, was responsible.[45]

Louis Pasteur's 1859 experiment is widely seen as having settled the
question of spontaneous generation.[47] He boiled a meat broth in a
swan neck flask. The bend in the neck of the flask prevented falling
particles from reaching the broth, while still allowing the free flow
of air. The flask remained free of growth for an extended period. When
the flask was turned so that particles could fall down the bends, the
broth quickly became clouded.[39] However, minority objections were
persistent and not always unreasonable, given that the experimental
difficulties were far more challenging than the popular accounts
suggest. The investigations of John Tyndall, a correspondent of
Pasteur and a great admirer of Pasteur's work, were decisive in
disproving spontaneous generation and dealing with lingering
issues. Still, even Tyndall encountered difficulties in dealing with
the effects of microbial spores, which were not well understood in his
day. Like Pasteur, he boiled his cultures to sterilize them, and some
types of bacterial spores can survive boiling. The autoclave, which
eventually came into universal application in medical practice and
microbiology to sterilise equipment, was not an instrument that had
come into use at the time of Tyndall's experiments, let alone those of
Pasteur.[3]

the land, which was like potters clay and entirely soft. But as the
sun’s fire shone upon the land, it first of all became firm, and then,
since its surface was in a ferment because of the warmth, portions of
the wet swelled up in masses in many places, and in these pustules
covered with delicate membranes made their appearance.  Such a
phenomenon can be seen even yet in swamps and marshy places whenever,
the ground having become cold, the air suddenly and without any
gradual change becomes intensely warm. And while the wet was being
impregnated with life by reason of the warmth in the manner described,
by night the living things forthwith received their nourishment from
the mist that feli from the envelop- ing air, and by day were made
solid by the intense heat; and finally, when the embryos had attained
their full development and the membranes had been thoroughly heated
and broken open, there was pro- duced every form of animal life. 1 Of
these, such as had partaken of the most warmth set off to the higher
regions, having become winged, and such as retained an earthy
consistency came to be numbered in the class of creeping things and of
the other land animals, while those whose composition partook the most
of the wet element gathered into the region congenial to them,
receiving the name of water animals. [https://archive.org/stream/DiodorosOfSicily034.598/Diodoros%20of%20Sicily%2001%20%281.1-2.34%29_djvu.txt]

** OLDER

It is the less-than-obvious connection between the realms of
material and living, energetic transformation and the worlds of
(human) technology, defined within embracing terms of command,
control, and communication [cybernetics, systems creation and
modelling, economy and the infrastructures and created mechanisms
which enable the feedback and construction of ...] which is made
evident within Flemmings's work, defining and defined by the point or
junction of flow between those Sour Bodies and those Low Places

[that the
technological realm which Flemming opens up and lets spill out 

(the contents of that particular black box transformed as if by magic,
so that the familiar contained materiality of algorithmic
infrastructures (even if we did expose them, we are none-the-wiser to
the microscoped conduits of silicon and copper) becomes sand, plastic,
buckets and pipes),

of a system-which-has-been-set-up (manufactured, machined howsoever primitively) with all its mechanisms and
circuits and discordant materialities, is the low place, like a swamp,
a dumping ground, midden, a bog, whereas the place of a more cohered and
involving process of fermentation, perhaps equally controlled but with
a more casual hand in its setting-in-process, maybe even more
contained and enclosed, is the body, or bodies, the sour, *pissed-off*
body at odds with and conflicting with both themselves and their
perhaps self-controlled environment [and what might cause such a body
to be so contrary to a place which they apparently have so adapted to
themselves - ref. Wiener, bio-adapter].

"this is how I do it; not exactly scientific; and good to read the
thing through as a whole, *it is not exaclty [sic] a step-by-step*"


I will try, like the little virus I am, to expose this essential
connection within this abstract series of recipes which equally form a
kind of journal [In the summer, during Peter's residency, we exchanged
rough recipes for ginger beer starters, known as ginger *bugs*,
experimenting with the addition of turmeric and honey to the mix.] Just
as Low Places can be viewed as an algorithm made flesh (hesitantly,
silently and without words which might enlighten), a straightforward
recipe is a series of instructions which makes visible its own
construction (in words). ["the magic of ordinary things" -
Henricks]. These words become bread, become pickles (of course with
access to suitable and seasonal materials or "produce"). [bread of
dreams - camporesi]. These words become dreams, repeating and changing
procedures, become new recipes in a kind of version control. The Low
Places are these dreamy, moulding, recipes, embodied and seperated
from any written series of awkward steps. Peter feigns to show us the
recipe to construct a Flemming [reminding me of the instructions for
maintaining Peter's .... "the electrodes will be LIVE and you must not
touch them!", the whispering mismatch between a decayed reality,
someone has moved the ladder, rinsed out the briny, salt water either
served for pickling or for dimming, and these ideal recipes]


"If you can't get the salt ratio, maybe just pour in 4 or 5 Arduinos to each bottle?"

All the pieces are there, we consider that we might even be able to
purchase all of the materials off-the-shelf from the local hardware store (OBI,
Bauhaus, Hellweg). No specialized materials or scientific equipment is
required for the construction of your ecosystem; if only we know what
to ask for, sourly and deadpan, for ourselves. There is something
which escapes us, sand trickling out of a useless bucket, pooling on
the floor. It is not wholly transparent. [closed exhalation of the
rubbered jar] Some kind of wordless, biting incantation for exposure would be
require in times of need, a magic circle or circuit chalked on the
ground or up the wall as follows:

spells or invocations from papyrus PGM as forms of recipe: we are
informed about the materials required (although some of the names may
seem unfamiliar and ...) and how these are to be put to use

example...

magic invocation for sand/silicon

[below as the first recipe with barbeque intro]

What do unknowable processes variously described as decay, rotting,
putrefaction, decomposition, deterioration, fermentation (controlled
rotting), circulation, corruption, spoiling, composting, digestion,
degradation, moulting, infection [Lister called infection
fermentation], dissolution, souring, moulding, disintegration -
processes which connect with the abject, with ordure, excreta,
disjecta, with the discarded and the rejected, the declining, the
defiled and unwanted, the sorely addled and the descending, the leaked
and spilled, frothed and then de-frothed, skimming its scum, what do
these processes have to do with technology [footnote rotting sounds]
and how does Flemming'[s work enlighten or enliven or even upset the
rotting and *worm-ridden* apple-cart of this potential relationship?

More simply, what do a laptop and a pickle have in common? Would it be
possible to devise simple recipes for either?

one is cooked. one is fermented. both as a putting to work in terms of eneregy

The simple answer is that they are both embedded within
thermocultural systems of control occupied with the conservation and
preservation [we can also call pickles, conserves] of state and the
(economic) management of discrete levels of energy. Within
technological infrastructures there is a maintenance of state (storage
in the cloud should maintain our memories without glitch) which
implies an expenditure of energy (a bucket spilling out water or sand
drives a mini turbine which generates electricity to charge my phone,
a pickle-pecked piper lifts and re-fills the bucket every few days,
nipping into the back room for a 25kg bad of sand, thus drawing on his own
restricted reserves of energy in some schoolbook illustration)[coal fired
comp]. A sandy-k/need demon surfs downhill a temperature gradient of entropy
leading us back into the dammed and thus civilized low countries.

The memorial of a one or a zero on a grand scale [Thomas Pynchon lets
us choose between: “If
patterns of ones and zeroes were "like" patterns of human lives and
deaths, if everything about an individual could be represented in a
computer record by a long strings of ones and zeroes, then what kind
of creature could be represented by a long string of lives and
deaths?” - Vineland? She pictures to herself the mattress he sleeps
on, bearing the “vestiges of every nightmare sweat, helpless
overflowing bladder, viciously, tearfully consummated wet dream, like
the memory bank to a computer of the lost.” Crying lot 49 - also
tastes like a urine-infested mattress ] also releases heat as
excess, a sour and unwanted byproduct of these bits circulating as a
flow of electricity through less-than-pure metals. [Finn Brunton "the
work of computation is the work of managing heat. The history of
computing is also the history of air conditioning and temperature control".] If the heat stays
inside, if it isn't dissipated as the balloons flexibly take in the
build up of carbon dioxide by the sour bodies, we risk cooking the
phone. A recipe for a mobile phone would also
include these now-wishful impurities, as happy rogue atoms nestling
within non-conductive silicon and allowing for a highly selective
circulation.


////

significance of these closed vessels, inhabited by some contained
process, impervious to other sour breaths or influences, allowing for
gassy expansions only and subsequent awaited and expected
contractions.  impermeable - rubber glove, balloon or condom.

an attention to detail within fermentation, observation of state (is
it bubbling yet, what happens when I open the jar or door, risking the
entry of unwanted agencies or wishful, dopey-eyed impurities,
maintaining a social distance which is all about exchange - as well
as a certain roughness, we do not need sterile conditions, we can make
vague measurements judging by eye or by hand, gauging temperature
without external apparatus, tasting and smelling as ways of becoming
acquainted and gauging the progress of invisible processes of inner
transformation, we can read the visible and tangible signs of
fermentation, cloudiness of the brine, changes in colour of a beetroot kimchi

- becoming familiar with the signallings of a certain complex of aromas, for example, of
fermenting, salted cabbage or of habanero peppers with crushed garlic
maturing in a salty brine

controlling temperature exchanges, managing gas exchanges, venting, air-locks

thermopolitics?

lactic acid fermentation - kimchi what is the process - and
putrefaction ?? enzymes produced

Semiconductor manufacturing works like a barbeque pit where hickory
smoke seeps into the meat and imparts a distinctive flavor. In the
diffusion process, a bar of silicon is cooked in a furnace at high
heat, and then a gas containing the appropriate doping impurities
... is pumped into the furnace ... In the same way that a barbeque
chef knows how long to cook the ribs to get the right taste of
hickory, solid-state physicists gradually determined the proper time
and temperature needed to put the precise amounts of impurities at
precise points on the silicon block.

[T.R. Reid quoted in Thermocultures of Geological Media. Nicole Starosielski]

Semiconductor manufacturing works like a blue cheese dairy where a
fungus such as Penicillium roqueforti are inoculated or injected
into sheep milk or milk curds and imparts a distinctive flavor. Just as in
the crystalline world of the diffusion process, ripening mould veins and
tyrosine or calcium crystals stud the cheese as it ferments. Once the cheese has
matured over several months, it is sterilized at ultra high
temperatures. This heat treatment also inactivates the Penicillium
roqueforti, inhibiting further fermentation. In the same manner,
solid-state physicists determine the proper time and temperature
needed to put the precise amounts of impurities at precise points on
the silicon block.

[the bacterium Brevibacterium linens is responsible for the smell of
many blue cheeses, as well as foot odour and other human body odors -
see peter notebook]

That the cheese maker could also become a barbeque chef, doping the
pure silicon of meat with hickory smoke, could equally be a
sacrificial priest if we take inspiration from the ancient practice of
alchemy - Zosimos - bodies are seperated, torn asunder, hewn like tree
trunks (Dante suicides) QUOTE zosimos - also the prima materia image
from Ripley scroll

And Putrefaction may thus be defined, after philosophers sayings,
To be the slaying of bodies,
And in our compound a division of things three,
Leading forth into the corruption of killed bodies,
And after enabling them unto regeneration,
For things being in the earth, without doubt,
Be engendered of rotation in the heavens about.
[ripley 12 gates putrefaction]


alchemist refer to the torture of metals - examples - with reference
to pasteurisation latour talks of the scientist as now being able to
"starve the microbes, kill them with antiseptics, make them eat
anything, in short, torture them in innumerable ways, in order to
learn something about them each time" (1988 the pasteurisation of france)


how can sacrifice emerge as a theme? though the sacrificial priest -
the sacrificed and the sacrificer - 

to be able to think in words or abstraction simultaneous with the
clear description of precise physical properties or processes,
Becket's peat thing

that all of these descriptions, analogies and connections are
fictions, not in a negative sense, they are myths - the cheesemaker,
the sacrificial priest, the pit barbeque chef, the chip manufacturer.


*** quotes

**** Inexplicable

Plants and fungi sense, transform and adapt. They speak with each
other and in this conversation acknowledge clear changes in the
earth. On a mundane level becoming indicators of changes in soil
chemistry, watchers of shifts in weather, observers of seasons and
migratory transformation. The forest bed, a base of earth, decay and
moss, turns over on itself in a sedimentary churn; the slow process of
earth coding, working perhaps through and towards a “mind of mud“, a
starred mushroom mind swallowing the observer. salt crystal
taste. entropy on the tongue.

In the slow swarm of light they remain silent, luminous. Eyes in the
place of eyes, Ears in the place of ears, tongues tasting chemical
gradients across the fungal network of thread-like cells. A truly
underground communications network, spreading through the vastness of
earth substrate, acting with ecosystem intelligence to form interfaces
across symbiotic networks of root chatter.

The forest smell of earth-veiled mycelium; observation of patterns,
fairy-ringed, white bulbous mushroom growth, and the first taste of
the peeled muscaria itself suggests another, perhaps more
constructive, microscopic interface. Sniffing, chewing, sipping the
earth substrate by way of those roots.

**** Cooked or Fermented? The Thermal Logic of Social Transformation
Elena Beregow

latest:

Lévi-Strauss compares these societies to a horologe, a clock-like
mechanism that measures time in order to maintain cyclic rhythms in
endless repetition, providing a steady regular movement that combats
disorder. By contrast, he compares hot societies to steam engines,
following a linear temporal logic.

p5

something like a horologe compared with a steam engine.

cooking replaces digestion in terms of energy - the energy comes from
outside us!

Digestion requires huge amounts fo energy; it takes hard work for the
body to process raw foods. Cooking literally externalizes this energy;
it uses fire energy in order to save body energy. 
p6

This primal metabolic process breaks living things down, reducing them
so their energies and atoms can be reused.
p9

Rot management strategies involve temperature control, as fermentation
usually requires specific outside temperature ranges. Most of the
lactic acid bacteria are metaphilic, which means they can cope with
normal room temperatures of 18 to 22*C .. whereas others - for
instance many yogurt cultures - are thermophilic and need cozier
temperatures of 42 to 45*C.

///

Inspired by thermodynamics, Serres notes that the 'best definition' of
the parasite is that it functions as a 'thermal exciter': it affects
the energy distribution within a system by warming it up or cooling it
down, by producing thermal noise and disorder.
p9

*necrological vitalism* of fermentation - fermentation's cold fire
... -> *these could go with alchemical torture bit*

Limiting fermentation to the endless cycle of ubiquitous, flourishing
life and renewal - as vitalist accounts tend to do - means to overlook
that fermentation irritates and interrupts this very cyclical logic of
life by introducing the irreducible principles of death and *mortification*.
p17

Accentuating this dark line ... fermentation would not stand for the
recycling of the existing world (after the virus), but for its slow
inner destruction. Indeed, it is not only the Anthropocene or the
Pasteurian scientist who is controlling and torturing microbes;
fermenting means that the involved bacteria eagerly begin their decay
work by killing other 'bad' microorganisms in a necrological
zombie-like movement between self-preservation and
self-elimination. Fermentation always has this uncanny, almost bleak
dimension to it: it is only the thin semi-permeable membrane of the
gastro-intestinal tract that prevents us from digesting ourselves.
p17

**** Thermocultures of Geological Media

Nicole Starosielski

... thermal technologies underpin the standardization of culture,
decreasing the distinctiveness of otherwise heterogenous meidia
objects and facilitating their circulation as global commodities. This
is visible in media production, as well as in the use of heating and
cooling to stabilize media over time, a key defense in the foght
against decay.
p294

The drive toward purity that structures the thermal production of
digital hardware is neither necessary nor neutral. It is designed
specifically to reduce error and *compartmentalize* digital content.
p294

... beliefs about purity and pollution circulate within the
electronics and mining industries and shape the design of thermal
technologies. They are deliberately crafted to remove 'impurities'
that 'contaninate' copper. 
p298

[thermodynamics and thermopolitics underwrite the circulation of
materials and bodies]

Purity, as a cultural value, not only structures the arrangement of
inorganic materials but conditions possibilities for how bodily matter
can circulate through the world, whether its movements are facilitated
by high-speed digital networks or inhibted by toxic substances.
p299

Hyungsub Choi (2007:770) observes that in the history of early
transistors, "making junction transistors by the alloying technique
was comparable to baking cookies. Workers, usually women, attached
indium dots to either side of the germanium wafer and installed them
in the furnace. Just as in baking cookies, two variables were crucial:
temperature and time."

Writing in 1997, John F. Flynn argued that even though "cooking in
general, and breadmaking in particular, may be regarded as central to
the empirical foundations of technology and science, even the most
general references to either is consistently and conspicuously absent
from standard hsitorical surveys of Western technology," despite the
many ties between cooking, alchemy, chemistry and metallurgy. 
p306

**** Internet Daemons. Fenwick McKelvey.

The "leaky bucket" algorithm imagines a packet flow as water filling a
bucket and leaking out of it through a hole. .... Leaky buckets
regulate the intermittent flow of packets by varying queue size (how
big a bucket) and average bandwidth (the size of the hole). A queue
fills with packets arriving irregularly and holds them until they
might be sent at a regular rate. When a bucket overfills, water spills
out, When the queue fills, daemons drop packet, signalling congestion.

p107/108

[water with sand]

**** Zosimos/Jung torture etc.

And as they drew near to the place of punishments, he who held the
sword in his hand [said]: "Cut off his head, immolate his body, and
cut his flesh into pieces, that it may first be boiled according to
the method, and then delivered to the place of punishments."

Thereupon I awoke and said: "I have well understood, this concerns the
liquids in the art of the metals." And he who bore the sword in his
hand said again: "You have completed the descent of the seven steps."
And the other answered, as he caused the waters to gush forth from all
the moist places: "The procedure is completed."

[gush forth from all the low places]

Collected Works of C.G. Jung: Alchemical Studies (Volume 13) C. G Jung
p?

more from Jung?/other article?

It is characteristic of this rite that the priest is at once the sacrificer and the sacrificed.

**** Mortifacio Edinger Anatomy of the Psyche

Ruland says: "Putrefaction takes place when a body becomes black. Then
it stinks like dung and true solution follows. The elements are
separated and destroyed."

...



**** Finn Brunton: Heat Exchanges

Blotchy burns on my legs from my macbook, my book

In the Princeton summers, attending to the ENIAC machine – with its
special refrigeration units because it ‘ran very hot’, constantly
failing – was like working in a ship’s furnace, and the gunk messing
up the IBM punch cards was tar that had melted and dripped down from
the roof. Air was blasted over the mechanism at 4,500 cubic feet a
minute and the humid atmosphere of New Jersey iced over the coils.

In the shitty Princeton summers, attending to the ENIAC machine – with
its special refrigeration units because it ‘ran very hot’, constantly
causing blotchy burns on my legs – was like working in a ship’s
furnace, and the gunk messing up the IBM punch cards was tar that had
melted and dripped down from the roof. Air was blasted over the
mechanism at 4,500 cubic feet a minute and the humid atmosphere of New
Jersey iced over the coils.

This is a system, in other words, in which the grain of the universe –
the movement of particles, the collisions of electrons and ions –
becomes a kind of friction brake on the operation of a social
mechanism. Joule heating has been used as a source of visible light,
and now it’s been repurposed as a source of trust, a trust bulb. 

Like an incandescent bulb, it mostly produces heat, but it has trust
as a side effect. 

The oblique ingenuity of cryptocurrency development was the
realization that the awkward place where computing scrapes,
friction-hot, against its physical substrate was precisely the place
where a new kind of money could be built as an awkward fit between
idea, confidence, trust, and material foundation. 

**** Thermocultures of memory

Memory institutions depend on heating-cooling infrastructures for the
long-term preservation and mediation of cultural heritage. The
energy-intensive thermal regulation of object and data storage
environments is guided by the need to ward off decay ...
p1

the 'stabilization of media in archives and [other memory
institutions] keeps them from degrading, becoming waste, [yet] the
shift to energy-intensice cooling mechanisms substitutes the wate of
media media objects for the waste produced by fossil fuels -
Starosielski 2017. 303
p2

**** Ernst

https://culturemachine.net/vol-17-thermal-objects/time-temperature/

In statistical 'thermic' distribution over time, spatiotemporal
islands emerge against the tendency towards 'heat death'.

thermal memory:

A History of Computing Technology by Michael R. Williams; Prentice-Hall, 1985.
LOC#QA71.W66 1985

1. THERMAL MEMORIES

"The idea of thermal memory was tried by A.D. Booth, who, through the
lack of other suitable material being available in Britain after the
Second World War, was forced to experiment with almost every physical
property of matter in order to construct a working memory. The device
was never put into production because of the inherent unreliability of
the system.

"Booth's thermal memory consisted of a small drum whose chalk surface
was capable of being heated by a series of small wires. These wires
would locally heat a small portion of the surface of the drum and, as
the drum rotated, these heated spots would pass in front of a series
of heat detectors. When a hot spot was detected, it was immediately
recycled back to the writing mechanism which would copy it onto a
clean (cool) part of the drum. The back of the drum was cooled
(erased) by a small fan so that, by the time the drum had rotated to a
bring the same area under the heating wires again, a fresh surface was
available to receive the recycled information."

**** Deep Shit. Nigel Clark Myra J. Hird

However, it’s worth dwelling on the fact that the mass of once living
organisms that have returned to base matter has been estimated at
somewhere between a 1,000 and 10,000 times the mass of the Earth
itself (see Davis 1996, 73), while as far as scientists have been able
to ascertain, matter has only organised itself into life but once on
our planet. There is, then, something of an asymmetry between the
transition from base matter to life and the traffic that passes in the
inverse direction. p45

Davis, M. 1996. ‘Cosmic Dancers on History's Stage? The Permanent Revolution in the
Earth Sciences.’ New Left Review 217: 48–84.

a consequence of human subterranean waste disposal is a stimulation of
bacterial proliferation that is likely to involve adaptation and
diversification. p46

Eventually, whatever we stash underground comes into
contact with the bacterial life that dwells in the soil, or rather,
given a populace of some 40 million per gram, we mkight say they *are*
the soil. p46

feeding on our shit and waste - link of the earth and soil

‘These results indicated that a variety of hydrocarbon-degrading populations exist in the deep-sea plume and that the microbial
communities appear to be undergoing rapid dynamic adaptation in response to oil
contamination’ (Hazen et al. 2010, 207).

Ontologically speaking, then, our point in sifting through the pits of accumulat-
ing human waste is less to highlight some grand anthropic rupture with the integri-
ty of earth processes and more to prompt some sense of our inescapable, non-
reckonable, and irrecompensable debt to other entities (Clark 2010). We may well
spread our shit around to signal possession of the spaces in which we dwell, as
Michel Serres (2011) suggests. We may even inject our excrement deep in the Earth
to extend this stain into the layerings of geological time. Either way, what finally
becomes of our defecations is up to the swarms of miniscule beings that ultimately
engendered our existence. p51

**** History of Shit. Dominique Laporte

In 1493, Parisian haberdashers ... appealed to the King himself:
"bonnets and other effects cleansed by means of piss are neither
proper nor appropriate nor healthy to place on one's head: there lurks
infection in these methods." [cited in paulet engrais humains p285]
p.32

Corpses are no more and no less than waste that one buries
p.60

urine pliny natural history p99/100 note-ch5.4 xxviii xix

... the cosmic vision of the authors of the /Biblioteca Scatologica/,
who asserted that "man has with good reason called a small worlds a
microcosm, and his evacuations are but an image of those of teh great
world, the macrocosm"

cosmogenic vertigo

link to the divine
p112

Now, shit has to become profitable.

As Jeremy Bentham reminds us, "we never exercise, or at least should
never exercise a /bespoin/ [in French in original text] as pure
loss. It should be put to use as manure.

note ch6,1. Cited by J. A. Miller, "La Mchine panoptique de Jeremy
Bentham," /Ornicar?/ no. 3, 1975.
p119

about Pierre Leroux - the doctrine of the circulus

Each and every one would religiously collect their own waste and hand
it over to the State, that is to say the tax inspector, in lieu of a
tax or personal contribution. Agricultural production would
immediately double and destitution would disappear from the face of
the earth.
p127


By nature's law every man is at once a producer and a consumer, and
if he consumes, he produces.
p131

... that this man, who ahd within him the right to love and the
strtrength to do so, should die because the known circle of economics,
by excluding it from its necessary tie to the earth, has destroyed
the natural cycle.
130

To produce is literally to shit.
131

Leroux protest that "every last one of these poor wretches could liove
off his own manure."
131

divine power of earthly silt from which the creator eternally fashions
all beings
131

recipe for the divine earth:

I gave that sand many washings, so as to ensure it was free of dirt. I
pounded it into as fine a dust as I could manage. 
I then took charcoal which I pounded.
I took ashes from our hearth, that is to say ashes from coal. 
I took a brick and pounded it as well. 
I mixed these substances to form a mineral-vegetal powder. I mixed
this powder to my urine and to my excrement and I *fashioned earth.*
note6.11. 
132

note 2.15
"... si l'ordure qui dore dans les champs fait or qui düre dans les allées citadines, L'odeur de l'ordure düre ou l'or dort.”

If the shit that glows in the fields becomes the everlasting gold of
city streets, the stench of shit lingers where gold sleeps.

odeur, ordure, duration ...

**** The Science of Cheese

...  sometimes you can find NaCl deposits on the outside of smear
ripened cheese; calcium-containing crystals inside Camembert, Cheddar
and Roquefort; and crystalline clusters of tyrosine inside well-aged
cheese ...
p.96

/P. roqueforti/ for use in Roquefort cheese is traditionally obtained
from homemade rye bread that is over-baked and allowed to deteriorate
for a month in the caves. The coat of mold that develops on the bread
is powdered and sprinkled on the cheese ...

[also on skewered cheese]
p.109

Dmitri Mendeleev - periodic table and cheese (for diagram):

Mendeleev was supposed to inspect cheesemaking cooperatives for the
Society (Free Economic Society for the Encouragement of Agriculture
and Husbandry) on March 1-12, 1869, but had to delay the trip by a day
because his final form of the periodic table was completed ... 
p.196

Another thing you can try at home is calculating the speed of light by
heating cheese in a microwave oven.
p.235

- mendeleev dream periodic table cheese

On the 17th of February, Mendeleev decided against going on a
consultancy visit to a local cheese co-operative in order to stay at
home to work on his book. It appears that at some point in the morning
he took the invitation to the cheese co-operative and turned it over
in order to sketch some ideas about what elements to treat next in his
book.

https://blog.oup.com/2012/08/how-exactly-did-mendeleev-discover-his-periodic-table-of-1869/

[Mendeleev’s sketched notes on the back on the invitation to visit a local cheese co-operative.] 

**** Hutton Theory

Theory of the Earth; or an Investigation of the Laws observable in the
Composition, Dissolution, and Restoration of Land upon the Globe

theory hinges on this dissolution

When we trace the parts of which this terrestrial system is composed,
and when we view the general connection of those several parts, the
whole presents a *machine* of a peculiar construction by which it is
adapted to a certain end.
[209]

fitness of its purpose - that it is made for us and we should thus not
be sour or ungrateful for its fruits 

We have an irregular body of land, raised above the level of the
ocean.
[212]

decay and dissolution is essential. the best of all possible worlds. 

A solid body of land could not have answered the purpose of a
habitable world; for a soil is necessary to the growth of plants; and
a soil is nothing but the materials collected from the destruction of
the solid land. Therefore, the surface of this land, inhabited by man,
and covered with plants and animals, is made by nature to decay ...
[215]

We have now considered the globe of this earth as a machine,
constructed on chemical as well as mechanical principles.
[216]

But is this world to be considered thus merely as a machine, to last no
longer than its parts retain their present position, their proper forms
and qualities? Or may it not be also considered as an organized body?
Such as has a constitution in which the necessary decay of the machine
is naturally repaired, in the exertion of those productive powers by
which it had been formed.

... a duration or stability thus procured to the machine, considered
as a world sustaining plants and animals.
[216]

Sand is separated and sized by streams and currents
[219]

Part IV. System of Decay and Renovation observed in the Earth.

Let us know take a view of that system of mineral economy, in which
may be perceived every mark of order and design, of provident wisdom
and benevolence.
287

Sand is a material which enters, perhaps in greatest quantity, the
composition of our land. But sand is no other than small fragments of
hard and solid bodies, worn or rounded more or less by attrition.
290


**** Post-Pasteurian Cultures: The Microbiopolitics of Raw-Milk Cheese in the United States

Heather Paxson

Marcellino, like Latour, points to the social characteristics of
microbes: natural flora and fauna, they materialize as specific
communities within ecologies of human practice.
p.25

A natural rind is not simply dried out; it is the result of
carefully nurtured bicochemical reactions - basically controlled
rotting or what Levi-Strauss (1968) in his attempt at a universal culinary syntax
might call the cultural elaboration of the raw by natural means.
p.27

[thinking of raw and cooked essay and idea of cooking as doing the
heat-driven work of digestion - then what is fermentation]

/Brevibacterium linens/  is closely related to /Brevibacterium
epidermis/, native to the "warm, humid clefts between human toes"
[Enserink 2002:901] - also in Science of Cheese on this p?
p.28

Pasteurianism us a biopolitics predicated on the indirect control of
human bodies through direct control over microbial bodies.
p.36

Peter Dixon explained the craft of curing washed-rind cheeses by
drawing agricultural analogies: "We want to cultivate the right soil,
if you will, for the right things to grow." - silt quote shit
p.38


*** cheese

The mold that gives Roquefort its distinctive character (Penicillium
roqueforti) is found in the soil of the local caves. Traditionally,
the cheesemakers extracted it by leaving bread in the caves for six to
eight weeks until it was consumed by the mold. The interior of the
bread was then dried to produce a powder. In modern times, the mold
can be grown in a laboratory, which allows for greater
consistency. The mold may either be added to the curd or introduced as
an aerosol through holes poked in the rind.

Contrary to popular belief, Penicillium roqueforti does not produce
penicillin.[15] However, due to the presence of other
anti-inflammatory proteins,[16] it was common in country districts for
shepherds to apply this cheese to wounds to avoid gangrene.[17]

Roquefort,Bleu de Bresse, Bleu du Vercors-Sassenage, Brebiblu,
Cabrales, Cambozola (Blue Brie), Cashel Blue, Danish blue, Polish
Rokpol, Fourme d'Ambert, Fourme de Montbrison,
Lanark Blue, Shropshire Blue, Stilton, Bleu
d'Auvergne, Gorgonzola, Bleu de Gex and Rochebaron.

rotting bread. hallucinatory bread of dreams, crow bread

blue cheese. MAOI inhibition, neurotoxins

How can anyone be expected to govern a country with 325 cheeses? De Gaulle.

*** mortifactio - aras and edinger

https://aras.org/concordance/content/mortificatio

And when this corpse the force of vital breath began to lack, This
dying Toad became forthwith like coal for color black: Thus drowned in
his proper veins of poisoned flood, For term of eighty days and four
he rotting stood: By trial then this venom to expel I did desire, For
which I did commit his carcass to a gentle fire: Which done, a wonder
to the sight, but more to be rehearsed,

Feces, excrement, and bad odors refer to the putrefactio. The common
dreams of neglected or overflowing toilets which plague puritan-minded
people belong to this symbolism. Odor sepulcrorum (the stench of the
graves) is another synonym for the putrefactio. Since people today
seldom smell a rotting corpse, this image does not appear often in
dreams

One modern equivalent I have encountered is a dream of severe air
pollution. Worms accompany putrefaction, and dreams of worms convey
this image with powerful impact (fig. 006.07). 

In the I Ching,
*Hexagram 18* is entitled, “Work on What has been Spoiled,” and the text
tells us that “the Chinese character ku represents a bowl in whose
contents the worms are breeding. This means decay” ( Wilhelm, trans.,
The I Ching or Book of Changes, p. 75 ). 


Typical of the paradoxical imagery of the unconscious, the despicable
worm can turn into the supreme value. Thus the Messiah is equated with
a worm in the messianic Psalm 22 : 6: “But I am a worm and no man; a
reproach of men, and despised of the people”


I am Ion, the priest of the inner sanctuaries, and I submit myself to
an unendurable torment. For there came one in haste at early morning,
who overpowered me, and pierced me through with the sword, and
dismembered me in accordance with the rule of harmony. And he drew off
the skin of my head with the sword, which he wielded with strength,
and mingled the bones with the pieces of flesh, and caused them to be
burned upon the fire of the art, till I perceived by the
transformation of the body that I had become spirit. And that is my
unendurable torment.”

Ion, the priest of the inner sanctuaries, is a personification of both
the prima materia and the Philosophers' Stone. He is both the
sacrificer and the sacrificed.

"This man of copper whom you have seen is the sacrificial priest and
the sacrifice and he who vomited out his own flesh. To him was given
authority over the water and over those men in mortification." -
zosimos

http://www.levity.com/alchemy/zosimos.html

- the despised, the most common - aurora consurgens, low places swamp
  man - 

“The prima materia is ‘saturnine,’ and the malefic Saturn is the abode
of the devil, or again it is the most despised and rejected thing,
‘thrown out into the street,’ ‘cast on the dung-hill,’ ‘found in
filth”.

**** ripley 12 gates putrefaction

And Putrefaction may thus be defined, after philosophers sayings,
To be the slaying of bodies,
And in our compound a division of things three,
Leading forth into the corruption of killed bodies,
And after enabling them unto regeneration,
For things being in the earth, without doubt,
Be engendered of rotation in the heavens about.

[...]

Make each the other then to hug and kiss,
And like as children to play them up and down,
And when their shirts are filled with piss,
Then let the woman to wash be bound,
Which often for faintness will fall in a swoon,
And die at last with her children all,
And go to purgatory to purge their filth original.

**** fermentation

For like as flour of wheat made into a paste,
Requires ferment, which we call leaven of bread,
That it may have the kindly taste,
And become cordial food to man and woman,
So you shall ferment your medicine,
That it may taste of the Ferment pure,
At all assays for ever to endure.

[...]

For true Fermentation as I tell you,
Is the incorporation of the soul with the bodies,
Restoring to it the kindly smell,
With taste and colour by natural compacting together,
Of things dissevered, a due re-integration,
Whereby the body of the spirit takes impression.
That either the other may help to have ingression.


**** un être condamnée aux cruels supplices d'un cloaque

a being condemned to the cruel tortures of a
shithole/cesspit/cloaque/which is another way of saying that all
energy is sucked down...

sticking fast in a black, dirty and foul smelling slime or clay

original text - french/german

Lennep quotes the original text, which describes "un être condamnée
aux cruels supplices d'un cloaque, paraissait aussi noir qu'un Maure,
n'épargnant rien de ses forces pour délivrer son corps condamné aux
infectes prisons de ce bourbier fangeux et plein d'immondices. Comme
chacun restait sourd à sa complainte, il n'aspirait plus qu'à la
Parque inhumaine, lorsqu'une jeune beauté plein d'humanité, vint à son
secours." As well as being called a "moor" in this text, other
alchemical texts refer to the figure as an Ethiopian (see Lennep,
op. cit. p. 119). The text goes on to tell how the woman clothes the
man in the robe, lifts him up and takes him with her to heaven.

Translation; "a being condemned to the cruel cloacal depths of
torture, 

the cruel tortures of a cesspool

looking as black as a Moor, trying with all his might to
extract his body condemned to the infected prison of this miry
quagmire of filth. As everyone was deaf to his cries, he had no hope
but to succumb to this inhuman fate, when a beautiful young woman,
full of humanity came to his rescue"

other/close version: https://archive.org/stream/latoysondorovlaf00tris#page/60/mode/2up

this is 1612 version of elaborated 1602 french translation. 

Das älteste bekannte Exemplar der alchemistischen Grundlehre stammt
aus den Jahren 1531–1532 und wird im Kupferstichkabinett (Handschrift
78 D 3) der Staatlichen Museen Berlin am Berliner Kulturforum
aufbewahrt.[3] Weitere Exemplare (insgesamt 20 sind bekannt) befinden
sich unter anderem in der British Library (MS Harley 3469) zu London
und der Pariser Nationalbibliothek.

Maier: 

Voici un extrait du traité alchimique de Michael Maïer "Symbola aurae mensae" édité en 1617 où il est question de Morienus le Romain :

 "Morien le sage avait quitté
Le monde impur, ses vaines joies
Pour embrasser dans le désert
Tout le poids de la solitude.
Au roi Calid, qui l'appelait,
Il sut montrer l'art intégral,
Tout en protégeant sa lumière
D'un voile aux yeux des ignorants.
Prends cette chose méprisée
Que tu foules aux pieds sans le voir,
Sinon tu montes sans échelle,
Sûr de tomber à la renverse." 

take this scorned thing, which you mess under your feet without seeing
it,

if not you will climb with out a ladder
sure to fall upside down

