Old earth, no more lies, I've seen you, it was me, with my other's
ravening eyes, too late. You'll be on me, it will be me, it will be
us, it was never us.




"... si l'ordure qui dore dans les champs fait or qui düre dans les allées citadines, L'odeur de l'ordure düre ou l'or dort.”

[If the shit that glows in the fields becomes the everlasting gold of
city streets, the stench of shit lingers where gold sleeps.]

[History of Shit. Dominique Laporte]



shit, the hot waste, lumps of steaming coal powering computation,
cryptocurrency, the cyclical, always thinking of its return, its is repetition

Shit as money is repetition and circulation, and all repetition is shit and circulates.


sand, the mineral, the geological, memory, Peter's imagination the low
places of woman of the dunes...

odd one out, the plain and pure sand, not studded with fermented salty blue
crystals of impurity - a physics of dirt

not so much as material, nor as cultures, but rather as process 

-> computation

described it as "like chewing a urine-infested mattress". 

mattress... 

hakarl icelandic shark buried in sand



decay or running down

descartes - machine made of earth - where?  “I suppose the body to be
nothing but a statue or machine made of earth"  Treatise on Man
(1633),



*** conclusions

obvious that technologies of computation, control and communication are always
subject to the noisy un-constraints of both materials (substrates) and
material-un-bound processes (thermodynamics), just as s/our bodies are
subject to disease, and disintegration, to good and bad microbes and moulds.


whilst relying on these materials - a reliance, a sub-orning (?), a parasiting

this world is us and is seemingly against us as decay

crossing nouns/material and processes - cheese, dunes, fermentation
and shit/shitting, sanding.

Peter Flemming - speculation of what a technology which acknowledges
its debts to the pleasures of approximate and un-studied cooking and
to fermentation, which attempts to willfully roll down into those low
places of thermodynamic gradient, of waste heat, to un-damm the flows
and circulations seperating various abysses with names such as
Anthropocene, computation, currency and exchange. sacrifice? burial of
the anthropocene

a darkly promiscuous set of technologies of sour-pissed-on/off bodies,
of local, overheating parasites (Inspired by thermodynamics, Serres
notes that the 'best definition' of the parasite is that it functions
as a 'thermal exciter': it affects the energy distribution within a
system by warming it up or cooling it down, by producing thermal noise
and disorder.  beregow p9 ), and perhaps finally of sand, rather than silicon,
dribbling and spilling over binary logic.

a bread of plagued and low dreams which is baked according to
technologies which are not for a human or a visible crow to
do-something-to-something-else with, to hide something or to transform
it, to transfer it, but technologies and techniques for the others,
precisely that imagination which mirrors all these of our endeavours
in another realm, of the decaying and of the dead.

woman of the dunes as postscript perhaps - a burial in sand, in the
lowest of places (lowest in alchemy, the most base)

Water will go to the low places
everyone despises
and be content.

Tao Te Ching

*** Recipes:

**** Shit, winter, summer, kimchi, bread, phone

kimchi in winter, bread in the spring, sand and shit in summer, phone
in autumn

**** Peter recipes

SAUERKRAUT
- salt
- water
- cabbage (or other vegetable matter)
Wait.
Eat.

GINGER BEER/GINGER BUG
- sugar
- water
- ginger (or turmeric, galangal etc)
Wait.
Stir.
Feed.
(repeat)
More water, more ginger.
Wait.
Drink.

DOSA
- any bean
- any grain
- water
Soak.
Wait a day.
Grind.
Wait a few hours, look for rise.
Eat.
(fenugreek for flavour)

BLUEBERRY WINE
- sugar
- water
- fruit mash
Wait.
Strain.
Drink.



*Splendor Solis - references to cooking in the Harley manuscript - third treatise, first parable explaining geology - also like the cheese/silicon chip*

third treatise, first parable

Where there are such hills and dales, there the Earth has been matured
and most perfectly mixed with heat and cold, moisture and dryness, and
there the best ores may be found. 

studded crystalline, blue cheese

But where the earth is flat there has been no accumulation of such
fumes and vapours, and there no ores will be found, while the uplifted
part of the soil, especially, such as has been slimy, loamy, and fat,
and has been saturated with a moisture from on high ; got soft again,
forming dough-like layers one on top of the other, which in the course
of time, under the influence of the Sun's heat, become more and more
firm, hard and baked ; and other ground as gravel and sand, brittle
and yet soft, hanging together like grapes, is too meagre and dry, and
has not received enough moisture, consequently it could not form
itself into layers, but remained full of holes, like badly prepared
pap, or like a mealy dough, which has not been watered enough ; for no
earth can become stone, unless it be rich and slimy and well mixed
with moisture.

Fourth parable: Make the bodies spiritual through dissolution and then

Exceptions and allied states of exception set into process cuts in and across
dead and living bodies and matter, [initiating the bread field and the stack] -
tehcnology as a recursive boundary-producing set of devices and blind
ruses - a world of hedgerows and hard shoulders, of a composting pile
or smouldering heap of leaves at the edges of the *garden*

about the cut: the Baradian cut, before which everything is mixed as a
dough.


question is how  an exception within a physical (computing) system,
an ecosystem for example, how could that exception be *trapped* and
signalled

*try/catch block*

states of exception - Agamben, J.-A. Mbembé - necropolitics

smell of these books: IC op-amp cookbook, CMOS cookbook, TTL Cookbook, TV Typewriter cookbook - recipes for electronics, cooking


A machine, made of earth, whose mechanical principle is dissolution, a
grinding down to spilling sand, a burning of wood, a free-range
anomaly. For all our coal and shit, life is buried. A divine power of
earthly silt from which the creator eternally fashions all beings.


coal, beckett and descartes - Obscure locks p. 57 - the ashes gray
p.30 in Watt



Life is an exception and, even for those living free range, is
experienced under a series of states of exception. This lively planet
is an un-homegenized anomaly in time and space, hoisting with the
universe towards a chilled, heat death, a decline in energy, the
dissipation or breathy running down of some kind of steamy engine constructed
on principles of energetic circulation and exchange. This cosmology is
an exceptional recipe which mires us in deep shit.

The texts of the Greek magical papyri are often written as we might
write a recipe: "Take the eyes of a bat..." for example. So in other
words the magic requires certain ingredients, much as Odysseus
required the herb Moly to defeat the magic of Circe. But it is not
just as simple as knowing how to put a recipe together. Appropriate
gestures, at certain points in the magical ritual, are required to
accompany the ingredients, different gestures it would seem produce
various effects. A magical ritual done in the right way can guarantee
the revealing of dreams and the rather useful talent of interpreting
them correctly. In other cases certain spells allow one to send out a
daemon or daemons to harm one's enemies or even to break up someone's
marriage.

https://en.wikipedia.org/wiki/Magic_in_the_Greco-Roman_world

PGM IV 1331-89

Powerful spell of the Bear - which accomplishes anything.

Anoint your lips with the fats, smear your whole body with oil, and
make your petition while holding a single-shooted Egyptian
onion. Speak concerning whatever you wish. Gird yourself with a a palm
fiber of a male date palm, kneel down, and speak the following *formula*:

"I call upon you ..."

Then write on a piece of papyrus the hundred-lettered name of Typhon,
curved as a star, nad bind it in the middle of the core with the
letters showing.

/This is the name:/ 

chemical curds 

shallow waters and sunken forests *stagnant waters*

Fizzles Old Earth. 

 “I'm all these words, all these strangers, this dust of words, with
 no ground for their settling, no sky for their dispersing, coming
 together to say, fleeing one another to say, that I am they, all of
 them, those that merge, those that part, those that never meet, and
 nothing else, yes, something else, that I'm something quite
 different, a quite different thing, a wordless thing in an empty
 place, a hard shut dry cold black place, where nothing stirs, nothing
 speaks, and that I listen, and that I seek, like a caged beast born
 of caged beasts born of caged beasts born of caged beasts born in a
 cage and dead in a cage, born and then dead, born in a cage and then
 dead in a cage, in a word like a beast, in one of their words, like
 such a beast, and that I seek, like such a beast, with my little
 strength, such a beast, with nothing of its species left but fear and
 fury, no, the fury is past, nothing but fear, nothing of all its due
 but fear centupled, fear of its shadow, no, blind from birth, of
 sound then, if you like, we'll have that, one must have something,
 it's a pity, but there it is, fear of sound, fear of sounds, the
 sounds of beasts, the sounds of men, sounds in the daytime and sounds
 at night, that's enough, fear of sounds all sounds, more or less,
 more or less fear, all sounds, there's only one, continuous, day and
 night, what is it, it's steps coming and going, it's voices speaking
 for a moment, it's bodies groping their way, it's the air, it's
 things, it's the air among the things, that's enough, that I seek,
 like it, no, not like it, like me, in my own way, what am I saying,
 after my fashion, that I seek, what do I seek now, what it is, it
 must be that, it can only be that, what it is, what it can be, what
 what can be, what I seek, no, what I hear, I hear them, now it comes
 back to me, they say I seek what it is I hear, I hear them, now it
 comes back to me, what it can possibly be, and where it can possibly
 come from, since all is silent here, and the walls thick, and how I
 manage, without feeling an ear on me, or a head, or a body, or a
 soul, how I manage, to do what, how I manage, it's not clear, dear
 dear, you say it's not clear, something is wanting to make it clear,
 I'll seek, what is wanting, to make everything clear, I'm always
 seeking something, it's tiring in the end, and it's only the
 beginning.”

― Samuel Beckett, The Unnamable 


worlding

low cold words and worlds



low places as (carbon) sinks and stores

contagion is easy to model, to simulate - exhibiting complex behaviour
from simple rules - Peter's greedy buckets


nourishing demons...

stomach as container

Our English word sour comes from the Indo-European word syr or sir , relating to
the souring of cheesemilk. Th e word is used for cheese in Slavic languages: cыp (“syr,”
Russian and Belarusian), cиp (“seer,” Ukrainian, Serbian, Croatian), cиpeнe (“seeren-
neh,” Bulgarian), ser (Polish), sýr (Czech), and syr (Slovak). Baltic languages also use
syr/sir as the root: siers (Latvian) and sūris (Lithuanian). (Science
of Cheese)

//////

Vitruvius, a Roman architect and writer of the 1st century BCE,
advised that libraries be placed facing eastwards to benefit from
morning light, but not towards the south or the west as those winds
generate bookworms.



midden old dumping place for waste


make the spiritual (vapour) corporeal by gentle cooking.

[the seventh parable]

Of my blood and water I wish
Plenty in all the World there is
It runneth in every place
Who it findeth he hath grace
In the World it runneth over all
And goeth round as a ball

Edinger p11/12

- massacre of the innocents

Coronis the crow maiden

Ernst - freezing and memory - thermal memory

shallow waters and sunken forests

The History of shit, the book itself, smells unbearably of that spray
which is administered to disguise an odour which cannot possibly be worse
than this dreadful perfume which finds its way into every pore.

smell of books

The History of shit, the book itself, smells unbearably of that spray
which is administered to disguise an odour which cannot possibly be worse
than this dreadful perfume which finds its way into every pore.

smell of books


**** Inexplicable

Plants and fungi sense, transform and adapt. They speak with each
other and in this conversation acknowledge clear changes in the
earth. On a mundane level becoming indicators of changes in soil
chemistry, watchers of shifts in weather, observers of seasons and
migratory transformation. The forest bed, a base of earth, decay and
moss, turns over on itself in a sedimentary churn; the slow process of
earth coding, working perhaps through and towards a “mind of mud“, a
starred mushroom mind swallowing the observer. salt crystal
taste. entropy on the tongue.

In the slow swarm of light they remain silent, luminous. Eyes in the
place of eyes, Ears in the place of ears, tongues tasting chemical
gradients across the fungal network of thread-like cells. A truly
underground communications network, spreading through the vastness of
earth substrate, acting with ecosystem intelligence to form interfaces
across symbiotic networks of root chatter.

The forest smell of earth-veiled mycelium; observation of patterns,
fairy-ringed, white bulbous mushroom growth, and the first taste of
the peeled muscaria itself suggests another, perhaps more
constructive, microscopic interface. Sniffing, chewing, sipping the
earth substrate by way of those roots.


**** ripley 12 gates putrefaction

And Putrefaction may thus be defined, after philosophers sayings,
To be the slaying of bodies,
And in our compound a division of things three,
Leading forth into the corruption of killed bodies,
And after enabling them unto regeneration,
For things being in the earth, without doubt,
Be engendered of rotation in the heavens about.

[...]

Make each the other then to hug and kiss,
And like as children to play them up and down,
And when their shirts are filled with piss,
Then let the woman to wash be bound,
Which often for faintness will fall in a swoon,
And die at last with her children all,
And go to purgatory to purge their filth original.

**** fermentation

For like as flour of wheat made into a paste,
Requires ferment, which we call leaven of bread,
That it may have the kindly taste,
And become cordial food to man and woman,
So you shall ferment your medicine,
That it may taste of the Ferment pure,
At all assays for ever to endure.

[...]

For true Fermentation as I tell you,
Is the incorporation of the soul with the bodies,
Restoring to it the kindly smell,
With taste and colour by natural compacting together,
Of things dissevered, a due re-integration,
Whereby the body of the spirit takes impression.
That either the other may help to have ingression.

other/close version: https://archive.org/stream/latoysondorovlaf00tris#page/60/mode/2up

this is 1612 version of elaborated 1602 french translation. 

Das älteste bekannte Exemplar der alchemistischen Grundlehre stammt
aus den Jahren 1531–1532 und wird im Kupferstichkabinett (Handschrift
78 D 3) der Staatlichen Museen Berlin am Berliner Kulturforum
aufbewahrt.[3] Weitere Exemplare (insgesamt 20 sind bekannt) befinden
sich unter anderem in der British Library (MS Harley 3469) zu London
und der Pariser Nationalbibliothek.
