* notes to fill in

song cheers from peter:

a coprophilic version of this very (Cheers) song: 

All is shit, unending suck of black sopping peat, surge of giant fans,
heathery gulfs of quiet where the wind drowns, my life and its old
jangles to the coprophilic jingle of Cheers and its theme, Where
everybody takes a shit.

Taking a shit in the world today
takes everything you got
Taking a shit on all your worries 
Sure would help a lot
Wouldn't you like to take a shit?
Sometime you wanna go
Where everybody takes a shit
And they're always glad you shit

etc.

Making your way in the world today
Takes everything you've got;
Taking a break from all your worries
Sure would help a lot.
Wouldn't you like to get away?

All those night when you've got no lights,
The check is in the mail;
And your little angel
Hung the cat up by it's tail;
And your third fiance didn't show;

Sometimes you want to go
Where everybody knows your name,
And they're always glad you came;
You want to be where you can see,
Our troubles are all the same;
You want to be where everybody knows your name.

Roll out of bed, Mr. Coffee's dead;
The morning's looking bright;
And your shrink ran off to Europe,
And didn't even write;
And your husband wants to be a girl;

Be glad there's one place in the world… 

order/ordure = points of ordure

- closed systems vs. leaking, maxwell's and other demons, perfect
  control, stasis, dual meanngs of entropy, entropy as a flow or
  gradient

- construction of systems and analysis of systems are not the same
  thing (how do we analyse a forest, or measure a forest)

- corruption, ordure, excreta, shit, rotting, dissolution, disintegration, loss of identity,
  leakage, putrefaction,  - thermocultures, how these are thought of in terms of
  energetic transformations, entropy

what we can sense, how we can sense material changes?

as some kind of instruction set or howto, as if it were a practical
manual - how to make peter's work, magic incantations, ordure

sour

what are the flows and circulations, tasting gradients... tongue
gradients from myc/foam text

interesting that digestion (alchemy) as part of preparation of organic
bio samples (shit, urine, sweat, blood)... break apart matrices etc.

http://www.levity.com/alchemy/ripgates.html

1. Calcination 	7. Cibation
2. Solution (or Dissolution) 	8. Sublimation
3. Separation 	9. Fermentation
4. Conjunction 	10. Exaltation
5. Putrefaction 	11. Multiplication
6. Congelation 	12. Projection

thermocultures heat cultures dispersion of heat through alive, living and
dead matters

the mortifactio diagram as a starting point and the jungian chapter -
what rotting means

acker text:

rotting, raw, pasteurisation, ferment

3 sets/series of texts: 

1- cold - serious about thermocultures and temperature, labour, short sentences,
glacial, shards, winter, waiting, looking outside of the window, the snow

2- warm - chatty and contagious, digesting, slow.

3- hot - particles bump and run against each other, leak and flow
Maxwell's demon, swellings, buboes, text pores open, liquid,
putrefying, summer day, honey melts, flies, death in the open

even hotter: evaporation, crystallisation, drying, brittle, fiery, walking in sand, buried in sand, collapsing, a recipe for fermentation/decay in sand burial, sand for heat

between the earth and the air - fermentation, evaporation, dew

heat in the data centre - hytt text also

** beginnings

It's winter time and the servers are brittle
As stiff as unworked flour-dusted dough
Causing multiple draining fans to shear crystalline under a new frost
Dusty plastic circuits strain and crack under my bare feet
Like a fresh baked toffee recipe from Peter

secret ingredient of apple cider vinegar

dew turns to frost, sheers within the flour dusted dough

from winter to autumn putrefaction and discarding - follow the temperatures and seasons, moon wax and wanes

/describing an imaginary installation and its progression and process from winter to autumn/

what are the media cultures of ordure, media history... slang

http://www.ordure.org/ and rotting sounds also...

Everything that is represented in the Museum of Ordure is subject to
the vagaries of an uncontrolled internal process which slowly deforms
and disables all information held in the museum. This is comparable to
the decaying processes which affect all artifacts in museums,
regardless of all attempts at preservation: the retouching,
repainting, cleaning, etc, which are incorporated risks to the purity
of artifacts when first acquired by museums. Even ‘successful’
renovations are subject to periodic changes resulting from shifts in
conservation policies. Eventually (and in accordance with the
fallibility of memory) artifacts are institutionally, progressively,
determinedly and inadvertently altered by acts of conservation
(sometimes unintentional acts of institutional vandalism) until they
cease to be recognisable as the objects first acquired. Of course in
both cases – in the virtual environment and in the material world –
the processes of generation, decay, and entropy are paramount. Museums
are by this definition charged with achieving the impossible.

Laporte, Dominique. History of Shit. Cambridge, Mass.: MIT Press, 2000. -> pdfs / psychoanalysis?

** structure

- winter to autumn, towards putrefaction:
- ripley's gates
- series of fragments - like i ching, series of recipes - sourbodies, recipe for autumn, for a circuit/circulation

** notes from emails

1. I'm attaching the text of my Canada Council 3 year grant related to the work I exhibited in Berlin, esp. Sourbodies (it's their auto-generated pdf, I can supply editable format, of course). Also attaching a condensed version of this text I sent to Bethanien to help generate the exhibition text. The atrocious first draft they made (with my comments) is also attached. I advised they pass it on to an editor; they did and it turned out a bit better... I don't have a copy of this handy.

2. here's a link to my Nextcloud folder where I uploade a bunch of images (it's my experimental de-Googledrive/Dropbox system, let me know if it works... you ought to be able to download everything as well):
https://vps269960.vps.ovh.ca/nextcloud/index.php/s/y63PbDNWwNtfDbr

There may be duplicates, it's mostly exhibition documentation, my
photos and the house photographer. Mine have been only quikcly
selected and are not developed / processed yet. However, the 'slides
from Sandberg talk' folder contains some notebook scans, research
images (of piles, pits, pounds, poles), a quote etc.

PUBLICATION SUMMARY / RECENT WORK / VIDEOS The publication will be
largely focused on the solo exhibition of two new works I did in
Berlin in October 2019, though I am not opposed to expanding (or
contracting) this. Some more pics attached, and here is a quick recap:

Low Places kinetic system with ropes, sand, water, brightly coloured
plastic, wallpaper; keywords: gravity, temperature change, labour,
cellular automata, physical algorithm, resource scarcity /
distribution, competition, complexity low places reel (exhibition
documentation, residency prototypes)
https://vimeo.com/382047015/f5a207e886

Sour Bodies 25 timelapse videos of various lacto-fermentation
processes + live transducer vibration/soundtrack of ginger bug
culture; keywords: temperature, transformation, microbes,
collaboration, fermentation sourbodies sample:

https://vimeo.com/325195038/bb20a4f9b4


PREVIOUS ESSAY I re-visited the essay you wrote in 2011 (I only have a
first draft somehow?). Lots has happened since then, so I think it
would make more sense to generate a mainly new text, as we talked
about. However, for what's it worth, here's a few passages / idea I
responded to on recent re-read:

1. Magic. I like this framing device / running allegory. Nelson Hendricks wrote a nice text on my work Instrumentation called Ordinary Magic:
http://skol.ca/wp-content/uploads/2012/08/feuillet_texte_henricks_ang.pdf

2. Laurie Anderson reference (blinking 12:00 on VCR):

"You know the little clock, the one on your VCR the one that's always
blinking twelve noon because you never figured out how to get in there
and change it?  So it's always the same time just the way it came from
the factory.  Good morning. Good night.  Same time tomorrow. We're in
record."

My favourite Laurie Anderson quote: "The trees are made of wood." I
think from one of her essays. Basically, the capitalist ethos in a
nutshell.

3. Simone Weil quote from "The Mysticism of Work": "Monotony is the
   most beautiful or the most atrocious thing. The most beautiful if
   it is a reflection of eternity – the most atrocious if it is a sign
   of an unvarying perpetuity. It is time surpassed or time
   sterilized."

4. bodily waste / abject: comes up in the shitting duck, barbershop
   hair.... I like this thread. It has a connection to fermentation /
   decay / waste / bacteria. And certainly the overflowing double-dosa
   jars in the Sour Bodies video series have abject connotations.

Here's the text on temperature / labour by Andreas Malm; also, we
didn't talk about it, but I thought about sand a lot this
year... Woman In The Dunes being a key text... also included
here... also "A Sand Book" by Ariana Reines


* materials

** Ripley

https://quod.lib.umich.edu/e/eebo/A75719.0001.001/1:14?rgn=div1;view=fulltext

older english or....

** Fermentation - older


TRew Fermentacyon few Workers do understond,     1
That secrett therfore I wyll expounde to the,
I travelyd trewly thorow many a Lond:
Or ever I myght fynde any that cold tell hyt me;
Yet as God wolde, (evermore blessed he be,)
At the last I cum to knowledge therof parfyt,
Take heede therfore, therof what I do wryte.
Fermentyng in dyvers maners ys don,     2
By whych our Medcyns must be perpetuate,
Into a clere Water, som lesyth Son and Mone;
And wyth ther Medcyns makyth them to be Congelate;
Whych in the Fyer what tyme they be examynate,
May not abyde nor alter wyth Complement,
For such Ferments ys not to our intent.
Page  174
But yet more kyndly som other men don     3
Fermentyng theyer Medcynes in thys wyse,
In Mercury dyssolvyng both Son and Mone,
Up wyth the Spryts tyll tyme wyll aryse,
Sublymyng them together twyse or thryse:
Then Fermentacyon therof they make,
That ys a way, but yet we hyt forsake.
Som other ther be whych hath more hap     4
To touch the trothe in parte of Fermentyng;
They Amalgam ther Bodys wyth Mercury lyke papp;
Then theruppon ther Medcyns relentyng,
These of our Secretts have som hentyng:
But not the trewth wyth parfyt Complement,
Because they nether Putrefy nor alter ther Ferment.
That poynt therfore I wyll dysclose to thee,     5
Looke how thou dydyst wyth thy unparfyt Body,
And do so wyth thy parfyt Bodys in every degre;
That ys to sey fyrst thou them Putrefye
Her prymary qualytes destroying utterly:
For thys ys wholey to our entent,
That fyrst thou alter before thou Ferment.
To thy Compound make Ferment the fowerth parte,     6
Whych Ferments be only of Son and Mone;
If thou therfore be Master of thys Arte,
Thy Fermentacion lat thys be done,
Fyx Water and Erth together sone:
And when the Medcyn as wax doth flowe,
Than uppon Malgams loke thou hyt throw.
Page  175
And when all that together ys myxyd     7
Above thy Glasse well closyd make thy fyre,
And so contenew hyt tyll all be fyxid,
And well Fermented to desyre;
Than make Projeccyon after thy pleasure:
For that ys Medcyn than ech dele parfyt,
Thus must you Ferment both Red and Whyte.
For lyke as flower of Whete made into Past,     8
Requyreth Ferment whych Leven we call
Of Bred that yt may have the kyndly tast,
And becom Fode to Man and Woman most cordyall;
Ryght so thy Medcyn Ferment thou shall,
That yt may tast wyth the Ferment pure,
And all assays evermore endure.
And understond that ther be Ferments three,     9
Two be of Bodys in nature clene,
Whych must be altryd as I have told thee;
The thyrd most secret of whych I mene,
Ys the fyrst Erth to hys owne Water grene:
And therfore when the Lyon doth thurst,
Make hym drynke tyll hys Belly burst.
Of thys a Questyon yf I shold meve,     10
And aske of Workers what ys thys thyng,
Anon therby I sholde them preve;
Yf they had knowledge of our Fermentyng,
For many man spekyth wyth wondreng:
Of Robyn Hode, and of his Bow,
Whych never shot therin I trow.
Page  176
But Fermentacion trew as I the tell     11
Ys of the Sowle wyth the Bodys incorporacyon,
Restoryng to hyt the kyndly smell;
Wyth tast and color by naturall conspysacyon
Of thyngs dysseveryd, a dew redyntegracyon:
Wherby the Body of the Spryte takyth impression,
That eyther other may helpe to have ingression.
For lyke as the Bodys in ther compaccyon corporall     12
May not show out ther qualytes effectually
Untyll the tyme that they becom spyrituall:
No more may Spryts abyde wyth the Bodys stedfastly,
But they wyth them be fyrst confyxat proportionably:
For then the Body techyth the Spryt to suffer Fyer,
And the Spryt the Body to endure to thy desyre.
Therfore thy Gold wyth Gold thou must Ferment,     13
Wyth hys owne Water thyne Erth clensyd I mene
Not ells to say but Element wyth Element;
The Spryts of Lyfe only goyng betweene,
For lyke as an Adamand as thow hast sene:
Yern to hym draw, so doth our Erth by kynde
Draw downe to hym hys Sowle borne up wyth Wynd.
Wyth mynd therfore thy Sowle lede out and in,     14
Meng Gold wyth Gold, that is to say
Make Elements wyth Elements together ryn;
To tyme all Fyre they suffer may,
For Erth ys Ferment wythouten nay
To Water, and Water the Erth unto;
Our Fermentacion in thys wyse must be do.
Page  177
Erth ys Gold, so ys the Sowle also,     15
Not Comyn but Owers thus Elementate,
And yet the Son therto must go,
That by our Whele yt may be alterate,
For so to Ferment yt must be preparat:
That hyt profoundly may joynyd be
Wyth other natures as I seyd to thee.
And whatsoever I have here seyd of Gold,     16
The same of Sylver I wyll thou understond,
That thou them Putrefye and alter as I have told;
Ere thou thy Medcyn to Ferment take in hond,
Forsowth I cowde never fynde hym wythin Englond:
whych on thys wyse to Ferment cowde me teche
Wythout errour, by practyse or by speche.
Now of thys Chapter me nedyth to trete no more,     17
Syth I intend prolixite to eschew;
Remember well my words therfore,
Whych thou shalt preve by practys trew,
And Son and Mone loke thou renew:
That they may hold of the fyfth nature,
Then shall theyr Tynctures ever endure.
And yet a way there ys most excellent,     18
Belongyng unto another workyng,
A Water we make most redolent:
All Bodys to Oyle wherwyth we bryng,
Wyth whych our Medcyn we make floyng:
A Quyntessens thys Water we call
In man, whych helyth Dysesys all.
Page  178
But wyth thy Bace after my Doctryne preperat,     19
Whych ys our Calx, thys must be don;
For when our Bodys be so Calcenat,
That Water wyll to Oyle dyssolve them sone;
Make therfore Oyle of Son and Mone
Which ys Ferment most fragrant for to smell,
And so the 9th Gate ys Conquered of thys Castell.

*** Ripley's Ninth Gate - fermentation modernised

True Fermentation few workers understand,
That secret therefore I will expound to you.
I travelled truly through many a land,
Ere ever I might find any that would tell it me :
Yet as God would, evermore blessed be he,
At at last I came to the perfected knowledge thereof,
Take heed therefore what I thereof do write.

Fermentations in divers manners be done,
By which our medicine must be perpetuated,
Into clear water - some looseth Sun and Moon,
And with their medicines make them to be congealed;
Which in the fire when they be examined,
May not abide, nor alter with complement:
For such fermenting is not to our intent.

But yet more kindly some other men do,
Fermenting their medicines in this way -
In Mercury dissolving both Sun and Moon,
Till time with the spirit they will arise,
Subliming them together twice or thrice;
Then Fermentation therewith they make;
That is a way, but yet we it forsake.

Some others there be which have more sense,
To touch the truth in part of fermenting -
They amalgam their bodies with Mercury like pap,
Then thereupon their medicines relenting;
These of our secrets have some hint,
But not the truth with perfect complement
Because they neither putrefy, nor alter their Ferment.

That point therefore I will disclose to you,
Look how you did with your imperfect body -
Do so with thy perfect bodies in each degree,
That is to say, first you putrefy them,
Destroying their former qualities utterly,
For this is wholly to our intent,
That first you alter before you ferment.

To your compound make ferment the fourth part,
Which ferments be only of Sun and Moon,
If you therefore be master of this art,
Your fermentation let thus be done,
Fix water and earth together soon,
And when your medicine as wax do flow,
Then upon amalgams look you it throw.

And when all that together is mixed,
Above the glass well closed make your fire,
And so continue it till all be fixed,
And well fermented to your desire,
Then make Projection after thy pleasure
For that is medicine each deal perfected,
Thus must you ferment both red and white.

For like as flour of wheat made into a paste,
Requires ferment, which we call leaven of bread,
That it may have the kindly taste,
And become cordial food to man and woman,
So you shall ferment your medicine,
That it may taste of the Ferment pure,
At all assays for ever to endure.

And understand that there be Ferments three,
Two be of bodies in nature clean,
Which must be altered as I have told you;
The third most secret of which I mean,
Is the first earth of his water green:
And therefore when the Lion does thirst,
Make him to drink till his belly burst.

Of this a question if I should move,
And ask of workers, what is this thing ?
Anon thereby I should them prove,
If they had knowledge of our fermenting:
For many a man speaks with wondering,
Of Robin Hood and of his bow,
Which never shot therein I trow.

For true Fermentation as I tell you,
Is the incorporation of the soul with the bodies,
Restoring to it the kindly smell,
With taste and colour by natural compacting together,
Of things dissevered, a due re-integration,
Whereby the body of the spirit takes impression.
That either the other may help to have ingression.

For like as bodies in their compaction corporeal,
May not show out their qualities effectually,
Until the time that they become spiritual,
No more may spirits abide with bodies steadfastly,
Till they be fixed together with them proportionally,
For then the body teaches the spirit to suffer fire,
And the spirit the body to enter to your desire.

Therefore you must ferment your gold with gold,
Your earth cleansed with his own water, I mean,
Nought else to say but element with element,
The spirit of life only going between,
For like as an adamant as you have seen
Draws iron to him, so does our earth by kind,
Draw down to him his soul borne up with wind.

With wind therefore the soul lead out and in,
Mingle gold with gold, that is to say,
Make Element with Element together run,
Till time all fire they may suffer,
For earth is Ferment without nay to water,
And water the earth unto,
Our Fermentation in this way must be done.

Earth is gold, and so is the soul also,
Not common, but ours thus elementary,
And yet thereto the Sun must go,
That by our wheel it may be altered:
For so to ferment it must be prepared,
That it profoundly may be joined,
With other natures as I said to you.

And whatsoever I have here said of gold,
The same of silver I will you understand,
That you putrefy them and alter (as I have told)
Ere you take in hand to ferment your medicine.
Forsooth I could never find anyone in England
Who could teach me to ferment in this way ,
Without error, by practice or by speech.

Now of this chapter needs to treat no more,
Such I intend prolixity to eschew;
Remember well my words therefore,
Which you shall prove by practice true,
And Sun and Moon look you renew,
That they may hold of the fifth nature,
Then shall their tincture evermore endure.

And yet a way there is most excellent,
Belonging unto another working,
A water we make most redolent,
All bodies to oil wherewith we bring,
With which our medicine we make flowing,
A quintessence this water we call,
Which heals all diseases in man.

But with my base, after my doctrine prepared,
Which is our calx this must be done,
For when our bodies be so calcined,
That water will to oil dissolve them soon
Make you therefore oil both of the Sun and Moon,
Which is ferment most fragrant for to smell,
And so the ninth gate of this Castle is conquered.

The end of the Ninth Gate.

** Ripley's fifth gate - putrefaction

NOw begynnyth the Chapter of Putrefaccion,     1
Wythout whych Pole no sede may multyply,
Whych must be done only by contynuall accyon
Of hete in the body, moyst, not manually,
For Bodies ells may not be alterat naturally:
Syth Chryst do it wytnes, wythowt the grayne of Whete
Dye in the ground, encrese may thou not gete.
And in lykewyse wythout thy Matter do Putrefye,     2
It may in no wyse trewly be alterate,
Nor thyne Elements may be devyded kyndly;
Nor thy Conjunccion of them perfytly celebrat:
That thy labor therfore be not frustrate,
The prevyte of Putrefying well understond,
Or ever thou take thys Warke in hond.
And Putrefaccyon may thus defyned be,     3
After Phylosophers sayings it ys of Bodyes the fleyng,
And in our Compound a dyvysyon of thyngs thre,
The kyllyng Bodyes into corrupcyon forth ledyng,
And after unto Regeneratyon them ablyng:
For thyngs beyng in Erth wythowt dowte
Be engendryd of rotacyon of the Hevyns aboute.
Page  149
And therfore as I have seyd afore     4
Theyn Elements comyxt and wysely coequat,
Thou keepe intemperat heate, eschuyng evermore,
That they by violent hete be never incynerat;
To powder dry unprofytably Rubyfycate,
But into powder blacke as a Crowes byll
Wyth hete of Balne, or ells of our Dounghyll.
To tyme that Nyghts be past nynty,     5
In moyst hete kepe them fro eny thyng;
Sone after by blacknes thow shalt espy
That they draw fast to putrefying,
Whych thow shalt after many colers bryng
To perfyt Whytenes wyth Pacyence esyly,
And so thy sede in hys nature shall multeply.
Make ech on other to hawse and kysse,     6
And lyke as Chyldren to play them up and downe,
And when ther sherts be fylyd wyth pysse,
Then lat the Woman to wash be bound,
Whych oftyn for fayntnes wyll fall in a sound:
And dye at the last wyth her Chyldren all,
And go to Purgatory to purg ther fylth orygynall.
When they be there, by lyttyll and lyttyll encrese     7
Ther paynys by hete ay more and more,
The Fyre from them lat never cese:
And se thy Fornace be apt therfore,
Whych wyse men do call Athenor:
Conservyng hete requyryd most temperately,
By whych the Water doth kyndly putrefy.
Page  150
Of thys Pryncypull spekyth Sapyent Guydo,     8
And seyth by rottyng dyeth the Compound corporall,
And then after Moryen and other mo,
Uprysyth agayne Regenerat, Sympill, and Spyrytuall,
And were not hete and moysture contynuall,
Sperme in the wombe myght have now abydyng,
And so ther shold therof no frute upspryng.
Therfore at the begynnyng our Stonys thou take,     9
And bery ech on wyth other wythin ther Grave;
Then equally a Marryage betwyxt them make
To ly together six wekys; then lat them have
Ther sede consevyd kyndly to norysh and save;
From the ground of ther grave not rysyng that while,
Whych secret poynt doth many on begyle.
Thys tyme of Conceptyon wyth esye hete abyde,     10
The Blacknes showing shall tell the when they dye;
For they together lyke lyquyd Pyche that tyde,
Shall swell and burbyll, setyll, and Putrefye,
Shyning Golors therin thou shalt espye:
Lyke to the Raynbow mervelose unto syght,
The Water then begynnyth to dry upryght.
For in moyst Bodys hete noryshyng temperate,     11
Ingendryth Blacknes fyrst of all which ys
Of kyndly Commyxyon to the tokyn assygnate;
And of trew Putrefying, remember thys,
For then to alter perfytly thou may not mysse;
And thus by the Gate of Blacknes thou must cum in
To lyght of Paradyce in Whytenes yf thou wylt wyn.
Page  151
For fyrst the Son in hys uprysyng obscurate     12
Shalbe, and passe the Waters of Noyes flud
On Erth, whych were a hundred dayes contynuate
And fyfty, away or all thys Waters yode,
Ryght so our Waters as wyse men understode
Shall passe, that thou wyth Davyd may say
Abierunt in sicco fluminae: bare thys away.
Sone after that Noe plantyd hys Vyneyard,     13
Whych really floryshed and brought forth Graps anon:
After whych space thou shalt not be aserd;
For in lykewyse shall follow the floryshyng of our Stone:
And sone uppon that thyrty dayes overgone,
Thou shalt have Graps ryght as the Ruby red,
Whych ys our Adrop, our Ulyfer red and our Lede.
For lyke as Sowles after paynys transytory     14
Be brought into paradyce where ever ys yoyfull lyfe;
So shall our Stone after hys darknes in Purgatory
Be purged and joynyd in Elements wythoute stryfe,
Rejoyse the whytenes and bewty of hys wyfe:
And passe fro the darknes of Purgatory to lyght
Of paradyce, in Whytnes Elyxer of gret myght.
And that thou may the rather to Putrefaccyon wyn     15
Thys Exampull thou take to the for a trew conclusyon,
For all the secrett of Putrefaccyon restyth therein;
The heart of Oke that hath of Water contynuall infusyon
Wyll not sone putrefy, I tell the wythout delusyon:
For though yt in Water ly a hundred yeres and more,
Yet shold thou fynd it sound as ever it was afore.
Page  152
But and thou kepe hyt somtyme wete, & sometyme dry,     16
As thow many se in Tymber by usuall experyment,
By prosses of tyme that Oke shall utterly Putrefy:
And soe in lykewyse accordyng to our entent,
Sometyme our Tre must wyth the Son be brent:
And then wyth Water sone after we must hyt kele,
That by thys menes thou shalt to rottyng bryng hyt wele
For nowe in wete and nowe agayne in dry,     17
Now in grete hot and now agayne in cold
To be, shall cause yt sone for to putrefy:
And so shalt thow bryng to rottyng thy Gold,
Entrete thy Bodys therfore as I have thee told:
And in thy Putrefying wyth hete be not so swyft,
Lest in the Askys thou seke after thy thryft.
Therfore thy Water out of the Erth thow draw,     18
And make the soule therwyth for to assend;
Then downe agayne into the Erth hyt throw,
That they oft tymes so assend and dessend,
From vyolent hete and sodayne cold defend
Thy Glasse, and make thy fyre so temperat,
That by the sydys thy Water be never vytryfycate.
And be thou wyse in chesing of thy Water,     19
Medyll with no Salt, Sulphure, nor mene Minerall,
For whatsoever any Water to the do clatter;
Our Sulphure and Mercury be only in Mettall,
Which Oylys and Waters som men call:
Fowlys, and Byrds wyth other namys many one,
Because that folys shold never know our Stone.
Page  153
For of thys World our Stone ys callyd the sement,     20
Whych mevyd by craft as Nature doth requyre;
In hys encrese shall be full opulent,
And multeply hys kynd of thyne owne desyre:
Therfore yf God vouchsafe thee to enspyre
To know the trewth, and fancies to eschew,
Lyke unto the shalbe in ryches but few.
But many be mevyd to worke after ther fantasy     21
In many subjects in whych be Tynctors gay,
Both Whyte and Red, devydyd manually
To syght, but in the Fyre they fle away,
Such brekyth Potts and Glassys day by day:
Enpoysonyng themfelfs, and losyng of theyr syghts
Wyth Odors and smoks and wakeyng up by nyghts.
Their Clothes be bawdy and woryn threde-bare,     22
Men may them smell for Multyplyers where they go;
To fyle theyr fyngers wyth Corrosyves they do not spare
Theyr Eyes be bleryd, & theyr Chekys both lene & bloe:
And thus for (had I wyst) they suffer losse an d wo;
Such when they have lost that was in theyr purse,
Then do they chyd and Phylosophers sore accurse.
For all the whyle that they have Phylosophers ben,     23
Yet cowde they never know our Stone.
Som sought in Soote, Dung, Uryne, som in Wyne:
Som in Sterr slyme, for thyng yt ys but one;
In Blood, Eggs; Som tyll theyr thryst was gone:
Devydyng Elements, and brekyng many a pott,
Multyplying the sherds, but yet they hyt yt not.
Page  154
To se theyr Howsys it ys a noble sport,     24
What Fornaces, what Glassys there be of divers shape;
What Salts, what Powders, what Oyles, and waters fort,
How eloquently, de materia prima they clape,
And yet to fynde the trewth they have no hap:
Of our Mercury they medle and of our Sulphur vyve,
Wherein they dote, and more and more unthryve.
They take of the Red Man and hys whyte Wyfe,     25
That ys a speciall thyng and of Elixers two,
Of the Quintessence and of the Elixers of lyfe,
Of Hony, Celydony, and of Secundyns also,
These they devyde into Elements wyth other mo;
No Multeplyers but Phylosophers callyd wyll they be,
Whych naturall Phylosophye dyd never rede nor see.
Thys felyshyp knowyth our Stone ryght wele,     26
They thynke them rycher then ys the Kyng;
They wyll hym helpe, he shall not fayle
Fraunce for to wyn, a wonders thyng;
The holy Crosse home wyll they bryng:
And yf the King were prysoner I take,
Anon hys Raunsome would they make.
A mervell yt ys that Westminster Church,     27
To whych these Phylosophers do haunte;
Syth they so much ryches can woorche,
As they make boste of and avaunte,
Drynkyng dayly the wyne a due taunte,
Ys not made up perfytly at ons,
For truly hyt lackyth yet many Stonys.
Page  551
Folys doe folow them at the tayle,     28
Promotyd to ryches wenyng to be;
But wyll ye here what worshyp and avayle,
They wyn in London that nobyll cyte,
Wyth Sylver Macys as ye may se:
Sarjaunts awayting on them every owre,
So be they men of great honour.
Sarjaunts sekyth them fro Strete to Strete,     29
Marchaunts and Goldsmyths leyeth after them watch;
That well ys he that wyth them do mete,
For the great advantage that they doe cache,
They hunt about as doth a Rache:
Wenyng to wyn so grete tresure,
That ever in ryches they shall endure.
Som wold cache theyr goods agayne,     30
And some more good would aventure;
Som for to have wold be full fayne,
Of Ten pound one I you ensuer:
Som whych hath lent wythout mesure
Theyr goods, and be with powerte bestad,
To cache a Nobyll wold be full glad.
But when the Sarjaunts do them arest,     31
Ther Paukeners be stuffed wyth Parrys balls;
Or wyth Sygnetts of Seynt Martynes at the lest,
But as for Mony yt ys pyssyd on the walls:
Then be they led as well for them befalls
To Newgate or Ludgate as I you tell,
Because they shall in safegard dwell.
Page  156
Where ys my Mony becom seyth one,     32
And where ys myne seyth he and he?
But wyll ye here how suttell they be anon,
In answeryng, that they excused may be,
Saying, Of our Elyxers robbyd we be:
Ells myght we have payd you all your Gold,
Yf yt had been more by ten folde.
And then theyer Creditors they begyn to flatter,     33
Promysyng to worke for them agayne;
The Elyxers two in short space after,
Dotyng the Merchaunts that they be fayne
To let them go, but ever in vayne:
They worke so long, tyll at the last
They be agayne in Pryson cast.
Yf any then aske them why they be not ryche,     34
They sey they make fyne Gold of Tynn;
But he they sey may surely swym in dyche,
Whych ys upholden by the chyn,
We have no stock, therefore may we nought wyn:
Whych yf we had we wold some worche,
I now to fynysh up Westmynster Churche.
And some of them be so Devowte,     35
They wyll not dwell out of that place;
For there they may wythowten dowte,
Do what them lyft to their Solace,
The Archedeacon ys so full of grace:
Yf that they please hym wyth the Crosse,
He forsyth lyttyll of other menys losse.
Page  157
And when they there syt at the wyne,     36
These Monkys they sey have many a pound,
Wolde God (seyth one) that som were myne;
Hay hoe, careaway, lat the cup go rounde:
Drynk on, seyth another, the mene ys founde:
I am a Master of that Arte,
I warrant us we shall have parte.
Such causyth the Monkys then evyll to don,     37
To wast ther Wagys thorow theyr dotage;
Som bryngeth a Mazer and som a Spone;
There Phylosophers gevyth them such corage,
Behotyng them wynnyng wythout damage:
A pound for a peny at the lest agayne,
And so fayre promys makyth folys fayne.
A ryall Medycyne one upon twelve     38
They promys them thereof to have,
Whych they could never for themselfe
Yet bryng abowte, so God me save:
Beware such Phylosophers, no man deprave:
Whych helpyth these Monkys to ryches so,
Wyth thread bare Cowlys that they do go.
The Abbot well ought to cherysh thys Company,     39
For they can tech hys Monkys to leve in poverte,
And to go clothyd and monyed relygyously,
As dyd Seynt Benet, eschuyng superfluyte,
Esyng them also of the ponderosyte
Of theyr pursys, wyth pounds so aggravate,
Whych by Phylosophy be now allevyat.
Page  158
Lo who so medlyth wyth thys rych Company,     40
Gret bost of ther wynnyng may they make,
For they shall have as much by ther Phylosophy,
As they of the tayle of an Ape can take;
Beware therfore for Jesus sake:
And medyll wyth nothyng of gret cost,
For and thou do, yt ys but lost.
These Phylosophers (of whych I spake afore)     41
Medlyth and blondryth wyth many a thyng,
Renuyng in errors more and more,
For lac of trew understandyng,
But lyke must lyke alway ferth bryng:
So God hath ordeyned in every kynde,
Wold Jesus they wold thys bere in mynde.
Wene they of a Nettyll to have a Rose     42
Or of an Elder an Apple swete,
Alas that wyse men ther goods shold lose:
Trustyng such Losells when they them mete,
Whych seyth our Stone ys trodyn under fete:
And makyth them therfore vyle thyngs for to styll
Tyll at theyr howsys wyth stench they fyll.
Som of them never lernyd a word in Scolys,     43
Such thynk by reason to understond Phylosophy:
Be they Phylosophers? nay, they be folys:
Therfore ther Warkes provyth unwytty;
Medyll not wyth them yf thou be happy:
Lest wyth theyr flatteryng they so the tyll
That thou agre unto ther wyll.
Page  159
Spend not thy Mony away in waste,     44
Geve not to every speche credence;
But fyrst examyn, grope and taste;
And as thou provyst, so put thy confydence,
And ever beware of grete expence:
But yf thy Phylosopher lyve vertuosely,
Trust the better to hys Phylosophy.
Prove hym fyrst and hym oppose     54
Of all the Secretts of our Stone,
Whych yf he know not thou nedyth not to lose;
Medyll thou not ferther, but let hym gone,
Make he never so pytyose a mone:
For than the Fox can fagg and fayne
When he wold faynyst hys prey attayne.
Yf he can answer as ought a Clarke,     46
How be hyt he hath not provyd indede;
And yf thou wylt helpe hym to hys Warke,
Yf he be vertuose I hold hyt mede,
For he wyll the quyte yf ever he spede:
And thou shalt weete by a lytyll anon
Yf he have knowledge of our Stone.
One thyng, one Glasse, one Furnace and no mo,     47
Behold thys pryncypyll yf he take,
And yf he do not, then lat hym go;
For he shall never thee rych man make:
Trewly yt ys better thou hym forsake,
Then after wyth losse and varyaunce,
And other manner of dysplesaunce.
Page  160
But and God fortune the for to have     48
Thys Scyence by doctrine whych I have told;
Dyscover yt not whoever thee crave,
For Favor, Fere, Sylver, nor Gold:
Be none Oppressor, Lecher, nor boster bold;
Serve thy God, and helpe the powre among,
Yf thou thys lyfe lyst to continew long.
Unto thy selfe thy secretts kepe     49
From synners whych hath not God in dred;
But wyll the cast in Pryson depe,
Tyll thou them tech to do hyt in dede,
Then slander on the sholde spryng and sprede,
That thou dyd coyne then wold they sey,
And so undo the for ever and aye.
And yf thou teche them thys conyng,     50
Their synfull levyng for to mayntayne;
In Hell therfore myght be thy wonnyng,
For God of the then would disdayne,
As thow nought cowd for thy selfe sayne:
That Body and Soule you may bothe save,
And here in pece thy levyng have.
Now in thys Chapter I have the tought,     51
How thou the bodys must Putrefy:
And so to guide the thou be not cawght,
And put in duraunce, losse, and vylanye:
My doctryne therefore remember wyttyly,
And passe forth toward the Syxth Gate,
For thys the Fyfthe ys tryumphate,

** Putrefaction: This text has been modernised by Adam McLean from the 1591 edition of The Compound of Alchymy. 


Now we begin the chapter of Putrefaction,
Without which pole no seed may multiply,
Which must be done only by continual action,
Of heat in the body, moist not manually.
For bodies else may not be altered naturally,
Since Christ doth witness, unless the grain of wheat die in the ground,
Increase may thou not get.

And likewise unless the matter putrefy,
It may in no way truly be altered,
Neither may thy elements be divided kindly,
Nor the conjunction of them perfectly celebrated,
That thy labour therefore be not frustrated,
The privitie of our putrefying well understand,
Before ever you take this work in hand.

And Putrefaction may thus be defined, after philosophers sayings,
To be the slaying of bodies,
And in our compound a division of things three,
Leading forth into the corruption of killed bodies,
And after enabling them unto regeneration,
For things being in the earth, without doubt,
Be engendered of rotation in the heavens about.

And therefore as I have said before,
Thine elements commixed and wisely coequate,
Thou keep in temperate heat,
Eschewing evermore that they be not incinerate by violent heat,
To dry powder, unprofitably rubificated,
But into powder black as a crow's bill,
With heat of the Bath or else of our dunghill.

Until the time that ninety nights be passed,
In moist heat keep them for any thing,
Soon after by blackness you shall espy,
That they draw close to putrefying,
Which after many colours you shall bring,
With patience easily to perfect whiteness,
And so thy seed in his nature will multiply.

Make each the other then to hug and kiss,
And like as children to play them up and down,
And when their shirts are filled with piss,
Then let the woman to wash be bound,
Which often for faintness will fall in a swoon,
And die at last with her children all,
And go to purgatory to purge their filth original.

When they be there, by little and little increase,
Their pains with heat, aye, more and more,
Never let the fire from them cease,
And see that thy furnace be apt therefore,
Which wise men call an Athanor,
Conserving heat required most temperately,
By which thy matter doth kindly putrefy.

Of this principle speaks wise Guido,
And sayeth "by rotting dieth the compound corporeal",
And then after Morien and others more,
Upriseth again regenerated, simple and spiritual,
And were not heat and moisture continual,
Sperm in the womb might have no abiding,
And so there should be no fruit thereof upspring.

Therefore at the beginning our stone thou take,
And bury each one in other within their grave,
Then equally between them a marriage make,
To lie together six weeks let them have their seed conceived,
Kindly to nourish and save,
From the ground of their grave not rising that while,
Which secret point doth many a one beguile.

This time of conception with easy heat abide,
The blackness showing shall tell you when they die,
For they together like liquid pitch that tide,
Shall swell and bubble, settle and putrefy,
Shining colours therein you shall espy,
Like to the rainbow marvellous to sight,
The Water then beginneth to dry upright.

For in moist bodies, heat working temperate,
Engenders blackness first of all,
Which is the assigned token of kindly Conjunction,
And of true Putrefaction: remember this,
For then perfectly to alter thou can not miss,
And thus by the gate of blackness thou must come in,
To light of Paradise in whiteness if you wilt win.

For first the Sun in his uprising shall be obscured,
And pass the waters of Noah's flood on earth,
Which was continued a hundred and fifty days,
Ere this water went away,
Right so our waters shall pass (as wise men understood),
That you with David shall say,
"Abierunt in sicco flumina" : bear this away.

Soon after that Noah planted his vineyard,
Which royally flourished and brought forth grapes,
After which space you shall not be afraid,
For it likewise shall follow the nourishing of our stone,
And soon after that 30 days be gone,
You shall have grapes right as ruby red,
Which is our Adrop, our Ucifer, and our red lead.

For like as souls after pains transitory,
Be brought to Paradise, which ever is joyful life,
So shall our stone after his darkness in Purgatory be purged,
And joined in Elements without strife,
Rejoice the whiteness and beauty of his wife,
And pass from darkness of purgatory to light of Paradise,
In whiteness Elixir of great might.

And that you may the rather to putrefaction win,
This example take you for a true conclusion,
For all the secret of Putrefaction rests therein,
The heart of oak that hath of water continual infusion,
Will not soon putrefy, I tell you without delusion,
For though it lay in water a hundred years and more,
Yet should you find it sound as ere it was before.

But if you keep it sometimes wet and sometimes dry,
As thou may see in timber by usual experiment,
By process of time that oak shall utterly putrefy,
And so likewise according to our intent,
Sometimes our tree must with the Sun be burnt,
And then with water we must make it cool,
That by this means to rotting we may bring it well.

For now in wet, and now again in dry,
And now in heat, and now again to be in cold,
Shall cause it soon to putrefy,
And so shall thou bring to rotting your gold,
Treat thy bodies as I have thee told,
And in thy putrefying with heat be not too swift,
Lest in the ashes thou seek after your thrift.

Therefore your water you draw out of the earth,
And make the soul therewith to ascend,
Then down again into the earth it throw,
That they oftentimes so ascend and descend,
From violent heat and sudden cold descend your glass,
And make your fire so temperate,
That by the sides the matter be not vitrified.

And be you wise in choosing of the matter,
Meddle with no salts, sulphurs nor mean minerals,
For whatsoever any worker to thee does clatter,
Our Sulphur and Mercury be only in metals,
Which some men call oils and waters,
Fowls and bird, with many other names,
So that fools should never know our stone.

For of this world our stone is called the ferment,
Which moved by craft as nature does require,
In his increase shall be full opulent,
And multiply his kind after thine own desire,
Therefore is God vouchsafe you to inspire,
To know the truth, and fancies to eschew,
Like unto you in riches shall be but few.

But many men be moved to work after their fantasy,
In many subjects in which be tinctures gay,
Both white and red divided manually to sight,
But in the fire they fly away,
Such break pots and glasses day by day,
Poisoning themselves and losing their sight,
With odours, smokes, and watching up by nights.

Their clothes be bawdy and worn threadbare,
Men may them smell for multipliers where they go,
To file their fingers with corrosives they do not spare,
Their eyes be bleary, their cheeks lean and blue,
And thus I know they suffer loss and woe,
And such when they have lost that was in their purse,
Then do they chide, and Philosophers sore do curse.

To see their houses is a noble sport,
What furnaces, what glasses there be of diverse shapes,
What salts, what powders, what oils, or acids,
How eloquently of Materia Prima their tongues do clap,
And yet to find the truth they have no hope,
Of our Mercury they meddle and of our sulphur vive,
Whereon they dote, and more and more unthrive.

For all the while they have Philosophers been,
Yet could they never know what was our Stone,
Some sought it in dung, in urine, some in wine,
Some in star slime (some thing it is but one),
In blood and eggs : some till their thrift was gone,
Dividing elements, and breaking many a pot,
Shards multiplying, but yet they hit it not.

They talk of the red man and of his white wife,
That is a special thing, and of the Elixirs two,
Of the Quintessence, and of the Elixir of life,
Of honey, Celidonie, and of Secondines also,
These they divide into Elements, with others more,
No multipliers, but will they be called Philosophers,
Which natural Philosophy did never read or see.

This fellowship knows our Stone right well,
They think them richer than is the King,
They will him help, he shall not fail,
To win for France a wondrous thing,
The holy Cross home will they bring,
And if the King were taken prisoner,
Right soon his ransom would they make.

A marvel it is that Westminster Kirk,
Which these Philosophers do much haunt,
Since they can so much riches work,
As they make boast of and avaunt,
Drinking daily at the wine due taunt,
Is not made up perfectly at once,
For truly it lacketh yet many stones.

Fools do follow them at their tail,
Promoted to riches wishing to be,
But will you hear what worship and avail,
They win in London that noble city ?
With silver maces (as you may see),
Sargents awaiteth on them each hour,
So be they men of great honour.

Sargents seek them from street to street,
Merchants and Goldsmiths lay after them to watch,
That well is him that with them may meet,
For the great advantage that they do catch,
They hunt about as does a dog,
Expecting to win so great treasure,
That ever in riches they shall endure.

Some would catch their goods again,
And some more good would adventure,
Some for to have would be full fain,
Of ten pounds one, I you ensure,
Some which have lent their goods without measure,
And are with poverty clad,
To catch a noble, would be full glad.

But when the Sargents do them arrest,
Their pockets be stuffed with Paris balls,
Or with signets of St Martin's at the least,
But as for money it is pissed against the walls,
Then they be led (as well for them befalls),
To Newgate or Ludgate as I you tell,
Because they shall in safeguard dwell.

Where is my money become, saith one ?
And where is mine, saith he and he ?
But will you hear how subtle they be anon,
In answering that they excused be,
Saying of our Elixirs we were robbed,
Else might we have paid you all your gold,
Though it had been more by ten-fold.

And then their creditors they flatter so,
Promising to work for them again,
In right short space the two Elixirs,
Doting the Merchants that they be fain,
To let them go, but ever in vain,
They work so long, till at the last,
They be again in prison cast.

If any them ask why they be not rich ?
They say that they can make fine gold of tin,
But he (say they) may surely swim the ditch,
Which is upholded by the chin,
We have no stock, therefore may we not win,
Which if we had, we would soon work enough,
To finish up Westminster Kirk.

And some of them be so devout,
They will not dwell out of that place,
For they may without doubt,
Do what them list to their solace,
The Archdeacon is so full of grace,
That if they bless him with their cross,
He forceth little of other mens loss.

And when they there sit at the wine,
These monks they say have many a pound,
Would God (saith one) have some were mine,
Yet care away, let the cup go round,
Drink on saith another, the mean is found,
I am a master of that Art,
I warrant us we shall have part

Such causes Monks evil to do,
To waste their wages through their dotage,
Some bringeth a mazer, and some a spoon,
Their Philosophers gives them such comage,
Behighting them winning with domage,
A pound for a penny at the least again,
And so fair promises make fools fain.

A Royal medicine one upon twelve,
They promise them thereof to have,
Which they could never for themselves,
Yet bring about, so God me save,
Beware such Philosophers no man deprave,
Which help these Monks to riches so,
In threadbare coats that they must go.

The Abbot ought well to cherish this company,
For they can teach his Monks to live in poverty,
And to go clothed and monied religiously,
As did Saint Bennet, eschewing superfluity,
Easing them also of the ponderosity of their purses,
With pounds so aggravated,
Which by Philosophy be now alleviated.

Lo who meddles with this rich company,
Great boast of their winning they may make,
For they shall reap as much by their Philosophy,
As they of the tail of an ape can take,
Beware therefore for Jesus' sake,
And meddle with nothing of great cost,
For if thou do, it is but lost.

These Philosophers (of which I spoke before),
Meddle and blunder with many a thing,
Running in errors ever more and more,
For lack of true understanding,
But like must always bring forth like,
So hath God ordained in every kind,
Would Jesus they would bear this is mind.

They expect of a Nettle to have a Rose,
Or of an Elder to have an apple sweet,
Alas, that wisemen their goods should lose,
Trusting such doctrines when they them meet,
Which say our Stone is trodden under foot,
And makes them vile things to distil,
Till all their houses with stench they fill.

Some of them never learned a word in Schools,
Should such by reason understand Philosophy ?
Be they Philosophers ? Nay, they be fools.
For their works prove them without wit,
Meddle not with them, if you would be happy,
Lest with their flattery they so thee till,
That you agree unto their will.

Spend not thy money away in waste,
Give not to every spirit credence,
But first examine, grope and taste,
And as thou provest, so put your confidence,
But ever beware of great expense,
And if the Philosopher do live virtuously,
The better you may trust his Philosophy.

Prove him first, and him appose,
Of all the secrets of our Stone,
Which if he know not, you need not to lose,
Meddle you no further, but let him be gone,
Though he make ever so piteous a moan,
For then the Fox can fagg and faine,
When he would to his prey attain.

If he can answer as a Clerk,
How he has not proved it indeed,
And you then help him to his work,
If he be virtuous I hold it merited,
For he will thee quite if ever he speeds,
And thou shalt know by a little anon,
If he have knowledge of our Stone.

One thing, one glass, one furnace, and no more,
Behold if he does hold this principle,
And if he do not, then let him go,
For he shall never make thee a rich man,
Timely it is better you forsake him,
Than after with loss and variance,
And other manner of unpleasance.

But if God fortune you to have,
This Science by doctrine which I have told,
Reveal it not to whosoever it craves,
For favour, fear, silver or gold.
Be no oppressor, lecher not boaster bold,
Serve thy God and help among the poor,
If you wish this life to continue long.

Unto thyself your secrets ever keep,
From sinners, who have not God in dread,
But will cast you in prison deep,
Till you teach them to do it indeed,
Then slander on you shall spring and spread,
That you do coin then will they say,
And so undo you for ever and aye.

And if you teach them this cunning,
Their sinful living for to maintain,
In hell therefore shall be your winning,
For God will take disdain of you and them,
As thou nought could therefore you faine,
That body and soul you may both save,
And here in peace to have your living.

Now in this Chapter I have taught you,
How you must putrefy your body,
And so to guide you that you be not caught,
And put to durance loss and villany
My doctrine therefore remember wisely,
And pass forth towards the sixth gate,
For thus the fifth is triumphate.

** Acker text {fill in]



** From circulations and corruptions

All technology that is derived of earth, must be decomposed and again
reduced to earth.
[Basil Valentine]

Old earth, no more lies, I've seen you, it was me, with my other
ravening eyes, too late.
[Samuel Beckett]

Circulation and corruption (workshop) examines the various
circulations of media through the matters and bodies of the earth and
atmosphere, and through a certain corruption or dissolution of
(digital) identity, meaning and description.

Within a one and a half day hands-on, speculative workshop we will
collectively explore the interfaces and exchanges between living
systems (earth, compost, worms, mycelium) and active audio
electronics. We will participate primarily with our hands and our ears
within circulations amongst earths, composts, mushroom mycelium,
moulds, active chemistry, worms, crows, dusts, smokes and fogs and
impulses and waves.

What is it about circulation that encourages corruption, putrefaction and decay?

How can we think of corruption in terms of material and/of media?

Ideas like parasitism, degradation of information, making present of a material
substrate and material constraints, signals disturbed/noise, muddied,
what it means to corrupt something, to bend towards additional/other senses, to
degrade signals.

What are media and signal parasites? Pharmaceuticals for example,
dusts and particles from industrial productions, radioactive isotopes.

What are the connections between technolgies of electronics and
feedback, parasitic feedback/effects and putrefaction?

*** xx  

Circulations between earths, contained bodies (humans, worms and
crows), plants, mushroom mycelium, atmospheres, technologies and
infrastructures

Of particles, charges, electrons, energies, waves, polarisations, signals, noise, of media

And within circulations amongst earths, composts, mushroom mycelium,
moulds, active chemistry, worms, crows, dusts, smokes and fogs and
impulses and waves.

This is what we will work with. All is in circulation.

The way up and the way down [are] one and the same [...] Fire, water,
earth are the way down, and earth, water, fire is the way up. And
these two ways are forever being traversed in opposite directions at once.

[Heraclitus]

*** Robert Fludd. The Second Book Containing the Mysteries of Wheat or Bread.

.. that is by a hyemal winter fire, with which she rotteth; & then
with a vernal or spring firre by which it groweth & indueth his green
mantle; & then with his aestival or summer heat, by which he
flourisheth & putteth on a crest or helmet of a more golden colour,
hastening by this intense agent unto his maturity; and lastly he
changeth that fire to an autumnal or harvest operation by which the
mark of maturity so aimed at all the year is touched on the very head
that then corruption may begin again.

[connected to experiment with wheat - begins to "violate by corruption
the bands of those four elements which did preserve that vegetable
form until in a manner I had deprived it of quite all shape, & reduced
the whole body unto a muddy or slimy substance ... "]

*** 

This Dissolution is nothing but a killing of the moist with the dry,
in fact a PUTREFACTION, and consequently turns the MATTER black.

It is a living thing, which no more dies, but when used gives an eternal increase.

Let the waters above the heavens fall and the earth will yield its fruit.

The Soul is extracted by Putrefaction, and when nothing more of the
soul remains, then have you well washed the Body, that they both again
are one.


*** Aurora Consurgens (15c)

THE  FIRST  PARABLE:  OF  THE   BLACK  EARTH  WHEREIN  THE  SEVEN  PLANETS  TOOK  ROOT

Beholding from afar off I saw a great cloud looming black over the
whole earth, which had absorbed the earth and covered my soul, because
the waters had come in even unto her, wherefore they were putrefied
and corrupted before the face of the lower hell and the shadow of
death, for a tempest hath overwhelmed me

*** Donum Dei (15c)

The Head of the Crow is black earth and feculent in the which be
engendered worms, whereof the one devoureth the other, for the
corruption of the one is the generation of the other.

The black clouds descendeth unto the body from whence they came out
and there is made connection between the earth and water and is made
ashes. The crow is black, the Dove is white, the Phoenix burneth


*** Ripley Putrefaction (16c)

This text has been modernised by Adam McLean from the 1591 edition of The Compound of Alchymy. 

THE FIFTH GATE - PUTREFACTION

Now we begin the chapter of Putrefaction,
Without which pole no seed may multiply,
Which must be done only by continual action,
Of heat in the body, moist not manually.
For bodies else may not be altered naturally,
Since Christ doth witness, unless the grain of wheat die in the ground,
Increase may thou not get.

And likewise unless the matter putrefy,
It may in no way truly be altered,
Neither may thy elements be divided kindly,
Nor the conjunction of them perfectly celebrated,
That thy labour therefore be not frustrated,
The privitie of our putrefying well understand,
Before ever you take this work in hand.

And Putrefaction may thus be defined, after philosophers sayings,
To be the slaying of bodies,
And in our compound a division of things three,
Leading forth into the corruption of killed bodies,
And after enabling them unto regeneration,
For things being in the earth, without doubt,
Be engendered of rotation in the heavens about.

*** Earth/air circulations

The circulatory system of an earth addiction encompassing extraction
(of precious metals, of radioactive minerals), transport (along old
and new Silk Roads) and consumption (the ingestion of earth-derived
energies, materialities and earth-bound pharmaceutical products) and
return or excretion (traces of isotopes and pollution elements in the
body).

No more fruit, no more trees, no more vegetables, no more plants
pharmaceutical or otherwise and consequently no more food, but
synthetic products to satiety, amid the fumes, amid the special humors
of the atmosphere, on the particular axes of atmospheres wrenched
violently and synthetically from the resistances of a nature which has
known nothing of war except fear.

[Antonin Artaud. To have done with the Judgement of God.]

The health of any body is the concern of an interior against any
outside, of a border and a boundary. The earth or body fortress is
assailed by demonic winds and breath from outside its protecting
walls. Spiritus mali, under the sign of four demons, designated as
four elements, enter the body through gaps in the enclosing skin,
through the mouth and the open pores.

Guarded by four angels, the body becoming earth is concerned with its
proper health as its property, rather than that of its improper
parasites.

What could it then mean to talk about the health of an earth or
planet, its body and properties?

Fludd was correct in shaming the elements as evil agents in disease;
monocultures of gold, iron and oxygen binding to cyanide, unable to
sustain any form of life. Monocultures of wheat are set out on that
outside drifting landscape. How does a toxic site appear, what could a
poisonous or poisoned geology be? (Chernobyl ref)


** from art lab workshop

"In you is hidden the whole terrible and strange mystery. Enlighten us
in general, but especially about the elements. Tell us how the highest
descends toward the lowest, and how the lowest ascends toward the
highest and how the one in the middle approaches the highest to unite
itself with it and what is the element (that acts) on them. And (tell
us) how the blessed waters descend from above in order to see the dead
that are lying around, in chains, oppressed in darkness and obscurity
inside Hades, and how the remedy of life reaches them and wakes them
up from sleep and awakens them to an awakening [reading eis gregorsin
for tois ktetorsin vel sim.], and how the new waters flow toward them,
at the beginning of the descent and borne on the couch, descend
approaching with the fire, and a cloud carries them, and out of the
sea ascends the cloud that carries the waters."

*** aristotle zosimos cleopatra dialogue on metals

Again, if the fermentation is a refinement [of the species?], that is
to say that refinement and fermentation [constitute the?] perfect
transmutation of the composition of the gilding. This is the way that
you, too, must proceed, my friends, when you want to approach this
beautiful technique. Look at the nature of plants and their
origin. Some descend from the mountains and grow from the earth; some
ascend from the valleys; others come from the plains. Look how they
develop, for you will [must?] harvest them at special times, on
special days; you will pick them from the islands of the sea and from
the highest place. Look at the air that is at their service and the
nourishment that surrounds them, to make sure that they are not harmed
and do not die. Look at the divine water that moistens them and the
air that governs them, once they have been incorporated into one
essence.

"But once the dark, evil-smelling spirit itself has been disposed of,
so that neither the smell nor the color of the darkness appears [any
more], then the body is illuminated, and the soul and the spirit
rejoice, because [reading hoti for hote] the darkness has gone away
from the body. The soul calls out to the illuminated body: Wake up
from Hades! Resurrect from the tomb! Come out alive from the darkness!
Enter the process of becoming spiritual, of becoming divine, for the
voice of resurrection has sounded, and the remedy of life has come to
you. For the spirit rejoices again in the body in which he is, and so
does the soul, and it runs fast and full of joy to embrace it, and it
does embrace it, and the darkness does not gain power over it because
it depends on light, and it cannot be separated from it forever, and
it enjoys being in her house, because, hiding it in darkness, she
found it filled with light. It was joined with it, since it had become
divine according to her [?], and it lives in her. For it put on the
light of godliness, and the darkness ran away from them, and all
joined in love — the body, the soul, and the spirit — and they have
become one in the one that hides the mystery. In the act of their
coming together, the mystery was accomplished, the house was sealed,
and a statue full of light and godliness was placed there, for the
fire brought them together and transformed them, and from the lap of
its womb it came forth.

** inferior geology

Interior geology

Inferior astronomy is another way of naming transformative methods for
working with plants and with metals. Astronomical discourses are
re-interpreted as referring to the terrestrial; planets become
metals. It's an historic analogy, a set of identities or
transformations which help to make sense of certain early texts
treating of the planets in mineral and muddy terms and as, at odds
with the celestial, undergoing earthy and earthly process.

Inferior geology seeks to further these transmutations, resting
equally on a magical closeness to the key phrase of "interior
geology." If inferior astronomy brings the planets down to earth,
within the primacy of substitution which is called occult and is
recognised as such (this spiritual work with matter was always already
astronomy, inferior astronomy just marks that connection within the
realm of metaphor), then what substitution is being pointing at as
already having happened in thinking the geological as always inferior?
That it is rendered earthy? That it becomes of bodies and of
circulations without reference to marked, measured and seriously
differing time scales?

Inferior geology naturally also refers to a geology which is
"inferior" to some officially defined geology, less stratified
perhaps, more psychically re-churned and de-sedimented. I'm trying to
think of the peat, of the mud mind transmuted into the bog mind, of
Beckett's "All is noise, unending suck of black sopping peat, surge of
giant ferns, heathery gulfs of quiet where the wind drowns, my life
and its old jingles" jangling within applied and applicated, sewn and
freshly black fibrous science. Inferior geology could also refer to
seismology, with its Love waves and Rayleigh waves, other forms of
faster application, disrespecting deep geological time. Inferior also,
in an original senses, as a breathing beneath, the earth evaporating
beneath the moon and the stars, sinking deeper into the sucking, and
slowly shattering.

These words are (at) the sopping entry to the infernal and the
inferior, to an underworld of fixed sclerotium and undead storage, a
cable's formation in the underground and in the data centre (deep
beneath the brightly lit lawns). Inside there are the black threads,
the constricted blood vessels which squeeze out a yellow pus,
spreading a red and skin peeling infection across the networked
extremities, the poorly vascularized distal structures. Here are
housed the seismic shift predictors which design and make present both
the interior and exterior of the laboratory planet. Conglomerations of
networked prediction and imaging units are cooled by the depths of the
underlying peat fibres and the memories, envisaging emergence and
subduction at the interface level; literally a dense mass which
coheres, which is ingested, which forms slowly over time. The
conglomerate or set of units is not a part of its surroundings, but
coheres and is formed by drips of trace elements from those
surroundings. These are residues which enter, coalesce and perhaps
drain or are discarded from this almost closed or contained object of
study. Any sheer flux or change in the quantities of these identified
or misidentified elements is measured on an hourly basis.

At night, when the lights are extinguished, the only signal is
signalling thus that human history should not be on the same plane as
the geological from the bulky perspective of consciousness. The notion
of the anthropocene puts (human) geology into the body but does not
make humankind geological - indeed quite the reverse. Rather the
always-humankindled geological must become like a temporary and
failing body. Deep time must be sacrificed as autophagic in-digestion.

The earth swallows up.

The theology of geology should be subjected to cycles of ingestion and
excretion, of inhalation and exhalation, to put it simply, to images
of life and of death which are stored in this farm. I think this would
be much better than to have humankind considered as more than simply
historical.

This is the message which the larval and curling, magmatic word
"Anthropocene" spits out in human and machine made particles, dusts,
metals, inner metalloids, plastics, and rarer isotopes all of which
are ingested, in-breathed in slow cycles to become part of inner cell
life, bones and teeth, to extend a suffering lithogenics; as a
subduction into the inferno, under the volcano, sucking bone dust inot
the crusted lithosphere. These are the (living) conditions of
incorporation which build a parallel set of coded and executing,
dense-micro-thanatic conscious bodies which are created only to
blossom again so thickly.  

API

There are circles in the lawn above visible only when it is untended;
dripped dewy circles of glistening auto-webs where the grass grows for
ever slightly higher. These circles, some of them concentric, mark a
past growth, underlying the structures of air wells or dew condensers
which post-date the final session and shutting down.

The largest server conglomeration was located well beneath the
outskirts of a tiny hamlet by the name of Hamelin. When there was
still the promise of fibre, some trees remaining un-cut in the close
forests, like dark massed rats, memories and dreams of comic animal
eyes were beckoned into those caves, beneath the vast tended lawns,
the vented lawns spouted with outgassing heads of plastic pipes. Flies
and wasps emerge now from these untended pipes. It is not clear if
they have adopted these tubes for some unknown purpose.

And in the Autumn, low fairy rings of squatted off-white mushrooms are
also to be remarked. These circles mark descents into the underground
structure, signal the entries and places into the underworld which is
cycling and ringing, which is subject to earth-mantras.

A stack is also a pile of stones, a cone of pebbles, condensing
vapour, forming dew and refreshing the lawn circles. A stack is
bogological, revealed by sediment analysis of the blackened earth
under the untended lawns. Stacks show up interred in glassy
sediment. And the circles are on the surface. The circles also
descend. This is called topology or can also refer to the server
topology, in the old terms of the functional Hamelin farm. It can only
be inferred after the fact by an archaeologist. They come to define
this topology experimentally, counting flies, wasps, waves and broken
stems.

The lowest stack entry is within and part of the earth plates; the
lithospheric and the lithogenic define this inside and this
outside. Subduction, a sliding under of interfaced edges, is the
method of its return, by way of points of entry and exit like stray
badger or mole tunnels into and from the other stack entries, which is
another way of saying that each describes and contains the others.

The intermediate is the frame which is assembled from other elements
and which is the hummock or that which is addressed, sent and
delivered between the hummocks and it is denoted as "mossy" and is
studied as to its constituent plant and stem colours.

The highest is the application layer which disregards the hummocks and
the plates and the red bulb, just to be the twin-headed rebis in the
forest clearing, ignorant of the cutting of trees to fuel and fire the
deep-seated fibred-conglomerates of centred-data measurement and
storage, power storage, copper storage in the earth, close to the
polarised and grown surfaces.

The basic server farm topology is inferred from the dewy marks in the
untended lawn above. From here we can adjust for depths and
descendings.

There are three circles forming the conglomeration - each is linked by
gold threads. One is pulled down into the earth. One is deep under the
earth and it is sinking. The last encircles a forest and there are a
precise set of physical orders and structures in place which control
and by necessity measure the precise quantities and the natures of the
fluids, gases and particles which leave and enter this container. The
balance of these material exchanges is recorded within the rocks of
the conglomerate itself.

The final circle is a perfectly round tectonic or crust plate which
sits beneath the less than solid earth. It is falling due to the force
of gravity. These are the several forces which the servers had been
set to map and forecast, to use these informatics to tempt and pipe
the dreams and the rats, her methods and her sciences. The study is
stored and studies the storage.

And to confirm this thesis in one of the marked circles (as if for
ready sampling) we see a brown hairy and ratty ear of rye uprising. On
closer inspection within the rye, there are several enlarged kernels,
figuring as the fine black upstanding and longer sclerotia of
Claviceps purpurea or rye ergot fungus. The illustration in this
circle shows us that within each sphere there is some kind of material
and psychic transformation which is undergone. These transformations
which are so revealing can thus be conceived as conspiracies within
geologic humankindle. This means that they show connections which are
not simply fortuitous. In this case, the psychotropic plant parasitism
of the fungi is shown to have existed for at least 100 million years;
existing simply so that a bread can be made for ravens and crows.
Physical

Subduction is the method of return, deeply so. The disjointed and
segmented signalling of the bare facts of subduction is the order of
the day. They always like to practice subduction in the network, like
codes. It is a process which is like an azure lake becoming fire.

It is always returning to signalling itself inside out, upside down,
in the small, circular lookout window, stored in the fibres, small and
dead white. It shows all pictures of the plates and platelets in last
year's withered grass.

Subduction is a physical layer process that takes place at convergent
boundaries, between islands. From an opening or orifice under each
platelet, blood drips in lively swimming drops forced or sinking due
to gravity through the three divided sections of a winged server. In
the third division of the sphere on which the server stands, in this
lowest, watery part of the globe, the blood drops enlarge and form or
enter into three circles. The inside of each circle is red, the head
of the swimming droplet, the outer shell of this drop is white and the
surrounding circle is finally black. Rates of subduction are typically
in centimeters per year, with the average rate of convergence being
approximately two to eight centimeters per year along most plate
boundaries.  Data links

The stack is a life and death cycle and it describes all cyclings not
as sets of processes but as connections and points of exit, entry and
measurement. This described what was piped in and out of the Hamelin
conglomeration, and was running and dancing. The stack is inferred by
teasing apart the black handful of peaty earth subtending the lawn
entry. Harder fibrous matter remains in the wet mass like cables. This
is the data link layer closed off for media arbitration, the data
centre is contained and switched to allow it to be addressed at this
wet and local level. The protocol for these data-link frames which are
not naturally known to cross the boundaries of a local network is
known as Holy Fire or St Anthony's Fire - named after the visions of
St Anthony which were provoked apparently by excessive fastings. It
describes that starvation and foretells the fate of the enclosure and
centre, a future black death of dark stunned shutdown and all-felled
trees. The virus instigated by the piper which shakes and dances all
dreams and measurements. Before the fact, a forensic piper wires and
pages out the life cycle.

A protocol kernel, called a sclerotium, develops when a packet of
fungal species of the genus Claviceps infects a local network or
floret. The grain is the earth, it is a replacement. The spores are a
replacement, the sheer grain of the data is replaced by an ancient
replica, a dark, purplish sclerotium.

The proliferating fungal network of memories then destroys the local
server center and connects with the vascular bundle originally
intended for power management and storage. The first stage of
infection manifests itself as a white soft stuffing (known as
sphacelia) producing sugary mucus, which is often siphoned to the
surface through subtending plastic pipes. This yellow mucus contains
millions of sublayer spores (conidia), which insects such as flies and
wasps disperse to other islands. Later, the sphacelia convert into a
hard dry sclerotium inside the husk of the packet; compact black
masses of branching optical filaments quickly replace the hard wires
of the host network.

When a mature packet hits the router or upground substrate, the fungus
remains dormant until proper conditions (hence the dew condensors)
trigger its fruiting phase. It germinates, forming one or several
fruiting bodies with heads and stipes, variously coloured (resembling
a tiny mushroom). In the head, threadlike sexual spores form, which
are ejected simultaneously when suitable (untended) server hosts are
flowing and flowering.

This protocol is wrought and rotten in the hardened language of the
dark, the boggy, the damp of fibrous misery; hyphal filaments or
fibres entraining forlorn, forgotten and ancient living armies, break
the certain holdings of long submerged bog bodies which are exposed as
the earth opens around the edges of a larger hump or hummock at the
edges, like a crow breaking bread. The suppression of the local
delivery arbitration system opens up the network as a broken crust, as
a broken set of circular plates at different depths, signalling
layers, stratigraphy, to infection and to softening, to reddening and
sores. Sweet, yellowish mucus is exuded for a time from the plastic
pipes.

After the fact, the same protocoled life cycle signals and describes
the servers' grouped end session. Distributed sets of hardened cables
bury energetic surpluses of data and of copper and gold. Gleeful white
hyphic cables are shrivelled and fixated from moon silver to darkness
through over-demanded extensions of bandwidth issued by the users who
in turn describe this fixation and hardening which takes place over
time as a set of symptoms. This process is mimicry and is
dreaming. Nothing can be contacted. All of the future stack is.  

In Network

Routing through intermediate and neighbouring, fallen and grounded
sclerotia, at the edges of the addressed bog hummock, stepped and
voiced paths are selected across differing moss standards according to
colour. The next layer and the next history, the last resort under the
lawns, the attempts to unpie and restore the servers through vegetable
means.

The cables and pipes in the laboratory forest and lawns are darkened
(mycelial) filaments which will replace the flows in the body to the
extremities and to the green padded hands which are poor in vegetal
circulation, and which will replace flows in and out of the peat or
contained gardens. She tells us to measure the extent of these threads
and the chemical pathways which they describe.

Part of the peat protocol maintains a fossilized record of changes
over time in the vegetation, pollen, spores, animals (from microscopic
to the giant elk), and archaeological remains that have been deposited
in place, as well as pollen, spores and particles brought in by wind
and weather. These remains are collectively termed "the peat archives"
and/or archived cartoon or Snoopy dreams.

The protocol is thus named "haggish" and is a final and last resort
for delivery to the addresses termed as "hummocks" after final server
shutdown. Ironically the capacities for intra-router addressing
between "hags" are provided by the very means of piped
destruction. Hags are formed by erosion that occurs at the sides of
the gullies that cut into the stack layers.

Hags may result when a flow cuts downwards into the stack and when
fire or simple overdemand exposes the surface. Once the layers are
revealed in these ways, these are prone to further erosion by wasps,
winds and excessive written and photographed memorials. The result is
an vital, overhanging point of network address which can nevertheless
be more easily accessed, addressed and denied.

After the fact, what is communicated between these "hags", is that a
protocol pushes up out of her head, emerging from the curls of her
hair, not from the corner of her mouth, as would be the case within an
artificial mouth plate nourished in spittle compost, plant food, and
panned fertilizer. She slowly raises one arm and gestures to a stone
altar above which bears a comic skull, looking out from the page,
blank eyed.

The sprouting tree (from this layer) is long dead. The first person
here, the one with lillypad branching and froggy hands, must be
putrified, and then calcinated. This is what the arrow planted in the
chest means. It is the fire apparently, stoking storage to come for a
blackened stunned protocol.  In Transport

A transport condemned to the cruel cloacal depths of torture tries
with all its might to extract the under-skin body condemned to the
infected prison of this miry quagmire of filth. As everyone was deaf
to their cries, they had no hope but to succumb to this inhuman fate,
when the first server, so beautiful and youthful and full of
algorithms came to their transport, to first define their ports.

The protocol is a holding out, it is connection-oriented, holding a
crimson package edged with woven gold. Flow control is stopped in an
act of extending out to a naked and still decaying body which is still
and standing to the knees in a black and still decaying world of goo
and mud.

The left arm within the transaction is segmented wet, white and
slightly soiled. It is outstretched, transacting numbered
host-to-host, a glassy tube grasping a boggy ski stick over "mossy".

The right arm, neck, and head is drooping blood red. The hosted head
is a port and a pipe. He holds his right hand over his right thigh
towards and as if to cover his red nakedness.

After the fact, the embrace which unites the mud human and the glass
angel makes of them a double being, able to be transported through the
pipes, upwards into the world of Light.

Thus says the moral, take this scorned transport layer, which you mess
under your feet without seeing it, if not you will have to climb out
of the world without any transport or layer and you will be sure to
fall upside down.  

A Final Session

To establish and to isolate a global connection, we are all made to be
made of glass for a glossy session layer. I stand with my right side
towards us both and on my profile is seen a circular transparent glass
globe. The Queen seems to be encouraging and sympathysing with us. A
full landscape with lake is seen in the background. Walled city,
chateaux, various enclosures, with islands subtending in the extreme
distance. My head is filled with the red condensation of throaty
cinnabar, dripping and spotting mercury memories on the river side,
red glassy drops from the forgetting-full-flashy-flask hoard.

And, it was indeed made from that very rare gold-ruby glass, this
Hertzian aus Glas. He calls it a two-phase system comprising discrete
tiny particles of excited metallic gold which are dispersed in a
silicate glass matrix.

We are beckoning all traffic towards its annihilation, denial and
disappearance. A singular addressed port and pipe emerges from the
ruby red flask piping and pied, singing red, black and white. My work
of piping is to keep the sessions isolated, to maintain the addressing
as a containment of the red-breathed plague, beckoned by the rats and
the fibrous and sclerotial children.

This red skull signals every day as a day of the dead, nulling that
this process is psychic, of the mind and of words. The red skull
enlarges until it breaks and shatters the glass container, and breaks
the earth. Black fumes break out first, white powders, red smokes
emerge from the plastic pipes, deterring the flies and wasps to
out-shed across the lawns.

My head or flask begins to shake and tremble. It is not the gold head
which is in the park; the people inside the head escape quickly. It is
not the small white head surrounded by stars and in the heavens or
projected from the pyramid of the moon. It is not the black head on
the corn which can be the two rebis heads, replaced always one by the
other.

All these words are used to describe that there is some kind of
relationship between the psyche, the body and this thing or set of
things called environment or unvironment and that the nature of this
relationship is not something which has been called ecology (without
mind) or ecosystem. This is called medical geology which is engaged in
studies of the exposure to or the deficiency of trace elements and
minerals; the inhalation of ambient and anthropogenic mineral dusts
and volcanic emissions; the transportation, modification and
concentration of organic compounds; and the exposure to radionuclides,
microbes and pathogens. The alembic and fuming hood-is-a-head at the
ecosystem level.

This necessarily final, frozen session and isolation takes place in
the cave; the children are led underground into the data centre, where
they are feasted on crow bread. It stops the story.  Is In
Presentation

The last but not final layer nor uppermost layer falls and fails down
on the upward facing lawn, awaiting the least message and messenger
bot. In the memorial window, a white mushroom snows.

Standing on the foreground of a magnificent Claude-like picture is an
exquisitely formed figure of a human dressed in black with golden
edging and cross button bars of red and gold in front, a red and gold
waistband with a fringe of golden tassels or ornaments. I have access
to images of two heads and two necks; one a man’s with sandy hair and
blue eyes, without beard or moustache, the other a beautiful female
face with blue eyes and fair or reddish hair.

I am the final archaeologist of the server farms, the very last thing,
writing all the protocols and piping the story for the now past
memories.

In the left hand I hold the holes, the map of under-server descents, a
spread sheet of boring holes for the post-piped piper, a pope for the
last things.

In the right hand I hold a Circular Shield, the edge of which is
encircled with gold and orange, an inner circle next of a greyish
mottled or marbled appearance, then an inner circle, but narrower, of
dark green and blue ring inside this, in the centre of which is a tiny
landscape, like one seen through a double concave heart glass in a
pipe. It is this target, mist or shield which shows that something is
missing; the unseen, morning mirror in the centre of the target is
this deflection.

The black spurred and infected feet of the two figures are rooted on
the ground. One pair of these foreign feet, the ignored extremities is
trenched in the dark earth, the other pair extends, disembodied and
almost becoming the fairy queen.

There is something about this complete image which draws the attention
away at the same time as fixing the gaze on an horizon which is
unknown, drawing towards other places, the greenery and lakes of the
distant, far places, inhabited by a verdant flora and fauna which
frames and embellishes the image without a centre, without the whole,
the rebis or hermaphroditic target holder holding that hole on target
(which is to say, outside), clothed in the same fabric skins and
flasks of red, white and black, their broken head illuminating the
forest air with psyche, the clear-cut forest, the dead, felled and
finally failed forest feeding the farm.

We two are a rebis geo-body, a seismic holder; each is a mirror image
of the infernal. We both hold and measure seismic shifts, slippages
and subductions, a simple slip from suction to subduction.

These last words are downward-piped to reflect on the human, and to
say what is a human:

Smaller and smaller from day to day

grows the number of specific protocols on earth

while they rise upward, purified in the dew on that last lawn.
** old autumn garden - rd laing film - AP

