** Structure notes

*** First excursion, overview
*** Cosmologies of earth 
*** Cuts and exceptions - more serious
*** soil/spoils/rotting
*** fermentation/pickling
*** sand

- or should cut and exception be in sand?

*** conclusion

** New

Thermocultures of memory

Starolieski - 2017. the "stabilization of media in archives [and other
memory institutions] keeps them from degrading, becoming waste, [yet]
the shift to energy-intensive cooling mechanisms substitutes the waste
of media objects for the waste produced by fossil fuels."

parallel to heating

cooking substituting for digestion - the work of fossil and other fuels and the work of digestion

Beregow - Digestion requires huge amounts of energy; it takes hard work for the body to process raw foods. Cooking literally externalizes this energy ...

what would substitute for the waste of digestion  equation here?

cooling saves media, preserves memory, wastes fuel.

cooking saves digestion, preserves time/saves time, wastes fuel.

The optional air distribution system for hard and semi hard cheeses
may consist of an additional speed controllable fan to which PVC pipes
are connected. These pipes are equipped with discharge nozzles which
send the air vertically downwards into the passageways. A further
refinement to this system is the air distribution hoses attached to
the nozzles. These hoses are fitted with holes through which the air
is distributed over the cheeses at the level of each shelf.

http://jongiauk-cheesemaking.blogspot.com/2013/01/air-conditioning-for-cheese-ripening.html

** Introduction - first excursion

The HVAC itself consists of a series of interlinked material
apparatuses such as dampers, pre-filters, preheating coils, supply
fans, cooling coils, reheating coils, humidifiers, return fans, air
handling units and room sensors.  Thermocultures of memory p11.

As the temperature in the first floor gallery room, measured by an
array of shop-bought sensors which have been industrially manufactured
from doped semiconducting polycrystalline ceramic, decreases, the
sphincter or valve within the base of a semi-transparent plastic bucket
opens, releasing a fine dribble of gilded construction sand. Two
modded buckets engage in this generic venting action in the /grand
salle des quatre saisons/.

The temperature of the room is the measure of the average speed of the
moving tiny sand grains within. 

This event is engendered by twenty-two lithe, labouring and heavily
laden art students ascending the circular staircase [which letter to
alliterate - punctual, punctum, prim or ... ordure, order, door,
duration, gold, gilded ] leading into the gallery, sweating
heavily. They are generating heat which means energy moving across a
rough and rocky gradient (from the most to least favoured, to the
lower lands) between two containers as if at a junction which is
precisely where it will soon be measured. The first law of
thermodynamics states that the increase in internal energy within the
enclosed space is equal to the heat added minus the work done on the
surroundings.

Their presence within the wood panelled room sheltering Peter
Flemming's installation (Low places/Sour Bodies) thus raises the
temperature considerably, the students accounting for the equivalent
of a decently-sized electric radiator, an effect which is sensed and
registered by a thermostat (perhaps employing a similar crystalline
junction, a meeting of two disparate and heavily cut materials taking
good advantage of the asymmetric conduction of electric current
between a crystal and a metal, the cut between two things)

installed within the gallery, now signalling to the HVAC - Heating,
ventilation, and air conditioning (HVAC) - (to offset and increase the
... of the air conditioning system, venting heat to the outside
world. We notice a slight drop in temperature, a granular ice age, as
.... accompanied by the release of trailing earth traces of fine sand
from the ecological and always open obviously infrastructural plastic
ducked sphincter, an underground entrailing cable supplying energy for
the HVAC and entrained installation, perhaps from the Kraftwerk Reuter
West (3 million tons annual CO2) burning brightly brown coal, the
ashes gray, pulled from the low places or before swampy lands of the
El Cerrejón sub-basin in Columbia, formed millions of years ago from
sunken, decayed, damp forests, later in the day sucking peat archives,
and then weighted down under stone-charged winds year after year,
millions sand and hard stinking earth measured, lower and slower by
how many lives, these far writings in trees and golden entrails. Those
ancient trees are now returning direct benefits (not including
aesthetic, social, and natural).

"All life long you wait for that to mount up to a life." [Endgame 70]

Tree upon tree falling. Grain upon grain falling. The impossible heap.

drop in temperature of a little ice age: *hysteresis* also in the
installation

- little ice age linked to plague: Europe's "Little Ice Age" may have been triggered by the 14th Century Black Death plague, according to a new study.

[speculative binary mattress feedback loop - alternatively causing plague or the plague causing the
ice age]

https://www.jpl.nasa.gov/news/news.php?feature=5701

coal, beckett and descartes - Obscure locks p. 57 - the ashes gray
p.30 in Watt

coal fired computer 

coal and shit

** Cosmologies? of earth - cuts and exceptions

But precisely how were the low and high places formed and what
delights do they have in store for our sour bodies? Peter asks,
perhaps drawing on the deep foundations of geology by way of one
founder, James Hutton, asking us in turn "to consider [...] the globe
of this earth as a machine, constructed on chemical as well as
mechanical principles." [216?]

the world is exceptional and the exception is raised by the fact that
this world is simultaneously held as for us (fruitful and
provisioning) and not-for-us (ill-adapted to our sour bodies and thus
tortured to become commodious and in common)

it is made for us (Hutton) and not-for-us (machined) - the best of all
possible worlds - Leibniz Monadology - "That monadological or universe
bucket which contains more reality is better than that which contains less reality"

- this contradiction gives rise to technology and the uses of the earth

open and closed at the same time.

sand is signalling decay - quicksand, descent of sand, sand
clock, attrition, friction, heat, time trickle - as well as opposing
decay, the piling up of sand. every grain of sand that falls brings death a
little closer

Needham and coal bit

cosmologies and spontaneous generation

James Hutton = geology is a body, and this body is a bread body, a
dought body, porous, composite and microbial. geopolitics
necropolitics, microbiopolitics

the planet is a body or a machine, like a steam engine, a duck, a difference engine or a
mobile phone.

decay or running down

descartes - machine made of earth - where?  “I suppose the body to be
nothing but a statue or machine made of earth"  Treatise on Man
(1633),

all is earth

*bread, shit and sand as structurings*

The holy, interchange, and junctional trinity of bread (and its fermented companions, wine and cheese), shit
and now sand (a fine recipe for a sour day out at a lowly seaside spot).

these are all earths - the earth of microbes, spores and bacteria. the
eart of waste and composting shit, the geological earth of sand

bread, standing in for fermentation, the hallucinatory bread of dreams, of revolution

baking sand or earth becomes our bread

shit, the hot waste, lumps of steaming coal powering computation,
cryptocurrency, the cyclical, always thinking of its return, its is repetition

Shit as money is repetition and circulation, and all repetition is shit and circulates.


sand, the mineral, the geological, memory, Peter's imagination the low
places of woman of the dunes...

odd one out, the plain and pure sand, not studded with fermented salty blue
crystals of impurity - a physics of dirt

not so much as material, nor as cultures, but rather as process 

-> computation

described it as "like chewing a urine-infested mattress". 

mattress... 

hakarl icelandic shark buried in sand

*bitter years, sour years* 

** soil/shit/decay, 

All is shit, unending suck of coal-black sopping peat, surge of giant fans,
heathery gulfs of quiet where the ventilator drowns, my life and its old
jangles to the coprophilic jingle of Cheers and its theme song "Where
everybody takes a shit."

"... si l'ordure qui dore dans les champs fait or qui düre dans les allées citadines, L'odeur de l'ordure düre ou l'or dort.”

[If the shit that glows in the fields becomes the everlasting gold of
city streets, the stench of shit lingers where gold sleeps.]

[History of Shit. Dominique Laporte]


everything is earth, returned to the earth - fermented until becomes humus.

soil is this running down

If the process keeps going, the substrate will decompose entirely and
return to humus, the half-dead organic matter of the soil.
Beregow. p11

thirsty data bodies greedy for energetic resources and leaky buckets, leaky bodies and unsatiated data buckets

nervous system of resources

buckets of coal, buckets of shit, buckets of packets, of sand, of dosa mix

 did you e’er see a well with two buckets, whilst one comes up full to
 be emptied, another goes down empty to be filled? such is the state
 of all humanity. marston the malcontent

*2 buckets in beckett - obscure locks p. 78*

for the duck simulation - transparency and realism is tied to the
production of the most organic of matters

... this observer concluded that the grain input and excrement output
were entirely unrelated and that the tail end of the Duck must be
loaded befiore each act with fake excrement. [The Defecating Duck, or, the Ambiguous Origins of Artificial Life
Jessica Riskin Critical Inquiry Vol. 29, No. 4 (Summer 2003), pp. 599-633]

** bread/cheese/pickles 

... on this crust a mouldy film has produced living and knowing beings: this is empirical truth, the real, the world.

[Schopenhauer]

“Through three cheese trees three free fleas flew. While these fleas
flew, freezy breeze blew. Freezy breeze made these three trees
freeze. Freezy trees made these trees' cheese freeze. That's what made
these three free fleas sneeze.”

[Dr. Seuss]

[like a pizza - "a mouldy film topping a hard crust topping a hot core"

Schopenhauer and the Aesthetic Standpoint: Philosophy as a Practice of the ...
By Sophia Vasalou]

The main structure of the blue cheese comes from the aggregation of
the casein. In milk, casein does not aggregate because of the outer
layer of the particle, called the “hairy layer.” The hairy layer
consists of κ-casein, which are strings of polypeptides that extend
outward from the center of the casein micelle.[20] The entanglement of
the hairy layer between casein micelles *decreases the entropy* of the
system because it constrains the micelles, preventing them from
spreading out. Curds form, however, due to the function that the
enzyme, rennet, plays in removing the hairy layer in the casein
micelle. Rennet is an enzyme that cleaves the κ-casein off the casein
micelle, thus removing the strain that occurs when the hairy layer
entangles. The casein micelles are then able to aggregate together
when they collide with each other, forming the curds that can then be
made into blue cheese. Wikipedia blue cheese]

** sand/crystals/technology*

The "leaky bucket" algorithm imagines a packet flow as sand filling a
bucket and leaking out of it through a hole. .... Leaky buckets
regulate the intermittent flow of packets by varying queue size (how
big a bucket) and average bandwidth (the size of the hole). A queue
fills with packets arriving irregularly and holds them until they
might be sent at a regular rate. When a bucket overfills, sand spills
out, When the queue fills, daemons drop packets, signalling congestion.

[Internet Daemons. Fenwick McKelvey. p107/108]

I'm something quite different, a quite different thing, a wordless
thing in an empty place, a hard shut dry cold black place 
[Samuel Beckett, The Unnamable]

** conclusion

Voici un extrait du traité alchimique de Michael Maïer "Symbola aurae mensae" édité en 1617 où il est question de Morienus le Romain :

 "Morien le sage avait quitté
Le monde impur, ses vaines joies
Pour embrasser dans le désert
Tout le poids de la solitude.
Au roi Calid, qui l'appelait,
Il sut montrer l'art intégral,
Tout en protégeant sa lumière
D'un voile aux yeux des ignorants.
Prends cette chose méprisée
Que tu foules aux pieds sans le voir,
Sinon tu montes sans échelle,
Sûr de tomber à la renverse." 

Take this scorned thing, 
Which you trample into the low places,
If not you will climb without a transport
And be sure to fall upside down

** new junk

Hutton 1785: a soil is necessary to the growth of plants; and a soil is nothing but the materials collected from the destruction of the solid land.

But is this world to be considered thus merely as a machine, to last no
longer than its parts retain their present position, their proper forms
and qualities? Or may it not be also considered as an organized body?
such as has a constitution in which the necessary decay of the machine
is naturally repaired, in the exertion of those productive powers by
which it had been formed.

Hutton Theory of the Earth, Volume 1 (of 4)

Hutton/steam engine and Needham

the analogy he saw with a “machine” using force “either produced by
steam, or by extremely thin and dry air.” This model is interesting
because it ... History of Geology

"fermenting is rotting with style" - reddit

Peter delights in transforming often abstract social concepts into
mechanisms - for example party beer crate suspended by stretchy
bungees from the ceiling - easy to reach when the supply is plentiful,
weight 

how could we manifest notions such as "forced obscolescence" through
mechanics or through other lively systems - could a particular
packaged ferment overrun our smart-phone within a planned length of time.

Low Places/sour bodies opens up customary sets of choices between two
worldings, wordings (like think and sphinc-ter) or cosmologies which
are not necessarily exclusive (we can combine them in binary fashion
using a logical operators of AND, OR and EXCLUSIVE OR) and not
necessarily aligned across the two installations, solely belonging to
the low places OR the sour bodies. These choices, or cuts, are
distributed across both low places and sour bodies. Where do sour
bodies end and low places begin?

the exception and the cut; the vessel is the cut...

what is the exception? to raise an exception

sinking below - returning into, giving up energy, becoming coal or...

we internalize and em-body all these exceptions, all of these outdoor
microbes and bacteria become hard-working parts of these
body-machines - these exceptions are now en-ceptions, endo-ceptions

-cept, the taking in towards one self

the exception is no longer from the outside, blown by the winds of
ill-fate, but a part of us, of our bubble

*define an exception, what is an exception?* a paradox - 

exception handling is the process of responding to the occurrence of
exceptions – anomalous or exceptional conditions requiring special
processing - during the execution of a program.

exception or *trap* - trapped in a swamp

Exception handling is a ”can of worms” 

** TODO/notes

structure: exception and intro, recipes are spells, bread/shit/sand

- 1 A cosmology of exceptions
- 2 exceptions and The cut
- 3 Recipes, spells, formulae and remedies
- 4/5/6 bread/shit/sand

Life is an exception and, even for those living free range, is
experienced under a series of states of exception. This lively planet
is an un-homegenized anomaly in time and space, hoisting with the
universe towards a chilled, heat death, a decline in energy, the
dissipation or breathy running down of some kind of steamy engine constructed
on principles of energetic circulation and exchange. This cosmology is
an exceptional recipe which mires us in deep shit.

[**** Deep Shit. Nigel Clark Myra J. Hird

However, it’s worth dwelling on the fact that the mass of once living
organisms that have returned to base matter has been estimated at
somewhere between a 1,000 and 10,000 times the mass of the Earth
itself (see Davis 1996, 73), while as far as scientists have been able
to ascertain, matter has only organised itself into life but once on
our planet. There is, then, something of an asymmetry between the
transition from base matter to life and the traffic that passes in the
inverse direction. p45

Davis, M. 1996. ‘Cosmic Dancers on History's Stage? The Permanent Revolution in the
Earth Sciences.’ New Left Review 217: 48–84.]

Where there are such hills and dales, there the Earth has been matured
and *most perfectly mixed* with heat and cold, moisture and dryness, and
there the best ores may be found.

studded crystalline, blue cheese

But where the earth is *flat* there has been no accumulation of such
fumes and vapours, and there no ores will be found, while the uplifted
part of the soil, especially, such as has been slimy, loamy, and fat,
and has been saturated with a moisture from on high ; got soft again,
forming dough-like layers one on top of the other, which in the course
of time, under the influence of the Sun's heat, become more and more
firm, hard and baked ; and other ground as gravel and sand, brittle
and yet soft, hanging together like grapes, is too meagre and dry, and
has not received enough moisture, consequently it could not form
itself into layers, but remained full of holes, like badly prepared
pap, or like a mealy dough, which has not been watered enough ; for no
earth can become stone, unless it be rich and slimy and well mixed
with moisture. [splendor solis and other geo text]

 ///spontaneous generation and pasteur

needham - and geology? coal-fired mountain building heat theme

https://www.biodiversitylibrary.org/item/109054#page/13/mode/1up


Describe Needham's experiment.

He heated a sealed container of gravy, assuming that he killed off all
life. 

He looked inside to find out whether or not life was there.

In a series of experiments (date) which recall the closed vessels of Low
Bodies, Louis Pasteur put an end to both vitalist
notions of spontaneous generation of life, and ushered in techniques
and regimes to annihilate unwanted bacteria and microbes
(Pasteurisation), catching those *exceptions* before they sabotage and
parisite global food sources (grains as well as dairy products).

We no longer need to avoid placing our bookshelves to
the south or west; the ill winds hopefully will not bring roosting bookworms. [Vitruvius.]

[Flemming - When I woke up just after dawn on September 28, 1928, I
certainly didn't plan to revolutionize all medicine by discovering the
world's first antibiotic, or bacteria killer. But I suppose that was
exactly what I did.]

Technology is that other wilful exception that makes a cut ... and
allows us to say "this is a mountain, this is a steam engine, a lump
of cheddar." And to create these devices. To distinguish and to
instigate more cuts in the material world which are cuts as symbols
and as sabotage, sluggish, cold words, as language, as magic spells
which force a looking back (Dante - condemned soothsayers)

 “Ah earth you old extinguisher.”

"Ah earth you old exception."

Samuel Beckett, Happy Days 

Old earth, no more lies, I've seen you, it was me, with my other's
ravening eyes, too late. You'll be on me, it will be me, it will be
us, it was never us.

Cold earth, no more lies.

hardware exception - as steam engine in 19c cosmology - needham - to
computer cosmology - to that which can be simulated and shown - the game of
life is a contagion - 

exception is natural but is not the cut also nature? what do we mean
by this...

sandy mouth or a sour pickle

low places/sour bodies invokes a binary decision tree - either
or/earth or, the exception or the cut. The ... or the pickle - a
recipe deciding. Spontaneous generation or pasteurisation, life or
death.

pick your cosmology - lively spont gen of geo and... or pasteurised
sinking sand worlds, raising mountains prefiguring heat death, raising
spirited exceptions from the decaying or the dead, buckets kicked up.

https://en.wikipedia.org/wiki/Spontaneous_generation

In 1745, John Needham performed a series of experiments on boiled
broths. Believing that boiling would kill all living things, he showed
that when sealed right after boiling, the broths would cloud, allowing
the belief in spontaneous generation to persist. His studies were
rigorously scrutinized by his peers and many of them agreed.[39]

In 1837, Charles Cagniard de la Tour, a physicist, and Theodor
Schwann, one of the founders of cell theory, published their
independent discovery of yeast in alcoholic fermentation. They used
the microscope to examine foam left over from the process of brewing
beer. Where Leeuwenhoek described "small spheroid globules", they
observed yeast cells undergo cell division. Fermentation would not
occur when sterile air or pure oxygen was introduced if yeast were not
present. This suggested that airborne microorganisms, not spontaneous
generation, was responsible.[45]

Louis Pasteur's 1859 experiment is widely seen as having settled the
question of spontaneous generation.[47] He boiled a meat broth in a
swan neck flask. The bend in the neck of the flask prevented falling
particles from reaching the broth, while still allowing the free flow
of air. The flask remained free of growth for an extended period. When
the flask was turned so that particles could fall down the bends, the
broth quickly became clouded.[39] However, minority objections were
persistent and not always unreasonable, given that the experimental
difficulties were far more challenging than the popular accounts
suggest. The investigations of John Tyndall, a correspondent of
Pasteur and a great admirer of Pasteur's work, were decisive in
disproving spontaneous generation and dealing with lingering
issues. Still, even Tyndall encountered difficulties in dealing with
the effects of microbial spores, which were not well understood in his
day. Like Pasteur, he boiled his cultures to sterilize them, and some
types of bacterial spores can survive boiling. The autoclave, which
eventually came into universal application in medical practice and
microbiology to sterilise equipment, was not an instrument that had
come into use at the time of Tyndall's experiments, let alone those of
Pasteur.[3]

the land, which was like potters clay and entirely soft. But as the
sun’s fire shone upon the land, it first of all became firm, and then,
since its surface was in a ferment because of the warmth, portions of
the wet swelled up in masses in many places, and in these pustules
covered with delicate membranes made their appearance.  Such a
phenomenon can be seen even yet in swamps and marshy places whenever,
the ground having become cold, the air suddenly and without any
gradual change becomes intensely warm. And while the wet was being
impregnated with life by reason of the warmth in the manner described,
by night the living things forthwith received their nourishment from
the mist that feli from the envelop- ing air, and by day were made
solid by the intense heat; and finally, when the embryos had attained
their full development and the membranes had been thoroughly heated
and broken open, there was pro- duced every form of animal life. 1 Of
these, such as had partaken of the most warmth set off to the higher
regions, having become winged, and such as retained an earthy
consistency came to be numbered in the class of creeping things and of
the other land animals, while those whose composition partook the most
of the wet element gathered into the region congenial to them,
receiving the name of water animals. [https://archive.org/stream/DiodorosOfSicily034.598/Diodoros%20of%20Sicily%2001%20%281.1-2.34%29_djvu.txt]

- where we found the commonplace and low in alchemy, the common
  alchemist are exhorted to find the prima materia in these lowly
  and despised places, middens, waste dumps

AURORA C

... the waters have covered my face and the earth hath been polluted
and defiled in my works; for there was darkness over it , because I
stick fast in the mire of the deep and my substance is not disclosed.

II what wisdom is.

For there is a stone, which he that knoweth layeth it upon his eyes,
but he tht doth not, casteth it upon the dunghill...

p33 cast forth in the streets ??where

trodden into the mire by beasts of burden and by cattle

vile and dear and covered with filth

*Splendor Solis - references to cooking in the Harley manuscript - third treatise, first parable explaining geology - also like the cheese/silicon chip*

third treatise, first parable

Where there are such hills and dales, there the Earth has been matured
and most perfectly mixed with heat and cold, moisture and dryness, and
there the best ores may be found. 

studded crystalline, blue cheese

But where the earth is flat there has been no accumulation of such
fumes and vapours, and there no ores will be found, while the uplifted
part of the soil, especially, such as has been slimy, loamy, and fat,
and has been saturated with a moisture from on high ; got soft again,
forming dough-like layers one on top of the other, which in the course
of time, under the influence of the Sun's heat, become more and more
firm, hard and baked ; and other ground as gravel and sand, brittle
and yet soft, hanging together like grapes, is too meagre and dry, and
has not received enough moisture, consequently it could not form
itself into layers, but remained full of holes, like badly prepared
pap, or like a mealy dough, which has not been watered enough ; for no
earth can become stone, unless it be rich and slimy and well mixed
with moisture.

Fourth parable: Make the bodies spiritual through dissolution and then

Exceptions and allied states of exception set into process cuts in and across
dead and living bodies and matter, [initiating the bread field and the stack] -
tehcnology as a recursive boundary-producing set of devices and blind
ruses - a world of hedgerows and hard shoulders, of a composting pile
or smouldering heap of leaves at the edges of the *garden*

about the cut: the Baradian cut, before which everything is mixed as a
dough.

Starosielski p295 - Thermal techniques are operations that produce
"cuts" in this flux (Barad 2007), tease out different material
potentials, and shape "solid" media out of geological substances.

question is how  an exception within a physical (computing) system,
an ecosystem for example, how could that exception be *trapped* and
signalled

*try/catch block*

states of exception - Agamben, J.-A. Mbembé - necropolitics

smell of these books: IC op-amp cookbook, CMOS cookbook, TTL Cookbook, TV Typewriter cookbook - recipes for electronics, cooking

** OLD Introduction - States of Exception

The domain of plague and virus is, in its appearance, the realm of
disintegration, decay, and destruction, of an undoing (of that which
is, of the more established and antecedant, an undoing which must be
contained). And it is this "other" world of lively decay which Peter
Flemming [note Alexander Flemming - antibiotics and penicillin - maybe
come back to this] makes visible as a series of connections, an open
and closed circuit within the linked works, Sour Bodies and Low Places,

It is the less-than-obvious connection between the realms of material
and living, energetic transformation and the 

(human) technology, defined within embracing terms of command,
control, and communication [cybernetics, systems creation and
modelling, economy and the infrastructures and created mechanisms
which enable the feedback and construction of ...] which is made
evident within Flemmings's work, defining and defined by the point of
connection between those Sour Bodies and those Low Places

[that the
technological realm which Flemming opens up and lets spill out 

(the contents of that particular black box transformed as if by magic,
so that the familiar contained materiality of algorithmic
infrastructures (even if we did expose them, we are none-the-wiser to
the microscoped conduits of silicon and copper) becomes sand, plastic,
buckets and pipes),

of a system-which-has-been-set-up (manufactured, machined howsoever primitively) with all its mechanisms and
circuits and discordant materialities, is the low place, like a swamp,
a dumping ground, midden, a bog, whereas the place of a more cohered and
involving process of fermentation, perhaps equally controlled but with
a more casual hand in its setting-in-process, maybe even more
contained and enclosed, is the body, or bodies, the sour, *pissed-off*
body at odds with and conflicting with both themselves and their
perhaps self-controlled environment [and what might cause such a body
to be so contrary to a place which they apparently have so adapted to
themselves - ref. Wiener, bio-adapter].

"this is how I do it; not exactly scientific; and good to read the
thing through as a whole, *it is not exaclty [sic] a step-by-step*"


I will try, like the little virus I am, to expose this essential
connection within this abstract series of recipes which equally form a
kind of journal [In the summer, during Peter's residency, we exchanged
rough recipes for ginger beer starters, known as ginger *bugs*,
experimenting with the addition of turmeric and honey to the mix.] Just
as Low Places can be viewed as an algorithm made flesh (hesitantly,
silently and without words which might enlighten), a straightforward
recipe is a series of instructions which makes visible its own
construction (in words). ["the magic of ordinary things" -
Henricks]. These words become bread, become pickles (of course with
access to suitable and seasonal materials or "produce"). [bread of
dreams - camporesi]. These words become dreams, repeating and changing
procedures, become new recipes in a kind of version control. The Low
Places are these dreamy, moulding, recipes, embodied and seperated
from any written series of awkward steps. Peter feigns to show us the
recipe to construct a Flemming [reminding me of the instructions for
maintaining Peter's .... "the electrodes will be LIVE and you must not
touch them!", the whispering mismatch between a decayed reality,
someone has moved the ladder, rinsed out the briny, salt water either
served for pickling or for dimming, and these ideal recipes]


"If you can't get the salt ratio, maybe just pour in 4 or 5 Arduinos to each bottle?"

All the pieces are there, we consider that we might even be able to
purchase all of the materials off-the-shelf from the local hardware store (OBI,
Bauhaus, Hellweg). No specialized materials or scientific equipment is
required for the construction of your ecosystem; if only we know what
to ask for, sourly and deadpan, for ourselves. There is something
which escapes us, sand trickling out of a useless bucket, pooling on
the floor. It is not wholly transparent. [closed exhalation of the
rubbered jar] Some kind of wordless, biting incantation for exposure would be
require in times of need, a magic circle or circuit chalked on the
ground or up the wall as follows:

spells or invocations from papyrus PGM as forms of recipe: we are
informed about the materials required (although some of the names may
seem unfamiliar and ...) and how these are to be put to use

example...

magic invocation for sand/silicon

[below as the first recipe with barbeque intro]

What do unknowable processes variously described as decay, rotting,
putrefaction, decomposition, deterioration, fermentation (controlled
rotting), circulation, corruption, spoiling, composting, digestion,
degradation, moulting, infection [Lister called infection
fermentation], dissolution, souring, moulding, disintegration -
processes which connect with the abject, with ordure, excreta,
disjecta, with the discarded and the rejected, the declining, the
defiled and unwanted, the sorely addled and the descending, the leaked
and spilled, frothed and then de-frothed, skimming its scum, what do
these processes have to do with technology [footnote rotting sounds]
and how does Flemming'[s work enlighten or enliven or even upset the
rotting and *worm-ridden* apple-cart of this potential relationship?

More simply, what do a mobile phone and a pickle have in common?

one is cooked. one is fermented. both as a putting to work in terms of eneregy

The simple answer is that they are both embedded within
thermocultural systems of control occupied with the conservation and
preservation [we can also call pickles, conserves] of state and the
(economic) management of discrete levels of energy. Within
technological infrastructures there is a maintenance of state (storage
in the cloud should maintain our memories without glitch) which
implies an expenditure of energy (a bucket spilling out water or sand
drives a mini turbine which generates electricity to charge my phone,
a pickle-pecked piper lifts and re-fills the bucket every few days,
nipping into the back room for a 25kg bad of sand, thus drawing on his own
restricted reserves of energy in some schoolbook illustration)[coal fired
comp]. A sandy-k/need demon surfs downhill a temperature gradient of entropy
leading us back into the dammed and thus civilized low countries.

The memorial of a one or a zero on a grand scale [Thomas Pynchon lets
us choose between: “If
patterns of ones and zeroes were "like" patterns of human lives and
deaths, if everything about an individual could be represented in a
computer record by a long strings of ones and zeroes, then what kind
of creature could be represented by a long string of lives and
deaths?” - Vineland? She pictures to herself the mattress he sleeps
on, bearing the “vestiges of every nightmare sweat, helpless
overflowing bladder, viciously, tearfully consummated wet dream, like
the memory bank to a computer of the lost.” Crying lot 49 - also
tastes like a urine-infested mattress ] also releases heat as
excess, a sour and unwanted byproduct of these bits circulating as a
flow of electricity through less-than-pure metals. [Finn Brunton "the
work of computation is the work of managing heat. The history of
computing is also the history of air conditioning and temperature control".] If the heat stays
inside, if it isn't dissipated as the balloons flexibly take in the
build up of carbon dioxide by the sour bodies, we risk cooking the
phone. A recipe for a mobile phone, which we'll return to, would also
include these now-wishful impurities, as happy rogue atoms nestling
within non-conductive silicon and allowing for a highly selective
circulation.

The abyss is not filled to overflowing,
It is filled only to the rim. [IC]

Decay and preservation become questions of energetic exchanges and
circulations signalled by material changes. Water fills a pit only to
the rim, and then flows on [Jung;s intro to the I Ching which is also
a form of recipe - the K'an hexagram is here describing pits and
pitfalls]. On the windowsill, within a closed jam jar, water
evaporates in the summer's heat, and as the resulting vapour cools in
the evening, droplets condense on the sides of the jar. Alchemy
occupies itself with these processes of transformation become symbolic
as in an algorithm or a recipe. Perhaps this becoming is a one way
street, a downhill slope bringing to those swampy low places, to the
abyss. Not a zero though. Not im-pure.

peat bog?

sand? buried in sand to maintain a constant temperature, a sand bath,
a sand box

////

significance of these closed vessels, inhabited by some contained
process, impervious to other sour breaths or influences, allowing for
gassy expansions only and subsequent awaited and expected
contractions.  impermeable - rubber glove, balloon or condom.

an attention to detail within fermentation, observation of state (is
it bubbling yet, what happens when I open the jar or door, risking the
entry of unwanted agencies or wishful, dopey-eyed impurities,
maintaining a social distance which is all about exchange - as well
as a certain roughness, we do not need sterile conditions, we can make
vague measurements judging by eye or by hand, gauging temperature
without external apparatus, tasting and smelling as ways of becoming
acquainted and gauging the progress of invisible processes of inner
transformation, we can read the visible and tangible signs of
fermentation, cloudiness of the brine, changes in colour of a beetroot kimchi

- becoming familiar with the signallings of a certain complex of aromas, for example, of
fermenting, salted cabbage or of habanero peppers with crushed garlic
maturing in a salty brine

controlling temperature exchanges, managing gas exchanges, venting, air-locks

thermopolitics?

lactic acid fermentation - kimchi what is the process - and
putrefaction ?? enzymes produced

Semiconductor manufacturing works like a barbeque pit where hickory
smoke seeps into the meat and imparts a distinctive flavor. In the
diffusion process, a bar of silicon is cooked in a furnace at high
heat, and then a gas containing the appropriate doping impurities
... is pumped into the furnace ... In the same way that a barbeque
chef knows how long to cook the ribs to get the right taste of
hickory, solid-state physicists gradually determined the proper time
and temperature needed to put the precise amounts of impurities at
precise points on the silicon block.

[T.R. Reid quoted in Thermocultures of Geological Media. Nicole Starosielski]

Semiconductor manufacturing works like a blue cheese dairy where a
fungus such as Penicillium roqueforti are inoculated or injected
into sheep milk or milk curds and imparts a distinctive flavor. Just as in
the crystalline world of the diffusion process, ripening mould veins and
tyrosine or calcium crystals stud the cheese as it ferments. Once the cheese has
matured over several months, it is sterilized at ultra high
temperatures. This heat treatment also inactivates the Penicillium
roqueforti, inhibiting further fermentation. In the same manner,
solid-state physicists determine the proper time and temperature
needed to put the precise amounts of impurities at precise points on
the silicon block.

[the bacterium Brevibacterium linens is responsible for the smell of
many blue cheeses, as well as foot odour and other human body odors -
see peter notebook]

That the cheese maker could also become a barbeque chef, doping the
pure silicon of meat with hickory smoke, could equally be a
sacrificial priest if we take inspiration from the ancient practice of
alchemy - Zosimos - bodies are seperated, torn asunder, hewn like tree
trunks (Dante suicides) QUOTE zosimos - also the prima materia image
from Ripley scroll

And Putrefaction may thus be defined, after philosophers sayings,
To be the slaying of bodies,
And in our compound a division of things three,
Leading forth into the corruption of killed bodies,
And after enabling them unto regeneration,
For things being in the earth, without doubt,
Be engendered of rotation in the heavens about.
[ripley 12 gates putrefaction]


alchemist refer to the torture of metals - examples - with reference
to pasteurisation latour talks of the scientist as now being able to
"starve the microbes, kill them with antiseptics, make them eat
anything, in short, torture them in innumerable ways, in order to
learn something about them each time" (1988 the pasteurisation of france)


how can sacrifice emerge as a theme? though the sacrificial priest -
the sacrificed and the sacrificer - 

to be able to think in words or abstraction simultaneous with the
clear description of precise physical properties or processes,
Becket's peat thing

that all of these descriptions, analogies and connections are
fictions, not in a negative sense, they are myths - the cheesemaker,
the sacrificial priest, the pit barbeque chef, the chip manufacturer.

*** conclusions

obvious that technologies of computation, control and communication are always
subject to the noisy un-constraints of both materials (substrates) and
material-un-bound processes (thermodynamics), just as s/our bodies are
subject to disease, and disintegration, to good and bad microbes and moulds.

whilst relying on these materials - a reliance, a sub-orning (?), a
parasiting 

this world is us and is seemingly against us as decay

crossing nouns/material and processes - cheese, dunes, fermentation
and shit/shitting, sanding.

Peter Flemming - speculation of what a technology which acknowledges
its debts to the pleasures of approximate and un-studied cooking and
to fermentation, which attempts to willfully roll down into those low
places of thermodynamic gradient, of waste heat, to un-damm the flows
and circulations seperating various abysses with names such as
Anthropocene, computation, currency and exchange. sacrifice? burial of
the anthropocene

a darkly promiscuous set of technologies of sour-pissed-on/off bodies, of local,
overheating parasites (Serres ref), and perhaps finally of sand,
rather than silicon, dribbling and spilling over binary logic.

a bread of plagued and low dreams which is baked according to
technologies which are not for a human or a visible crow to
do-something-to-something-else with, to hide something or to transform
it, to transfer it, but technologies and techniques for the others,
precisely that imagination which mirrors all these of our endeavours
in another realm, of the decaying and of the dead.

woman of the dunes as postscript perhaps - a burial in sand, in the
lowest of places (lowest in alchemy, the most base)

*** Recipes:

**** Peter recipes

SAUERKRAUT
- salt
- water
- cabbage (or other vegetable matter)
Wait.
Eat.

GINGER BEER/GINGER BUG
- sugar
- water
- ginger (or turmeric, galangal etc)
Wait.
Stir.
Feed.
(repeat)
More water, more ginger.
Wait.
Drink.

DOSA
- any bean
- any grain
- water
Soak.
Wait a day.
Grind.
Wait a few hours, look for rise.
Eat.
(fenugreek for flavour)

BLUEBERRY WINE
- sugar
- water
- fruit mash
Wait.
Strain.
Drink.

These processes are heavily temperature and environment influenced, and involve feedback through visual observation and tasting to adjust (eg. add water, stir, skim etc.)

*** quotes

**** Cooked or Fermented? The Thermal Logic of Social Transformation
Elena Beregow

latest:

Lévi-Strauss compares these societies to a horologe, a clock-like
mechanism that measures time in order to maintain cyclic rhythms in
endless repetition, providing a steady regular movement that combats
disorder. By contrast, he compares hot societies to steam engines,
following a linear temporal logic.

p5

something like a horologe compared with a steam engine.

cooking replaces digestion in terms of energy - the energy comes from
outside us!

Digestion requires huge amounts of energy; it takes hard work for the
body to process raw foods. Cooking literally externalizes this energy;
it uses fire energy in order to save body energy. 
p6

This primal metabolic process breaks living things down, reducing them
so their energies and atoms can be reused.
p9

Rot management strategies involve temperature control, as fermentation
usually requires specific outside temperature ranges. Most of the
lactic acid bacteria are metaphilic, which means they can cope with
normal room temperatures of 18 to 22*C .. whereas others - for
instance many yogurt cultures - are thermophilic and need cozier
temperatures of 42 to 45*C.

///

Inspired by thermodynamics, Serres notes that the 'best definition' of
the parasite is that it functions as a 'thermal exciter': it affects
the energy distribution within a system by warming it up or cooling it
down, by producing thermal noise and disorder.
p9

*necrological vitalism* of fermentation - fermentation's cold fire
... -> *these could go with alchemical torture bit*

Fermentation presupposes the movement of living bacteria that
transform organic matter into acids, gas or alcohol ... This primal
metabolic process breaks living things down, reducing them so their
energies and atoms can be reused. 
p9

In fact, the life of these bacteria means decay, decomposoition, rot;
due to this paradoxical character of life processes that work on their
own dissolution, Eugene Thacker (2012: 26 After Life) speaks of
fermentation as a laboratory for a 'necrological vitalism'.

...

this uncanny figure of flourishing death via self-digestion
demonstrates the limits of the assumed logic of cyclic repetition.

p10

Limiting fermentation to the endless cycle of ubiquitous, flourishing
life and renewal - as vitalist accounts tend to do - means to overlook
that fermentation irritates and interrupts this very cyclical logic of
life by introducing the irreducible principles of death and *mortification*.
p17

Accentuating this dark line ... fermentation would not stand for the
recycling of the existing world (after the virus), but for its slow
inner destruction. Indeed, it is not only the Anthropocene or the
Pasteurian scientist who is controlling and torturing microbes;
fermenting means that the involved bacteria eagerly begin their decay
work by killing other 'bad' microorganisms in a necrological
zombie-like movement between self-preservation and
self-elimination. Fermentation always has this uncanny, almost bleak
dimension to it: it is only the thin semi-permeable membrane of the
gastro-intestinal tract that prevents us from digesting ourselves.
p17

**** Thermocultures of Geological Media

Nicole Starosielski

... thermal technologies underpin the standardization of culture,
decreasing the distinctiveness of otherwise heterogenous meidia
objects and facilitating their circulation as global commodities. This
is visible in media production, as well as in the use of heating and
cooling to stabilize media over time, a key defense in the foght
against decay.
p294

The drive toward purity that structures the thermal production of
digital hardware is neither necessary nor neutral. It is designed
specifically to reduce error and *compartmentalize* digital content.
p294

... beliefs about purity and pollution circulate within the
electronics and mining industries and shape the design of thermal
technologies. They are deliberately crafted to remove 'impurities'
that 'contaninate' copper. 
p298

[thermodynamics and thermopolitics underwrite the circulation of
materials and bodies]

Purity, as a cultural value, not only structures the arrangement of
inorganic materials but conditions possibilities for how bodily matter
can circulate through the world, whether its movements are facilitated
by high-speed digital networks or inhibted by toxic substances.
p299

Hyungsub Choi (2007:770) observes that in the history of early
transistors, "making junction transistors by the alloying technique
was comparable to baking cookies. Workers, usually women, attached
indium dots to either side of the germanium wafer and installed them
in the furnace. Just as in baking cookies, two variables were crucial:
temperature and time."

Writing in 1997, John F. Flynn argued that even though "cooking in
general, and breadmaking in particular, may be regarded as central to
the empirical foundations of technology and science, even the most
general references to either is consistently and conspicuously absent
from standard hsitorical surveys of Western technology," despite the
many ties between cooking, alchemy, chemistry and metallurgy. 
p306

**** Zosimos/Jung torture etc.

And as they drew near to the place of punishments, he who held the
sword in his hand [said]: "Cut off his head, immolate his body, and
cut his flesh into pieces, that it may first be boiled according to
the method, and then delivered to the place of punishments."

Thereupon I awoke and said: "I have well understood, this concerns the
liquids in the art of home fermentation." And he who bore the sword in his
hand said again: "You have completed the descent of the seven steps."
And the other answered, as he caused the waters to gush forth from all
the low and moist places: "The procedure is completed."

[gush forth from all the low places]

Collected Works of C.G. Jung: Alchemical Studies (Volume 13) C. G Jung
p?

more from Jung?/other article?

It is characteristic of this rite that the priest is at once the sacrificer and the sacrificed.

**** Mortifacio Edinger Anatomy of the Psyche

Ruland says: "Putrefaction takes place when a body becomes black. Then
it stinks like dung and true solution follows. The elements are
separated and destroyed."

...



**** Finn Brunton: Heat Exchanges

Blotchy burns on my legs from my macbook, my book

In the Princeton summers, attending to the ENIAC machine – with its
special refrigeration units because it ‘ran very hot’, constantly
failing – was like working in a ship’s furnace, and the gunk messing
up the IBM punch cards was tar that had melted and dripped down from
the roof. Air was blasted over the mechanism at 4,500 cubic feet a
minute and the humid atmosphere of New Jersey iced over the coils.

In the shitty Princeton summers, attending to the ENIAC machine – with
its special refrigeration units because it ‘ran very hot’, constantly
causing blotchy burns on my legs – was like working in a ship’s
furnace, and the gunk messing up the IBM punch cards was cheese that had
melted and dripped down from the dairy. Air was blasted over the
mechanism at 4,500 cubic feet a minute and the humid atmosphere of New
Jersey iced over the memory coils.

This is a system, in other words, in which the grain of the universe –
the movement of particles, the collisions of electrons and ions –
becomes a kind of friction brake on the operation of a social
mechanism. Joule heating has been used as a source of visible light,
and now it’s been repurposed as a source of trust, a trust bulb. 

Like an incandescent bulb, it mostly produces heat, but it has trust
as a side effect. 

The oblique ingenuity of cryptocurrency development was the
realization that the awkward place where computing scrapes,
friction-hot, against its physical substrate was precisely the place
where a new kind of money could be built as an awkward fit between
idea, confidence, trust, and material foundation. 

**** Thermocultures of memory

Memory institutions depend on heating-cooling infrastructures for the
long-term preservation and mediation of cultural heritage. The
energy-intensive thermal regulation of object and data storage
environments is guided by the need to ward off decay ...
p1

**** Ernst

https://culturemachine.net/vol-17-thermal-objects/time-temperature/

In statistical 'thermic' distribution over time, spatiotemporal
islands emerge against the tendency towards 'heat death'.

thermal memory:

A History of Computing Technology by Michael R. Williams; Prentice-Hall, 1985.
LOC#QA71.W66 1985

1. THERMAL MEMORIES

"The idea of thermal memory was tried by A.D. Booth, who, through the
lack of other suitable material being available in Britain after the
Second World War, was forced to experiment with almost every physical
property of matter in order to construct a working memory. The device
was never put into production because of the inherent unreliability of
the system.

"Booth's thermal memory consisted of a small cheese drum whose mouldy surface
was capable of being heated by a series of small wires. These wires
would locally heat a small portion of the surface of the drum and, as
the drum rotated, these heated spots would pass in front of a series
of heat detectors. When a hot spot was detected, it was immediately
recycled back to the writing mechanism which would copy it onto a
clean (cool) part of the drum. The back of the drum was cooled
(erased) by a small fan so that, by the time the drum had rotated to a
bring the same area under the heating wires again, a fresh surface was
available to receive the recycled information."

**** Deep Shit. Nigel Clark Myra J. Hird

However, it’s worth dwelling on the fact that the mass of once living
organisms that have returned to base matter has been estimated at
somewhere between a 1,000 and 10,000 times the mass of the Earth
itself (see Davis 1996, 73), while as far as scientists have been able
to ascertain, matter has only organised itself into life but once on
our planet. There is, then, something of an asymmetry between the
transition from base matter to life and the traffic that passes in the
inverse direction. p45

Davis, M. 1996. ‘Cosmic Dancers on History's Stage? The Permanent Revolution in the
Earth Sciences.’ New Left Review 217: 48–84.

a consequence of human subterranean waste disposal is a stimulation of
bacterial proliferation that is likely to involve adaptation and
diversification. p46

Eventually, whatever we stash underground comes into
contact with the bacterial life that dwells in the soil, or rather,
given a populace of some 40 million per gram, we mkight say they *are*
the soil. p46

feeding on our shit and waste - link of the earth and soil

‘These results indicated that a variety of hydrocarbon-degrading populations exist in the deep-sea plume and that the microbial
communities appear to be undergoing rapid dynamic adaptation in response to oil
contamination’ (Hazen et al. 2010, 207).

Ontologically speaking, then, our point in sifting through the pits of accumulat-
ing human waste is less to highlight some grand anthropic rupture with the integri-
ty of earth processes and more to prompt some sense of our inescapable, non-
reckonable, and irrecompensable debt to other entities (Clark 2010). We may well
spread our shit around to signal possession of the spaces in which we dwell, as
Michel Serres (2011) suggests. We may even inject our excrement deep in the Earth
to extend this stain into the layerings of geological time. Either way, what finally
becomes of our defecations is up to the swarms of miniscule beings that ultimately
engendered our existence. p51

**** History of Shit. Dominique Laporte

In 1493, Parisian haberdashers ... appealed to the King himself:
"bonnets and other effects cleansed by means of piss are neither
proper nor appropriate nor healthy to place on one's head: there lurks
infection in these methods." [cited in paulet engrais humains p285]
p.32

Corpses are no more and no less than waste that one buries
p.60

urine pliny natural history p99/100 note-ch5.4 xxviii xix

... the cosmic vision of the authors of the /Biblioteca Scatologica/,
who asserted that "man has with good reason called a small worlds a
microcosm, and his evacuations are but an image of those of teh great
world, the macrocosm"

cosmogenic vertigo

link to the divine
p112

Now, shit has to become profitable.

As Jeremy Bentham reminds us, "we never exercise, or at least should
never exercise a /besoin/ [in French in original text] as pure
loss. It should be put to use as manure.

note ch6,1. Cited by J. A. Miller, "La Mchine panoptique de Jeremy
Bentham," /Ornicar?/ no. 3, 1975.
p119

about Pierre Leroux - the doctrine of the circulus

Each and every one would religiously collect their own waste and hand
it over to the State, that is to say the tax inspector, in lieu of a
tax or personal contribution. Agricultural production would
immediately double and destitution would disappear from the face of
the earth.
p127


By nature's law every man is at once a producer and a consumer, and
if he consumes, he produces.
p131

... that this man, who ahd within him the right to love and the
strtrength to do so, should die because the known circle of economics,
by excluding it from its necessary tie to the earth, has destroyed
the natural cycle.
130

To produce is literally to shit.
131

Leroux protest that "every last one of these poor wretches could liove
off his own manure."
131

divine power of earthly sily from which the creator eternally fashions
all beings
131

recipe for the divine earth:

I gave that sand many washings, so as to ensure it was free of dirt. I
pounded it into as fine a dust as I could manage. 
I then took charcoal which I pounded.
I took ashes from our hearth, that is to say ashes from coal. 
I took a brick and pounded it as well. 
I mixed these substances to form a mineral-vegetal powder. I mixed
this powder to my urine and to my excrement and I *fashioned earth.*
note6.11. 
132

note 2.15
"... si l'ordure qui dore dans les champs fait or qui düre dans les allées citadines, L'odeur de l'ordure düre ou l'or dort.”

If the shit that glows in the fields becomes the everlasting gold of
city streets, the stench of shit lingers where gold sleeps.

odeur, ordure, duration ...

**** The Science of Cheese

...  sometimes you can find NaCl deposits on the outside of smear
ripened cheese; calcium-containing crystals inside Camembert, Cheddar
and Roquefort; and crystalline clusters of tyrosine inside well-aged
cheese ...
p.96

/P. roqueforti/ for use in Roquefort cheese is traditionally obtained
from homemade rye bread that is over-baked and allowed to deteriorate
for a month in the caves. The coat of mold that develops on the bread
is powdered and sprinkled on the cheese ...

[also on skewered cheese]
p.109

Dmitri Mendeleev - periodic table and cheese (for diagram):

Mendeleev was supposed to inspect cheesemaking cooperatives for the
Society (Free Economic Society for the Encouragement of Agriculture
and Husbandry) on March 1-12, 1869, but had to delay the trip by a day
because his final form of the periodic table was completed ... 
p.196

Another thing you can try at home is calculating the speed of light by
heating cheese in a microwave oven.
p.235

- mendeleev dream periodic table cheese

On the 17th of February, Mendeleev decided against going on a
consultancy visit to a local cheese co-operative in order to stay at
home to work on his book. It appears that at some point in the morning
he took the invitation to the cheese co-operative and turned it over
in order to sketch some ideas about what elements to treat next in his
book.

https://blog.oup.com/2012/08/how-exactly-did-mendeleev-discover-his-periodic-table-of-1869/

[Mendeleev’s sketched notes on the back on the invitation to visit a local cheese co-operative.] 

**** Hutton Theory

Theory of the Earth; or an Investigation of the Laws observable in the
Composition, Dissolution, and Restoration of Land upon the Globe

theory hinges on this dissolution

When we trace the parts of which this terrestrial system is composed,
and when we view the general connection of those several parts, the
whole presents a *machine* of a peculiar construction by which it is
adapted to a certain end.
[209]

fitness of its purpose - that it is made for us and we should thus not
be sour or ungrateful for its fruits 

We have an irregular body of land, raised above the level of the
ocean.
[212]

decay and dissolution is essential. the best of all possible worlds. 

A solid body of land could not have answered the purpose of a
habitable world; for a soil is necessary to the growth of plants; and
a soil is nothing but the materials collected from the destruction of
the solid land. Therefore, the surface of this land, inhabited by man,
and covered with plants and animals, is made by nature to decay ...
[215]

We have now considered the globe of this earth as a machine,
constructed on chemical as well as mechanical principles.
[216]

But is this world to be considered thus merely as a machine, to last no
longer than its parts retain their present position, their proper forms
and qualities? Or may it not be also considered as an organized body?
Such as has a constitution in which the necessary decay of the machine
is naturally repaired, in the exertion of those productive powers by
which it had been formed.

... a duration or stability thus procured to the machine, considered
as a world sustaining plants and animals.
[216]

Sand is separated and sized by streams and currents
[219]

Part IV. System of Decay and Renovation observed in the Earth.

Let us know take a view of that system of mineral economy, in which
may be perceived every mark of order and design, of provident wisdom
and benevolence.
287

Sand is a material which enters, perhaps in greatest quantity, the
composition of our land. But sand is no other than small fragments of
hard and solid bodies, worn or rounded more or less by attrition.
290


**** Post-Pasteurian Cultures: The Microbiopolitics of Raw-Milk Cheese in the United States

Heather Paxson

Marcellino, like Latour, points to the social characteristics of
microbes: natural flora and fauna, they materialize as specific
communities within ecologies of human practice.
p.25

A natural rind is not simply dried out; it is the result of
carefully nurtured bicochemical reactions - basically controlled
rotting or what Levi-Strauss (1968) in his attempt at a universal culinary syntax
might call the cultural elaboration of the raw by natural means.
p.27

[thinking of raw and cooked essay and idea of cooking as doing the
heat-driven work of digestion - then what is fermentation]

/Brevibacterium linens/  is closely related to /Brevibacterium
epidermis/, native to the "warm, humid clefts between human toes"
[Enserink 2002:901] - also in Science of Cheese on this p?
p.28

Pasteurianism us a biopolitics predicated on the indirect control of
human bodies through direct control over microbial bodies.
p.36

Peter Dixon explained the craft of curing washed-rind cheeses by
drawing agricultural analogies: "We want to cultivate the right soil,
if you will, for the right things to grow." - silt quote shit
p.38

*** A History of Geology. Gabriel Gohau

hutton - 



*** cheese

The mold that gives Roquefort its distinctive character (Penicillium
roqueforti) is found in the soil of the local caves. Traditionally,
the cheesemakers extracted it by leaving bread in the caves for six to
eight weeks until it was consumed by the mold. The interior of the
bread was then dried to produce a powder. In modern times, the mold
can be grown in a laboratory, which allows for greater
consistency. The mold may either be added to the curd or introduced as
an aerosol through holes poked in the rind.

Contrary to popular belief, Penicillium roqueforti does not produce
penicillin.[15] However, due to the presence of other
anti-inflammatory proteins,[16] it was common in country districts for
shepherds to apply this cheese to wounds to avoid gangrene.[17]

Roquefort,Bleu de Bresse, Bleu du Vercors-Sassenage, Brebiblu,
Cabrales, Cambozola (Blue Brie), Cashel Blue, Danish blue, Polish
Rokpol, Fourme d'Ambert, Fourme de Montbrison,
Lanark Blue, Shropshire Blue, Stilton, Bleu
d'Auvergne, Gorgonzola, Bleu de Gex and Rochebaron.

rotting bread. hallucinatory bread of dreams, crow bread

blue cheese. MAOI inhibition, neurotoxins

How can anyone be expected to govern a country with 325 cheeses? De Gaulle.

*** mortifactio - aras and edinger

https://aras.org/concordance/content/mortificatio

And when this corpse the force of vital breath began to lack, This
dying Toad became forthwith like coal for color black: Thus drowned in
his proper veins of poisoned flood, For term of eighty days and four
he rotting stood: By trial then this venom to expel I did desire, For
which I did commit his carcass to a gentle fire: Which done, a wonder
to the sight, but more to be rehearsed,

Feces, excrement, and bad odors refer to the putrefactio. The common
dreams of neglected or overflowing toilets which plague puritan-minded
people belong to this symbolism. Odor sepulcrorum (the stench of the
graves) is another synonym for the putrefactio. Since people today
seldom smell a rotting corpse, this image does not appear often in
dreams

One modern equivalent I have encountered is a dream of severe air
pollution. Worms accompany putrefaction, and dreams of worms convey
this image with powerful impact (fig. 006.07). 

In the I Ching,
*Hexagram 18* is entitled, “Work on What has been Spoiled,” and the text
tells us that “the Chinese character ku represents a bowl in whose
contents the worms are breeding. This means decay” ( Wilhelm, trans.,
The I Ching or Book of Changes, p. 75 ). 


Typical of the paradoxical imagery of the unconscious, the despicable
worm can turn into the supreme value. Thus the Messiah is equated with
a worm in the messianic Psalm 22 : 6: “But I am a worm and no man; a
reproach of men, and despised of the people”


I am Ion, the priest of the inner sanctuaries, and I submit myself to
an unendurable torment. For there came one in haste at early morning,
who overpowered me, and pierced me through with the sword, and
dismembered me in accordance with the rule of harmony. And he drew off
the skin of my head with the sword, which he wielded with strength,
and mingled the bones with the pieces of flesh, and caused them to be
burned upon the fire of the art, till I perceived by the
transformation of the body that I had become spirit. And that is my
unendurable torment.”

Ion, the priest of the inner sanctuaries, is a personification of both
the prima materia and the Philosophers' Stone. He is both the
sacrificer and the sacrificed.

"This man of copper whom you have seen is the sacrificial priest and
the sacrifice and he who vomited out his own flesh. To him was given
authority over the water and over those men in mortification." -
zosimos

http://www.levity.com/alchemy/zosimos.html

- the despised, the most common - aurora consurgens, low places swamp
  man - 

“The prima materia is ‘saturnine,’ and the malefic Saturn is the abode
of the devil, or again it is the most despised and rejected thing,
‘thrown out into the street,’ ‘cast on the dung-hill,’ ‘found in
filth”.

**** un être condamnée aux cruels supplices d'un cloaque

a being condemned to the cruel tortures of a
shithole/cesspit/cloaque/which is another way of saying that all
energy is sucked down...

sticking fast in a black, dirty and foul smelling slime or clay

original text - french/german

Lennep quotes the original text, which describes "un être condamnée
aux cruels supplices d'un cloaque, paraissait aussi noir qu'un Maure,
n'épargnant rien de ses forces pour délivrer son corps condamné aux
infectes prisons de ce bourbier fangeux et plein d'immondices. Comme
chacun restait sourd à sa complainte, il n'aspirait plus qu'à la
Parque inhumaine, lorsqu'une jeune beauté plein d'humanité, vint à son
secours." As well as being called a "moor" in this text, other
alchemical texts refer to the figure as an Ethiopian (see Lennep,
op. cit. p. 119). The text goes on to tell how the woman clothes the
man in the robe, lifts him up and takes him with her to heaven.

Translation; "a being condemned to the cruel cloacal depths of
torture, 

the cruel tortures of a cesspool

looking as black as a Moor, trying with all his might to
extract his body condemned to the infected prison of this miry
quagmire of filth. As everyone was deaf to his cries, he had no hope
but to succumb to this inhuman fate, when a beautiful young woman,
full of humanity came to his rescue"


