** There are entrails

Where there are such hills and dales, there the Earth has been matured
and *most perfectly mixed* with heat and cold, moisture and dryness,
and there the best crystals may be found. 

But where the earth is low there has been no accumulation of such
fumes and vapours, and there no ores will be found.  
[splendor solis]

The world is dirt.

When the temperature in the first floor gallery room at Kottbusser
Straße 10, a former early lighting fixtures factory in Kreuzberg, as
measured by an array of shop-bought sensors manufactured in a distant
contemporary factory from doped semiconducting polycrystalline
ceramic, decreases, a sphincter or valve within the base of a
semi-transparent plastic bucket opens, releasing a fine tape-like stream of
gilded construction sand. Two modded buckets occasionally engage in
this generic venting action in the /grand salle des quatre saisons/.

The temperature of the room is the measure of the average speed of the
bustling sand grains within. These will settle in the low places, the
temperate pits of apparent homogeniety.

The entanglement of the hairy layer between casein micelles *decreases
the entropy* of the system because it constrains the micelles,
preventing them from spreading out. [ in blue cheese making - wikipedia]

This event of quiet leakage is engendered by twenty-two ordered and
heavily laden art students ascending the circular staircase gliding
into the gallery, sweating heavily. They are cast as "thermal
exciters" (Serres/Parasite) which means vibrant particular energy
moments moving across, down and out of a necessarily rough and rocky
gradient from the most to least favoured, to the lower lands, between
two containers as if at a junction which is precisely where it will
soon be measured. The first law of thermodynamics states that the
increase in internal energy within this enclosed space is equal to the
heat added minus the work done on the outsides.

Their presence within the wood panelled room sheltering Peter
Flemming's installation ("Sour Bodies + Low Places") thus raises the
temperature considerably; the students account for the equivalent
of a decently-sized electric radiator. This effect is sensed and
registered by a thermostat, installed within the gallery, employing a
similar crystalline junction, a meeting of two disparate and heavily
cut materials taking good advantage of the asymmetric conduction of
electric current between a crystal and a metal, the cut between two
apparently discrete materials or objects.

Within this nervous system composed by and occupied with the
management of resources (not including the aesthetic, social, and
natural), signals are sent to the HVAC (Heating, ventilation, and air
conditioning) units to offset and increase the ... of the air
conditioning system, venting heat to the outside world. We notice a
slight drop in temperature, a granular ice age, as .... accompanied by
the visible and audible release of trailing earth traces of fine sand
from the ecological and always open infrastructural plastic sphincter,
an underground entrailing duck-cable supplying energy for the HVAC and
entrained installation from the Kraftwerk Reuter West (3 million tons
annual CO2) burning brightly hard black bloody coal, the ashes gray,
pulled from the low places or before swampy lands of the El Cerrejón
sub-basin in Columbia, formed millions of years ago from sunken,
decayed, damp forests, later in those churning days of sucking peat
archives, and then weighted down under stone-charged winds year after
year, millions sand and hard stinking earth measured, lower and slower
by how many lives, these far writings in trees, golden entrails and
coated arterial sheer nets. Those ancient trees are now returning
direct benefits on that Paleocenic investment; they are looking back
thankfully and in frozen tears. 

The HVAC itself consists of a series of perfectly mixed material
apparatuses such as dampers, pre-filters, preheating coils, supply
fans, cooling coils, reheating coils, humidifiers, return fans, air
handling units and room sensors.  
[Thermocultures of Memory p11. altered]

All life long you wait for that to mount up to a life. [Endgame 70]

Tree upon tree falling. Grain upon grain falling. The impossible heap.

sand is signalling decay - quicksand, descent of sand, sand
clock, attrition, friction, heat, time trickle - as well as opposing
decay, the piling up of sand. every grain of sand that falls brings death a
little closer

In conversation, discussing the obscure bucket logic and simple rules
of Flemming's LP, he talks of an "ideal window" for temperature; not
losing too much sand that will need to be *plains-takingly
re-plenished*, avoiding the destruction of the mounds or islands which
have been formed by the activities of a subtle nervous system, a
"water war" between greedy buckets pulling these more peacable time
keepers slowly too and fro. Those buckets will also need to be topped
up by hand, under the temperature dependent effects of evaporation, a
vapourous and energetic transformation. We also talk about
*hysteresis*, ensuring that another kind of window exists, a quiet,
resting place of measurements which ensures that a valve or thermostat
does not simply go flip-flopping backwards and forwards, adjusting for
cold, becoming too warm, returning to this warmth and comfort and so
on back up and down. It should stay up or down for at least some
dribbling measure of time.

Rot management strategies involve temperature control, as fermentation
usually requires specific outside temperature ranges. Most of the
lactic acid bacteria are metaphilic, which means they can cope with
normal room temperatures of 18 to 22*C [...] whereas others - for
instance many yogurt cultures - are thermophilic and need cozier
temperatures of 42 to 45*C.
[Beregow.]

This ideal window also describes both the conditions for the exception
that is life on the island, and perhaps a gaze into the jar of a
clouded ferment or the furnace of a coal fired computer furnished for
a Turing tar or sand *pit*.

A one-hundred year old, 18-ton showman's steam engine powers a
computer with 2.5 tons of coal. Black lungs inflate every time a
database record of miners' lung disease is shown on the computer
monitors. It feels like you've been invited into a fun fair, but one
where the rides log their own accidents – a fun fair run by people who
long ago became indistinct from the machines they maintain.
[FOOTNOTE - http://yoha.co.uk/cfc YoHa 2010]

** Earthrise Eternal  - Earth you low exception.

"How were these low and high places of crystal, dead coal and
loamy or doughy sand formed and what delights do they have in store for our sour
bodies, eyes and ears?" Peter Flemming asks, perhaps drawing on the deepest
foundations of geology by way of core founder, James Hutton,
asking us in turn "to consider [...] the globe of this earth as a
machine, constructed on chemical as well as mechanical principles."
[216?]

In "Sour Bodies + Low Places" (SB+LP) Peter appears to offer up a
rather-more-lively binary choice between these two discrete worldings,
earth origin stories, or geologies; the chemical and the
mechanical. 

Our English word sour comes from the Indo-European word syr or sir ,
relating to the souring of cheesemilk.  
[Science of Cheese]

On the one hand, the Low Places of call-them-coal-powered
battling buckets of strung sand and water, and on the other hand the
extensive serial genesis, the witnessed time-lapsed fermentation of
cucumber, cabbage, blueberry wine, ginger beers, and a spoiling
doubled dosa dose. [footnote recipe: DOSA
- any bean
- any grain
- water
Soak.
Wait a day.
Grind.
Wait a few hours, look for rise.
Eat.
(fenugreek for flavour)
]

We watch a flickering cinema of relaxed and incidental light changes, clocking of
temperature, and listen to the bubbled sparse crackling of a ginger
bug culture. Closed vessels, inhabited by some contained process,
impervious and impermeable to other fouler breaths or influences,
allow for gassy rubbered up expansion and silent, prepared
contraction. Rising and falling.

This dirty physics of cracking-crystal fermentation depends on casual
observation and light, if not rough, intervention. Is it bubbling
today, what happens when I open or vent the jar or door, risking the
entry of wishful, dopey-eyed impurities. Judging by eye or by hand,
gauging temperature without external apparatus, tasting and smelling
as ways of becoming acquainted and auguring the progress of invisible
processes of inner transformation, the cloudiness of the solute, subtle
rainbows of deep red in a beetroot kimchi, the signallings of a certain
complex of aromas, for example, of fermenting, salted cabbage or of
habanero peppers with crushed garlic maturing in a salty brine.


If you can't get the salt ratio, maybe just pour in 4 or 5 Arduinos to each bottle?
[Peter Flemming. Email communication]

It is not so easy to make that cut, to split the coiled and wiry,
vanishing hairs of a balding, ducked decision between the chemical,
verging on the lively, and the lowly sandbagged mechanicals with no
theatre or magic.

We return to that point of assymetric flow between two materials, the
"thermal exciters", parasites munching cheese rinds alongside,
scanning the greying coals, close to those ...

between those Sour Bodies and those Low Places, between self-preservation and
self-elimination, between cooking, alchemy, chemistry and metallurgy, between
idea, confidence, trust, and material foundation, between the
transition from base matter to life and the traffic that passes in the
inverse directio, between human toes, between casein micelles, between two
worldings, wordings like think and sphinc-ter. between the realms of material
and living, energetic transformation.

In the case of the crystal which forms one essential element within
the construction of a crystal radio [footnote workshop] we cannot
point solely to the fine gold wire, or the crystalline mineral (such
as galena) as operative agent in this essential radio wave detection,
rather it is the un-narrowable point of flow and assymetric exchange
between these two cut and sometimes-refined earth mineralities, a flow
which extends and entrails outwards through all of the earth.

Hyungsub Choi (2007:770) observes that in the history of early
transistors, "making junction transistors by the alloying technique
was comparable to baking cookies. Workers, usually women, attached
indium dots to either side of the germanium wafer and installed them
in the furnace. Just as in baking cookies, two variables were crucial:
temperature and time."

Thermocultures of Geological Media Nicole Starosielski

This flow of electrons, of electricity, of energetic particles and
absence, can also be modelled and simulated as a flow of water or sand
for that matter, reflect that (SB+LP) is amorphous, allowing for a
non-homogenous re-modelling of itself in other muddy forms.

The contents of that technological black box transformed as if by magic,
so that the familiar contained materiality of algorithmic and media
infrastructures - even if we did expose them, we are none-the-wiser to
the microscoped conduits of silicon and copper - becomes sand, plastic,
buckets and pipes.

of a system-which-has-been-set-up (manufactured, machined howsoever
primitively) with all its mechanisms and circuits and discordant
materialities, is the low place, like a swamp, a dumping ground, a
bog, whereas the place of a more cohered and involving process of
fermentation, perhaps equally controlled but with a more casual hand
in its setting-in-process, maybe even more contained and enclosed, is
the body, or bodies, the sour, *pissed-off* body at odds with and
conflicting with both themselves and their perhaps self-controlled
environment [and what might cause such a body to be so contrary to a
place which they apparently have so adapted to themselves

The abyss is not filled to overflowing,
It is filled only to the rim. [IC]

Water (or sand) fills a pit only to the rim, and then flows on.

Starosielski p295 - Thermal techniques are operations that produce
"cuts" in this flux (Barad 2007), tease out different material
potentials, and shape "solid" media out of geological substances.

These processes are heavily temperature and environment influenced,
and involve feedback through visual observation and tasting to adjust
(eg. add water, stir, skim etc.) [Flemming]]

... it’s worth dwelling on the fact that the mass of once living
organisms that have returned to base matter has been estimated at
somewhere between a 1,000 and 10,000 times the mass of the Earth
itself (see Davis 1996, 73), while as far as scientists have been able
to ascertain, matter has only organised itself into life but once on
our planet. There is, then, something of an asymmetry between the
transition from base matter to life and the traffic that passes in the
inverse direction. p45 [**** Deep Shit. Nigel Clark Myra J. Hird]

For both Low Places (Hutton's geological foundation) and Sour Bodies
(Alexander Flemming) the liveliness of this earthy machine depends on
essential dissolution and decay: for example, the grinding down of
rock to sand:

A solid body of land could not have answered the purpose of a
habitable world; for a soil is necessary to the growth of plants; and
a soil is nothing but the materials collected from the destruction of
the solid land. Therefore, the surface of this land, inhabited by man,
and covered with plants and animals, is made by nature to decay ...
[215]

Decay and dissolution are essential for the creation of this least
sour of all possible worlds, if solely to show us that it is not simply a
machine in its breathy running down into dis-repair, a chilled heat
death and burial:

But is this world to be considered thus merely as a machine, to last no
longer than its parts retain their present position, their proper forms
and qualities? Or may it not be also considered as an organized body?
such as has a constitution in which the necessary decay of the machine
is naturally repaired, in the exertion of those productive powers by
which it had been formed.
[216] Hutton Theory of the Earth, Volume 1 (of 4)

And, like the Kraftwerk, we can where the power in "the exertion of
those productive powers" comes from that enables a dough-like raising up from
the low places, if not from those low places? Where does this
"necrological vitalism" [ref] spring up from and how like SB+LP can we
forge crystalline junctions between these disparate matters, between
coal, crystals and liveliness?

The land, which was like potters clay and entirely soft. But as the
sun’s fire shone upon the land, it first of all became firm, and then,
since its surface was in a ferment because of the warmth, portions of
the wet swelled up in masses in many places, and in these pustules
covered with delicate membranes made their appearance.  Such a
phenomenon can be seen even yet in swamps and marshy places whenever,
the ground having become cold, the air suddenly and without any
gradual change becomes intensely warm. And while the wet was being
impregnated with life by reason of the warmth in the manner described,
by night the living things forthwith received their nourishment from
the mist that feli from the envelop- ing air, and by day were made
solid by the intense heat; and finally, when the embryos had attained
their full development and the membranes had been thoroughly heated
and broken open, there was pro- duced every form of animal life. 1 Of
these, such as had partaken of the most warmth set off to the higher
regions, having become winged, and such as retained an earthy
consistency came to be numbered in the class of creeping things and of
the other land animals, while those whose composition partook the most
of the wet element gathered into the region congenial to them,
receiving the name of water animals. [https://archive.org/stream/DiodorosOfSicily034.598/Diodoros%20of%20Sicily%2001%20%281.1-2.34%29_djvu.txt]

In like manner, we can read in Gabriel Gohau's "History of Geology"
that:

"Needham's most original idea on mountain building was the analogy he
saw with a “machine” using force “either produced by steam, or by
extremely thin and dry air.” This model is interesting because it
comes close to the idea of the steam engine." [ref p.120]

And what is the source of heat which powers this engine?

"The solution he came up with was a simple one and not at all new:
combustion of coal [...] Hutton made it a permanent cause, saying that
each cycle forms new continents which produce new forests; their
destruction on turn forms new layers of coal."[ref p.120]

Describe Needham's experiment.

He heated a sealed container of gravy, assuming that he killed off all life. He looked inside to find out whether or not life was there.

What was Needham's independent variable?
Heat (of the gravy)

[ref: https://www.brainscape.com/flashcards/spontaneous-generation-scientific-experim-5608742/packs/7911289]

Indeed, some of these ancient creation stories do contain an element of scientific fact to them.

In a series of experiments (date) which recall the closed vessels of Low
Bodies, Louis Pasteur put an end to both vitalist
notions of spontaneous generation of life, and ushered in techniques
and regimes to annihilate unwanted bacteria and microbes
(Pasteurisation), catching those *exceptions* before they sabotage and
parisite global food sources (grains as well as dairy products).

This junction point or bodily detector is a holy interchange of bread (and its fermented companions, wine and cheese), shit
and crystalline sand (a fine recipe for a sour day out at a dismal
seaside spot). These are all our only earths, in their running down
and up.

/P. roqueforti/ for use in Roquefort cheese is traditionally obtained
from homemade rye bread that is over-baked and allowed to deteriorate
for a month in the caves. The coat of mold that develops on the bread
is powdered and sprinkled on the cheese ...
[Science of Cheese]

If the process [of fermentation] keeps going, the substrate will decompose entirely and
return to humus, the half-dead organic matter of the soil.
[Beregow. p11]

... sand is no other than small fragments of hard and solid bodies,
worn or rounded more or less by attrition.  [Hutton 290]

"every last one of these poor wretches could live off his own manure."
[History of Shit p131]

... on this crust a mouldy film has produced living and knowing beings: this is empirical truth, the real, the world.
[Schopenhauer]

/////

** Ethereal Strainer + Spoils - soil/shit/decay - but maybe combine all 3 as a kind of interlude - Low bodies  - Narrate three lies - Digestion - bread/cheese/pickles

Flemming's work shows us that these earths and sands are vitalist, diverse and
extensible uncut equivalences. They form economies of production and
consumption at every kind of junction:

When a bucket overfills, sand gushes out. When the queue fills,
daemons drop packets, signalling congestion.  
[Internet Daemons. Fenwick McKelvey. p107/108. altered]

For example, these thirsty data bodies are greedy for energetic resources.

... did you e’er see a well with two buckets, whilst one comes up full to
be emptied, another goes down empty to be filled? such is the state of
all humanity. 

[marston the malcontent]

The buckets always appear to be balanced. Hungry or thirsty. Winning
or losing. Eating and shitting.

But un-fortunately for Jacques de Vaucanson and his rusing duck in the /grand
salle des quatres saisons/, in this garden of earthly delights:

... this observer concluded that the grain input and excrement output
were entirely unrelated and that the tail end of the Duck must be
loaded befiore each act with fake excrement.  
[The Defecating Duck, or, the Ambiguous Origins of Artificial Life
Jessica Riskin Critical Inquiry Vol. 29, No. 4 (Summer 2003),
pp. 599-633]

Equally in this series of equivalences:

[for] the "stabilization of media in archives [and other
memory institutions] keeps them from degrading, becoming waste, [yet]
the shift to energy-intensive cooling mechanisms substitutes the waste
of media objects for the waste produced by fossil fuels."
[Starolieski - 2017]

In LP+SB the junctions are everywhere, the entrails can be divined
from, looking back acrosss geological time like Dante's cursed soothsayers. 

Digestion requires huge amounts of energy; it takes hard work for the
body to process raw foods. Cooking (and fermentation) literally externalizes this energy
[Beregow]

Peter answers the winding gutty question as to what unknowable
processes variously described as decay, rotting, putrefaction,
decomposition, deterioration, fermentation (controlled rotting),
circulation, corruption, spoiling, composting, digestion, degradation,
moulting, infection [Lister called infection fermentation],
dissolution, souring, moulding, disintegration - processes which
connect with the abject, with ordure, excreta, disjecta, with the
discarded and the rejected, the declining, the defiled and unwanted,
the sorely addled and the descending, the leaked and spilled, frothed
and then de-frothed, skimming its scum, what these processes have
to do with (technology, defined as command, control, and
communication.

He poses more simply, what do a laptop or a thermostat and a pickle have in common? 

The simple answer is that they are both embedded within thermocultural
systems of control occupied with the conservation and preservation
(preserves, conserves) of state and the (economic) management of
discrete levels of energy. Within technological infrastructures there
is a maintenance of state (storage in the cloud should maintain our
memories without glitch) which implies an expenditure of energy (a
bucket spilling out water or sand drives a mini turbine which
generates electricity to charge my phone, a pickle-pecked piper lifts
and re-fills the bucket every few days, nipping into the back room for
a 25kg bad of sand, thus drawing on his own restricted reserves of
energy in some schoolbook illustration). A sandy-k/need demon surfs
downhill a temperature gradient of entropy leading us back into the
dammed and thus civilized and effluent low countries.

The memorial of a one or a zero on a grand scale [Thomas Pynchon lets
us choose between: “If patterns of ones and zeroes were "like"
patterns of human lives and deaths, if everything about an individual
could be represented in a computer record by a long strings of ones
and zeroes, then what kind of creature could be represented by a long
string of lives and deaths?” - Vineland? She pictures to herself the
mattress he sleeps on, bearing the “vestiges of every nightmare sweat,
helpless overflowing bladder, viciously, tearfully consummated wet
dream, like the memory bank to a computer of the lost.” Crying lot
49 - sand-buried pickle tasting like a urine-infested mattress ] also releases heat
as excess, a sour and unwanted byproduct of these bits circulating as
a flow of electricity through less-than-pure metals. [Finn Brunton
"the work of computation is the work of managing heat. The history of
computing is also the history of air conditioning and temperature
control".] 

In an ideal world.

** Earthen retailers + Deceivers

Semiconductor manufacturing works like a blue cheese dairy where a
fungus such as Penicillium roqueforti is inoculated into sheep milk or
milk curds and imparts a distinctive flavor. Just as in the
crystalline world of the diffusion process, ripening mould veins and
calcium crystals stud the cheese as it ferments. Once the cheese has
matured over several months, it is sterilized at ultra high
temperatures. This heat treatment also inactivates the Penicillium
roqueforti, inhibiting further fermentation. In the same manner,
solid-state physicists determine the proper time and temperature
needed to put the precise amounts of impurities at precise points on
the silicon block.  
[T.R. Reid quoted in Thermocultures of Geological
Media. Nicole Starosielski]

In this story, the cheese maker could also be a barbeque chef, doping
the pure silicon of meat with hickory smoke, and she could equally be
a sacrificial priest. The continuous extensible bodies are seperated,
torn asunder, hewn like tree trunks, slayed, divided, leading forth
into the corruption of killed bodies. Commercial metallurgists talk of
the torture of ores pulled from the earth. With reference to
pasteurisation Bruno Latour talks of the scientist as now being able to
"starve the microbes, kill them with antiseptics, make them eat
anything, in short, torture them in innumerable ways, in order to
learn something about them each time" [1988 the pasteurisation of
france]. Fermentation is an "uncanny figure of flourishing death via self-digestion
[which] demonstrates the limits of the assumed logic of cyclic repetition."
[p10 beregow]

It is painfully obvious that technologies of computation, control and
communication are always subject to the noisy un-constraints of both
materials (substrates) and material-un-bound processes
(thermodynamics), just as s/our bodies are subject to disease, and
disintegration, to good and bad microbes and moulds; whilst relying on
these materials as a necessity.

Peter Flemming shows us a set of speculative technologies which
acknowledge the pleasures of approximate and un-studied cooking and
to fermentation, which attempt to willfully roll down into those low
places of thermodynamic gradient, of waste heat, to un-damm the flows
and circulations seperating various abysses with names such as
Anthropocene, computation, currency and exchange. 

... fermentation would not stand for the recycling of the existing world,
but for its slow inner destruction. Indeed, it is not only the
Anthropocene or the Pasteurian scientist who is controlling and
torturing microbes; fermenting means that the involved bacteria
eagerly begin their decay work by killing other 'bad' microorganisms
in a necrological zombie-like movement between self-preservation and
self-elimination. Fermentation always has this uncanny, almost bleak
dimension to it: it is only the thin semi-permeable membrane of the
gastro-intestinal tract that prevents us from digesting ourselves.
[p17 Beregow]

These are darkly promiscuous set of technologies of sour-pissed-on/off
bodies, of local, overheating parasites, technologies which are not
for a human or a visible crow to do-something-to-something-else with,
to hide something or to transform it, to transfer it, but technologies
and techniques for the others, precisely that imagination which
mirrors all these of our endeavours in another realm, of the decaying
and of the dead.

Technologies for the most despised, the unwanted, vile and the
excluded in this vile world of plenty, this cloacal cesspit
homogenized without the dreadful and synthetic cut, sucking down all
energy, sticking fast in a black, dirty and foul smelling slime or
clay, which is vile and dear and covered with filth, a quite different thing.

Prends cette chose méprisée
Que tu foules aux pieds sans le voir,
Sinon tu montes sans échelle,
Sûr de tomber à la renverse." 

Take this scorned thing, 
Which you trample into the low places,
If not you will climb out of the sand without a ladder
And be sure to fall back down

["Symbola aurae mensae" 1617 Michael Maïer]



