* notes for v2 pages/andreas

- 3x images: 2x dissolutions, 1x argotine - mentioned on back page

** TITLE: corporeal geology

The body is and has always been geological. We can think of kidney
stones, of crystals formed in urine and of iron in the blood. We
incorporate the earth and its minerals, becoming sedimentary. New
layers of anthropological minerals and particles deposit in blood and
brain. From 1945 onwards, radioactive Strontium-90 replaces Strontium
in bones and teeth. These is a new environment which can be extracted
as a contemporary resource.

*** Tiny Mining [project description] - 350->1150 chars

In today's world, metals are in greater demand but are becoming ever
scarcer. Tiny Mining aims to recover more than 20 elements including
precious and other metals from a novel, sustainable and renewable
resource: from within the living human body.

We believe that the earth should remain as pristine and untouched
nature; we have no desire to carry on extracting resources from an
ever depleted world, polluting and laying waste to the
landscape. Saving the planet is now a matter of becoming sensitive to
our own geological being. In mining ourselves we gain knowledge of our
own bodies, our selves and the global environment. This is a final
ecology for the end days. Nature will remain and our technologies will
now be sourced from within; we will thus no longer be dependent on
scarce and already polluted environmental resources.

Tiny Mining [TM] is the first mineral exploration co-operative and
resource specialist committed to the potential exploitation of the
interior of the human body for rare earth and other mineral resources
in the interests of human and planetary health and to create
sustainable values for our members.

**** original texts

Tiny Mining is a speculative, interventionist artistic research and
media project examining the links between extractivism, pharmacology
and medical or environmental geology.

Tiny Mining explores the material basis of computational and
communications technology and infrastructures in relation to the human
body and asks what such a potential relationship could be in terms of
a closer connection between the material and environmental effects of
the extraction and return (planned obsolescence, e-waste) of
technology and the body could be. At the same time it explores and
asks questions about the practical and ethical nature of this proposed
new relationship.

Media, computation and communications have always been geological,
entering into material cycles through both extraction (mining, for
example, copper), and processing (for example, the reburial of copper
and fiber optic cables in the earth). What is perhaps new, in the
recent naming of the becoming-geological of humankind (as the
anthropocene or capitalocene), is the conjoined transformation and
awareness of humans and their home planet as at once media and matter,
information and geology. Industrial plastics, dust and radioactive
isotopes lodge within all kinds of bodies, equally marking all things
as geologic.

At the same time, humankind can be defined as always incorporating the
earth: as food, as pharmakon and as media and this incorporation can
be defined as geological. We can catalogue a history and a "bestiary"
of an inner geology with its bezoars, otoliths, gallstones and
gastroliths. Geology is not outside us; various timescales must be
compared and contrasted (of lives and deaths, eating and shitting, of
deep time and geological formation).

This idea of a sensitivity to planetary and bodily health underwrites
the Tiny Mining project with the Anthropocene viewed as both
symptomatic and as psychosomatic.

The focus of the project is on the transitional interior and inferior
geologies of media and communications. The notion of interior geology
refers also to the circulatory system of an earth addiction
encompassing extraction (of precious metals, of radioactive minerals),
transport/circulation and consumption (the ingestion of earth-derived
energies, materialities and earth-bound pharmaceutical products) and
return or excretion (traces of isotopes and pollution elements in the
body).

Matter, like media are both purposefully ingested and accidentally
absorbed, forming new internal, circulatory and transitional
geologies.

Tiny Mining explores these multiple links and circulations between
technology, the environment and the human body and psyche. It's
important in times of climate disruption and environmental destruction
that we begin to think and work deeply within these relationships and
within the histories of media such as scientific discourse,
pharmacological matters and medical geology; to think an alien,
potentially geological post-nature.

/////


We will explore both of these potential outcomes of this near-future
scenario within a series of fictions, video works, practical
investigations, installations and interventions. On the one hand, a
startup company will be created, seeking venture capital for
investment and exploring various models for the functionality of a
tiny nano-mining pill. At the same time, Tiny Mining is an open source
project which explicitly attempts to mine, harvest or recover precious
or useful minerals from within living bodies. It is made manifest as a
collection of online practices and recipes for DIY recovery of
elements, an ongoing research, and as an online community of DIY
practitioners sharing artefacts and techniques.

/////

Preliminary research suggests the formulation of a nanite, molecular
machine or nanomachine, a parasitic composite of polarized molecules
that once stimulated, produce mechanical movements on cellular
surfaces in order to remove, harvest and restructure minerals from the
human body on a macroscopic scale.

The parasite, named Argotine (with reference to the rich history and
folklore of the ergot fungus) is designed as an assemblage of
nanoscopic units, each of them measuring around 10nm, that have
specific compositions and electrical charges corresponding to the
desired mining process.

The different nanomachines create bonds, communicate and form larger
structures (up to 100 micrometers) similar to fungi's mineral mining
hyphae. Once injected into the bloodstream, they travel and stick to
the affected/healthy cells where the extraction begins.

This micro/tiny mining process, as in the case of soil mineral
extractions performed by plants, fungi and microorganisms is
facilitated thanks to bioleaching (the process of extracting metals
from their ores through the use of living organisms) through
chelation. The process is highly efficient for lead, arsenic,
antimony, molybdenum, gold, silver and cobalt extractions.


*** image captions

[author; title; technical details, maybe context where the image was
taken; date; photographer; rights holder; several images will be
numbered 1. - x.; where this makes sense, captions can be summarised
"Fig. 1 – 4 ..." etc.]

Fig. 1. Argotine packaging, 2019, drug packaging for the Tiny Mining
chelation or extraction agent based on DMPS
(2,3-Dimercapto-1-propanesulfonic acid). Photographer Martin Howse

Fig. 2. Gold mine tailings and cyanide pipings, close to Westwood IAMGOLD Mine, Rouyn-Noranda, Québec, Canada. Photographer Peter Flemming

Fig. 3. Tests for cyanide on mine tailings, Dissolutions exhibition, Perte de Signal, Montreal, Canada. Photographer Peter Flemming

*** Reference keys

- body -- corps eclate
- ecology of resources - ration alimentaire
- geology - deuxieme peau
- extraction - creusets stellaires

*** references

Concept: Martin Howse

With thanks to: Jonathan Kemp, Ioana Vreme Moser, IXDM/Critical Media
Lab Basel, Boris Debackere, Nik Gaffney, Alfonso Borragan, Theun
Karelse, Ines Tomasek and V2_.

Tiny Mining is supported by The Alex Adriaansens Residency 2019, at V2_.

*** optional text
