* notes/brainstorm

1- minuser's testimony

2- traditions of chinese mummies and elixir poisoning

3- extraction, incorporation and immortality. bezoars also.

extraction images

4- modern movements - transhumanism, grinders and now the minusers, users, mining is mine, tiny miners

images from forum

5- how that works - argotine - ergot history

images of packaging, of ergot growing

6- what they believe in briefly // breakdown




* first notes for v2 presentation dec 5 (from notebook)

If a guy like me with no medical or scientific background can start
tiny mining, chances are you can too, despite what you might have
heard. I think everyone has something to contribute, especially now
that we are in an era where collaborations are increasingly
multidisciplinary.


- academic analysis of Tiny Mining users in relation to ancient
  Greek/Egyptian practices of immortality through (all forms of)
  extraction (some of these can be invented). how contemporary forms
  of extraction can be seen in relation to death and immortality

- extraction towards storage and towards memorial. eg. mercury and
  copper are extracted from the earth and placed into the human body
  in order to preserve it. transhumanism is about material
  augmentation, flesh is replaced by metal and mineral which is
  (apparently) a renewable resource. tiny miners go in reverse
  direction - becoming mineral and purging oneself of minerals

- arguments against animal sacrifice. nature of daemons (collect
  texts). Iamblichus.

- start off with chinese mummies preservation

https://www.ancient-origins.net/history/dying-live-forever-reasons-behind-self-mummification-003166

explain also elixir poisoning and immortality

self-mummification: (Needham, p299+) - a living tradition in Japan

The adept towards the end of his life abstains for a long time from
all cereal food, living only on plant material such as chestnuts,
Torreya nuts, pine-tree bark and the roots of grasses; then just
before dearh he may claim the distinction of being buried alive. After
death has occurred the corpse is dried over charcoal fires and smoked
with the fumes of incense, then when fully dessicated lacquered all
over or used as the base for a statue of dried clay or plaster. 

... p301. whether by arsenical elixir-poisoning or by
self-mummification, the continued existence of the body was felt to
justify in some measure the Taoist techniques.

What is shih chieh? (from a Taoist catechism p301 - Li Shu-Huan)

After the death of an adept seeking immortality, the form and skeleton
remain behind while the immortal goes away; this is what is meant by
shih chieh. When one is ready to rise up as an immortal, one leaves
behind the malodorous house of clay, hence the expession "corpse"
(shih) from which the hsien ius "liberated".

The Chu Hsien Lu says "When the appearance is like that of a living
person - that is (proof of) shih chieh. When the feet have not turned
bluish in colour, and the skin not shrunk - that is shih chieh. When
the light in the eyes has not gone dull, and looks like that of a
person still alive - that again (shows) shih chieh. There are also
those who have become alive once more after being dead; and some whose
bodies have disappeared altogether before being encoffined; and others
who have ascended, leaving only their hair behind - all these things
are called shih chieh. Those who effect their liberation during the
light of day become immortals of the higfher category, who those who
do so at night join the company of the lower.

- stories of immortals ->

----

After taking Argotine, if your face and body itch as though insects
were crawling over them, if your hands and feet swell, if you cannot
stand the smell of food and vomit it up after you have eaten it, if
you feel as if you were going to be sick most of the time, if you
experience weakness in your arms and lgs, if you have to go often to
the toilet, or if your head or stomach violently ache - do not be
alarmed or disturbed. All these effects are merely proof that the
Argotine you are taking is succesfully mining your insides.

- who are the tiny miners, the real miners, the minusers?

- new form nowadays - brief background TM -> Argotine - from ergot,
  the parasitic mushroom which renders bodies hard, black and
  geologic - a petrification from the inside, a black death.

- excerpts/screenshots (fake) from forums

- manifesto/user testimony/at beginning - natural methods


to andreas:

For the presentation I thought of a mock/pseudo scientific lecture on
Tiny Mining[TM]/DIY self mining considered as another (real) body/mind
modification community (eg. cyborg, biohacking, Transcranial magnetic
stimulation (TMS) and chelation/heavy metal detox groupings) in
relation to an anthropology/history of preservation and immortality of
environments and bodies. Through this playful mock lecture I would
unravel the core ideas of the Tiny Mining project and of interior
geology - which very much relates to im/materiality - that geological
time-scales and processes can now be considered as interior to the
human body with all that this implies. The idea is also to treat TM as
a reality rather than (just) as an artistic project.

The page/s title could be either Argotine (the drug used in Tiny
Mining) or Interior Geology with an introduction to its operations
within the concept of Interior Geology. The iconic image would be of a
standard Argotine drug package, looking very much like any other pill
packaging. Any accompanying text could relate more to the lecture,
perhaps also touching on ideas of material self-sacrifice.
